### ISSUE TITLE
Error: ZeroDivisionError: float division by zero

### ISSUE THREAD

**Issue by shenuhcide** [tanghaibao/jcvi#10]
Aloha!

I've run Allmaps on variations of my data without error previously, but on the last run I received the error:  "ZeroDivisionError: float division by zero" when it was in the process of writing the chr.pdfs.  Do you happen to know how I can fix this?

Attached is the error output.

Thanks!
Sheina
[Allmaps_21053.err.txt](https://github.com/tanghaibao/jcvi/files/198463/Allmaps_21053.err.txt)

**Comment by tanghaibao** [comment]
Sheina,

It seems that the plotting script failed on a specific chromosome that appear to be contain only co-segregating markers (markers at the same distance 0, leading to the `ZeroDivisionError`). The computation is already completed. Would you be able to ATTACH a file that ends with ``.lifted.bed``?

Haibao

**Comment by shenuhcide** [comment]
Aloha Haibao,

Thanks for your reply!  Here is the file that ends with .lifted.bed.  I
think I'll also just run the analysis again without the linkage group that
only contains co-segregating markers.

Cheers,
Sheina

Sheina B. Sim, Ph.D.
Junior Researcher
University of Hawaii at Manoa and USDA-ARS Daniel K. Inouye US PBARC
Phone: 808-932-2175
