### ISSUE TITLE
How does ALLMAPS deal with partially redundant genome information in contigs?

### ISSUE THREAD

**Issue by chklopp** [tanghaibao/jcvi#100]
Hi,

I have any assembly of a highly heterozygous genome in which some contigs or contig parts are redundant (both separated alleles). Markers are mapping on both contigs.

Is there documentation about how ALLMAPS deals with such a case or about how the process the data with ALLMAPS to remove these redundant contigs or contig parts?

Cheers

**Comment by tanghaibao** [comment]
@chklopp 
Unfortunately the current version of ALLMAPS would not be able to handle redundant contigs due to heterzygosity. It is currently still an open area of research. The temporary solution is to somehow non-redundify the contig inputs prior to sending to ALLMAPS.

Haibao
