### ISSUE TITLE
unable to use Bionano .bed file

### ISSUE THREAD

**Issue by amit4mchiba** [tanghaibao/jcvi#106]
Hi,

My name is Amit, and I am working on plant genome. My plant species genome size is 440Mb, and used 130x PacBio, Bionano and HiC to eventually derive my final genome assembly. I also used Falcon-phasing to obtain phased genome of my plant species. Now, I wanted to perform ALLMAPs analysis using draft genome as reference and linking it with two haplotigs to check the assembly quality. I also performed Bionano de novo assembly, and wanted this result to match with reference and assess its quality. One possible way is to obtain CMAP files (insilico digestion) for all these files, and then just compare them. This comparison generates XMAP file in bionano. I used this XMAP file and converted into .bed file, but unable to use for ALLMAPs analysis. Please guide me on how shall i proceed to achieve my objective.

thank you so much in advance,

with best regards
Amit

**Comment by tanghaibao** [comment]
@amit4mchiba 

Unfortunately, ALLMAPS does not currently support conversion from the XMAP file.

Haibao
