### ISSUE TITLE
Install with pip

### ISSUE THREAD

**Issue by ksw9** [tanghaibao/jcvi#113]
Hi,
I am wondering how to properly complete the pip install? 
After pip install jcvi, do I need to run setup.py or other scripts? How do I correctly set up the package so that I can use the command as you describe in the README:    python -m jcvi.formats.fasta ACTION 

Thank you!

**Comment by tanghaibao** [comment]
@ksw9 
Sorry for a late response -
If you installed using `pip` then the command should just be able to run. For it to run, the `jcvi` package needs to sit inside your `PYTHONPATH`. Details in the README installation section:
https://github.com/tanghaibao/jcvi#installation

Haibao
