### ISSUE TITLE
Synteny estimation of genome size is super high

### ISSUE THREAD

**Issue by XClaws** [tanghaibao/jcvi#115]
Dear Haibao,

I am using ALLMAPS to reconstruct my genome assembly with genetic data and comparative data.
The re-scaffolding was succeeded. However, I found out that the estimation genome size of synteny map is up to thousand cM high which is more than 10 times of the genetic map.  Is this normal? Personally, I think it is dependent on the size of the genome. So if my assumption is correct, then I think the unit should be Mb instead of cM right?
![image](https://user-images.githubusercontent.com/14818616/50836992-db600c00-135a-11e9-88d1-ec6e002c91e3.png)

**Comment by tanghaibao** [comment]
@XClaws 
In the case of synteny, the units is number of markers (which is the number of genes on the syntenic chromosome). The graph says 3095 cM, but the unit is not correct (the plotting script assumes a genetic map). So, just ignore the unit for now.

Haibao

**Comment by XClaws** [comment]
Dear Haibao,

thank you for your help! It is clear to me now.
