### ISSUE TITLE
Kent tools licence

### ISSUE THREAD

**Issue by timothymillar** [tanghaibao/jcvi#116]
Hi, 
is it possible to get more clarity over which parts of the Kent tools package may be required as dependencies?

The Kent tools package is made available under a  [custom license](https://genome.ucsc.edu/license/) in which some parts of the software are not freely available for commercial use.

Your installation instructions don't specify which parts of their source code might be required so it is unclear whether or not the dependencies can be installed for commercial use.

Thanks

**Comment by tanghaibao** [comment]
@timothymillar 
You are right about the Kent tools license. This package (or rather the ALLMAPS tool) uses two Kent executables - `faSize` and `liftOver`.

I have communicated with the UCSC staff and the `liftOver` tool is not freely available. 

This distinction is made here in the wiki page:
https://github.com/tanghaibao/jcvi/wiki/ALLMAPS#external-dependencies

Haibao

**Comment by timothymillar** [comment]
Thank you for your your quick response.
My mistake, I should have checked the wiki more thoroughly.

Tim
