### ISSUE TITLE
the meaning of gene color in the microsynteny plot

### ISSUE THREAD

**Issue by XClaws** [tanghaibao/jcvi#117]
Dear Haibao,

Thank you for developing this fancy function. I've been enjoying it to make a nice plot.
However, there is a query bothering me,
What do the green and blue color represent in the Microsynteny plot?

Thank you and wish to hear from you.

**Comment by tanghaibao** [comment]
@XClaws 

Gene orientation (relative to the region).

![image](https://user-images.githubusercontent.com/106987/51289920-f82dbc80-19b6-11e9-8282-62b071f9ed01.png)

**Comment by XClaws** [comment]
Ah, right. I should have noticed. 
Thank you!
