### ISSUE TITLE
'catalog.py orthologs' results in a large number of duplicates in allopolyploid species comparison

### ISSUE THREAD

**Issue by dejonggr** [tanghaibao/jcvi#118]
Hi there,

**Edit:** I was concerned about issues RE: trying to make a four-way progenitor-subgenome duplicate list but I realized I wasn't running the full catalog.py ortholog options. The _--full_ option seemed to be what I was looking for but before I close the issue do you mind elaborating on which of the .ortholog, .last.filtered, .blocks, or .rbh represents the most accurate ortholog list? 

Alternatively, if there's any documentation that explains this in more detail I'd be happy to read over it!
 
Thanks!
Grant

**Comment by dejonggr** [comment]
Update: I've used the --full option and increased the cscore but I'm still seeing a notable number of duplicate elements using:
_python -m jcvi.compara.catalog ortholog genomeA genomeC --full --cscore=.99 --quota=1:1_

Could this be because I removed GLPK? It causes the below error each time I run it (glpk version 4.61) so I've uninstalled the module:

> glpsol --cuts --fpump --lp /scratch/dejonggr/brassica/pair_analysis/synteny/c.value.test/glpktest/work/data.lp -o /scratch/dejonggr/brassica/pair_analysis/synteny/c.value.test/glpktest/work/data.lp.out -w /scratch/dejonggr/brassica/pair_analysis/synteny/c.value.test/glpktest/work/data.lp.list >/dev/null
> Traceback (most recent call last):
>   File "/cvmfs/soft.computecanada.ca/easybuild/software/2017/Core/python/2.7.14/lib/python2.7/runpy.py", line 174, in _run_module_as_main
>     "__main__", fname, loader, pkg_name)
>   File "/cvmfs/soft.computecanada.ca/easybuild/software/2017/Core/python/2.7.14/lib/python2.7/runpy.py", line 72, in _run_code
>     exec code in run_globals
>   File "/home/dejonggr/python2.7/synteny/lib/python2.7/site-packages/jcvi/compara/catalog.py", line 841, in <module>
>     main()
>   File "/home/dejonggr/python2.7/synteny/lib/python2.7/site-packages/jcvi/compara/catalog.py", line 73, in main
>     p.dispatch(globals())
>   File "/home/dejonggr/python2.7/synteny/lib/python2.7/site-packages/jcvi/apps/base.py", line 96, in dispatch
>     globals[action](sys.argv[2:])
>   File "/home/dejonggr/python2.7/synteny/lib/python2.7/site-packages/jcvi/compara/catalog.py", line 684, in ortholog
>     quota_main([anchors, "--quota=1:1", "--screen"])
>   File "/home/dejonggr/python2.7/synteny/lib/python2.7/site-packages/jcvi/compara/quota.py", line 304, in main
>     solver=opts.solver, verbose=opts.verbose)
>   File "/home/dejonggr/python2.7/synteny/lib/python2.7/site-packages/jcvi/compara/quota.py", line 216, in solve_lp
>     filtered_list = GLPKSolver(lp_data, work_dir, verbose=verbose).results
>   File "/home/dejonggr/python2.7/synteny/lib/python2.7/site-packages/jcvi/algorithms/lpsolve.py", line 78, in __init__
>     self.results = self.parse_output(outfile)
>   File "/home/dejonggr/python2.7/synteny/lib/python2.7/site-packages/jcvi/algorithms/lpsolve.py", line 125, in parse_output
>     rows = int(rows)
> ValueError: invalid literal for int() with base 10: 'Problem:'

Is this necessary?

Also, I've noticed other catalog.py options (omg, omgparse, etc). Are these a necessary part of the pipeline?

Thanks!

**Comment by tanghaibao** [comment]
@dejonggr 

Thank you for using the synteny package, and for going through the (many) functions in it. Yes, it is a bit confusing and lacks documentation for many parts.

`omg`, `omgparse` were used for specialized studies (e.g. in _Brassica napus_ genome paper). These were perhaps difficult to apply in a general sense. Please use `ortholog` routine which is better tested and supported.

Haibao
