### ISSUE TITLE
IOError: [Errno 2] No such file or directory: 'JM-2.lifted.bed'

### ISSUE THREAD

**Issue by jgroh** [tanghaibao/jcvi#121]
I'm getting this error when running `python -m jcvi.assembly.allmaps path JM-2.bed scaffolds.fasta`:

```
IOError: [Errno 2] No such file or directory: 'JM-2.lifted.bed'
```

Is this file supposed to be present after merging linkage maps? `JM-2.bed` is present but not `JM-2.lifted.bed`.

Nonetheless the command produces some output files, but they appear incomplete. Looking at `JM-2.summary.txt`, the summary for the consensus map has fewer oriented markers than what is shown in the wiki page. Any suggestions?

**Comment by tanghaibao** [comment]
@jgroh 

Have you installed the UCSC `liftOver` command in your path? This output requires the program to be installed, as stated in the documentation.

Haibao

**Comment by jgroh** [comment]
Hi Haibao, 

Yes it was a dependency issue. Fixed now, thank you.
