### ISSUE TITLE
Split chimeric chromosomes

### ISSUE THREAD

**Issue by francicco** [tanghaibao/jcvi#122]
Hi,

AllMaps was very successfully able to super-scaffold my assembly using the synteny map with a reference genome. AllMaps scaffolded my scaffolds into 21 pseudochromosomes + 276 minor scaffolds. The 21 pseudochromosomes are exactly the number of chrs as in the reference; since my species has 31 chrs, that means there are clearly some chrs artificially joined. Is there a way to split those pseudochromosomes?

Thanks
F

**Comment by tanghaibao** [comment]
@francicco 

You need to somehow identify where the splits may be. Obviously, if you use a 21-chr reference, it will just end up having a 21-chr assembly.

Do you happen to have a genetic map that has 31 linkage groups? 

Haibao

**Comment by francicco** [comment]
Hi @tanghaibao,

I think there should be available a linkage map for my species, but I not sure I use it I never did. I was also thinking at [reapr](https://www.sanger.ac.uk/science/tools/reapr), would it help?

Thanks
F

**Comment by tanghaibao** [comment]
@francicco 

Finding breakpoints based on paired reads (such as using `reapr`) might work. My worry is that it may end up giving you way too many candidate splits than you want (in your case, 10 splits) due to repeats and inaccuracy in read mapping. It's worth trying though.

Haibao

**Comment by francicco** [comment]
I'm trying, let's see.
F
