### ISSUE TITLE
expandFaFastBuf: integer overflow when trying to increase buffer size from 2147483648 to a min of 61.

### ISSUE THREAD

**Issue by mictadlo** [tanghaibao/jcvi#126]
Hi,
We have one population consisted of 192 F3 lines resulting from a cross between two plants (Lab x QLD).
Additionally, we created 2 assemblies out of the above two plants and grouped them and grouped them with ALLHIC. While running ALLMAPS the following error appeared:

```
faSize -detailed lab-qld.fasta >lab-qld.fasta.sizes
expandFaFastBuf: integer overflow when trying to increase buffer size from 2147483648 to a min of 61.
```

The below linkagmaps were generanted genotype-correcotor followed my MSTmap:
```
> cat qld.csv | head
Scaffold_ID,Scaffold_Position,LG,Genetic_Position
g17,1342110,lg156,0.000
g17,1544315,lg156,6.222
g17,1546635,lg156,17.660
g17,1546673,lg156,23.626
g17,1546698,lg156,29.274
g17,1611784,lg156,35.795
g17,1622467,lg156,41.497
g17,1730449,lg156,47.886
g17,1944079,lg156,57.860
...
```

```
> cat lab.csv | head
Scaffold_ID,Scaffold_Position,LG,Genetic_Position
g6,125965058,lg141,0.000
g6,125956467,lg141,6.601
g6,125430892,lg141,13.181
g6,125405167,lg141,17.022
g6,125232209,lg141,20.757
g6,124836887,lg141,23.207
g6,124686936,lg141,26.912
g6,124219707,lg141,29.675
g6,123443587,lg141,32.543
...
```

```
> grep ">" lab-qld.chr.fasta
>chrlg141
```

```
grep ">" lab-qld.fasta
>chrlg141
```

What did I miss?

Thank you in advance.

Michal

**Comment by tanghaibao** [comment]
@mictadlo 

Haven't seen this error before. `faSize` is a UCSC tool which calculates the sequence length for each FASTA record. Do you happen to have a gigantic-ish FASTA file?

Haibao

**Comment by mictadlo** [comment]
Hi,
The assembly which I provide to ALLMAPS has 19 chromosomes please see below:
```
>>> from Bio import SeqIO
>>>  
... for seq_record in SeqIO.parse("/scratch/waterhouse_team/benth/Nb_Polar_Purge/Nb_Falcon/bam-hic-pure-pacbio/asm-19g.chr.fasta", "fasta"):
...      output_line = '%s\t%i' % (seq_record.id, len(seq_record))
...      print(output_line)
... 
g1	187342259
g2	137376219
g3	137137493
g4	135869878
g5	131849954
g6	130089204
g7	129785760
g8	129263530
g9	126952998
g10	126860275
g11	110566009
g12	179419090
g13	177111707
g14	172660526
g15	154098882
g16	148803856
g17	145615698
g18	144500917
g19	137830787
```
However, ALLMAPS seems to create a new FASTA file which appears to have only one entry and contain the assembly in it.

```
>>> from Bio import SeqIO
>>>  
... for seq_record in SeqIO.parse("lab-qld.fasta", "fasta"):
...      output_line = '%s\t%i' % (seq_record.id, len(seq_record))
...      print(output_line)
... 
chrlg141	2743136842
```
What did I miss?

Thank you in advance,

Michal

**Comment by tanghaibao** [comment]
@mictadlo 

Interesting that ALLMAPS seem to merge all your chromosomes into one. How many linkage groups do you have from your genetic mapping?

Haibao

**Comment by mictadlo** [comment]
Hi @tanghaibao,
MSTmap created many linkage groups:
[lab-mstmap.txt](https://github.com/tanghaibao/jcvi/files/3051083/lab-mstmap.txt)
[qld-mstmap.txt](https://github.com/tanghaibao/jcvi/files/3051084/qld-mstmap.txt)

However, when I ran `python -m schnablelab.formats.mstmap mstmap2allmaps` with `--min_markers 15` I only end up 1 linkage group for each parent:

[lab-mstmap2allmaps.xlsx](https://github.com/tanghaibao/jcvi/files/3051074/lab-mstmap2allmaps.xlsx)
[qld-mstmap2allmaps.xlsx](https://github.com/tanghaibao/jcvi/files/3051075/qld-mstmap2allmaps.xlsx)

What should I change?

Thank you in advance,

Michal
