### ISSUE TITLE
No chromosome labels in Macrosynteny 

### ISSUE THREAD

**Issue by PizzaKid** [tanghaibao/jcvi#127]
Dear tanghaibao,
I created a beautiful karyotype.pdf (thank you for that!), but the labels of the chromosomes (plasmids in my case) are missing. In the example the lables were generated automatically. Can you please tell me how to do it manually in the layout-file? 
  
My files:
  
layout:
```text
# y, xstart, xend, rotation, color, label, va,  bed
 .6,     .3,    .9,       0,      , plasmidsGenome1, top, Genome1.bed 
 .4,     .3,    .9,       0,      , plasmidsGenome2, top, Genome2.bed 
# edges
e, 0, 1, Genome1.Genome2.anchors.simple
```

seqids:
```text
pGenome1-1,pGenome2-2
pGenome1-1,pGenome2-2
```

Thank you!

**Comment by tanghaibao** [comment]
@PizzaKid 

Can you list the chr column in the bed file? We wanted to make sure that they match.

```bash
$ cut -f1 Genome1.bed | sort -u
$ cut -f1 Genome2.bed | sort -u
```

They should match what you specify in the `seqids` file. Also, why are you repeating `pGenome1-1,pGenome2-2` on both lines?

Haibao

**Comment by PizzaKid** [comment]
@tanghaibao 

`Also, why are you repeating pGenome1-1,pGenome2-2 on both lines?`
Sorry I made a typing error while replacing the real names! Seqids-file with real names looks like:
```text
pBPS33-1,pBPS33-2
pPBL-H3-1,pPBL-H3-2
```

layout:
```text
# y, xstart, xend, rotation, color, label, va,  bed
 .6,     .3,    .9,       0,      , pBPS33, top, BPS33.bed 
 .4,     .3,    .9,       0,      , pPBL-H3, top, PBL-H3.bed 
# edges
e, 0, 1, BPS33.PBL-H3.anchors.simple
```

.bed-files:

> ```bash
> $ cut -f1 BPS33.bed | sort -u  
> ```

```bash
chrBPS33
pBPS33-1
pBPS33-2
```

> ```
> $ cut -f1 Genome2.bed | sort -u
> ```

```
chrPBL-H3
pPBL-H3-1
pPBL-H3-2
```

Also: Is there any possibility to display gene-names?

**Comment by tanghaibao** [comment]
@PizzaKid 
I don't see anything that would prevent labels from getting shown...`pBPS33-1` will show up as `331` since the plotter will strip all the non-digit letters (it was intended to plot something like `chr1`, `chr2`, ..`scaffold_001` etc). If you still can't see the labels, feel free to send your input files and I can take a look.

Also, not possible to display gene names.

Haibao
