### ISSUE TITLE
Microsynteny - IndexError: list index out of range 

### ISSUE THREAD

**Issue by PizzaKid** [tanghaibao/jcvi#129]
Dear @tanghaibao  

I executed the following commands as you described in MCscan documentation:

```bash
$ python -m jcvi.compara.synteny mcscan BPS33.bed BPS33.PBL-H3.lifted.anchors -o BPS33.PBL-H3.i1.blocks
$ head -50 BPS33.PBL-H3.i1.blocks > blocks 
$ cat BPS33.bed PBL-H3.bed > BPS33_PBL-H3.bed
$ python -m jcvi.graphics.synteny BPS33.PBL-H3.i1.blocks BPS33_PBL-H3.bed blocks.layout
```
The last one throws the following error:
```bash 
Column 0: fig|47420.13.peg.1 - fig|47420.13.peg.6465 (None:1-106863)
  None .. 10621 (6465) features .. +
Column 1: fig|434010.4.peg.1 - fig|434010.4.peg.4613 (None:1-97832)
  None .. 5078 (2835) features .. +
Column 2: fig|434010.4.peg.33 - fig|434010.4.peg.4620 (None:38406-103244)
  None .. 5053 (182) features .. +
Column 3: fig|434010.4.peg.1462 - fig|434010.4.peg.3921 (chrPBL-H3:1499314-4164354)
  chrPBL-H3 .. 2460 (23) features .. +
Traceback (most recent call last):
  File "/data/bioconda/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/data/bioconda/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/data/bioconda/lib/python2.7/site-packages/jcvi/graphics/synteny.py", line 403, in <module>
    main()
  File "/data/bioconda/lib/python2.7/site-packages/jcvi/graphics/synteny.py", line 392, in main
    scalebar=opts.scalebar)
  File "/data/bioconda/lib/python2.7/site-packages/jcvi/graphics/synteny.py", line 285, in __init__
    r = Region(root, ext, lo[i], bed, scale, switch,
IndexError: list index out of range
```

Can you tell what went wrong?
  
Also: Is there a possibility to specify the area for local synteny other than ```head -50```? I just want to look at a certain contig.

Thank you!

**Comment by tanghaibao** [comment]
@PizzaKid 

It's a bit hard to say what went wrong, it could be in both layout file or the bed file. Your gene names contain "|" in them - these can also create issues.

With regards to the area for local synteny other than `head` - yes! That first 50 lines was just an example. Of course you can choose any section in the file.

**Comment by EvoEpi** [comment]
@PizzaKid and @tanghaibao

Did this issue get resolved? I am experiencing the same error...

```bash
Column 0: AmTr_v6.0_c1.2350 - AmTr_v6.0_c1.2840 (AT_V6_CHR01:3887750-4917767)
  AT_V6_CHR01 .. 50 (50) features .. +
Column 1: CorFlo20856-RA - CorFlo20876-RA (Contig2:26264314-26636264)
  Contig2 .. 18 (12) features .. -
Column 2: CorFlo28703-RA - CorFlo28715-RA (Contig6:118089014-118214418)
  Contig6 .. 13 (12) features .. -
Traceback (most recent call last):
  File "/anaconda2/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/anaconda2/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/Users/dave/jcvi/jcvi/graphics/synteny.py", line 403, in <module>
    main()
  File "/Users/dave/jcvi/jcvi/graphics/synteny.py", line 392, in main
    scalebar=opts.scalebar)
  File "/Users/dave/jcvi/jcvi/graphics/synteny.py", line 285, in __init__
    r = Region(root, ext, lo[i], bed, scale, switch,
IndexError: list index out of range
```

**Comment by tanghaibao** [comment]
@EvoEpi 

This error is due to the plotter not able to find the layout for a certain column. 

One thing to check is your `layout` file contains one line for each column in the `blocks` file. In your case, the plotter fails on the 4th column, suggesting that your layout file only contains 3 lines in it.

For example, if you take a look at this `blocks` file, you see it has 3 columns.

```
GSVIVT01012255001	ppa000919m	Thecc1EG011472t1
GSVIVT01012253001	ppa010733m	Thecc1EG011473t1
GSVIVT01012252001	ppa015194m	Thecc1EG011474t1
```

The `layout` file now must have 3 lines (before the line `# edges`), one line for each of the columns in `blocks`.

```
# x,   y, rotation,     ha,     va, color, ratio,            label
0.5, 0.6,        0, center,    top,      ,     1,       grape Chr1
0.3, 0.4,        0, center, bottom,      ,    .5, peach scaffold_1
0.7, 0.4,        0, center, bottom,      ,    .5, cacao scaffold_2
# edges
e, 0, 1
e, 0, 2
```

**Comment by EvoEpi** [comment]
@tanghaibao

That makes perfect sense, and adding in additional lines based on `iter` value resolves the error.

Many thanks!

**Comment by U201412486** [comment]
@tanghaibao 
Hi,I am experiencing the same error.
`23:46:28 [base] Load file `gp.bed`
23:46:28 [base] Load file `sl.bed`
Traceback (most recent call last):
  File "/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/lib/python3.7/site-packages/jcvi/compara/catalog.py", line 939, in <module>
    main()
  File "/lib/python3.7/site-packages/jcvi/compara/catalog.py", line 80, in main
    p.dispatch(globals())
  File "/lib/python3.7/site-packages/jcvi/apps/base.py", line 111, in dispatch
    globals[action](sys.argv[2:])
  File "/lib/python3.7/site-packages/jcvi/compara/catalog.py", line 687, in ortholog
    blastfilter_main([last, "--cscore={0}".format(ccscore), "--no_strip_names"])
  File "/lib/python3.7/site-packages/jcvi/compara/blastfilter.py", line 274, in main
    blastfilter_main(blastfile, p, opts)
  File "/python3.7/site-packages/jcvi/compara/blastfilter.py", line 40, in blastfilter_main
    qbed, sbed, qorder, sorder, is_self = check_beds(blast_file, p, opts)
  File "/lib/python3.7/site-packages/jcvi/compara/synteny.py", line 506, in check_beds
    sbed = Bed(opts.sbed, sorted=sorted)
  File "/lib/python3.7/site-packages/jcvi/formats/bed.py", line 148, in __init__
    b = BedLine(line)
  File "/lib/python3.7/site-packages/jcvi/formats/bed.py", line 51, in __init__
    self.start = int(args[1]) + 1
IndexError: list index out of range
`
And my gp.bed looks like this.
`
chr1    5929    6197    chr1.1  0       +
chr1    8708    13978   chr1.2  0       -
chr1    30427   36634   chr1.3  0       -
chr1    55085   72398   chr1.4  0       +
chr1    296491  298464  chr1.11 0       +
chr1    494900  514634  chr1.14 0       -
chr1    535290  539522  chr1.18 0       +
chr1    544124  553523  chr1.19 0       +
chr1    553757  558213  chr1.20 0       -
chr1    562328  577556  chr1.21 0       +
chr1    578382  585267  chr1.22.1.5dee199e      0       +
chr1    586761  623096  chr1.23.1.5dee199f      0       +
`
my sl.bed look like this.
`
chr10 42784871 42785477 XP_025888968.1 . +
chr10 41765252 41769334 XP_025888967.1 . -
chr10 35332976 35334130 XP_025888964.1 . +
chr10 26959649 26962461 XP_025888960.1 . +
chr10 26957033 26958369 XP_025888959.1 . -
chr10 24392368 24398685 XP_025888957.1 . -
chr10 23526223 23529191 XP_025888955.1 . +
chr10 19168683 19170249 XP_025888954.1 . +
chr1 91831712 91842329 XP_025888952.1 . +
chr10 13083208 13083676 XP_025888948.1 . -
chr10 9148364 9150611 XP_025888941.1 . +
chr9 11026922 11027326 XP_025888888.1 . +
chr9 1415472 1415895 XP_025888884.1 . -
`

**Comment by tanghaibao** [comment]
@U201412486 

Please check to see if your BED file is separated by TAB ('\t'), not space.

Haibao

**Comment by U201412486** [comment]
Thank you.your advice works.However it report the error when I run the code.
 `python3 -m jcvi.compara.catalog ortholog --dbtype=prot --no_strip_names A B`
  `Failed to init heights (error: Failed to parse /usr/share/texmf/fonts/enc/dvips/base/8r.enc as Postscript encoding). Variable label sizes skipped.
`
Does the error matter ?

**Comment by tanghaibao** [comment]
@U201412486 

This error does not matter. As the error suggests, the dot plot won't be able to show contig/chromosome labels (the texts along the x-axis and y-axis on top and right of the scatter plot) with different sizes and will be all of the same sizes. This is just a visual difference.

**Comment by U201412486** [comment]
many thanks.
