### ISSUE TITLE
output is mixing linkage groups

### ISSUE THREAD

**Issue by pdimens** [tanghaibao/jcvi#131]
Good afternoon,

I have been trying to run allmaps, but the output pdf's for our data seem to indicated that multiple LG's are being mapped onto a single chromosome as shown in the image below:

![image](https://user-images.githubusercontent.com/19176506/57487452-386ebe80-7276-11e9-9075-cc87dd1dd845.png)

It is unclear why this is happening, as we have tested this on the provided test data without issue, and on another dataset without issue. Mapping distances were generated using `Lepmap3` and converted into CSV using a custom script and marker positions provided by `vcftools`, and the format follows the convention:
```
Cneb00004748,137875,7,0
Cneb00004115,67566,7,4.538
Cneb00003206,236520,7,21.786
Cneb00002416,260672,7,23.511
Cneb00010985,287083,7,23.511
Cneb00005487,43859,7,23.511
Cneb00005498,8907,7,23.511
Cneb00010811,141183,7,23.727
Cneb00010811,136587,7,23.727
Cneb00006428,29607,7,23.942
Cneb00000893,971225,7,24.158
Cneb00002036,515033,7,24.158
Cneb00007740,4077,7,24.158
Cneb00002039,192614,7,24.158
```

the resulting `.bed` file looks like
```
Cneb00000192	42016	42017	sexaverage_distances_ALLMAPS-9:13.711000	Cneb00000192:42017
Cneb00000192	42131	42132	sexaverage_distances_ALLMAPS-9:14.358000	Cneb00000192:42132
Cneb00000192	46813	46814	sexaverage_distances_ALLMAPS-9:21.470000	Cneb00000192:46814
Cneb00000216	19301	19302	sexaverage_distances_ALLMAPS-4:22.958000	Cneb00000216:19302
Cneb00000216	103245	103246	sexaverage_distances_ALLMAPS-4:25.328000	Cneb00000216:103246
Cneb00000216	103258	103259	sexaverage_distances_ALLMAPS-4:35.027000	Cneb00000216:103259
Cneb00000216	103481	103482	sexaverage_distances_ALLMAPS-4:25.328000	Cneb00000216:103482
Cneb00000216	171993	171994	sexaverage_distances_ALLMAPS-4:25.328000	Cneb00000216:171994
Cneb00000216	179291	179292	sexaverage_distances_ALLMAPS-4:25.328000	Cneb00000216:179292
Cneb00000216	179294	179295	sexaverage_distances_ALLMAPS-4:25.544000	Cneb00000216:179295
Cneb00000216	199326	199327	sexaverage_distances_ALLMAPS-4:25.544000	Cneb00000216:199327
Cneb00000216	223043	223044	sexaverage_distances_ALLMAPS-4:22.958000	Cneb00000216:223044
```

Looking at open and closed issues, I have been unable to find anyone with a similar issue and hoped that perhaps you had insight as to what may be going on?

Thank you,

Pavel

**Comment by agroppi** [comment]
Hi @pdimens did you find out what was going on ?
I had the same "bug" here : 
![Capture d’écran 2021-03-25 120553](https://user-images.githubusercontent.com/5609985/112464199-7c341980-8d63-11eb-9e50-9cc56cf37fc8.JPG)

@tanghaibao any idea ?

Thanks

Cheers from Bordeaux (France) ;)

**Comment by pdimens** [comment]
Unfortunately I haven't. I was under the impression it might be chimeric contigs, so I kept redoing my assembly. When I tried the misassemby methods proposed in the wiki and reran it, it was substantially worse. I'm still at a standstill with this :(

**Comment by tanghaibao** [comment]
@agroppi 

The reason that "-6" is shown here is that it is best aligned to chr5. Take a look at other figures and see if you find "-6" somewhere else.

While you can't easily remove the influence "-6" during assembly, you can remove it from the figure by using the option "--links 20", thereby plotting all alignments with more than 20 markers (default is 10, I counted that there were just over 10 markers for "-6"). Judging by the small number of aligned markers, the influence should be pretty minor.

**Comment by tanghaibao** [comment]
@pdimens 

Sorry that I overlooked your issue earlier, the assembly that you have isn't as bad as you think based on the figure. If you do "--links 20" or 30, it will substantially clear up this visualization.

The real question is why are these linkage groups get partitioned together but they don't seem to have many informative markers to offer. This isn't a partition error --  the partition algorithm looks for the best partition they should land -- so there really isn't a better place for them to go.

I'd suggest identifying those linkage groups or maps that don't seem to help and remove them from the input.

**Comment by agroppi** [comment]
@tanghaibao thanks for your answer and advice.
It worked perfectly.

By the way while trying to solve this problem by using the most up to date version of JVCI (1.1.10), I had this issue #363 

Thanks again

Best

Alexis
