### ISSUE TITLE
User warning: Glyph may be wrong

### ISSUE THREAD

**Issue by hyl317** [tanghaibao/jcvi#135]
When I was following the demo, I got the follwoing user warnings. It seems to be from the matplotlib. Although I can still get the final pdf output, I'd like to know what the warning mean exactly and how I might fix it. Thanks!

yh362@mocha:~/work/MCscan$ python -m jcvi.compara.catalog ortholog grape peach
16:27:00 [driver] Generating grammar tables from /usr/lib/python2.7/lib2to3/Gram                                                                             mar.txt
16:27:00 [driver] Generating grammar tables from /usr/lib/python2.7/lib2to3/Patt                                                                             ernGrammar.txt
16:27:00 [base] lastdb peach peach.cds
16:27:25 [base] lastal -u 0 -P 64 -i3G -f BlastTab peach grape.cds >grape.peach.                                                                             last
16:27:38 [synteny] Assuming --qbed=grape.bed --sbed=peach.bed
16:27:38 [base] Load file `grape.bed`
16:27:39 [base] Load file `peach.bed`
16:27:40 [blastfilter] Load BLAST file `grape.peach.last` (total 403868 lines)
16:27:40 [base] Load file `grape.peach.last`
16:27:47 [blastfilter] running the cscore filter (cscore>=0.70) ..
16:27:48 [blastfilter] after filter (294217->31226) ..
16:27:48 [blastfilter] running the local dups filter (tandem_Nmax=10) ..
16:27:48 [blastfilter] after filter (31226->21087) ..
16:27:49 [synteny] Assuming --qbed=grape.bed --sbed=peach.bed
16:27:49 [base] Load file `grape.bed`
16:27:49 [base] Load file `peach.bed`
16:27:50 [base] Load file `grape.peach.last.filtered`
16:27:51 [synteny] A total of 21087 BLAST imported from `grape.peach.last.filter                                                                             ed`.
16:27:51 [synteny] Chaining distance = 20
16:27:51 [base] Load file `grape.peach.anchors`
A total of 14695 (NR:14578) anchors found in 678 clusters.
Stats: Min=4 Max=385 N=678 Mean=21.6740412979 SD=39.560620805 Median=7.0 Sum=146                                                                             95
NR stats: Min=4 Max=383 N=678 Mean=21.5014749263 SD=39.355416627 Median=7.0 Sum=                                                                             14578
16:27:51 [base] Load file `grape.bed`
16:27:52 [base] Load file `peach.bed`
16:27:53 [base] Load file `grape.peach.last`
16:27:59 [synteny] A total of 294217 BLAST imported from `grape.peach.last`.
16:28:00 [base] Load file `grape.peach.anchors`
16:28:01 [synteny] A total of 14695 anchors imported.
16:28:02 [synteny] 15966 new pairs found.
16:28:02 [synteny] Removed 7 existing anchors.
16:28:02 [synteny] Corrected scores for 904 anchors.
16:28:02 [synteny] Anchors written to `grape.peach.lifted.anchors`.
16:28:02 [base] Load file `grape.peach.lifted.anchors`
A total of 30654 (NR:18661) anchors found in 678 clusters.
Stats: Min=4 Max=683 N=678 Mean=45.2123893805 SD=80.8407828815 Median=16.0 Sum=3                                                                             0654
NR stats: Min=4 Max=460 N=678 Mean=27.5235988201 SD=48.0461479616 Median=11.0 Su                                                                             m=18661
16:28:03 [synteny] Assuming --qbed=grape.bed --sbed=peach.bed
16:28:03 [base] Load file `grape.bed`
16:28:03 [base] Load file `peach.bed`
16:28:05 [dotplot] Showing a random subset of 10000 data points (total 14695) fo                                                                             r clarity.
16:28:05 [dotplot] xsize=26346 ysize=28701
/usr/local/lib/python2.7/dist-packages/matplotlib/textpath.py:389: UserWarning:                                                                              The glyph (99) of font (/usr/share/texlive/texmf-dist/fonts/type1/urw/helvetic/u                                                                             hvr8a.pfb) cannot be converted with the encoding. Glyph may be wrong
  "be wrong" % (glyph, font_bunch.filename))
/usr/local/lib/python2.7/dist-packages/matplotlib/textpath.py:389: UserWarning:                                                                              The glyph (104) of font (/usr/share/texlive/texmf-dist/fonts/type1/urw/helvetic/                                                                             uhvr8a.pfb) cannot be converted with the encoding. Glyph may be wrong
  "be wrong" % (glyph, font_bunch.filename))
/usr/local/lib/python2.7/dist-packages/matplotlib/textpath.py:389: UserWarning:                                                                              The glyph (114) of font (/usr/share/texlive/texmf-dist/fonts/type1/urw/helvetic/                                                                             uhvr8a.pfb) cannot be converted with the encoding. Glyph may be wrong
  "be wrong" % (glyph, font_bunch.filename))
/usr/local/lib/python2.7/dist-packages/matplotlib/textpath.py:389: UserWarning:                                                                              The glyph (48) of font (/usr/share/texlive/texmf-dist/fonts/type1/urw/helvetic/u                                                                             hvr8a.pfb) cannot be converted with the encoding. Glyph may be wrong
  "be wrong" % (glyph, font_bunch.filename))
/usr/local/lib/python2.7/dist-packages/matplotlib/textpath.py:389: UserWarning:                                                                              The glyph (49) of font (/usr/share/texlive/texmf-dist/fonts/type1/urw/helvetic/u                                                                             hvr8a.pfb) cannot be converted with the encoding. Glyph may be wrong
  "be wrong" % (glyph, font_bunch.filename))
16:28:27 [dotplot] Dot plot title: Inter-genomic comparison: grape vs peach (14,                                                                             695 gene pairs)
16:28:36 [base] savefig failed. Reset usetex to False.
[Errno 2] No such file or directory: 'dvipng'
/usr/local/lib/python2.7/dist-packages/matplotlib/font_manager.py:1316: UserWarn                                                                             ing: findfont: Font family [u'sans-serif'] not found. Falling back to DejaVu San                                                                             s
  (prop.get_family(), self.defaultFamily[fontext]))
16:28:44 [base] Figure saved to `grape.peach.pdf` (720px x 720px)

**Comment by crisvives** [comment]
Hi @hyl317 
I have got the same problem, and I figured out that Latex software is required:
pdfTeX home page: <http://pdftex.org>
Hope it is useful for you,
Cristina

**Comment by LHXqwq** [comment]
Do you solve your problem?I met the same problem and I don't know how to da
