### ISSUE TITLE
Reproducibility problem

### ISSUE THREAD

**Issue by francicco** [tanghaibao/jcvi#140]
Hi,

I'm desperately trying to reproduce my results, since I did a small change in the assembly before running AllMaps, and unfortunately results are differente of chromosome is over scaffolded. I'm wondering if I'm doing something wrong with my script.

```
python -m jcvi.assembly.allmaps merge $LinkMAP.csv -o $LinkMAP.bed
python -m jcvi.assembly.allmaps split $LinkMAP.bed --chunk=4 > $LinkMAP.breakpoints.bed
python -m jcvi.formats.fasta gaps $ASSEMBLY.fasta
python -m jcvi.assembly.patch refine --closest $LinkMAP.breakpoints.bed $ASSEMBLY.gaps.bed
python -m jcvi.formats.sizes agp $ASSEMBLY.fasta
python -m jcvi.formats.agp mask $ASSEMBLY.fasta.agp $ASSEMBLY.gaps.bed --splitobject --splitsingle
python -m jcvi.formats.agp build $ASSEMBLY.fasta.masked.agp $ASSEMBLY.fasta $ASSEMBLY.SPLIT.fasta
python -m jcvi.assembly.allmaps path --renumber --cpus=$THREADS --ngen=1000 $LinkMAP.bed $ASSEMBLY.SPLIT.fasta
```

Am I doing something wrong?
Thanks
F

**Comment by tanghaibao** [comment]
@francicco 

The workflow seems fine. Have you looked at the graphical output (PDF) to determine whether the new run is good or not? Since you mentioned "... results are differente of chromosome is over scaffolded". I assume the results are a lot worse than before? Also, are you using the same ALLMAPS version before and after?

Haibao

**Comment by francicco** [comment]
is this line correct?

`python -m jcvi.assembly.allmaps path --renumber --cpus=$THREADS --ngen=1000 $LinkMAP.bed $ASSEMBLY.SPLIT.fasta`

I'm a bit confused now where all other file are used? 
When I use `$ASSEMBLY.SPLIT.fasta` instead of `$ASSEMBLY.fasta` I get an error:

```
>chr32 (EisaPacBio-32) FINAL
Scf0000482? Scf0000224? Scf0000408? Scf0000141+ Scf0000295?
Traceback (most recent call last):
  File "/usr/lib64/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib64/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/fc464/software/jcvi/jcvi_env/lib/python2.7/site-packages/jcvi/assembly/allmaps.py", line 1871, in <module>
    main()
  File "/home/fc464/software/jcvi/jcvi_env/lib/python2.7/site-packages/jcvi/assembly/allmaps.py", line 827, in main
    p.dispatch(globals())
  File "/home/fc464/software/jcvi/jcvi_env/lib/python2.7/site-packages/jcvi/apps/base.py", line 96, in dispatch
    globals[action](sys.argv[2:])
  File "/home/fc464/software/jcvi/jcvi_env/lib/python2.7/site-packages/jcvi/assembly/allmaps.py", line 1494, in path
    chrsizes[s.object] = sum(sizes[x] for (x, o) in s.tour) + \
  File "/home/fc464/software/jcvi/jcvi_env/lib/python2.7/site-packages/jcvi/assembly/allmaps.py", line 1494, in <genexpr>
    chrsizes[s.object] = sum(sizes[x] for (x, o) in s.tour) + \
KeyError: 'Scf0000025'
```

ALLMAPS version is the same and the results are all comparable but that chromosome.

This is the previous result
![circos EisaHmel](https://user-images.githubusercontent.com/9006870/59862971-b8ab3800-937b-11e9-8e0d-40fcbd6f1016.png)

This is the new
![circos](https://user-images.githubusercontent.com/9006870/59863028-d7113380-937b-11e9-8a92-da817e148723.png)
As you can see for `chr2`, it is badly put together.

F
