### ISSUE TITLE
Color of interchromosomal connections

### ISSUE THREAD

**Issue by fantasticair** [tanghaibao/jcvi#144]
Hello,haibao
If I want to get the picture below, how to set the color of the middle line？
![QQ截图20190710153832](https://user-images.githubusercontent.com/35028002/60949952-cde70700-a328-11e9-8774-481b87780670.png)

**Comment by tanghaibao** [comment]
@fantasticair 

Yes, it is possible but a little tedious to specify all the colors in the input file. If you go through the [tutorial](https://github.com/tanghaibao/jcvi/wiki/MCscan-(Python-version)#macrosynteny-visualization), you may notice how we can specifically highlight one block (in the tutorial example, a single block was colored green by specifying `g*` in the `.simple` file). Just repeat this for all blocks and use different color symbols for each block.

Haibao

**Comment by fantasticair** [comment]
thank  you !
