### ISSUE TITLE
OSError: [Errno 2] No such file or directory: 'latex'

### ISSUE THREAD

**Issue by VickeyH** [tanghaibao/jcvi#146]
python -m jcvi.graphics.blastplot aly_ath.blast.filtered --sbed ath.bed --qbed aly.bed
23:38:59 [base] File `aly.sizes` already exists. Skipped.
23:38:59 [base] Load file `aly.bed`
23:39:00 [base] File `ath.sizes` already exists. Skipped.
23:39:00 [base] Load file `ath.bed`
23:39:00 [base] Load file `aly.sizes`
23:39:00 [base] Load file `ath.sizes`
23:39:00 [blastplot] xsize=200480144 ysize=119657994
23:39:01 [blastplot] xbreaks=437 ybreaks=7
23:39:02 [texmanager] serif font is not compatible with usetex.
23:39:02 [texmanager] serif font is not compatible with usetex.
23:39:02 [texmanager] family: serif, font: Computer Modern Roman, info: ('cmr', '')
23:39:02 [texmanager] family: sans-serif, font: Helvetica, info: ('phv', '\\usepackage{helvet}')
23:39:02 [texmanager] cursive font is not compatible with usetex.
23:39:02 [texmanager] cursive font is not compatible with usetex.
23:39:02 [texmanager] family: cursive, font: Zapf Chancery, info: ('pzc', '\\usepackage{chancery}')
23:39:02 [texmanager] monospace font is not compatible with usetex.
23:39:02 [texmanager] monospace font is not compatible with usetex.
23:39:02 [texmanager] family: monospace, font: Computer Modern Typewriter, info: ('cmtt', '')
23:39:02 [texmanager] following keys changed: ['text.latex.preamble', 'font.family', 'font.serif', 'font.sans-serif', 'font.cursive', 'font.monospace']
23:39:02 [texmanager] text.latex.preamble : None       -> []        
23:39:02 [texmanager] font.family         : None       -> ['sans-serif']
23:39:02 [texmanager] font.serif          : None       -> ['DejaVu Serif', 'Bitstream Vera Serif', 'Computer Modern Roman', 'New Century Schoolbook', 'Century Schoolbook L', 'Utopia', 'ITC Bookman', 'Bookman', 'Nimbus Roman No9 L', 'Times New Roman', 'Times', 'Palatino', 'Charter', 'serif']
23:39:02 [texmanager] font.sans-serif     : None       -> ['Helvetica']
23:39:02 [texmanager] font.cursive        : None       -> ['Apple Chancery', 'Textile', 'Zapf Chancery', 'Sand', 'Script MT', 'Felipa', 'cursive']
23:39:02 [texmanager] font.monospace      : None       -> ['DejaVu Sans Mono', 'Bitstream Vera Sans Mono', 'Computer Modern Typewriter', 'Andale Mono', 'Nimbus Mono L', 'Courier New', 'Courier', 'Fixed', 'Terminal', 'monospace']
23:39:02 [texmanager] RE-INIT
old fontconfig: sans-serifcmrphvpzccmttd41d8cd98f00b204e9800998ecf8427e
23:39:02 [texmanager] serif font is not compatible with usetex.
23:39:02 [texmanager] serif font is not compatible with usetex.
23:39:02 [texmanager] family: serif, font: Computer Modern Roman, info: ('cmr', '')
23:39:02 [texmanager] family: sans-serif, font: Helvetica, info: ('phv', '\\usepackage{helvet}')
23:39:02 [texmanager] cursive font is not compatible with usetex.
23:39:02 [texmanager] cursive font is not compatible with usetex.
23:39:02 [texmanager] family: cursive, font: Zapf Chancery, info: ('pzc', '\\usepackage{chancery}')
23:39:02 [texmanager] monospace font is not compatible with usetex.
23:39:02 [texmanager] monospace font is not compatible with usetex.
23:39:02 [texmanager] family: monospace, font: Computer Modern Typewriter, info: ('cmtt', '')
23:39:02 [texmanager] fontconfig: sans-serifcmrphvpzccmttd41d8cd98f00b204e9800998ecf8427e
23:39:02 [texmanager] fontconfig: sans-serifcmrphvpzccmttd41d8cd98f00b204e9800998ecf8427e
23:39:02 [texmanager] ['latex', '-interaction=nonstopmode', '--halt-on-error', '/share/workplace/home/off_liuxing/.cache/matplotlib/tex.cache/d2acc2706db635f7f7afe7dc80ac47f1.tex']
23:39:02 [base] savefig failed. Reset usetex to False.
[Errno 2] No such file or directory: 'latex'
/share/workplace/home/off_liuxing/miniconda3/envs/python2/lib/python2.7/site-packages/matplotlib/font_manager.py:1331: UserWarning: findfont: Font family [u'sans-serif'] not found. Falling back to DejaVu Sans
  (prop.get_family(), self.defaultFamily[fontext]))
23:39:02 [font_manager] findfont: Matching :family=DejaVu Sans:style=normal:variant=normal:weight=normal:stretch=normal:size=10.0 to DejaVu Sans (u'/share/workplace/home/off_liuxing/software/anaconda3/lib/python3.6/site-packages/matplotlib/mpl-data/fonts/ttf/DejaVuSans.ttf') with score of 0.050000
23:39:02 [font_manager] findfont: Matching :family=STIXGeneral:style=normal:variant=normal:weight=normal:stretch=normal:size=10.0 to STIXGeneral (u'/share/workplace/home/off_liuxing/software/anaconda3/lib/python3.6/site-packages/matplotlib/mpl-data/fonts/ttf/STIXGeneral.ttf') with score of 0.050000
23:39:02 [font_manager] findfont: Matching :family=STIXSizeOneSym:style=normal:variant=normal:weight=normal:stretch=normal:size=10.0 to STIXSizeOneSym (u'/share/workplace/home/off_liuxing/software/anaconda3/lib/python3.6/site-packages/matplotlib/mpl-data/fonts/ttf/STIXSizOneSymReg.ttf') with score of 0.050000
23:39:02 [font_manager] findfont: Matching :family=STIXGeneral:style=normal:variant=normal:weight=bold:stretch=normal:size=10.0 to STIXGeneral (u'/share/workplace/home/off_liuxing/software/anaconda3/lib/python3.6/site-packages/matplotlib/mpl-data/fonts/ttf/STIXGeneralBol.ttf') with score of 0.000000
23:39:02 [font_manager] findfont: Matching :family=STIXSizeThreeSym:style=normal:variant=normal:weight=normal:stretch=normal:size=10.0 to STIXSizeThreeSym (u'/share/workplace/home/off_liuxing/software/anaconda3/lib/python3.6/site-packages/matplotlib/mpl-data/fonts/ttf/STIXSizThreeSymReg.ttf') with score of 0.050000
23:39:02 [font_manager] findfont: Matching :family=STIXSizeFourSym:style=normal:variant=normal:weight=normal:stretch=normal:size=10.0 to STIXSizeFourSym (u'/share/workplace/home/off_liuxing/software/anaconda3/lib/python3.6/site-packages/matplotlib/mpl-data/fonts/ttf/STIXSizFourSymReg.ttf') with score of 0.050000
23:39:02 [font_manager] findfont: Matching :family=STIXSizeFiveSym:style=normal:variant=normal:weight=normal:stretch=normal:size=10.0 to STIXSizeFiveSym (u'/share/workplace/home/off_liuxing/software/anaconda3/lib/python3.6/site-packages/matplotlib/mpl-data/fonts/ttf/STIXSizFiveSymReg.ttf') with score of 0.050000
23:39:02 [font_manager] findfont: Matching :family=STIXSizeTwoSym:style=normal:variant=normal:weight=normal:stretch=normal:size=10.0 to STIXSizeTwoSym (u'/share/workplace/home/off_liuxing/software/anaconda3/lib/python3.6/site-packages/matplotlib/mpl-data/fonts/ttf/STIXSizTwoSymReg.ttf') with score of 0.050000
23:39:02 [font_manager] findfont: Matching :family=STIXGeneral:style=italic:variant=normal:weight=normal:stretch=normal:size=10.0 to STIXGeneral (u'/share/workplace/home/off_liuxing/software/anaconda3/lib/python3.6/site-packages/matplotlib/mpl-data/fonts/ttf/STIXGeneralItalic.ttf') with score of 0.050000
23:39:02 [font_manager] findfont: Matching :family=STIXNonUnicode:style=italic:variant=normal:weight=normal:stretch=normal:size=10.0 to STIXNonUnicode (u'/share/workplace/home/off_liuxing/software/anaconda3/lib/python3.6/site-packages/matplotlib/mpl-data/fonts/ttf/STIXNonUniIta.ttf') with score of 0.050000
23:39:02 [font_manager] findfont: Matching :family=STIXNonUnicode:style=normal:variant=normal:weight=normal:stretch=normal:size=10.0 to STIXNonUnicode (u'/share/workplace/home/off_liuxing/software/anaconda3/lib/python3.6/site-packages/matplotlib/mpl-data/fonts/ttf/STIXNonUni.ttf') with score of 0.050000
23:39:02 [font_manager] findfont: Matching :family=STIXNonUnicode:style=normal:variant=normal:weight=bold:stretch=normal:size=10.0 to STIXNonUnicode (u'/share/workplace/home/off_liuxing/software/anaconda3/lib/python3.6/site-packages/matplotlib/mpl-data/fonts/ttf/STIXNonUniBol.ttf') with score of 0.000000
23:39:02 [font_manager] findfont: Matching :family=cmb10:style=normal:variant=normal:weight=normal:stretch=normal:size=10.0 to cmb10 (u'/share/workplace/home/off_liuxing/software/anaconda3/lib/python3.6/site-packages/matplotlib/mpl-data/fonts/ttf/cmb10.ttf') with score of 0.050000
23:39:02 [font_manager] findfont: Matching :family=cmtt10:style=normal:variant=normal:weight=normal:stretch=normal:size=10.0 to cmtt10 (u'/share/workplace/home/off_liuxing/software/anaconda3/lib/python3.6/site-packages/matplotlib/mpl-data/fonts/ttf/cmtt10.ttf') with score of 0.050000
23:39:02 [font_manager] findfont: Matching :family=cmmi10:style=normal:variant=normal:weight=normal:stretch=normal:size=10.0 to cmmi10 (u'/share/workplace/home/off_liuxing/software/anaconda3/lib/python3.6/site-packages/matplotlib/mpl-data/fonts/ttf/cmmi10.ttf') with score of 0.050000
23:39:02 [font_manager] findfont: Matching :family=cmex10:style=normal:variant=normal:weight=normal:stretch=normal:size=10.0 to cmex10 (u'/share/workplace/home/off_liuxing/software/anaconda3/lib/python3.6/site-packages/matplotlib/mpl-data/fonts/ttf/cmex10.ttf') with score of 0.050000
23:39:02 [font_manager] findfont: Matching :family=cmsy10:style=normal:variant=normal:weight=normal:stretch=normal:size=10.0 to cmsy10 (u'/share/workplace/home/off_liuxing/software/anaconda3/lib/python3.6/site-packages/matplotlib/mpl-data/fonts/ttf/cmsy10.ttf') with score of 0.050000
23:39:02 [font_manager] findfont: Matching :family=cmr10:style=normal:variant=normal:weight=normal:stretch=normal:size=10.0 to cmr10 (u'/share/workplace/home/off_liuxing/software/anaconda3/lib/python3.6/site-packages/matplotlib/mpl-data/fonts/ttf/cmr10.ttf') with score of 0.050000
23:39:02 [font_manager] findfont: Matching :family=cmss10:style=normal:variant=normal:weight=normal:stretch=normal:size=10.0 to cmss10 (u'/share/workplace/home/off_liuxing/software/anaconda3/lib/python3.6/site-packages/matplotlib/mpl-data/fonts/ttf/cmss10.ttf') with score of 0.050000
23:39:02 [font_manager] findfont: Matching :family=DejaVu Sans:style=normal:variant=normal:weight=bold:stretch=normal:size=10.0 to DejaVu Sans (u'/share/workplace/home/off_liuxing/software/anaconda3/lib/python3.6/site-packages/matplotlib/mpl-data/fonts/ttf/DejaVuSans-Bold.ttf') with score of 0.000000
23:39:02 [font_manager] findfont: Matching :family=DejaVu Sans Mono:style=normal:variant=normal:weight=normal:stretch=normal:size=10.0 to DejaVu Sans Mono (u'/share/workplace/home/off_liuxing/software/anaconda3/lib/python3.6/site-packages/matplotlib/mpl-data/fonts/ttf/DejaVuSansMono.ttf') with score of 0.050000
23:39:02 [font_manager] findfont: Matching :family=DejaVu Sans:style=italic:variant=normal:weight=normal:stretch=normal:size=10.0 to DejaVu Sans (u'/share/workplace/home/off_liuxing/software/anaconda3/lib/python3.6/site-packages/matplotlib/mpl-data/fonts/ttf/DejaVuSans-Oblique.ttf') with score of 0.150000
23:39:02 [font_manager] findfont: Matching :family=DejaVu Sans Display:style=normal:variant=normal:weight=normal:stretch=normal:size=10.0 to DejaVu Sans Display (u'/share/workplace/home/off_liuxing/software/anaconda3/lib/python3.6/site-packages/matplotlib/mpl-data/fonts/ttf/DejaVuSansDisplay.ttf') with score of 0.050000
23:39:02 [texmanager] serif font is not compatible with usetex.
23:39:02 [texmanager] serif font is not compatible with usetex.
23:39:02 [texmanager] family: serif, font: Computer Modern Roman, info: ('cmr', '')
23:39:02 [texmanager] family: sans-serif, font: Helvetica, info: ('phv', '\\usepackage{helvet}')
23:39:02 [texmanager] cursive font is not compatible with usetex.
23:39:02 [texmanager] cursive font is not compatible with usetex.
23:39:02 [texmanager] family: cursive, font: Zapf Chancery, info: ('pzc', '\\usepackage{chancery}')
23:39:02 [texmanager] monospace font is not compatible with usetex.
23:39:02 [texmanager] monospace font is not compatible with usetex.
23:39:02 [texmanager] family: monospace, font: Computer Modern Typewriter, info: ('cmtt', '')
23:39:02 [texmanager] following keys changed: ['text.latex.preamble', 'font.family', 'font.serif', 'font.sans-serif', 'font.cursive', 'font.monospace']
23:39:02 [texmanager] text.latex.preamble : None       -> []        
23:39:02 [texmanager] font.family         : None       -> ['sans-serif']
23:39:02 [texmanager] font.serif          : None       -> ['DejaVu Serif', 'Bitstream Vera Serif', 'Computer Modern Roman', 'New Century Schoolbook', 'Century Schoolbook L', 'Utopia', 'ITC Bookman', 'Bookman', 'Nimbus Roman No9 L', 'Times New Roman', 'Times', 'Palatino', 'Charter', 'serif']
23:39:02 [texmanager] font.sans-serif     : None       -> ['Helvetica']
23:39:02 [texmanager] font.cursive        : None       -> ['Apple Chancery', 'Textile', 'Zapf Chancery', 'Sand', 'Script MT', 'Felipa', 'cursive']
23:39:02 [texmanager] font.monospace      : None       -> ['DejaVu Sans Mono', 'Bitstream Vera Sans Mono', 'Computer Modern Typewriter', 'Andale Mono', 'Nimbus Mono L', 'Courier New', 'Courier', 'Fixed', 'Terminal', 'monospace']
23:39:02 [texmanager] RE-INIT
old fontconfig: sans-serifcmrphvpzccmttd41d8cd98f00b204e9800998ecf8427e
23:39:02 [texmanager] serif font is not compatible with usetex.
23:39:02 [texmanager] serif font is not compatible with usetex.
23:39:02 [texmanager] family: serif, font: Computer Modern Roman, info: ('cmr', '')
23:39:02 [texmanager] family: sans-serif, font: Helvetica, info: ('phv', '\\usepackage{helvet}')
23:39:02 [texmanager] cursive font is not compatible with usetex.
23:39:02 [texmanager] cursive font is not compatible with usetex.
23:39:02 [texmanager] family: cursive, font: Zapf Chancery, info: ('pzc', '\\usepackage{chancery}')
23:39:02 [texmanager] monospace font is not compatible with usetex.
23:39:02 [texmanager] monospace font is not compatible with usetex.
23:39:02 [texmanager] family: monospace, font: Computer Modern Typewriter, info: ('cmtt', '')
23:39:02 [texmanager] fontconfig: sans-serifcmrphvpzccmttd41d8cd98f00b204e9800998ecf8427e
23:39:02 [texmanager] fontconfig: sans-serifcmrphvpzccmttd41d8cd98f00b204e9800998ecf8427e
23:39:02 [texmanager] ['latex', '-interaction=nonstopmode', '--halt-on-error', '/share/workplace/home/off_liuxing/.cache/matplotlib/tex.cache/5bf06717c882fcd459d27f1eaff2bc60.tex']
Traceback (most recent call last):
  File "/share/workplace/home/off_liuxing/miniconda3/envs/python2/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/share/workplace/home/off_liuxing/miniconda3/envs/python2/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/share/workplace/home/off_liuxing/miniconda3/envs/python2/lib/python2.7/site-packages/jcvi/graphics/blastplot.py", line 304, in <module>
    savefig(image_name, dpi=iopts.dpi, iopts=iopts)
  File "/share/workplace/home/off_liuxing/miniconda3/envs/python2/lib/python2.7/site-packages/jcvi/graphics/base.py", line 188, in savefig
    plt.savefig(figname, dpi=dpi)
  File "/share/workplace/home/off_liuxing/miniconda3/envs/python2/lib/python2.7/site-packages/matplotlib/pyplot.py", line 695, in savefig
    res = fig.savefig(*args, **kwargs)
  File "/share/workplace/home/off_liuxing/miniconda3/envs/python2/lib/python2.7/site-packages/matplotlib/figure.py", line 2062, in savefig
    self.canvas.print_figure(fname, **kwargs)
  File "/share/workplace/home/off_liuxing/miniconda3/envs/python2/lib/python2.7/site-packages/matplotlib/backend_bases.py", line 2263, in print_figure
    **kwargs)
  File "/share/workplace/home/off_liuxing/miniconda3/envs/python2/lib/python2.7/site-packages/matplotlib/backends/backend_pdf.py", line 2586, in print_pdf
    self.figure.draw(renderer)
  File "/share/workplace/home/off_liuxing/miniconda3/envs/python2/lib/python2.7/site-packages/matplotlib/artist.py", line 55, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)
  File "/share/workplace/home/off_liuxing/miniconda3/envs/python2/lib/python2.7/site-packages/matplotlib/figure.py", line 1493, in draw
    renderer, self, artists, self.suppressComposite)
  File "/share/workplace/home/off_liuxing/miniconda3/envs/python2/lib/python2.7/site-packages/matplotlib/image.py", line 141, in _draw_list_compositing_images
    a.draw(renderer)
  File "/share/workplace/home/off_liuxing/miniconda3/envs/python2/lib/python2.7/site-packages/matplotlib/artist.py", line 55, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)
  File "/share/workplace/home/off_liuxing/miniconda3/envs/python2/lib/python2.7/site-packages/matplotlib/axes/_base.py", line 2635, in draw
    mimage._draw_list_compositing_images(renderer, self, artists)
  File "/share/workplace/home/off_liuxing/miniconda3/envs/python2/lib/python2.7/site-packages/matplotlib/image.py", line 141, in _draw_list_compositing_images
    a.draw(renderer)
  File "/share/workplace/home/off_liuxing/miniconda3/envs/python2/lib/python2.7/site-packages/matplotlib/artist.py", line 55, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)
  File "/share/workplace/home/off_liuxing/miniconda3/envs/python2/lib/python2.7/site-packages/matplotlib/text.py", line 751, in draw
    mtext=mtext)
  File "/share/workplace/home/off_liuxing/miniconda3/envs/python2/lib/python2.7/site-packages/matplotlib/backends/backend_pdf.py", line 1919, in draw_tex
    dvifile = texmanager.make_dvi(s, fontsize)
  File "/share/workplace/home/off_liuxing/miniconda3/envs/python2/lib/python2.7/site-packages/matplotlib/texmanager.py", line 365, in make_dvi
    texfile], tex)
  File "/share/workplace/home/off_liuxing/miniconda3/envs/python2/lib/python2.7/site-packages/matplotlib/texmanager.py", line 335, in _run_checked_subprocess
    stderr=subprocess.STDOUT)
  File "/share/workplace/home/off_liuxing/miniconda3/envs/python2/lib/python2.7/site-packages/subprocess32.py", line 337, in check_output
    process = Popen(stdout=PIPE, *popenargs, **kwargs)
  File "/share/workplace/home/off_liuxing/miniconda3/envs/python2/lib/python2.7/site-packages/subprocess32.py", line 617, in __init__
    restore_signals, start_new_session)
  File "/share/workplace/home/off_liuxing/miniconda3/envs/python2/lib/python2.7/site-packages/subprocess32.py", line 1415, in _execute_child
    raise child_exception_type(errno_num, err_msg)
OSError: [Errno 2] No such file or directory: 'latex'
i have used 'pip install latex' to install latex and use whereis latex to check, but the error did not disappear. can anyone help?  Thanks in advance.

**Comment by tanghaibao** [comment]
@VickeyH 

As with Matplotlib (which is called from the library), we'll need a latex installation. 

https://matplotlib.org/users/usetex.html

Not sure if the pip command you tried correctly installed latex though. On Debian linux you can do:

```console
apt-get install -y texlive texlive-latex-extra texlive-latex-recommended
```

Google around for how you install latex on other OS.

Haibao

**Comment by VickeyH** [comment]
actually i think it will not work with root right
