### ISSUE TITLE
Manage with mummer output

### ISSUE THREAD

**Issue by AlexWanghaoming** [tanghaibao/jcvi#148]
Hi Dr.Tang，I have two genome assembly drafts without annotation. I have used mummer to make a global alignment. Next，I want to plot a linear synteny plot among scaffolds of the two assemblies. Which commands should I use? 
Thanks!

**Comment by tanghaibao** [comment]
@AlexWanghaoming 

Search for `mummerplot` - which is commonly used exactly for this purpose.

Haibao

**Comment by qiuyixmm** [comment]
@tanghaibao hello, i want to search synteny region cross whole genome not just limited to cds region.
For example,  i want to search synteny region cross whole genome among grape, peach and cacao and use  karyotype figure for visualization. Can i achieved it by using jcvi.
   The karyotype figure is very beautiful in MCscan (Python version) manual. What a pity is that cds sequences and gff3 file are required. If we just have some genome assembly drafts without annotation ,as mentioned above, can we use it ?

**Comment by qiuyixmm** [comment]
@tanghaibao  hello，mummerplot can just draw dotplot. It is feasible that we use your tools to do macrosynteny visualization and generate karyotype figure for output of mummer when there are only two draft genomes without annotation files, as mentioned above.
    Thanks !

**Comment by tanghaibao** [comment]
@qiuyixmm 

Currently this is not yet supported. This particular program was initially written to view relationships between large plant genomes where unfiltered whole genome alignments are often too dense.
