### ISSUE TITLE
question: cross-species synteny

### ISSUE THREAD

**Issue by StefanoLonardi** [tanghaibao/jcvi#15]
Do you have a recommendation on which tool to use to generate a cross-species synteny map? You mention in your wiki to use BLAST bidirectional hits between the two species. Thanks.

**Comment by tanghaibao** [comment]
@StefanoLonardi that's the easiest. There are other tools like i-ADHoRe or MCscan that are specialized in calling syntenic blocks. However, that's a beast in itself and outside the scope of this package.

**Comment by StefanoLonardi** [comment]
I am not sure what's the easiest ... maybe you left the name of the name of the tool out?

**Comment by tanghaibao** [comment]
@StefanoLonardi taking bidirectional BLAST hits may be the easiest
