### ISSUE TITLE
customize dotplot

### ISSUE THREAD

**Issue by MichelMoser** [tanghaibao/jcvi#152]
Hi, 
Is there an easy option to increase resolution (reduce size of the dots) in the synteny dotplots created by jcvi.graphics.dotplot. 

I could probably find the parameter in jcvi/graphics/dotplot.py but its kind of ugly to have it  hardcoded.
Wonder if its somewhere in styles option. Otherwise i could add it as an option.
Thanks, 
Michel

**Comment by tanghaibao** [comment]
@MichelMoser 

The default canvas size is `9x9` inches (option `--figsize`). I usually find that changing the canvas mostly could address my need. It is also important to know that the default output is `pdf` (option `--format`) -- this is a vector graphic format so the dot sizes are really quite discrete and vary widely between different values. If you want really fine-grained level of dot sizes, use `--format=png` instead.

That said, we can also change the dot sizes directly, please feel free to open a pull request and I'll merge that in.

Thanks,
Haibao
