### ISSUE TITLE
 jcvi.graphicscould not work

### ISSUE THREAD

**Issue by liufuyan2016** [tanghaibao/jcvi#159]
Dear profesor,

Beacause of I have not permission for my conputer. I install the jcvi use the command:

python setup.py install --user

All depndent package is installed　and the output  log showing the install is completely finished.
But the all functions of jcvi.graphics is could not be used. The error information is below:

/share/nas2/genome/biosoft/Python/2.7.8/bin/python -m jcvi.graphics.blastplot

 [blast] Fall back to Python implementation of BlastLine
Bus error

Could you help me ?Thank you!

**Comment by tanghaibao** [comment]
@liufuyan2016 

I have not seen this error before. Can you try installing the PyPI version?

```console
pip install jcvi --user
python -m jcvi.graphics.blastplot
```

Also, I am trying the switch the codebase to Python3 in the near future. Please try the same command using Python3.7 and see if it works.

Haibao
