### ISSUE TITLE
Draw dotplot for a certain chromosome

### ISSUE THREAD

**Issue by HengyouZhang** [tanghaibao/jcvi#166]
Hi, Haibao,

I have a big dotplot for a comparison of two plant species, including all chromosomes. I wonder is there a way to only dotplot a certain chromsome in a single plot, for example only output chr8 in A species vs chr9 in B species. I tried to keep chr8vschr9 block only in the .simple file, but it still outputs the big plot (all small plots) with only chr8vschr9 being plotted. 

Thanks in advance,
Hengyou

**Comment by tanghaibao** [comment]
@HengyouZhang 

Were you using this command?
```console
python -m jcvi.graphics.dotplot A.B.anchors
```

If so, just make smaller `.bed` files. For example, you can try:
```console
grep ^chr8 A.bed > A_chr8.bed
grep ^chr9 B.bed > B_chr9.bed
python -m jcvi.graphics.dotplot A.B.anchors --qbed=A_chr8.bed --sbed=B_chr9.bed
```

Haibao

**Comment by HengyouZhang** [comment]
Yes. This is great and very helpful, thank you.

Hengyou
