### ISSUE TITLE
Identifying Segmental and Tandem Duplications within a Genome

### ISSUE THREAD

**Issue by venuraherath** [tanghaibao/jcvi#167]
Hi Haibao,

I have two questions; hope you can help me in this regard.
1. I want to find seg. and tandem duplications within [potato genome](http://plants.ensembl.org/Solanum_tuberosum/Info/Index). Guide only shows how to conduct the analysis between genomes. May I know how I can find duplications within the genome?
2. Is there a way to import ensembel plant genome data directly similar to phytozome import?
Thank you!

**Comment by tanghaibao** [comment]
@venuraherath 

Unfortunately, neither functionalities currently exist in the library. If you write up something, feel free to contribute 😄

**Comment by venuraherath** [comment]
Thank you for the Reply @tanghaibao . 
One day when I ace programing :) I am still a grasshopper.
