### ISSUE TITLE
karyotype plot: changing chromosome length

### ISSUE THREAD

**Issue by MichelMoser** [tanghaibao/jcvi#168]
Hi @tanghaibao ,

I am currently playing with your awesome synteny visualization library and am wondering if I could change chromosome size of vertical chromosomes as in the plot here: 

![HIVE_Pike_CHR4_blunt](https://user-images.githubusercontent.com/4695665/67075998-9b04a880-f18c-11e9-9b75-285a59e1f098.jpg)

I could probably influence chromosome size with xstart and xend if they were spread horizontally, but those parameters dont influence chromosome length if rotated to 90° of course. 

If you could point me ruffly to the script and line number, where chromosome sizes in karyotype plots get computet, that would be great, so i can do some adjustments and maybe implement some relative size settings between chromosomes of different species. 

Thanks a lot, 
Michel

**Comment by tanghaibao** [comment]
@MichelMoser 

This is a nice figure!

The most relevant code piece to handle drawing is here:
https://github.com/tanghaibao/jcvi/blob/master/jcvi/graphics/karyotype.py#L174

Haibao
