### ISSUE TITLE
Flipped pseudomolecules in (alignment) Dotplot 

### ISSUE THREAD

**Issue by Semiramis-2019** [tanghaibao/jcvi#169]
I have aligned two pseudomolecules (same pseudomolecules) from two assemblies using nucmer in mummer. Both assemblies were anchored to pseudomolecules based on (almost) the same genetic map using Allmaps, but different sequencing and assembly approaches were used. The mummerplot using nucmer indicated the two pseudomolecules are flipped relative to each other. I was wondering if you might know why I observe this pattern only for this particular chromosome (considering the same genetic map is used for anchoring) and what is the solution to correct it? Is it related to pseudomolecule or scaffold construction? Could it be a plotting issue? I am writing all the different steps that I have taken so far to figure out the problem but have not been able to make a conclusion.

This is the Allmaps output for the pseudomolecule of interest (assembly1). I am not sure about the other one. 
![image](https://user-images.githubusercontent.com/56731614/67106442-42370f00-f190-11e9-9959-4fda7a385745.png)

1)	nucmer
MUMmer3.23/nucmer -l 100 --prefix= chr1_nucmer chr1_assembly_1.fasta chr1_assembly_2.fasta
MUMmer3.23/show-coords -rcl chr1_nucmer.delta > chr1_nucmer.delta.coords
MUMmer3.23/mummerplot chr1_nucmer.delta -R chr_assembly_1.fasta -Q chr1_assembly_2.fasta  --filter --layout -png -p chr1_nucmer
![image](https://user-images.githubusercontent.com/56731614/67106521-6abf0900-f190-11e9-817d-0ae062ab85f5.png)

2)	Reverse complemented one of the chromosomes (assembly1) because I assumed this pattern is due to difference in strand orientation, nucmer still generated a flipped alignment. (I also tried only reverse or only complementing one of the chromosomes but they did not generate any alignment)
![image](https://user-images.githubusercontent.com/56731614/67106685-b4a7ef00-f190-11e9-8c8d-194e1bff3aaa.png)

3)	When markers on the genetic map are blasted against both assemblies, the position of the markers is correct on both pseudomolecules and in concordance with genetic map positions.
![image](https://user-images.githubusercontent.com/56731614/67106944-27b16580-f191-11e9-9e1f-f67814f6490e.png)

4)	nucmer .coords plot in R
If I plot the .coords file _generated by nucmer_ in R, the pseudomolecules do not look flipped!  At this point I thought may be this is a plotting issue. so tried MUMer -mum and Last.
![image](https://user-images.githubusercontent.com/56731614/67106562-7f030600-f190-11e9-8182-b1b2d8fa809d.png)

5)	If -mum is used in MUMmer, the expected alignment is generated (not flipped)
MUMmer3.23/mummer -mum -b -c -l 100  chr1_assembly_1.fasta chr1_assembly_2.fasta
 > chr1.mums
MUMmer3.23/mummerplot -png --filter --layout --prefix= chr1.mums chr1.mums
![image](https://user-images.githubusercontent.com/56731614/67106795-e4ef8d80-f190-11e9-96cb-5d41ae867d65.png)

6)	When Last was used and the .maf file (converted to tab format) was plotted in R, both alignment situations (flipped and expected alignment) are observed in one plot! (I tried different -l values, 50,100, 1000 (1kb), and the 1kb gives the clearest plot but the other two also support the same pattern)
last-984
lastdb -P4 -uNEAR -R11 -c chr1_assembly_1.fasta
lastal chr1_assembly_1 -P10 -l1000 chr1_assembly_2.fasta > chr1_last_l1kb.maf
maf-convert tab chr1_last_l1kb.maf > chr1_last_l1kb.maf.txt
![image](https://user-images.githubusercontent.com/56731614/67107039-4adc1500-f191-11e9-9956-2693a4641004.png)

**Comment by tanghaibao** [comment]
@Semiramis-2019 

There seem to be multiple things going on here. 

First of all, I doubt it is a scaffolding issue since the ALLMAPS output looks great. Nice and collinear with the markers. Some of these dot plots (like 6) are probably due to plotting issues. It is difficult for me to sort out what the issue might be, since there are many factors at work here - aligners, plotters, etc.

I wouldn't be too worried about flipping, just remember the orientation of the chromosome is arbitrary. There is some sort of duplication towards the right half of the chromosomes, which I think might deserve more attention.

**Comment by Semiramis-2019** [comment]
Thank you for your prompt reply and your feedback. The only part that worries me is if this will cause issues in gene annotation (orientation of the genes).
