### ISSUE TITLE
warning: spaces in the .csv files will prevent ALLMAPS from completing

### ISSUE THREAD

**Issue by StefanoLonardi** [tanghaibao/jcvi#17]
I have been trying to figure out why ALLMAPS did not finish on one of my maps, then I realized that my .cvs file have spaces in them (after the commas). In this case, ALLMAPS will take " 1" (or " 2", or " 3") as the linkage group name, instead of "1", and it will fail at the end (after running the TSPs for all linkage groups). Just FYI.

**Comment by tanghaibao** [comment]
@StefanoLonardi thanks for the report. Fixed.
