### ISSUE TITLE
personalization on Macrosynteny visualization

### ISSUE THREAD

**Issue by HippoYI** [tanghaibao/jcvi#171]
Hi Dr. Tang,
    I noticed that  the lines between chromosomes can be highlighted using different color, but the color of the chromosomes were the same. If I want to draw two colors in one chromosome, with one block colored A,  another block colored B (because this chromosome were formed by recombination of ancient chromosomes), is this work can be done?
Just like this:
![1](https://user-images.githubusercontent.com/57170696/67839780-69e28b80-fb2f-11e9-9572-374c1410525e.png)

**Comment by tanghaibao** [comment]
@HippoYI 

This is a nice idea. I won't have time to work on this myself, but if you or others find the time to find a way to plot that, I'd be happy to merge it in.

Haibao

**Comment by mrmrwinter** [comment]
@HippoYI,

Did you ever make any progress on this?
