### ISSUE TITLE
some function of Mcscan or McscanX 

### ISSUE THREAD

**Issue by xizhesun** [tanghaibao/jcvi#176]
Hi  Dr. Tang
I try to find some function like "ColumnComparer.pl" in Mcscan, "KaKs calculator" in Mcscanx

but I cann't find it in the WIKI. Are these functions canceled in JCVI ?

best regards,
Xizhe

**Comment by tanghaibao** [comment]
@xizhesun 

There is a similar function to calculate Ka and Ks in the package - specifically `python -m jcvi.apps.ks` but it requires setting up a couple of external programs first ... and I don't have the time to write a full tutorial for it yet so it is not well supported at this point.

Haibao

**Comment by xizhesun** [comment]
thank you.
