### ISSUE TITLE
highlight the links in microsynteny

### ISSUE THREAD

**Issue by HengyouZhang** [tanghaibao/jcvi#177]
Hi, Haibao,

A quick question, is there any way I can highlight one or more syntenic links of interest between different chromosomes/species, like the green one in macrosynteny image?

Thank you
Hengyou

**Comment by tanghaibao** [comment]
@HengyouZhang 

Yes you can. It is similar to how you highlight links in the macrosynteny. For example, for a given `blocks` file (example below):

```
GSVIVT01012261001	.	.
GSVIVT01012259001	ppa005716m	.
GSVIVT01012258001	.	.
GSVIVT01012257001	ppa002846m	.
g*GSVIVT01012255001	ppa000919m	Thecc1EG011472t1
GSVIVT01012253001	ppa010733m	Thecc1EG011473t1
GSVIVT01012252001	ppa015194m	Thecc1EG011474t1
```

Note that one of the lines has `g*` at the beginning. This specifies that all pairwise links in this row will be highlighted as green. Please let me know if this doesn't work.

Haibao

**Comment by HengyouZhang** [comment]
Great, thank you, Haibao,

Hengyou


Hengyou Zhang, Ph.D
-----------------------
Postdoctoral Associate
Donald Danforth Plant Science Center, USDA
975 N Warson Rd, St. Louis, MO 63132
Tel: (314)-587-1450
Fax: (314)-587-1550
