### ISSUE TITLE
Inverse a chromosome in karyotype plot

### ISSUE THREAD

**Issue by gsun2unl** [tanghaibao/jcvi#178]
Hi Haibao, is there a way to reverse the plot of one or multiple chromosomes for karyotype plot? 
Like what I attached here, I want to reverse the two chromosomes in the upper panel so people won't be thinking there is a chromosomal inversion in this species. 
Thank you very much! 
![image](https://user-images.githubusercontent.com/32845401/69014358-12c22080-094f-11ea-82e6-c6c9fd924355.png)

**Comment by tanghaibao** [comment]
@gsun2unl 

In your `seqids` file, try append a `-` in the chromosome id that you want to invert, like so:

```console
chr2,chr4-,chr3-,chr1
```
It has been a while, please let me know if this doesn't work.

Haibao

**Comment by gsun2unl** [comment]
Thank you very much! It worked!
Sincerely,
Guangchao

On Mon, Nov 18, 2019 at 1:49 AM Haibao Tang <notifications@github.com>
wrote:

> @gsun2unl
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_gsun2unl&d=DwMCaQ&c=Cu5g146wZdoqVuKpTNsYHeFX_rg6kWhlkLF8Eft-wwo&r=bpPja-iLrguf4IhfTv-Rq9hsz9Rhz4Unof38pJsCvb4&m=tlVtJpsMqo6w9qiwJ7KeiGF2TsPq3wAEanOsET6GY8U&s=91KEws6yfcFwy8cJSpj1NJMlM_XnrQr6Sa7U4FFRLhI&e=>
>
> In your seqids file, try append a - in the chromosome id that you want to
> invert, like so:
>
> chr2,chr4-,chr3-,chr1
>
> It has been a while, please let me know if this doesn't work.
>
> Haibao
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_tanghaibao_jcvi_issues_178-3Femail-5Fsource-3Dnotifications-26email-5Ftoken-3DAH2S4WNKWGSQV5H4NMVDIIDQUJCJ5A5CNFSM4JOL3VS2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEEJQOBI-23issuecomment-2D554895109&d=DwMCaQ&c=Cu5g146wZdoqVuKpTNsYHeFX_rg6kWhlkLF8Eft-wwo&r=bpPja-iLrguf4IhfTv-Rq9hsz9Rhz4Unof38pJsCvb4&m=tlVtJpsMqo6w9qiwJ7KeiGF2TsPq3wAEanOsET6GY8U&s=MsK5t0RmbVBprlR6ynIBlJ96HDjSzd5YKavFmbQVjBg&e=>,
> or unsubscribe
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AH2S4WL6N35FKHOWVYEQINDQUJCJ5ANCNFSM4JOL3VSQ&d=DwMCaQ&c=Cu5g146wZdoqVuKpTNsYHeFX_rg6kWhlkLF8Eft-wwo&r=bpPja-iLrguf4IhfTv-Rq9hsz9Rhz4Unof38pJsCvb4&m=tlVtJpsMqo6w9qiwJ7KeiGF2TsPq3wAEanOsET6GY8U&s=ovFCLT8g5vdSzBL0V7LWtSApuN2K3suaL6P6c18XGAg&e=>
> .
>


-- 
Guangchao Sun
Post-doctoral research associate
Plant Science Innovation Center
University of Nebraska Lincoln
