### ISSUE TITLE
Issues running example data

### ISSUE THREAD

**Issue by Thijmen18** [tanghaibao/jcvi#179]
Dear all,

I am trying to run the example test data of ALLMAPS to see if everything is installed properly. Unfortunately immediately get the following error: 

sh run.sh
/usr/bin/python: No module named jcvi.assembly
/usr/bin/python: No module named jcvi.assembly

I initially thought jcvi.assembly needed to be installed with pip additionally but I was wrong here. And all my further attempts to run the test data failed.

Can someone help me here?

**Comment by Thijmen18** [comment]
Tried to edit the above message but couldn't. Just want to share the pip error I received:

Collecting jcvi.assembly
  Could not find a version that satisfies the requirement jcvi.assembly (from versions: )
No matching distribution found for jcvi.assembly

**Comment by tanghaibao** [comment]
@Thijmen18 

Did you install `jcvi`?

```console
pip install -U jcvi
```

Haibao

**Comment by Thijmen18** [comment]
Hi Haibao,

I did try this but this resulted in the following error:

Traceback (most recent call last):
  File "/usr/bin/pip2", line 9, in <module>
    load_entry_point('pip==8.1.1', 'console_scripts', 'pip2')()
  File "/usr/lib/python2.7/dist-packages/pip/__init__.py", line 215, in main
    locale.setlocale(locale.LC_ALL, '')
  File "/usr/lib/python2.7/locale.py", line 581, in setlocale
    return _setlocale(category, locale)
locale.Error: unsupported locale setting

I realise this seems more like a pip problem, but still didn't find a solution though. If you do know whats going on here, please let me know!

**Comment by tanghaibao** [comment]
@Thijmen18 

Might as well use Python 3 (since Python 2 will be deprecated this year). I am very happy with Miniconda (https://docs.conda.io/en/latest/miniconda.html). After installing miniconda, do the pip install again to see if it works.

Haibao

**Comment by Thijmen18** [comment]
Ha! Great, after installing miniconda it did work.. Thanks!
Did got another error will try to solve this myself of course, I have the impression that there is still a problem with the jcvi.. If I find a solution I will post it here.

Just for completeness, and if you do know what the problem is that results in this error please let me know:

/bin/bash: liftOver: command not found
Traceback (most recent call last):
  File "/home/thijmen/miniconda3/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/thijmen/miniconda3/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/thijmen/miniconda3/lib/python3.7/site-packages/jcvi/assembly/allmaps.py", line 1872, in <module>
    main()
  File "/home/thijmen/miniconda3/lib/python3.7/site-packages/jcvi/assembly/allmaps.py", line 828, in main
    p.dispatch(globals())
  File "/home/thijmen/miniconda3/lib/python3.7/site-packages/jcvi/apps/base.py", line 100, in dispatch
    globals[action](sys.argv[2:])
  File "/home/thijmen/miniconda3/lib/python3.7/site-packages/jcvi/assembly/allmaps.py", line 1519, in path
    build([inputbed, fastafile])
  File "/home/thijmen/miniconda3/lib/python3.7/site-packages/jcvi/assembly/allmaps.py", line 1645, in build
    sh(cmd, check=True)
  File "/home/thijmen/miniconda3/lib/python3.7/site-packages/jcvi/apps/base.py", line 794, in sh
    return call_func(cmd, shell=True, executable=shell)
  File "/home/thijmen/miniconda3/lib/python3.7/subprocess.py", line 347, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'liftOver -minMatch=1 JM-2.bed JM-2.chain JM-2.lifted.bed unmapped' returned non-zero exit status 127.

**Comment by Thijmen18** [comment]
Update: adding jcvi in my path seems to solve a part of the problem. And forgot this initially.

But still: 
RuntimeError: Failed to process string with tex because latex could not be found

So will try to install latex now.

**Comment by tanghaibao** [comment]
@Thijmen18 

You have to have `liftOver` on your PATH. This program has a licensing constraint so I cannot include it in the distribution. Download it from UCSC (free for academic use if I remember correctly):

https://genome-store.ucsc.edu/

These dependencies were also mentioned in the [wiki](https://github.com/tanghaibao/jcvi/wiki/ALLMAPS#external-dependencies) in case you want to look it up later.

Haibao

**Comment by Thijmen18** [comment]
Must have overlooked liftOver but the latex issues remains. Further, I did follow the installation steps provided on the webpage. 

I tried to install latex with pip and conda, but this all resulted in nothing. I'm a bit out of possibilities so any help is welcome!

NotADirectoryError: [Errno 20] Not a directory: 'latex'

**Comment by tanghaibao** [comment]
Try google on how to install Latex (it was only an optional requirement before when ALLMAPS was developed a few years ago, however, matplotlib has changed its way to interact with latex in recent versions, so it's emitting this error). 

Please take a look at [Get LaTeX](https://www.latex-project.org/get/) for various options for each major OS. For example, on Debian-like Linux OS you can often do:

```console
sudo apt-get install -y texlive texlive-latex-extra texlive-latex-recommended
```

Haibao

**Comment by Thijmen18** [comment]
Works perfect now! Thanks a lot for your help!

**Comment by aaronphillips7493** [comment]
Hey,

I am having a similar issue trying to follow these steps:
https://github.com/tanghaibao/jcvi/wiki/ALLMAPS%3A-How-to-install

I am working on my universities HPC, so installing things with pip is not an option. We have Biopython, numpy, and matplotlib installed on the system as modules, so I did not install them, I just loaded the modules. 

I was confused by the instruction:
`cp jcvi-bin/bin/* ~/bin            # ~/bin is your own PATH`
What does this mean? I copied the contents of icvi-bin/bin to a directory called bin, and then added bin/ to my PYTHONPATH. I'm not sure what PATH is? Please clarify. 

When I run sh run.sh to test the installation I get the error:
`[a1779884@l01 ALLMAPS-testdata]$ sh run.sh
/apps/software/Python/2.7.12-foss-2016uofa/bin/python: No module named jcvi.assembly
/apps/software/Python/2.7.12-foss-2016uofa/bin/python: No module named jcvi.assembly`

Can you please advise on how I can fix this?

Thank you,
Aaron :)

**Comment by aaronphillips7493** [comment]
Ok, update:

I ran 
`export PATH=/hpcfs/users/a1779884/rice_genomics/scaffolds_to_contigs/bin:$PATH`
and that has removed the error reported in my last post. 

However, I have a new error now that I am sure how to fix

[`a1779884@l01 ALLMAPS-testdata]$ sh run.sh `
`/apps/software/Anaconda3/2019.03/bin/python: Error while finding module specification for 'jcvi.assembly.allmaps' (ModuleNotFoundError: No module named 'jcvi')`
`/apps/software/Anaconda3/2019.03/bin/python: Error while finding module specification for 'jcvi.assembly.allmaps' (ModuleNotFoundError: No module named 'jcvi')`

How can I fix this?

Thank you,
Aaron :)
