### ISSUE TITLE
Customize the PDF output?

### ISSUE THREAD

**Issue by StefanoLonardi** [tanghaibao/jcvi#18]
I am really happy with ALLMAPS, but we have 7 genetic maps, and the graphs are a little hard to read (see attached). Is there an easy way I can increase the page size in the PDF, so that I can get a higher resolution and more readable PDF that I could include in our paper?

[chr8.pdf](https://github.com/tanghaibao/jcvi/files/364593/chr8.pdf)

**Comment by tanghaibao** [comment]
@StefanoLonardi these are really beautiful results. I wish I had clean maps like you have! Yes, you can specify the canvas size:

```$ python -m jcvi.assembly.allmaps plotall input.bed --figsize=12x8```

There is no need to re-run ALLMAPS. Just the command above. The default canvas size is 10 inches x 6 inches.

Finally, there are two optional libraries that would make your plot appear nicer. Try to install:

- seaborn (https://web.stanford.edu/~mwaskom/software/seaborn/); you can install via ``pip install seaborn``
- LaTex (http://matplotlib.org/users/usetex.html). You may need admin priviledge for this.

Once you have seaborn, explore other options like ``--style`` (which controls the canvas color) and ``--diverge`` (color palette). Get a full list of options without any arguments.

```$ python -m jcvi.assembly.allmaps plotall```

ALLMAPS plotter still works without these two softwares but fonts and styles are a bit basic (ugly).

Haibao

**Comment by StefanoLonardi** [comment]
Thanks for your help. I installed both seaborn and LaTex, and the output looks a lot nicer.
I will play with the styles and the color schemes. I am glad I can increase the DPIs.  Thanks again for a great tool.

I have read on a different thread that we should not trust the optional gap estimation step in **ALLMAPS**. Can you confirm?

Stefano

**Comment by tanghaibao** [comment]
@StefanoLonardi yes the gap estimates based on genetic map are highly variable - due to the uneven recombination rates. This tends to be worse around gaps since those regions are often repeat rich, poorly recombined, etc.

Haibao

**Comment by StefanoLonardi** [comment]
Thank you again, Haibao.
