### ISSUE TITLE
what's the meaning about the green lines of Pairwise synteny visualization

### ISSUE THREAD

**Issue by LHXqwq** [tanghaibao/jcvi#184]
![无标题](https://user-images.githubusercontent.com/50397597/70374179-f81a1080-192a-11ea-8d0d-f2b41fc64524.png)

**Comment by tanghaibao** [comment]
@LHXqwq 

The boundary of chromosomes - you are seeing lots of lines towards the top in your plot as there are lots of small contigs/scaffolds included in the plot. Use `--skipempty` to remove the small contigs that contain no syntenic blocks, to minimize cluttering in those cases.

**Comment by LHXqwq** [comment]
Thank you very much, my problem is solved, rest early
