### ISSUE TITLE
the process of simple

### ISSUE THREAD

**Issue by MMengrui** [tanghaibao/jcvi#187]
Hi Dr. Tang,
I found that it would lost some blocks after generating the .simple file because of the parameter --minspan. However, I did not figure out it meanings.

**Comment by tanghaibao** [comment]
@MMengrui 

The parameter `--minspan` is from the step `screen`. Step `screen` filters the identified blocks with certain criteria, so the parameter `--minspan=30` means only syntenic blocks with at least 30 genes in size will be kept. Note that this is different from another parameter `--minsize` that keeps blocks with at least XX anchors.

The other parameter of `screen`: `--simple` converts the `.anchors` format to `.simple` format which is easier to manipulate especially for plotting scripts.

Finally you can check the usage of `screen` by not giving any parameters:

```console
$ python -m jcvi.compara.synteny screen
Usage:
    synteny.py screen anchorfile newanchorfile --qbed=qbedfile --sbed=sbedfile [options]

    Extract subset of blocks from anchorfile. Provide several options:

    1. Option --ids: a file with IDs, 0-based, comma separated, all in one line.
    2. Option --seqids: only allow seqids in this file.
    3. Option --seqpairs: only allow seqpairs in this file, one per line, e.g. "Chr01,Chr05".
    4. Option --minspan: remove blocks with less span than this.
    5. Option --minsize: remove blocks with less number of anchors than this.


Options:
  -h, --help           Show this help message and exit
  --qbed=QBED          Path to qbed [default: none]
  --sbed=SBED          Path to sbed [default: none]
  --ids=IDS            File with block IDs (0-based) [default: none]
  --seqids=SEQIDS      File with seqids [default: none]
  --seqpairs=SEQPAIRS  File with seqpairs [default: none]
  --nointra            Remove intra-chromosomal blocks [default: none]
  --minspan=MINSPAN    Only blocks with span >= [default: 0]
  --minsize=MINSIZE    Only blocks with anchors >= [default: 0]
  --simple             Write simple anchorfile with block ends [default: none]
```

Haibao

**Comment by obenno** [comment]
Hi @tanghaibao,

After reading the docs, I'm still a little bit confused with the two arguments. May I confirm with you about:

- Does `--minspan` only count gene numbers (from `query.bed`) in query species no matter how many subject ortholog genes found for them? 
- Does `--minsize` count gene pairs (anchors) in `.anchor` file?
- What does the fifth column stand for in `.simple` file?
```
PAC:19656964    PAC:19650281    AL1G10010.t1.v2.1       AL1G11530.t1.v2.1       136     -
```

Thanks,
obenno

**Comment by tanghaibao** [comment]
@obenno 

`--minspan` counts genes from the bed file, regardless of whether anchors or not. `--minsize` is only anchors.
5th column in the `.simple` file is a score, which is the geometric mean: `sqrt(a_span * b_span)`, where `a_span` is the span on genome A and `b_span` is the span on genome B.

https://github.com/tanghaibao/jcvi/blob/5e720870c0928996f8b77a38208106ff0447ccb6/jcvi/compara/synteny.py#L1242

**Comment by obenno** [comment]
@tanghaibao 

Thank you very much for the explanation, I found the code for `minspan`:

https://github.com/tanghaibao/jcvi/blob/5e720870c0928996f8b77a38208106ff0447ccb6/jcvi/compara/synteny.py#L1437-L1439
