### ISSUE TITLE
Different output plots but similar command!

### ISSUE THREAD

**Issue by Thijmen18** [tanghaibao/jcvi#188]
Dear all,

I have done two separate species comparisons against the same reference genome using jcvi.assembly.allmaps. Strangely in the chromosome plots for one of the analysis I do get gray bars in the chromosome as reference points (which is helpfull) but in the second analysis I do not get the gray bars. What do I need to change to actually get the gray bars in my analysis?
Command 1 (with gray bars, example Chr 9):
python -m jcvi.assembly.allmaps path order_sp1.bed sp1_assembly04.fasta
[chr9.pdf](https://github.com/tanghaibao/jcvi/files/4029991/chr9.pdf)

Command 2 (without the gray bars, example Chr 10):
python -m jcvi.assembly.allmaps path order_sp2.bed sp2_assembly.fa
[chr10.pdf](https://github.com/tanghaibao/jcvi/files/4029992/chr10.pdf)

How to customise the output and actually getting the gray bars?

**Comment by Thijmen18** [comment]
And just as a quick additonal question: the chromosome in the middle of the figure is the one you are reconstructing of the subject species, the blocks around it from the reference genome and the lines correspond to syntenic blocks. Am I correct?

**Comment by tanghaibao** [comment]
@Thijmen18 

First of all, ALLMAPS is intended to assemble scaffolds/contigs, so it is important to understand that it is not a visualization tool.

The gray bars are different scaffolds/contigs pieced together. It appears that your chr10 consists of a single scaffold/contig, where chr9 consists of multiple scaffolds/contigs. Gray bars are the contigs with alternating gray, white, gray, ... etc. to highlight the boundaries. So no you can't customize the output to get gray bars, the gray bars are there or not there based on the scaffolding results.

For your second question - yes.
