### ISSUE TITLE
[blastfilter] error in  jcvi.compara.catalog 

### ISSUE THREAD

**Issue by ig624** [tanghaibao/jcvi#189]
Dear all,
similarly to that described in previous opened questions, while running the 
`python -m jcvi.compara.catalog ortholog [...]  --no_strip_names` command line, the ` [blastfilter] scaffold_111_74 not in set.bed` message appeared. The bed and cds files derive from drafts that I assembled (so not form Phytozome). 
my bed file(s) (`--type=gene`) look(s) like:
`scaffold_111_74	2810	3875	g1	0	+`
`scaffold_111_74	6150	7931	g2	0	+`
`scaffold_111_74	10566	11930	g3	0	-`
`scaffold_111_74	12800	14381	g4	0	+`
`scaffold_111_74	14398	14970	g5	0	-`
`...`

I also tried to use the files used in the tutorial, and it worked: the bed files generated from them look identical to mine.
Are you aware of any update on this issue? Has anyone successfully fixed the problem?
Regards,
IG

**Comment by tanghaibao** [comment]
@ig624 

Does the sequence ids in your CDS fasta file match up with the 4th column in the BED file? in other words, they should all look like g1, g2, g3, ... as appeared in your BED file.

Haibao

**Comment by ig624** [comment]
Dear Haibao,
I apologise for the late reply. Thank you very much for your answer. I have to say I misunderstood what the tutorial said, and I used the draft genome to produce the cds file, not the list of genes. I have rerun the commands with the right fasta and everything worked well.
Thank you very much.
regards,
IG
