### ISSUE TITLE
Cross-species synteny 1x1.anchor file 3 column

### ISSUE THREAD

**Issue by Imoteph** [tanghaibao/jcvi#2]
Hi

Could you just shortly explain what the third column defines of the 1x1.anchor file?

###
Ca_02944        Medtr2g105830   2116
Ca_02943        Medtr2g105680   3858
Ca_02942        Medtr2g105640   1908

thx!

**Comment by tanghaibao** [comment]
This .anchors file contains:
```
chickpea-genename    medicago-genename    BLAST-score
```
The third column (BLAST score) is NOT really used in ALLMAPS, so you can just put a fake score there (like 100). You can parse the BLAST results to retrieve this. However, you should consider enriching the syntenic anchors for best results, for example, only using reciprocal best BLAST hit.

**Comment by Imoteph** [comment]
@tanghaibao 

Thx a lot, for clarification.
