### ISSUE TITLE
I am confused about the jcvi.compara.reconstruct adjgraph

### ISSUE THREAD

**Issue by whitepencil233333** [tanghaibao/jcvi#200]
the 'reconstruct.py' scripts includes the 'adjgraph' method, the method needs input files called ' adjacency.txt' and  'subgraph.txt'. I don't know which program can generate this two files, because in the reconstruct.py, other methods cannot generate the two files.

**Comment by tanghaibao** [comment]
@whitepencil233333 

Unfortunately, 'reconstruct.py' is no longer supported since the program that can generate these two files is no longer available. Sorry for the confusion.

Haibao
