### ISSUE TITLE
ValueError: A total of 0 anchor was found. Aborted.

### ISSUE THREAD

**Issue by fantasticair** [tanghaibao/jcvi#202]
Hello,
I run `python -m jcvi.compara.catalog ortholog Dglomerata Osativa` command, an error appeared,
`python -m jcvi.compara.catalog ortholog Dglomerata Osativa
13:51:33 [synteny] Assuming --qbed=Dglomerata.bed --sbed=Osativa.bed
13:51:33 [base] Load file `Dglomerata.bed`
13:51:34 [base] Load file `Osativa.bed`
13:51:35 [base] Load file `Dglomerata.Osativa.last.filtered`
13:51:35 [synteny] A total of 24 BLAST imported from `Dglomerata.Osativa.last.filtered`.
13:51:35 [synteny] Chaining distance = 20
13:51:35 [base] Load file `Dglomerata.Osativa.anchors`
13:51:35 [synteny] A total of 0 anchor was found. Aborted.
Traceback (most recent call last):
  File "/home/suer1/anaconda2/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/home/suer1/anaconda2/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/suer1/anaconda2/lib/python2.7/site-packages/jcvi/compara/catalog.py", line 928, in <module>
    main()
  File "/home/suer1/anaconda2/lib/python2.7/site-packages/jcvi/compara/catalog.py", line 80, in main
    p.dispatch(globals())
  File "/home/suer1/anaconda2/lib/python2.7/site-packages/jcvi/apps/base.py", line 111, in dispatch
    globals[action](sys.argv[2:])
  File "/home/suer1/anaconda2/lib/python2.7/site-packages/jcvi/compara/catalog.py", line 696, in ortholog
    scan([filtered_last, anchors, dist, "--liftover={0}".format(last)])
  File "/home/suer1/anaconda2/lib/python2.7/site-packages/jcvi/compara/synteny.py", line 1876, in scan
    summary([anchor_file])
  File "/home/suer1/anaconda2/lib/python2.7/site-packages/jcvi/compara/synteny.py", line 1415, in summary
    raise ValueError("A total of 0 anchor was found. Aborted.")
ValueError: A total of 0 anchor was found. Aborted.
`

**Comment by tanghaibao** [comment]
@fantasticair 

Make sure that the gene names in the CDS FASTA header match the gene names in the BED file (4th column); otherwise, the LAST output will not get imported correctly.

Haibao

**Comment by fantasticair** [comment]
Thank you@Haibao
I have found the reason for the error. `Gene id needs to follow the naming principle of ranking on the chromosome in descending order.`, so I sugank you@Haibao
I have found the reason for the error. `Gene id needs to follow the naming principle of ranking on the chromosome in descending order.`, so I suggested that the newer version can be more perfect.

**Comment by fantasticair** [comment]
Thank you@Haibao
I have found the reason for the error. `Gene id needs to follow the naming principle of ranking on the chromosome in descending order`,  so I suggested that the newer version can be more perfect.

**Comment by HuangMin0702** [comment]
I met the same problem with you. The four files follow is my test data:
[ath3.cds.txt](https://github.com/tanghaibao/jcvi/files/5352443/ath3.cds.txt)
[aly3.cds.txt](https://github.com/tanghaibao/jcvi/files/5352444/aly3.cds.txt)
[aly3.bed.txt](https://github.com/tanghaibao/jcvi/files/5352445/aly3.bed.txt)
[ath3.bed.txt](https://github.com/tanghaibao/jcvi/files/5352447/ath3.bed.txt)

run the commond: python -m jcvi.compara.catalog ortholog --no_strip_names ath3 aly3. There were still the same error:
}_HVG6`FY)LPK](https://user-images.githubusercontent.com/40498583/95541939-3e4a6f80-0a27-11eb-80d6-739effa880d4.png)

what's wrong? Thank u.
