### ISSUE TITLE
ZeroDivisionError: float division by zero

### ISSUE THREAD

**Issue by taotaoyuan** [tanghaibao/jcvi#207]
dear,
I got a err:
$python -m jcvi.graphics.karyotype seqids layout
20:56:58 [base] Load file `layout`
20:56:58 [base] Load file `aly.bed`
20:56:58 [base] Load file `ath.bed`
Traceback (most recent call last):
  File "/home/spider/soft/miniconda3/envs/py27/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/home/spider/soft/miniconda3/envs/py27/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/spider/soft/miniconda3/envs/py27/lib/python2.7/site-packages/jcvi/graphics/karyotype.py", line 422, in <module>
    main()
  File "/home/spider/soft/miniconda3/envs/py27/lib/python2.7/site-packages/jcvi/graphics/karyotype.py", line 409, in main
    generank=(not opts.basepair),
  File "/home/spider/soft/miniconda3/envs/py27/lib/python2.7/site-packages/jcvi/graphics/karyotype.py", line 358, in __init__
    tr = Track(root, lo, gap=gap, height=height, lw=lw, draw=False)
  File "/home/spider/soft/miniconda3/envs/py27/lib/python2.7/site-packages/jcvi/graphics/karyotype.py", line 146, in __init__
    ratio = span / total
ZeroDivisionError: float division by zero

please！
Thanks

**Comment by tanghaibao** [comment]
@taotaoyuan 

Please check if the names in the `seqids` file match the chromosome names in `aly.bed` and `ath.bed`. If they look fine, please send your `layout` file to help me debug.

P.S. in the long run, you can just use Python3 since Python2 is being deprecated and will not get maintained anymore.

**Comment by taotaoyuan** [comment]
There are the seqids and layout file.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Haibao Tang"<notifications@github.com&gt;;
发送时间:&nbsp;2020年2月16日(星期天) 晚上11:44
收件人:&nbsp;"tanghaibao/jcvi"<jcvi@noreply.github.com&gt;;
抄送:&nbsp;"Ti amo"<909474045@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [tanghaibao/jcvi] ZeroDivisionError: float division by zero (#207)




@taotaoyuan
 
Please check if the names in the seqids file match the chromosome names in aly.bed and ath.bed. If they look fine, please send your layout file to help me debug.
 
P.S. in the long run, you can just use Python3 since Python2 is being deprecated and will not get maintained anymore.

**Comment by taotaoyuan** [comment]
This is the seqids file
scaffold_1,scaffold_2,scaffold_3,scaffold_4,scaffold_5,scaffold_6,scaffold_7,scaffold_8
Chr1,Chr2,Chr3,Chr4,Chr5

This is layout file
# y, xstart, xend, rotation, color, label, va,  bed
 .4,     .2,    .8,       0,      , Athaliana, top, ath.bed
 .6,     .2,    .8,       0,      , Alyrata, top, aly.bed
# edges
e, 0, 1, ath.aly.anchors.simple

**Comment by pgonzale60** [comment]
I got the same error and in my case was that the seqids were in different order. So, if your error arised for the same reason, you should be ablo to solve it by having your seqid as follows:

```
Chr1,Chr2,Chr3,Chr4,Chr5
scaffold_1,scaffold_2,scaffold_3,scaffold_4,scaffold_5,scaffold_6,scaffold_7,scaffold_8
```

**Comment by lplough** [comment]
I also recieved this error on Chr5 (of 45): 
`File "/data/users/root/miniconda/lib/python3.6/site-packages/jcvi/graphics/chromosome.py", line 254, in __init__
    ratio = r / max_chr_len
ZeroDivisionError: float division by zero`
, but not sure where to find these files (seqid, layout file)?
