### ISSUE TITLE
Add gene ID on local synteny

### ISSUE THREAD

**Issue by guosongjia** [tanghaibao/jcvi#209]
Dear Haibao:
Thanks for your detailed manual! I already got a local synteny figure like below.
![image](https://user-images.githubusercontent.com/37890107/74640794-1ca42b80-51ab-11ea-880a-199e5eae4dad.png)
I'm willing to add geneID on each block but I can not find related options. So I'm wondering whether it can be realized in our software package?
Thank you!

**Comment by tanghaibao** [comment]
@guosongjia 

This is not supported yet in the package. I thought having the gene labels may make the plot appear cluttered. Do you wish to plot the show labels above, below or on the gene blocks? 

Tip: if you specify your label like this, "*S.octosporus* oct_chr1", the species name will show up in _italics_.  You may also want to use the option `--switch` to rename your chromosome label.

Haibao

**Comment by guosongjia** [comment]
@tanghaibao 

Thanks for your advice and now I can change _italics_ format of the label.
It's difficult to define where to draw gene labels because different genomic loci have different gene density. I have some ideas but I don't know how difficult to achieve it.

1. For those large gene blocks, draw the gene labels onto the gene blocks. For those small gene blocks, it's reasonable to draw it above or below the gene blocks and use a line to link it. 
2. Add some appendix information in the `blocks.layout` file to define which gene label can be showed onto the figure. Maybe it's easy to deal with a limited number of gene labels.

Besides, how about generating all the figures in vector diagram (like SVG or EPS) not PDF? Vector diagram can be manually adjusted in many software like Adobe Illustrator and can be integrated into publishable figures more easily. 

Guo-Song

**Comment by tanghaibao** [comment]
@guosongjia 

I'll leave this issue open until I find time to work on it.

You can directly use the PDF in Adobe Illustrator, it is vector graphics and I use it for publications all the time. Nonetheless, feel free to output other formats by `--format=svg` or `--format=eps`. Just running the command without any arguments show you the options, including `--format`.

```console
$ python -m jcvi.graphics.synteny
Usage:
synteny.py mcscan.txt all.bed layout.csv

Illustrate MCscan multiple collinearity alignments. Use layout.csv to indicate
the positions of tracks. For example:

#x, y, rotation, ha, va, color, ratio
0.5, 0.6, 0, left, center, g
0.25, 0.7, 45, top, center, m

With the row ordering corresponding to the column ordering in the MCscan output.


Options:
  -h, --help            Show this help message and exit
  --switch=SWITCH       Rename the seqid with two-column file [default: none]
  --tree=TREE           Display trees on the bottom of the figure [default:
                        none]
  --extra=EXTRA         Extra features in BED format [default: none]
  --scalebar            Add scale bar to the plot [default: False]
  --shadestyle=SHADESTYLE
                        Style of syntenic wedges, must be one of curve|line
                        [default: curve]

  Image options:
    --figsize=FIGSIZE   Figure size `width`x`height` in inches [default: 8x7]
    --dpi=DPI           Physical dot density (dots per inch) [default: 300]
    --format=FORMAT     Generate image of format, must be one of
                        emf|eps|pdf|png|ps|raw|rgba|svg|svgz [default: pdf]
    --font=FONT         Font name, must be one of
                        Arial|Helvetica|Palatino|Schoolbook [default:
                        Helvetica]
    --style=STYLE       Axes background, must be one of
                        dark|darkgrid|ticks|white|whitegrid [default:
                        darkgrid]
    --diverge=DIVERGE   Contrasting color scheme, must be one of
                        BrBG|PRGn|PiYG|PuOr|RdBu|RdGy|RdYlBu|RdYlGn|Spectral
                        [default: PiYG]
    --cmap=CMAP         Use this color map [default: jet]
    --notex             Do not use tex [default: False]

JCVI utility libraries v1.0.3+11.gaca1b83f [Copyright (c) 2010-2019, Haibao
Tang]
```

Haibao

**Comment by tanghaibao** [comment]
@guosongjia 

Just implemented the gene label, with the option `--genelabelsize`. Please see [related section on wiki](https://github.com/tanghaibao/jcvi/wiki/MCscan-(Python-version)#microsynteny-visualization).

Special thanks to @Tong-Chen (#256) to come up with the implementation.

Haibao
