### ISSUE TITLE
Failed: savefig failed. Reset usetex to False.

### ISSUE THREAD

**Issue by sophy7074** [tanghaibao/jcvi#21]
Hi,

It failed when saving figure. Infos are below:

16:26:24 [base] savefig failed. Reset usetex to False.
LaTeX was not able to process the following string:
'lp'
Here is the full report generated by LaTeX: 

This is pdfTeX, Version 3.1415926-1.40.10 (TeX Live 2009/Debian)
entering extended mode
(./1d97300a39adbdb822e515e35e631e34.tex
LaTeX2e <2009/09/24>
Babel <v3.8l> and hyphenation patterns for english, usenglishmax, dumylang, noh
yphenation, loaded.
(/usr/share/texmf-texlive/tex/latex/base/article.cls
Document Class: article 2007/10/19 v1.4h Standard LaTeX document class
(/usr/share/texmf-texlive/tex/latex/base/size10.clo))

! LaTeX Error: File `type1cm.sty' not found.

Type X to quit or <RETURN> to proceed,
or enter new name. (Default extension: sty)

Enter file name: 
! Emergency stop.
<read *> 

l.3 \renewcommand
                 {\rmdefault}{pnc}^^M
No pages of output.
Transcript written on 1d97300a39adbdb822e515e35e631e34.log.

/usr/local/lib/python2.7/dist-packages/matplotlib/font_manager.py:1288: UserWarning: findfont: Font family [u'sans-serif'] not found. Falling back to Bitstream Vera Sans
  (prop.get_family(), self.defaultFamily[fontext]))
/usr/local/lib/python2.7/dist-packages/matplotlib/font_manager.py:1288: UserWarning: findfont: Font family [u'Helvetica'] not found. Falling back to Bitstream Vera Sans
  (prop.get_family(), self.defaultFamily[fontext]))

Any suggestion about this problem?

Sincerely,
Tiany

**Comment by tanghaibao** [comment]
@sophy7074 you should still be able to see a figure (maybe a slightly ugly figure) because the TeX rendering failed. Please see possible solution here: http://stackoverflow.com/questions/11354149/python-unable-to-render-tex-in-matplotlib

**Comment by sophy7074** [comment]
Thank you.
After installing dvipng, texlive-latex-extra, and texlive-fonts-recommended packages, everthing is right.

**Comment by tanghaibao** [comment]
@sophy7074 no problem. Closing this issue for now but please feel free to re-open if needed. Thanks.

**Comment by jguppy** [comment]
seems like now in addition to these packages you also need to install cm-super

**Comment by goeckeritz** [comment]
Hi jguppy et al., 

I had a similar error to this old one above. I was wondering if the issue was obviously because cm-super isn't installed? I don't have sudo privileges to download it myself so I'll have to contact the admin if that is the case. Here's the error -- everything ran fine until I ran **python -m jcvi.compara.synteny depth --histogram file.anchors**, when this error was thrown:

ERROR    savefig failed. Reset usetex to False.                                                                         base.py:278
                       latex was not able to process the following string:
                       b'peach_gene vs tart_cherry_gene syntenic depths'

                       Here is the full report generated by latex:
                       This is pdfTeX, Version 3.14159265-2.6-1.40.21 (TeX Live 2020) (preloaded format=latex)
                        restricted \write18 enabled.
                       entering extended mode

                       (/mnt/home/goeckeri/.cache/matplotlib/tex.cache/e144d04f609c8937a265bc2d361211d
                       7.tex
                       LaTeX2e <2020-10-01> patch level 4
                       L3 programming layer <2021-02-18>
                       (/opt/software/texlive/20210316/texmf-dist/tex/latex/base/article.cls
                       Document Class: article 2020/04/10 v1.4m Standard LaTeX document class
                       (/opt/software/texlive/20210316/texmf-dist/tex/latex/base/size10.clo))
                       (/opt/software/texlive/20210316/texmf-dist/tex/latex/type1cm/type1cm.sty)
                       (/opt/software/texlive/20210316/texmf-dist/tex/latex/cm-super/type1ec.sty
                       (/opt/software/texlive/20210316/texmf-dist/tex/latex/base/t1cmr.fd))
                       (/opt/software/texlive/20210316/texmf-dist/tex/latex/psnfss/helvet.sty
                       (/opt/software/texlive/20210316/texmf-dist/tex/latex/graphics/keyval.sty))
                       (/opt/software/texlive/20210316/texmf-dist/tex/latex/base/inputenc.sty)
                       (/opt/software/texlive/20210316/texmf-dist/tex/latex/geometry/geometry.sty
                       (/opt/software/texlive/20210316/texmf-dist/tex/generic/iftex/ifvtex.sty
                       (/opt/software/texlive/20210316/texmf-dist/tex/generic/iftex/iftex.sty))

                       Package geometry Warning: Over-specification in `h'-direction.
                           `width' (5058.9pt) is ignored.


                       Package geometry Warning: Over-specification in `v'-direction.
                           `height' (5058.9pt) is ignored.

                       ) (/opt/software/texlive/20210316/texmf-dist/tex/latex/base/textcomp.sty)
                       (/opt/software/texlive/20210316/texmf-dist/tex/latex/l3backend/l3backend-dvips.
                       def)
                       No file e144d04f609c8937a265bc2d361211d7.aux.
                       *geometry* driver: auto-detecting
                       *geometry* detected driver: dvips
                       (/opt/software/texlive/20210316/texmf-dist/tex/latex/psnfss/ot1phv.fd)
                       ! Missing $ inserted.
                       <inserted text>
                                       $
                       l.19 {\sffamily peach_
                                             gene vs tart_cherry_gene syntenic depths}
                       No pages of output.
                       Transcript written on e144d04f609c8937a265bc2d361211d7.log.



Traceback (most recent call last):
  File "/mnt/ufs18/home-087/goeckeri/software/jcvi/jcvi/lib/python3.6/site-packages/matplotlib/texmanager.py", line 277, in _run_checked_subprocess
    stderr=subprocess.STDOUT)
  File "/opt/software/Python/3.6.4-iomkl-2018a/lib64/python3.6/subprocess.py", line 336, in check_output
    **kwargs).stdout
  File "/opt/software/Python/3.6.4-iomkl-2018a/lib64/python3.6/subprocess.py", line 418, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['latex', '-interaction=nonstopmode', '--halt-on-error', '/mnt/home/goeckeri/.cache/matplotlib/tex.cache/e144d04f609c8937a265bc2d361211d7.tex']' returned non-zero exit status 1.


Any advice on how to fix this error and properly create the syntenic depth figure? Thank you in advance for all help!

Kindly, 
Charity

**Comment by tanghaibao** [comment]
@goeckeritz 

This is a bug and I just fixed it in 1842df. The issue was that there were underscores ('_') in your genome name which latex did not like. Please upgrade to the latest version (`pip install -U jcvi`). Thank you for reporting the bug.

Haibao
