### ISSUE TITLE
Link broken. May need to replace.. 

### ISSUE THREAD

**Issue by rahulvrane** [tanghaibao/jcvi#213]
https://github.com/tanghaibao/jcvi/blob/73b181da1f9c5a650d634ace0ba9e0ec8b5f7f5d/jcvi/apps/vecscreen.py#L51

Hi - I think NCBI changed some link formats this year - so this link is broken. May need to be replaced with ftp://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/000/019/425/GCF_000019425.1_ASM1942v1/GCF_000019425.1_ASM1942v1_genomic.fna.gz

Thanks a ton!

**Comment by tanghaibao** [comment]
@rahulvrane 

Thanks for the update. I just made a couple of changes. Please let me know if there are other issues.
