### ISSUE TITLE
How to set thread number of MCSCAN? 

### ISSUE THREAD

**Issue by liufuyan2016** [tanghaibao/jcvi#215]
I use JCVI ,The command is below:
/share/nas2/genome/biosoft/Python/3.5.2/bin/python -m jcvi.compara.catalog ortholog
But the default is use all the thread of the computer. How to asssign an   thread number to  MCSCAN mannually ?Thank you!

**Comment by tanghaibao** [comment]
@liufuyan2016 

I just added support for `--cpus` option. Now you can do:

```console
python -m jcvi.compara.catalog ortholog --cpus 2
```

To use only 2 threads. FYI, the multi-threading is only used when running the LAST command, all other steps are single-threaded. The default `--cpus 0` will continue to use all cpu cores available.

Haibao
