### ISSUE TITLE
Can I do the synteny among more than 3 species?

### ISSUE THREAD

**Issue by awesomedeer** [tanghaibao/jcvi#218]

**Comment by tanghaibao** [comment]
@awesomedeer 

The current workflow is to do pairwise synteny first and then assemble the results in the end. So the pipeline is something like:

```console
$ python -m jcvi.compara.ortholog A B
$ python -m jcvi.compara.ortholog A C
$ python -m jcvi.compara.synteny A.bed A.B.anchors --iter 1
$ python -m jcvi.compara.synteny A.bed A.C.anchors --iter 1
$ python -m jcvi.formats.base join A.B.i1.blocks A.C.i1.blocks --noheader | cut -f1,2,4 > A.B.C.blocks
```
In this example, the final blocks file contains 3 columns, one for each of the genome. You can visualize part of this blocks file following the microsynteny plotting section in the tutorial.

**Comment by evolgenomology** [comment]
In regard to this: is there an easy (implemented) way to get the pairs of gene/protein IDs that are plotted by position in the dotplot grid? My aim here is actually do to a multi species comparison. That is taking my reference species A and other species B and C, I want to know if the genes on Chr5 of species A  which form a cluster of synteny with genes on Chr 2 of species B are the same ones linking Chr5 of A with Chr 17 of species C.

**Comment by tanghaibao** [comment]
@evolgenomology 

There is no such tool implemented in the dot plot (which is just a static image, plotting IDs on thousands of dots would appear crowded). 

As a temporary solution, perhaps what you can do for now is to navigate `A.B.anchors` and `A.C.anchors` file using Linux `grep` or in-file searching function. All the ids for the syntenic gene pairs are in the `.anchors` file or `.blocks` the file generated in the workflow I posted above.

Haibao

**Comment by evolgenomology** [comment]
@tanghaibao 
Thanks for the reply!
Ja sure, makes no sense to plot the IDs.
To be honest I wasn't sure how to best parse the anchors and blocks files for these information. I was hoping there is already something in your code to easily connect the orthologous genes in these files to their position, which must come from the bed files.

Phil

**Comment by evolgenomology** [comment]
Guess as a quick hack I will just pull in the scaffold names into the anchors and blocks file. This will allow me to select my syntenic chromosomes of interest from looking at the plots and then get the genes defining these.

**Comment by tanghaibao** [comment]
@evolgenomology 

Yeah I agree that recoding the gene ids (e.g. prefix them with the scaffold names) may be the right way to go - a little scripting is needed though for that to work.

Let me know what your flow looks like and whether you have ideas to simplify this. Others may find it useful at some point. 

Thanks,
Haibao

**Comment by evolgenomology** [comment]
@tanghaibao

Will write a quick hack to do this. Yeah, very happy to share more details about what I am looking for and share a work flow. Will be in touch as soon as I have some results, couple of days or so.

Since I am writing, this set of tools of yours, it is just brilliant. Thanks to you and your guys for all the effort. Very much appreciated.

Philipp
