### ISSUE TITLE
Alternative way to call lastal

### ISSUE THREAD

**Issue by Tdanis** [tanghaibao/jcvi#225]
Hello, so is the first time that I use MCscan and I want to ask if there is another way to call the lastl without installing it to path. I use HPC cluster and it is very difficult to install last in path.

Thank you

**Comment by lufuhao** [comment]
use environment variable PATH to include last folder which you can find lastal and lastdb. Last can be compiled without root.

Fuhao

发自我的iPhone

在 2020年3月20日，21:40，Tdanis <notifications@github.com> 写道：

﻿

Hello, so is the first time that I use MCscan and I want to ask if there is another way to call the lastl without installing it to path. I use HPC cluster and it is very difficult to install last in path.

Thank you

**Comment by Tdanis** [comment]
Thank you for your reply, but I have already tryed this and does not work properly.
The errors are:

23:32:21 [base] Set text.usetex=False. Font styles may be inconsistent.
23:32:21 [base] lastdb peach peach.cds
/bin/bash: lastdb: command not found
23:32:21 [base] lastal -u 0 -P 24 -i3G -f BlastTab peach grape.cds >./grape.peach.last
/bin/bash: lastal: command not found
23:32:21 [synteny] Assuming --qbed=grape.bed --sbed=peach.bed
23:32:21 [base] Load file `grape.bed`
23:32:21 [base] Load file `peach.bed`
23:32:22 [blastfilter] Load BLAST file `grape.peach.last` (total 0 lines)
23:32:22 [base] Load file `grape.peach.last`
23:32:22 [blastfilter] running the cscore filter (cscore>=0.70) ..
23:32:22 [blastfilter] after filter (0->0) ..
23:32:22 [blastfilter] running the local dups filter (tandem_Nmax=10) ..
23:32:22 [blastfilter] after filter (0->0) ..
23:32:22 [synteny] Assuming --qbed=grape.bed --sbed=peach.bed
23:32:22 [base] Load file `grape.bed`
23:32:22 [base] Load file `peach.bed`
23:32:23 [base] Load file `grape.peach.last.filtered`
23:32:23 [synteny] A total of 0 BLAST imported from `grape.peach.last.filtered`.
23:32:23 [synteny] Chaining distance = 20
23:32:23 [base] Load file `grape.peach.anchors`
23:32:23 [synteny] A total of 0 anchor was found. Aborted.
Traceback (most recent call last):
  File "/usr/lib/python3.5/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home1/tdanis/.local/lib/python3.5/site-packages/jcvi/compara/catalog.py", line 930, in <module>
    main()
  File "/home1/tdanis/.local/lib/python3.5/site-packages/jcvi/compara/catalog.py", line 80, in main
    p.dispatch(globals())
  File "/home1/tdanis/.local/lib/python3.5/site-packages/jcvi/apps/base.py", line 111, in dispatch
    globals[action](sys.argv[2:])
  File "/home1/tdanis/.local/lib/python3.5/site-packages/jcvi/compara/catalog.py", line 694, in ortholog
    "--no_strip_names",
  File "/home1/tdanis/.local/lib/python3.5/site-packages/jcvi/compara/synteny.py", line 1902, in scan
    summary([anchor_file])
  File "/home1/tdanis/.local/lib/python3.5/site-packages/jcvi/compara/synteny.py", line 1441, in summary
    raise ValueError("A total of 0 anchor was found. Aborted.")
ValueError: A total of 0 anchor was found. Aborted.

Thank you

**Comment by lufuhao** [comment]
find you lastdb folder, for example, /path/to/folder; And in this folder, you can see lastdb and lastal
Then, in your terminal, execute
`export PATH=/path/to/folder:$PATH`

otherwise, add this line to the end of ~/.bashrc
`export PATH=/path/to/folder:$PATH`
then, in terminal
`source ~/.bashrc`

The first method only support temporary usage; the second method works from now on.

Good luck

**Comment by Tdanis** [comment]
Hello, yes I have already implemented both ways, but it still does not work.
Any other suggestion please?


Thank you
