### ISSUE TITLE
The output of Last

### ISSUE THREAD

**Issue by MMengrui** [tanghaibao/jcvi#226]
Dear Dr. Tang,
I have some question about the process of pairwise synteny search.
The comparison is done with LAST, however, I didnot find the paramenter of e-value. 
Besides, Is the e-value related to the c-score?

**Comment by MMengrui** [comment]
And when I set the c-score of 0.7 and 0.3, I got less blocks by 0.7, but one block seemed to have more genes.
I found that some genes didnot appear in any block of c-score 0.3, but appeared in the block of c-score 0.7.

**Comment by tanghaibao** [comment]
@MMengrui 

LAST output does not report e-value like in the BLAST. 

The c-score used in the synteny pipeline extends the idea of 'mutual best hit'. So a mutual best hit would have a c-score of 1, while other hits will have a c-score less than 1. I often use the c-score cutoff of 0.99 to find blocks that are orthologous as detailed in the wiki.

It is recommended to always do a dot plot to see what your results look like after changing c-score cutoffs. The number of blocks or the number of gene pairs within a block doesn't tell you how good your results are.

Haibao
