### ISSUE TITLE
How to change the font size of chr labels?

### ISSUE THREAD

**Issue by awesomedeer** [tanghaibao/jcvi#232]
Can I modify the code to change the font size of chr labels and some parameters like offset to manipulate the labels.
Thanks a lot!

**Comment by tanghaibao** [comment]
@awesomedeer 

Please attach a screenshot and use arrows to indicate which labels you want control over. Thanks.

**Comment by awesomedeer** [comment]
![demo](https://user-images.githubusercontent.com/42170723/78658834-481adb00-78fd-11ea-822a-ba2c6a63df0f.png)
Sorry. I have attached the file which show the label I want to modify.
Thank you!

**Comment by tanghaibao** [comment]
@awesomedeer 

Sorry for a late response. A small tip here is that sometimes you can achieve the effect you want through modifying the figure size (`--figsize`). For example,

```console
python -m jcvi.graphics.synteny blocks --figsize=6x5
```

![image](https://user-images.githubusercontent.com/106987/78943730-3f4b1600-7a71-11ea-94a4-f1206b12e70a.png)

Compare to:

```console
python -m jcvi.graphics.synteny blocks --figsize=10x8
```

![image](https://user-images.githubusercontent.com/106987/78943816-6bff2d80-7a71-11ea-8d4a-8202547e866a.png)

**Comment by awesomedeer** [comment]
Cool! It was what I expected.
Thanks a lot!

Song
