### ISSUE TITLE
run python -m jcvi.graphics.karyotype with three genome error!

### ISSUE THREAD

**Issue by sunnycqcn** [tanghaibao/jcvi#240]
Hello Dr. Tang,
When I run MCscan, I met a error about using three genomes. If I run two genomes, L022 and L023, it works well. LREF has different scaffold numbers, 33 scaffolds. L022 and L023 are 20 scaffolds.
could you help me check this error?
Thanks,
Fuyou

 python -m jcvi.graphics.karyotype seqids layout
14:14:58 [base] Load file `layout`
14:14:58 [base] Load file `LREF.bed`
14:14:59 [base] Load file `L022.bed`
14:14:59 [base] Load file `L023.bed`
Traceback (most recent call last):
  File "/home/AAFC-AAC/fuf/miniconda3/envs/py2/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/home/AAFC-AAC/fuf/miniconda3/envs/py2/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/AAFC-AAC/fuf/miniconda3/envs/py2/lib/python2.7/site-packages/jcvi/graphics/karyotype.py", line 435, in <module>
    main()
  File "/home/AAFC-AAC/fuf/miniconda3/envs/py2/lib/python2.7/site-packages/jcvi/graphics/karyotype.py", line 422, in main
    generank=(not opts.basepair),
  File "/home/AAFC-AAC/fuf/miniconda3/envs/py2/lib/python2.7/site-packages/jcvi/graphics/karyotype.py", line 371, in __init__
    tr = Track(root, lo, gap=gap, height=height, lw=lw, draw=False)
  File "/home/AAFC-AAC/fuf/miniconda3/envs/py2/lib/python2.7/site-packages/jcvi/graphics/karyotype.py", line 175, in __init__
    ratio = span / total
ZeroDivisionError: float division by zero

**Comment by tanghaibao** [comment]
@sunnycqcn 

Would you please share your `seqids` file and `layout` file for me to take a look? 
Please redact any sensitive data before sharing.

Haibao

**Comment by sunnycqcn** [comment]
Hello Haibao,
I am sorry I submitted a duplicate issues. I think it was the newwork problem. 
My seqid is
sc01,sc02,sc03,sc04,sc05,sc06,sc07,sc08,sc09,sc10,sc11,sc12,sc13,sc14,sc15,sc16,sc17,sc18,sc19,sc20
sc01,sc02,sc03,sc04,sc05,sc06,sc07,sc08,sc09,sc10,sc11,sc12,sc13,sc14,sc15,sc16,sc17,sc18,sc19,sc20
UN01,UN02,UN03,UN04,UN05,UN06,UN07,UN08,UN09,UN10,UN11,UN12,UN13,UN14,UN15,UN16,UN17,UN18,UN19,UN20,UN21,UN22,UN23,UN24,UN25,UN26,UN27,UN28,UN29,UN30,UN31,UN32,UN33

layout file is
# y, xstart, xend, rotation, color, label, va,  bed
 .7,     .1,    .8,      15,      , LREF, top, LREF.bed
 .5,     .1,    .8,       0,      , L022, top, L022.bed
 .3,     .1,    .8,     -15,      , L023, bottom, L023.bed
# edges
e, 0, 1, LREF.L022.anchors.simple
e, 1, 2, L022.L023.anchors.simple
.
Thanks,
Fuyou

**Comment by tanghaibao** [comment]
@sunnycqcn 

The files that you sent seem okay. However, please check that:

- sc01 to sc20 are present in the first column of `LREF.bed`
- sc01 to sc20 are present in the first column of `L022.bed`
- UN01 to UN33 are present in the first column of `L023.bed`

In other words, the BED files should have the corresponding scaffold ids that you listed in the seqids file.

Haibao

**Comment by sunnycqcn** [comment]
[karyotype.pdf](https://github.com/tanghaibao/jcvi/files/4604272/karyotype.pdf)
Hi Haibao,
I am much appreicated for your suggestions. It is working well now. I have one more question about this figure.
Can I highlight some regions? for example, some links are not the same chromosomes or with deletion or instertion.
Can extract the genes in these regions?
Thanks
Fuyou
