### ISSUE TITLE
Plotting physical and genetic  maps co-linearity and latex error

### ISSUE THREAD

**Issue by WimSpee** [tanghaibao/jcvi#242]
I am trying to plot marker locations on 2 physical maps and multiple genetic maps. 
1 short read reference genome, 1 long read reference genome of the same biomaterial and multiple genetic maps.  The maps should all be very co-linear.

Is is possible with Allmaps to plot the co-linearity between multiple physical and genetic maps? 
Most maps are already on chromosome scale, only some genetic maps are still more fragmented (more linkage groups than chromosomes).

Also I am getting this error, I don't see anything strange the input bed file. Are there extra latex related packages that I should install on RedHat? (I only saw in another issue Debian packages mentioned, but these don't exist for RedHat)

```
RuntimeError: latex was not able to process the following string:
b'chr1_HRSCAF_38 (25Mb)'
```

Thank you.

**Comment by tanghaibao** [comment]
@WimSpee 

Right now with ALLMAPS, you can plot 1 physical map at a time. Basically start with short reference genome, compare with all genetic maps. Then the long read reference, compare with all genetic maps. I don't think you can use all physical maps at the same time, unless you treat the physical map as synteny (instructions [here](https://github.com/tanghaibao/jcvi/wiki/ALLMAPS%3A-How-to-use-different-types-of-genomic-maps), but may need rather complicated processing).

The latex installation is fine, it wasn't able to deal with the underscore '_' in the name. Normally ALLMAPS should have cleaned the names for you not sure why this happens. Try renaming your scaffolds to use other symbols like '-' instead. Please try it but it may need to change this in multiple places.

Haibao
