### ISSUE TITLE
How to changed the genetic map to the format of ALLMAP

### ISSUE THREAD

**Issue by shehongbing** [tanghaibao/jcvi#245]
Hi there,
I get a genetic map using SLAF-seq. Can I align the sequence (including SLAF marker) to scaffold and get the physical position?

THX

**Comment by tanghaibao** [comment]
@shehongbing 

Yes, you can and you would need to convert the results from your alignment to CSV format similar to [here](https://github.com/tanghaibao/jcvi/wiki/ALLMAPS#walk-through-example).

Haibao
