### ISSUE TITLE
input gff files format, error *** not in xxx.bed  

### ISSUE THREAD

**Issue by Qiaojilim** [tanghaibao/jcvi#248]
hello Prof. Tang 
I ran peach and grape test data on jcvi successfully. but when I tried my own data which I downloaded other genomes  .gff files and .faa files from Coge platform (worked with prof Sankoff) it failed to read data on pairwise synteny search step.  I think it is because of the original input data format. I  got  bed file and cds file from converting  .gff and .faa by your code  but not sure that is right output files or not. could you give me some instructions about the correct input data ??? thanks for your patience
here is the error
$ python3 -m jcvi.compara.catalog ortholog nelumbo vitis  --no_strip_names                    
12:43:35 [base] lastdb vitis vitis.cds
12:47:40 [base] lastal -u 0 -P 12 -i3G -f BlastTab vitis nelumbo.cds >./nelumbo.vitis.last
13:12:59 [synteny] Assuming --qbed=nelumbo.bed --sbed=vitis.bed
13:12:59 [base] Load file `nelumbo.bed`
13:12:59 [base] Load file `vitis.bed`
13:13:05 [blastfilter] Load BLAST file `nelumbo.vitis.last` (total 33023486 lines)
13:13:05 [base] Load file `nelumbo.vitis.last`
13:18:15 [blastfilter] gi|1 not in nelumbo.bed
13:18:15 [blastfilter] gi|1 not in nelumbo.bed
13:18:15 [blastfilter] gi|1 not in nelumbo.bed
13:18:15 [blastfilter] gi|5 not in nelumbo.bed
13:18:15 [blastfilter] gi|5 not in nelumbo.bed
13:18:15 [blastfilter] gi|1 not in nelumbo.bed
13:18:15 [blastfilter] gi|1 not in nelumbo.bed
13:18:15 [blastfilter] gi|5 not in nelumbo.bed
13:18:15 [blastfilter] gi|2 not in nelumbo.bed
13:18:15 [blastfilter] gi|2 not in nelumbo.bed
13:18:15 [blastfilter] gi|2 not in nelumbo.bed
13:18:15 [blastfilter] gi|5 not in nelumbo.bed
13:18:15 [blastfilter] gi|5 not in nelumbo.bed
13:18:15 [blastfilter] gi|1 not in nelumbo.bed
13:18:15 [blastfilter] gi|1 not in nelumbo.bed
13:18:15 [blastfilter] gi|1 not in nelumbo.bed
13:18:15 [blastfilter] gi|1 not in nelumbo.bed
13:18:15 [blastfilter] gi|5 not in nelumbo.bed
13:18:15 [blastfilter] gi|5 not in nelumbo.bed
13:18:15 [blastfilter] gi|5 not in nelumbo.bed
13:18:15 [blastfilter] gi|2 not in nelumbo.bed
13:18:15 [blastfilter] gi|1 not in nelumbo.bed
13:18:15 [blastfilter] gi|8 not in nelumbo.bed
13:18:15 [blastfilter] gi|2 not in nelumbo.bed
13:18:15 [blastfilter] gi|1 not in nelumbo.bed
13:18:15 [blastfilter] gi|1 not in nelumbo.bed
13:18:15 [blastfilter] gi|4 not in nelumbo.bed
13:18:15 [blastfilter] gi|8 not in nelumbo.bed
13:18:15 [blastfilter] gi|1 not in nelumbo.bed
13:18:15 [blastfilter] gi|8 not in nelumbo.bed
13:18:15 [blastfilter] gi|1 not in nelumbo.bed
13:18:15 [blastfilter] gi|4 not in nelumbo.bed
13:18:15 [blastfilter] gi|1 not in nelumbo.bed
13:18:15 [blastfilter] gi|4 not in nelumbo.bed
13:18:15 [blastfilter] gi|8 not in nelumbo.bed
13:18:15 [blastfilter] gi|4 not in nelumbo.bed
13:18:15 [blastfilter] gi|1 not in nelumbo.bed
13:18:15 [blastfilter] gi|1 not in nelumbo.bed
13:18:15 [blastfilter] gi|2 not in nelumbo.bed
13:18:15 [blastfilter] gi|2 not in nelumbo.bed
13:18:15 [blastfilter] gi|1 not in nelumbo.bed
13:18:15 [blastfilter] gi|5 not in nelumbo.bed
13:18:15 [blastfilter] gi|3 not in nelumbo.bed
13:18:15 [blastfilter] gi|2 not in nelumbo.bed
13:18:15 [blastfilter] gi|5 not in nelumbo.bed
13:18:15 [blastfilter] gi|6 not in nelumbo.bed
13:18:15 [blastfilter] gi|2 not in nelumbo.bed
13:18:15 [blastfilter] gi|2 not in nelumbo.bed
13:18:15 [blastfilter] gi|1 not in nelumbo.bed
13:18:15 [blastfilter] gi|1 not in nelumbo.bed
13:18:15 [blastfilter] gi|2 not in nelumbo.bed
13:18:15 [blastfilter] gi|1 not in nelumbo.bed
13:18:15 [blastfilter] gi|2 not in nelumbo.bed
13:18:15 [blastfilter] gi|3 not in nelumbo.bed
13:18:15 [blastfilter] gi|1 not in nelumbo.bed
13:18:15 [blastfilter] gi|3 not in nelumbo.bed
13:18:15 [blastfilter] gi|2 not in nelumbo.bed
13:18:15 [blastfilter] gi|1 not in nelumbo.bed
13:18:15 [blastfilter] gi|8 not in nelumbo.bed
13:18:15 [blastfilter] gi|6 not in nelumbo.bed
13:18:15 [blastfilter] gi|4 not in nelumbo.bed
13:18:15 [blastfilter] gi|6 not in nelumbo.bed
13:18:15 [blastfilter] gi|6 not in nelumbo.bed
13:18:15 [blastfilter] gi|1 not in nelumbo.bed
13:18:15 [blastfilter] gi|5 not in nelumbo.bed
13:18:15 [blastfilter] gi|3 not in nelumbo.bed
13:18:15 [blastfilter] gi|3 not in nelumbo.bed
13:18:15 [blastfilter] gi|6 not in nelumbo.bed
13:18:15 [blastfilter] gi|1 not in nelumbo.bed
13:18:15 [blastfilter] gi|1 not in nelumbo.bed
13:18:15 [blastfilter] gi|4 not in nelumbo.bed
13:18:15 [blastfilter] gi|1 not in nelumbo.bed
13:18:15 [blastfilter] gi|1 not in nelumbo.bed
13:18:15 [blastfilter] gi|1 not in nelumbo.bed
13:18:15 [blastfilter] gi|1 not in nelumbo.bed
13:18:15 [blastfilter] gi|1 not in nelumbo.bed
13:18:15 [blastfilter] gi|4 not in nelumbo.bed
13:18:15 [blastfilter] gi|1 not in nelumbo.bed
13:18:15 [blastfilter] gi|1 not in nelumbo.bed
13:18:15 [blastfilter] gi|2 not in nelumbo.bed
13:18:15 [blastfilter] gi|2 not in nelumbo.bed
13:18:15 [blastfilter] gi|4 not in nelumbo.bed
13:18:15 [blastfilter] gi|4 not in nelumbo.bed
13:18:15 [blastfilter] gi|3 not in nelumbo.bed
13:18:15 [blastfilter] gi|2 not in nelumbo.bed
13:18:15 [blastfilter] gi|3 not in nelumbo.bed
13:18:15 [blastfilter] gi|3 not in nelumbo.bed
13:18:15 [blastfilter] gi|5 not in nelumbo.bed
13:18:15 [blastfilter] gi|3 not in nelumbo.bed
13:18:15 [blastfilter] gi|1 not in nelumbo.bed
13:18:15 [blastfilter] gi|1 not in nelumbo.bed
13:18:15 [blastfilter] gi|1 not in nelumbo.bed
13:18:15 [blastfilter] gi|1 not in nelumbo.bed
13:18:15 [blastfilter] gi|1 not in nelumbo.bed
13:18:15 [blastfilter] gi|8 not in nelumbo.bed
13:18:15 [blastfilter] gi|1 not in nelumbo.bed
13:18:15 [blastfilter] gi|1 not in nelumbo.bed
13:18:15 [blastfilter] gi|6 not in nelumbo.bed
13:18:15 [blastfilter] gi|3 not in nelumbo.bed
13:18:15 [blastfilter] gi|1 not in nelumbo.bed
13:18:15 [blastfilter] too many warnings.. suppressed
13:18:38 [blastfilter] running the cscore filter (cscore>=0.70) ..
13:18:38 [blastfilter] after filter (0->0) ..
13:18:38 [blastfilter] running the local dups filter (tandem_Nmax=10) ..
13:18:38 [blastfilter] after filter (0->0) ..
13:18:46 [synteny] Assuming --qbed=nelumbo.bed --sbed=vitis.bed
13:18:46 [base] Load file `nelumbo.bed`
13:18:46 [base] Load file `vitis.bed`
13:18:46 [base] Load file `nelumbo.vitis.last.filtered`
13:18:46 [synteny] A total of 0 BLAST imported from `nelumbo.vitis.last.filtered`.
13:18:46 [synteny] Chaining distance = 20
13:18:46 [base] Load file `nelumbo.vitis.anchors`
13:18:46 [synteny] A total of 0 anchor was found. Aborted.
Traceback (most recent call last):
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.7/site-packages/jcvi/compara/catalog.py", line 939, in <module>
    main()
  File "/usr/local/lib/python3.7/site-packages/jcvi/compara/catalog.py", line 80, in main
    p.dispatch(globals())
  File "/usr/local/lib/python3.7/site-packages/jcvi/apps/base.py", line 111, in dispatch
    globals[action](sys.argv[2:])
  File "/usr/local/lib/python3.7/site-packages/jcvi/compara/catalog.py", line 707, in ortholog
    scan(dargs)
  File "/usr/local/lib/python3.7/site-packages/jcvi/compara/synteny.py", line 1902, in scan
    summary([anchor_file])
  File "/usr/local/lib/python3.7/site-packages/jcvi/compara/synteny.py", line 1441, in summary
    raise ValueError("A total of 0 anchor was found. Aborted.")
ValueError: A total of 0 anchor was found. Aborted.

**Comment by tanghaibao** [comment]
@Qiaojilim 

I recommend downloading data from Phytozome, as in the wiki. 

The important thing is to make sure that the sequence names must match between the BED (4th column should contain the gene names, for example, At1g12345. Then the FASTA header of the CDS file must contain the same set of names. When they don't match, you'll see the warnings "XXX not in xxx.bed".

Haibao

**Comment by Qiaojilim** [comment]
@tanghaibao 
thanks a lot. but I have several genomes which are not available on Phytozome so I have to download them from other websites. any suggestion or reference link to reformatted input files from other webs like Coge, NCBI???

appreciate for  your help


Qiaoji

**Comment by tanghaibao** [comment]
@Qiaojilim 

Try looking at `grape.bed` and `grape.cds` to see how to properly format your input. As I said in the previous comment, as long as the gene ids match, you should be able to run it.
