### ISSUE TITLE
Problems running jcvi.compara.catalog ortholog - bed file

### ISSUE THREAD

**Issue by sn-hoff** [tanghaibao/jcvi#253]
Hi,
I have tried to use your tool `jcvi.compara.catalog ortholog` to do synteny analysis between two chromosome level assemblies. However, I'm encountering this issue - which I've seen other users also have had - that the program has some problem with my input files.
I am running the program as so:
`python -m jcvi.compara.catalog ortholog --cpus=24 Species1 Species2`

In the directory, ive converted gff3 files for both species as well as the genomes to the correct *.bed and *.cds formats using `python -m jcvi.formats.gff`, that worked fine. 

When I then try to do the synteny analysis the program complains about not recognizing the chromosome names. Ive seen others having the issue if there are symbols such as "." in the naming, however, this isn't the case with my data. Also, I'm not able to download the phytozome data to have a look at that bed file for comparison...
Any help here would be much appreciated!! thank you!

Output from the program
```
22:09:17 [base] Set text.usetex=False. Font styles may be inconsistent.
22:09:17 [synteny] Assuming --qbed=species1.bed --sbed=species2.bed 
22:09:17 [base] Load file `species1.bed `
22:09:18 [base] Load file `species2.bed `
22:10:07 [blastfilter] Load BLAST file `species1.species2.last` (total 226572206 lines)
22:10:07 [base] Load file `species1.species2.last`
22:25:30 [blastfilter] Chr2 not in species1.bed
22:25:30 [blastfilter] Chr2 not in species1.bed
22:25:30 [blastfilter] Chr4 not in species1.bed
22:25:30 [blastfilter] Chr2 not in species1.bed
22:25:30 [blastfilter] Chr5 not in species1.bed
22:25:30 [blastfilter] Chr8 not in species1.bed
22:25:30 [blastfilter] Chr8 not in species1.bed
22:25:30 [blastfilter] Chr3 not in species1.bed
22:25:30 [blastfilter] Chr14 not in species1.bed
and so on
```
```
head species1.bed
Chr1	9636	14768	mrna_27996	0	+
Chr1	17762	19046	mrna_28008	0	+
Chr1	19439	20451	mrna_28012	0	+
Chr1	28787	30562	mrna_28020	0	-
Chr1	30645	42935	mrna_28028	0	-
Chr1	45633	48738	mrna_28056	0	+
Chr1	50724	51996	mrna_28070	0	-
Chr1	54605	59144	mrna_28080	0	-
Chr1	70575	71261	mrna_28092	0	-
Chr1	72530	73583	mrna_28098	0	-
```
```
head species2.bed
Chr1	1631	3814	mrna_16971	0	+
Chr1	14182	15137	mrna_16979	0	+
Chr1	30787	31767	mrna_16987	0	+
Chr1	34078	36380	mrna_16993	0	+
Chr1	52169	56584	mrna_17001	0	+
Chr1	63422	65245	mrna_17009	0	+
Chr1	73069	74799	mrna_17017	0	-
Chr1	75347	76124	mrna_17023	0	-
Chr1	79396	81342	mrna_17029	0	+
Chr1	97176	97428	mrna_17039	0	-
```

**Comment by tanghaibao** [comment]
@sn-hoff 

The issue is the CDS files. The sequence identifiers in your CDS files should match the 4th column in the BED file. 

From the errors, I guess that you accidentally used the genome sequences as the CDS files. You need a FASTA file listing the sequences for all those mrnas, NOT chromosomes.

Haibao
