### ISSUE TITLE
Try to use Arrows instead of Rectangles to represent genes but get wrong gene length

### ISSUE THREAD

**Issue by Tong-Chen** [tanghaibao/jcvi#256]
Thanks for the great tool!

I have done some modifications to `jcvi/graphics/synteny.py` and `jcvi/graphics/glyph.py` to show `gene_legend`,  add `gene names`.

However, when I use `Arrow` instead of `Rectangle` to represent genes, I found that the final representation arrows have less width compared with rectangle representations. 

I wonder if you can guide me the right way.

Thanks!

Chen Tong

![](http://www.ehbio.com/synteny.gif)

Github transfers the gif to a static picture, check [here](http://www.ehbio.com/synteny.gif) for the compare effect.

Here is the main code changed (Full commits can be found in <https://github.com/Tong-Chen/jcvi/commit/d2e4a4267d1c7ee32cdcec1793703571fb4d1692>):

`jcvi/graphics/glyph.py`

```
    def __init__(self, ax, x1, x2, y, height=0.04, gradient=True, fc="gray", pic_type='Rectangle',  **kwargs):

        super(Glyph, self).__init__(ax)
        width = x2 - x1
        # Frame around the gradient rectangle
        p1 = (x1, y - 0.5 * height)
        if pic_type == 'Rectangle':
            self.append(Rectangle(p1, width, height, fc=fc, lw=0, **kwargs))
        elif pic_type == 'Arrow':
            style="Simple,head_length=1,head_width=5,tail_width=5"
            x_tail = x1
            y_tail = y
            x_head = x2
            y_head = y
            self.append(FancyArrowPatch((x_tail, y_tail), (x_head, y_head),
                arrowstyle=style, fc=fc, lw=0,  **kwargs))
```

Here is my running command:

```
python -m jcvi.graphics.synteny test.Block test.Bed test.layout --scalebar --gene_style Arrow
```

Here is my test files:

test.Bed

```
chr6	1376353	1379120	TT031256.1	0	-
chr6	1383528	1386122	TT031255.1	0	-
chr6	1390246	1393700	TT031254.1	0	-
chr6	1404200	1409606	TT031253.1	0	-
NC_026150.1	18060005	18063562	rna17296	0	-
NC_026150.1	18085413	18090477	rna17299	0	+
NC_026150.1	18092324	18099844	rna17300	0	-
Chr06	23246823	23250353	Sb06t19660	0	-
Chr06	23232997	23236402	Sb06t19620	0	-
Chr06	23240508	23242110	Sb06t19650	0	-
scaffold45	2989852	2993973	Saspl_017770.T1	0	+
scaffold45	3000570	3001566	Saspl_017771.T1	0	+
scaffold45	3025859	3029056	Saspl_017772.T1	0	-
scaffold372	111490	115032	Saspl_048790.T1	0	+
scaffold372	127103	130463	Saspl_048791.T1	0	+
scaffold372	134141	137734	Saspl_048792.T1	0	+
```

test.Block

```
TT031256.1	rna17296	Sb06t19620	Saspl_017772.T1	Saspl_048792.T1
TT031255.1	rna17300	Sb06t19650	.	Saspl_048791.T1
TT031254.1	.	.	Saspl_017771.T1	.
TT031253.1	rna17299	Sb06t19660	Saspl_017770.T1	Saspl_048790.T1
```

test.layout

```
#x, y, rotation, ha, va, color, ratio, label
0.43, 0.6, 0, center, top, #ccee61, 1, DS
0.43, 0.2, 0, center, top, #fcdd61, 1, Sin NC_026150.1
0.45, 0.4, 0, center, top, #fcdd61, 2, HQ Chr06
0.580138130520194, 0.8, 0, center, top, #fcdd61, 0.6, Ssp scaffold45
0.2016165756624234, 0.8, 0, center, top, #fcdd61, 0.6, Ssp scaffold372
# edges
e, 0, 3
e, 0, 4
e, 0, 2
e, 0, 2
e, 2, 1
```

**Comment by tanghaibao** [comment]
@Tong-Chen 

Thanks. Is there any padding on the arrow itself? Have you tried changing the numbers in the style? I'll try to take a look at this over the weekend otherwise.

**Comment by Tong-Chen** [comment]
Thanks for your quick response.

I have tried changing the number in the style with no luck.

Besides, below codes can generate almost the same length of  Rectangles and Arrows.

```
import matplotlib.patches as mpatches
import matplotlib.pyplot as plt
x_tail = 0.5
y_tail = 0.5
dx = 500
dy = y_tail
fig, axs = plt.subplots(nrows=2)
arrow = mpatches.Rectangle((x_tail, 0.5), width=dx-x_tail,height=0.1)
axs[0].add_patch(arrow)
axs[0].set_xlim(0, 600)

style="Simple,head_length=4,head_width=5,tail_width=5"
arrow = mpatches.FancyArrowPatch((x_tail, y_tail), (dx, dy),
                                 mutation_scale=1,arrowstyle=style, lw=0,fc="green")
axs[1].add_patch(arrow)
axs[1].set_xlim(0, 600)
axs[1].set_ylim(0, 1)
```

**Comment by tanghaibao** [comment]
@Tong-Chen 

Thanks for sending in the patch. It appears that there are two options `shrinkA=2, shrinkB=2` for `FancyArrowPatch` that's causing the arrow to shrink on both sides. I changed these to 0 and it seems to be much closer to the rectangles. See below for alternating between "box" and "arrow". However, with PDF reader, it seems the "box" are still slightly bigger on the borders.

![Jun-12-2020 20-25-41](https://user-images.githubusercontent.com/106987/84559006-2b7b9480-acec-11ea-8ec7-9336d605ad43.gif)

Also, I have added this as an option `--glyphstyle` to the synteny plotting script and pushed it to master (credits to you). The default is still `box`, however, now you can choose `arrow` as an alternative glyph style.

Your patch also has other things, including plotting gene labels. I'll incorporate this feature later when I get a chance. Please feel free to send in a pull request.

Haibao

**Comment by Tong-Chen** [comment]
Thanks for your help. Sorry for missing these two parameters. These changes will really supply feasibility.

Chen Tong

**Comment by tanghaibao** [comment]
@Tong-Chen 

Just added the gene label based on your commit, with the option `--genelabelsize`, and use font size as the argument. Please see [related section on wiki](https://github.com/tanghaibao/jcvi/wiki/MCscan-(Python-version)#microsynteny-visualization).

Many thanks for coming up with the implementation.

Haibao
