### ISSUE TITLE
Whether the size of rectangle displayed in karyotype.pdf represent the real length of each chromosome

### ISSUE THREAD

**Issue by cherrie-g** [tanghaibao/jcvi#257]
Hi Dr.Tang,
I'm doing a three species synteny and i notised that the size of rectangle in karyotype figure did not match the real length of the chromosomes. 
For example, the No1 chromosome is the longest chromosome in my species, but in the figure, the third chromosome seems to be the longest.
So i am very curious that what the size of the rectangle represent for? I have compared the coding region length too. It doesn't seem to represent that either.

Thank for any advise.

**Comment by tanghaibao** [comment]
@cherrie-g 

By default, the length is relative to the number of genes on each chromosome. When option `--basepair` is on, the length is relative to the base pair size.

```console
  --basepair            Use base pair position instead of gene rank [default:
                        False]
```

**Comment by cherrie-g** [comment]
Thanks for a lot
