### ISSUE TITLE
Find_Inversion

### ISSUE THREAD

**Issue by wzhjlau2009** [tanghaibao/jcvi#259]
Hi,@tanghaibao:
    I am trying to highlight some Inversion region in the simple file, but i can't found the Inversion block from the bed position ， can you give me some suggestion if JCVI can found out this region ，that will help a lot ，thanks！

**Comment by tanghaibao** [comment]
@wzhjlau2009 

Not sure I fully understand your question here. You currently have a figure and you saw some inversion - and you are interested in knowing the boundary of that inversion ... correct?

First of all, you should know the rough regions, like which chromosome pairs. Your goal is to find the line in the `.simple` file that corresponds to the inversion. What I often do is I'll try to highlight different lines in the `.simple` file, by adding `*` (asterisk) in the front. Sometimes, you can also use different colors like `g*` will color them differently, in this case, by green color. 

The 5th column is the score of the synteny block. Bigger score means bigger size. Try highlighting a number of lines in `.simple` file at first, then remove half of the highlights, then re-plot to see if the inversion is still there. You should be able to find your inversion after a few tries. Kind of like binary search.

Haibao

**Comment by wzhjlau2009** [comment]
@tanghaibao 
Thanks for your help. Yep, I want to highlight some Inversion region in the karyotype, I have found some block from the anchor file, thanks so much.
