### ISSUE TITLE
Possible to retrieve alt_id using obo.py?

### ISSUE THREAD

**Issue by chiayic** [tanghaibao/jcvi#264]
Hello~

I was wondering if it's possible to retrieve the alt_id from obo file using obo.py. For example, for this term
```
id: GO:0000003
name: reproduction
namespace: biological_process
alt_id: GO:0019952
alt_id: GO:0050876
```
It'd be great if the two alt_id would be appended to the output. Right now I don't get that
```
$ python -m jcvi.formats.obo go.obo 
GO:0000001      level-06        mitochondrion inheritance [biological_process]
GO:0000002      level-06        mitochondrial genome maintenance [biological_process]
GO:0000003      level-01        reproduction [biological_process]
```
If this supported? Thank you for answering this question.

**Comment by tanghaibao** [comment]
@chiayic 

The obo parser in formats.obo is now unmaintained and deprecated. We have another library, [goatools](https://github.com/tanghaibao/goatools) that specifically handles the Gene Ontology. 

I have kept the script as is, but you'll need to install goatools first.

```console
$ pip install -U goatools
$ python -m jcvi.formats.obo go.obo
#id	level	name	alt_ids
GO:0000001	level-06	mitochondrion inheritance [biological_process]
GO:0000002	level-06	mitochondrial genome maintenance [biological_process]
GO:0000003	level-01	reproduction [biological_process]	GO:0019952,GO:0050876
GO:0000006	level-07	high-affinity zinc transmembrane transporter activity [molecular_function]
```

Notice column 4 contains alt_id if any (in this case, GO:0000003 has alt_ids). Also, please use Python 3 when possible as we are dropping Python 2 support.

Haibao
