### ISSUE TITLE
concorde-TSP failure--potential issues in tsp.py

### ISSUE THREAD

**Issue by gordonyounkin** [tanghaibao/jcvi#265]
Hi jcvi team,

I believe I may have found a few issues in `jcvi/algorithms/tsp.py. I first ran into these issues with my own data, but the issue persists if I use the provided test dataset, so that is the dataset I used to produce the below errors. 

When running `python -m jcvi.assembly.allmaps path JM-2.bed scaffolds.fasta`, the process completes and gives the same outputs shown in the ALLMAPS wiki (including a figure identical to the one under "Visualize alignments"). However, when I look at the command line output, it says that concorde-TSP has failed and default scaffold ordering is used:
```
14:29:22 [allmaps] Working on JMMale-23|JMFemale-23 ...
14:29:27 [allmaps] Graph size: |V|=24, |E|=474.
14:29:28 [allmaps] concorde-TSP failed. Use default scaffold ordering.
```
The rest of the code runs as expected. Concorde is installed on my computer, so I went to the location in `jcvi/assembly/allmaps.py` where the error message `concorde-TSP failed. Use default scaffold ordering.` originates:
```
311         except:
312             logging.debug("concorde-TSP failed. Use default scaffold ordering.")
```
And added `print(sys.exc_info())` to the exception to give more information about why concorde-TSP was failing. 
```
311         except:
312             logging.debug("concorde-TSP failed. Use default scaffold ordering.")
313             print(sys.exc_info())
```
When I run `python -m jcvi.assembly.allmaps path JM-2.bed scaffolds.fasta` with this addition, I get:

```
14:36:43 [allmaps] Working on JMMale-23|JMFemale-23 ...
14:36:43 [allmaps] Graph size: |V|=24, |E|=474.
14:36:43 [allmaps] concorde-TSP failed. Use default scaffold ordering.
(<class 'TypeError'>, TypeError("'<' not supported between instances of 'str' and 'tuple'"), <traceback object at 0x1a1ab22588>)
```
After tracing this error through various functions, I found that this error is ultimately raised by the `node_to_edge()` function in `jcvi/algorithms/tsp.py` because it cannot handle the input handed to it by `hamiltonian()` via `tsp()`. To demonstrate, I used the simplified example edges provided in the description of the `hamiltonian()` function. In python, if I run:
```
from jcvi.algorithms.tsp import *

g = [(1,2), (2,3), (3,4), (4,2), (3,5)]
hamiltonian(g)
```
I get the error
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/gordonyounkin/.local/lib/python3.7/site-packages/jcvi/algorithms/tsp.py", line 179, in hamiltonian
    tour = tsp(dummy_edges, precision=precision)
  File "/Users/gordonyounkin/.local/lib/python3.7/site-packages/jcvi/algorithms/tsp.py", line 198, in tsp
    c = Concorde(edges, precision=precision)
  File "/Users/gordonyounkin/.local/lib/python3.7/site-packages/jcvi/algorithms/tsp.py", line 40, in __init__
    self.print_to_tsplib(edges, tspfile, precision=precision)
  File "/Users/gordonyounkin/.local/lib/python3.7/site-packages/jcvi/algorithms/tsp.py", line 66, in print_to_tsplib
    incident, nodes = node_to_edge(edges, directed=False)
  File "/Users/gordonyounkin/.local/lib/python3.7/site-packages/jcvi/algorithms/tsp.py", line 138, in node_to_edge
    nodes = sorted(nodes)
TypeError: '<' not supported between instances of 'str' and 'int'
```
I think what's happening is that `hamiltonian()` adds dummy edges to `g` before passing to `node_to_edge()` via `tsp()`, and `node_to_edge()` cannot handle the modified `dummy_edges` object. Below, I run the code contained within the hamiltonian function (lines 172-180, with edits to reflect arguments `directed=False, precision=0`), using `g` as the input edges object.
```
edges = populate_edge_weights(g)
incident, nodes = node_to_edge(edges, directed=False)
DUMMY = "DUMMY"
dummy_edges = edges + [(DUMMY, x, 0) for x in nodes]
tour = tsp(dummy_edges, precision=0) 
```
Which gives the same error indicated above involving `TypeError: '<' not supported between instances of 'str' and 'int'`. When I run `tour = tsp(edges, precision=0)`, the function runs as expected. When dummy edges are added, the `nodes` object cannot be properly sorted by `node_to_edge()` function due to a mix of strings and integers.

I did find a workaround to this by just removing line 138 `nodes = sorted(nodes)`, though I imagine this messes up the output. It runs, but I'm not sure that it's giving a meaningful output, so I'll leave it to you to figure out what's going on.

A sidenote: I also found an error I believe has to do with migrating from python2.7 to python3. In `jcvi/algorithms/tsp.py`, line 116, I think the code as written is deprecated, as text file objects no longer have a next method:
`dimension = int(fp.next().strip())`
should instead be
`dimension = int(fp.readline().strip())`

Thanks for your help!
Gordon

**Comment by tanghaibao** [comment]
@gordonyounkin 

Thank you for the detailed analysis of the error. I'll patch it up with the lead that you have here. Luckily, for most ALLMAPS applications, the concorde step is not needed. The step is there to speed up the calculation, however, in most cases, the speed savings isn't all that significant compared to the overall run time.

Yes, py2 to py3 has caused lots of issues and I only fix them one by one for some of the more frequently used scripts. My unit test coverage is very low and it is difficult to spot those errors unless myself or other people start executing some code paths.

Please feel free to send in PR or bug reports like this one. Really appreciate it!

Haibao

**Comment by gordonyounkin** [comment]
Thanks for the patch @tanghaibao. I'll be sure to let you know if I run into any other issues.
