### ISSUE TITLE
How to change the synteny trend in dotplot

### ISSUE THREAD

**Issue by cfc424** [tanghaibao/jcvi#267]
Dear Tang,

In my dataset, the dotplot is as below:
![image](https://user-images.githubusercontent.com/30213207/84898686-3bbfb500-b0da-11ea-9ce5-85cd8d598534.png)

I want to change the synteny trend in red circle to the trend in blue circle. How can I manipulate my data.
I've tried get the reversed compmlement  sequences of chromosome LG07, but the result is unchanged. 

Thanks.

**Comment by tanghaibao** [comment]
@cfc424 

The trend is affected by the gene positions in the BED file. So you'll need to adjust the positions of all the genes on that chromosome. 

For example, your current BED has:
```
LG07    1000   2000    gene1
LG07    3000   4000    gene2
```

And LG07 has length of 10000, then after the reverse complement:
```
LG07    6000   7000    gene2
LG07    8000   9000    gene1
```

I do not have a script that currently does this, however, so you may have to find a way to generate a reverse-complemented BED file that contains the FLIPPED chromosomes.

Haibao

**Comment by cfc424** [comment]
Thanks for your prompt answer！ I will try it.
