### ISSUE TITLE
How to recompile faSize and liftOver

### ISSUE THREAD

**Issue by jaflury** [tanghaibao/jcvi#270]
Dear all, 

I ran into problems while running the examples. I was able to run

python -m jcvi.assembly.allmaps merge JMMale.csv JMFemale.csv -o JM-2.bed

but the next command gave me this error:

(base) Janas-MacBook-Pro:ALLMAPS-testdata Jana$ python -m jcvi.assembly.allmaps path JM-2.bed scaffolds.fasta
16:39:38 [base] Set text.usetex=False. Font styles may be inconsistent.
16:39:38 [base] Load file `JM-2.bed`
16:39:38 [allmaps] Map contains 120 markers in 2 linkage groups.
16:39:38 [allmaps] Retained 120 of 120 (100.0%) clean markers.
16:39:38 [base] Load file `weights.txt`
16:39:38 [base] Imported 2 records from `weights.txt`.
16:39:38 [allmaps] Map weights: odict_items([('JMFemale', 1), ('JMMale', 1)])
16:39:38 [allmaps] Linkage function: double-linkage
16:39:38 [allmaps] Partition LGs based on JMFemale
16:39:38 [base] faSize -detailed /Users/Jana/ALLMAPS-testdata/scaffolds.fasta >scaffolds.fasta.sizes
/bin/bash: /Users/Jana/opt/anaconda3/bin/faSize: cannot execute binary file
16:39:38 [base] Load file `scaffolds.fasta.sizes`
Traceback (most recent call last):
  File "/Users/Jana/opt/anaconda3/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/Users/Jana/opt/anaconda3/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/Jana/opt/anaconda3/lib/python3.7/site-packages/jcvi/assembly/allmaps.py", line 2037, in <module>
    main()
  File "/Users/Jana/opt/anaconda3/lib/python3.7/site-packages/jcvi/assembly/allmaps.py", line 863, in main
    p.dispatch(globals())
  File "/Users/Jana/opt/anaconda3/lib/python3.7/site-packages/jcvi/apps/base.py", line 111, in dispatch
    globals[action](sys.argv[2:])
  File "/Users/Jana/opt/anaconda3/lib/python3.7/site-packages/jcvi/assembly/allmaps.py", line 1573, in path
    sizes = Sizes(fastafile).mapping
  File "/Users/Jana/opt/anaconda3/lib/python3.7/site-packages/jcvi/formats/sizes.py", line 69, in __init__
    ctgs, sizes = zip(*sizes)
ValueError: not enough values to unpack (expected 2, got 0)

It must be a problem with faSize and also liftOver cannot be executed:

(base) Janas-MacBook-Pro:bin Jana$ ./liftOver
-bash: ./liftOver: cannot execute binary file

There is only the example to recompile concorde, but not the other two. I am using a Mac, OS Catalina, and I don't have much experience with compiling. I already used chmod 777 but it didn't change anything.

Thank you for your help,

Jana

**Comment by tanghaibao** [comment]
@jaflury 

Download `faSize` here (search for it within the page):
http://hgdownload.cse.ucsc.edu/admin/exe/macOSX.x86_64/

`liftOver` can be found here (choose macOS version in your case), please confirm the license requirement:
https://genome-store.ucsc.edu/

Haibao

**Comment by jaflury** [comment]
Thank you very much for the quick answer. I downloaded both to my homedirectory, but I still get the error, since python uses the anaconda bin. 

(base) Janas-MacBook-Pro:~ Jana$ ./faSize
faSize - print total base count in fa files.
usage:
   faSize file(s).fa
Command flags
   -detailed        outputs name and size of each record
                    has the side effect of printing nothing else
   -tab             output statistics in a tab separated format

(base) Janas-MacBook-Pro:~ Jana$ faSize
-bash: /Users/Jana/opt/anaconda3/bin/faSize: cannot execute binary file

How can I tell allmaps to use the ones in my home directory? I know it has something to do with the PATH, but I don't know what I have to change.

Best,
Jana

**Comment by tanghaibao** [comment]
@jaflury 

I assume that you downloaded the binaries in `/path/bin`. Then this command below puts it on your PATH.

```console
export PATH=/path/bin:$PATH
```

Check which faSize you are using

```console
which faSize
```

This works for your current terminal session. To make it work for all future sessions, add the line `export PATH=/path/bin:$PATH` in your `~/.bashrc` file or `~/.bash_profile` (can't remember which one to use on macOS, but feel free to try both).

**Comment by jaflury** [comment]
The thing is, I have both bin in my PATH:

**/Users/Jana/opt/anaconda3/bin**:/Users/Jana/opt/anaconda3/condabin:/opt/local/bin:/opt/local/sbin:/anaconda3/bin:/Library/Frameworks/Python.framework/Versions/3.7/bin:**/usr/local/bin**:/usr/bin:/bin:/usr/sbin:/sbin:/Users/Jana/bpp-4.1.4-macos-x86_64/bin:/opt/X11/bin:/Users/Jana/scripts

But it uses automatically the wrong one
(base) Janas-MacBook-Pro:~ Jana$ which faSize
/Users/Jana/opt/anaconda3/bin/faSize

How can I change this?

**Comment by tanghaibao** [comment]
@jaflury 

Whichever comes first in your `$PATH` is run. In your case, the anaconda one occurs before everybody else so that gets run.

So I specifically added your path in front of everything else `export PATH=/path/bin:$PATH`.

**Comment by jaflury** [comment]
I am getting a bit desperate here, I see that adding it export PATH=/usr/local/bin:$PATH adds it in front, but saving with the bash_profile does not work. I use nano to add it and save it, but somehow anaconda3 seems to be programmed through the bash_profile to jump in front again. This should not be your issue, I will just add it manually as long as I need it and will try to find a solution for the bash_profile.

**Comment by tanghaibao** [comment]
@jaflury 

Conda auto inserts itself in front of the PATH in the bash_profile. You would have to identify that part and amend your PATH AFTER conda does its thing.
