### ISSUE TITLE
How to highlight one gene in Microsynteny？

### ISSUE THREAD

**Issue by wzhjlau2009** [tanghaibao/jcvi#271]
@tanghaibao ，Hi
Thanks for so powerful tools！
I was trying to know if i could highlight one or two genes in the Microsynteny function and how， Thanks！

**Comment by tanghaibao** [comment]
@wzhjlau2009 

Currently you can only highlight the synteny connection (see wiki), not the gene itself. The easiest, for now, is perhaps to use Adobe Illustrator or Inkscape to manually edit the gene or interest.

**Comment by wzhjlau2009** [comment]
@tanghaibao ，hi
Thanks for your reply！
And I have another question about Microsynteny， I want to use 9 genomes to see the Microsynteny，but i think some of the genome can find the correct position and chromosome info during the synteny analysis. And i don't know why, Because the gene ID looks like from the same spieces or genome? 
![image](https://user-images.githubusercontent.com/6326115/85314827-9c8d2a00-b4ec-11ea-92fb-a7b01fb07f9e.png)
For some column , the pos infomation is not correct.

**Comment by wzhjlau2009** [comment]
or It is because one gene id is also exists in another genome? For example , the Column with none sign  in the brace and the position is also wrong，and i can't get the final pdf results. Can you give me some suggestions about this ? thanks!

**Comment by tanghaibao** [comment]
@wzhjlau2009 

Check your column 4, 6, and 8 carefully (the first column is 0). It is likely that these columns contain genes that map to different chromosomes. Also, please make sure that the gene ids are unique in the BED file (`CS_B_CS_A_N02_CS_D....bed`) that you are using here.

Use Column 4 as an example, are `EVM0046481` and `EVM0030971` on the same chromosome? If they are not, then jcvi cannot identify the region covering both genes.

**Comment by wzhjlau2009** [comment]
![image](https://user-images.githubusercontent.com/6326115/85935827-4e7e8900-b927-11ea-9c4e-ceaacc2a8497.png)
@tanghaibao 
Thanks for your help！Now，I got the karotype pdf ， but i found each region was consists of  genes from different genome，and i don‘t know why. Thanks very much!

**Comment by tanghaibao** [comment]
@wzhjlau2009 

Would you please double-check that in your .blocks file, every single column contains genes from just one chromosome, and the regions in the BED file contain the right genes? Also, please send the log that appeared on the screen when you did the plotting.
