### ISSUE TITLE
Install error

### ISSUE THREAD

**Issue by tuguangxian** [tanghaibao/jcvi#275]
Hi Haibao,
I'm trying to install the jcvi package by **pip install --user ./jcvi**. I got these errors:
**ERROR: Directory './jcvi' is not installable. Neither 'setup.py' nor 'pyproject.toml' found.**
Do you have any suggestion？
Thanks！

**Comment by tanghaibao** [comment]
@tuguangxian 

Make sure you are pointing to the right folder. As seen in the error message, there needs to be a "setup.py" inside the folder. If you just download it or clone it from the folder, it should already contain this file. Check your path if you meant the current folder ".", or "./jcvi".
