### ISSUE TITLE
Contigs present in only one map.

### ISSUE THREAD

**Issue by gordonyounkin** [tanghaibao/jcvi#276]
Hi @tanghaibao,

Thanks again for your help with my previous issue  #265 . I have been able to run ALLMAPS on my own data, but the results are not quite what I would have expected, and I am wondering if you have any recommendations. I am working to reconcile two maps: a genetic linkage map based on an F2 population and a Hi-C-based proximity-guided assembly. I am more confident in the F2 map, so it is weighted more heavily, but it only has markers on the largest contigs. The Hi-C map is less reliable, but it is useful because many small contigs which do not appear in the F2 map do appear in the Hi-C map. When I run `python -m jcvi.assembly.allmaps path` on my appropriately formatted files, the result is as expected for the large contigs present in both maps, but the contigs which are only present in the Hi-C map do not behave as I would expect. 

For example, take linkage group 8 in the F2 map, as shown [in this figure](https://github.com/tanghaibao/jcvi/files/4839358/chrF2LG8_weights_10_1.pdf). In the Hi-C map, there are some inversions and rearrangements. I am hoping that ALLMAPS will be able to use the order of the large contigs present in the F2 map to correct these issues, pulling small contigs along with them in the case of rearrangements and inversions. However, the result I am getting is that the order of the large contigs is correct, but any contigs present only in the Hi-C map are being ordered by the absolute position in the Hi-C map, rather than by the position relative to contigs present in the F2 map. You can see this most clearly near the top of of PGA-HiCscaf5 in the figure, where the large contigs have markers that are farther apart and are placed at the bottom of the final assembly. However, the small contigs in this region, which are the closely packed markers flanking these contigs, remain at the top of the final assembly. I would have expected them to be pulled along with the large contigs to the bottom to retain the relative order of the Hi-C map.

Is this the behavior you would expect, or are there parameters I can alter to try and improve the reconciliation? I realize this may be a unique case where the less reliable map has so many contigs that are not present in the more reliable map.

Thanks again for your help and prompt response to my questions!
Gordon

**Comment by tanghaibao** [comment]
@gordonyounkin 

I think these results appear as what I'd expect. The computational goal is to maximize the total score for both maps. In the case of small contigs, the F2 map imposes zero constraints on them so they'd order themselves in such a way that will maximize the score on the HIC map (basically just follow the order of the HIC map).

Can you think of other evidence that you use to bind these small contigs relative to the large contigs? Currently, the only linkage info is on the HIC map and they'd follow that map to the teeth. Do you have another map that you can use for this?

**Comment by gordonyounkin** [comment]
@tanghaibao thanks for the response. My only other option without doing additional data collection would be to use synteny, but I'm not sure I want to go down that road. I guess I'm surprised that the score is maximized over the absolute map position, rather than the position relative to contigs that are well-anchored in the more reliable map. It seems to me that this could be an issue when using proximity-guided assemblies or cross-species synteny, both of which are prone to large inversions and rearrangements similar to what I am dealing with. I'm certainly no expert in this area though, so maybe my case is more unique than I thought. Would you not recommend using ALLMAPS given the data I currently have?
