### ISSUE TITLE
how can i highlight genome duplications?

### ISSUE THREAD

**Issue by niuhuifei** [tanghaibao/jcvi#277]
Dear Tang, 
Firstly many thanks for this wonderful python-version of MCScanX. I have a question when I do some comparative case such as finding 3:1 synteny regions between grape and Amborella, how can I find them and highlighted in the figure? the ortholog resulted file .anchors seems only 1:1 ones. Many thanks!

**Comment by tanghaibao** [comment]
@niuhuifei 

You can identify blocks that are aligned to the same region in Amborella. Below is some commands to get started:

```console
$ python -m jcvi.compara.catalog ortholog amborella grape
$ python -m jcvi.compara.synteny mcscan amborella.bed amborella.grape.lifted.anchors --iter=3 -o amborella.grape.i3.blocks
```

The output `amborella.grape.i3.blocks` contains 4 columns: 1st is Amborella genes, columns 2-4 are grape genes aligned.

See also:
https://github.com/tanghaibao/jcvi/wiki/MCscan-(Python-version)#microsynteny-getting-fancy

**Comment by Qiaojilim** [comment]
hello Haibao,
when I use the command to identify blocks, it seems cut off some blocks though it is aligned to the same region in one genome. I mean the number of highlight blocks is less than what I observed just from karyotype plot. so I am sort of confused how to highlight all of the duplications. thanks for your time.

**Comment by Qiaojilim** [comment]
besides, it also git an error like "KeyError: 'Aco005086.1'" after executing command '"--iter=3", could you please give me some suggestion? thanks

**Comment by sunnycqcn** [comment]
Dear Dr. Tang,
I have a question about colummns 2-4. 2 is the single genes aligned with the reference genome. 3 and 4 are duplicated genes?
I can not really understand this. 
Thanks,
Fuyou

> @niuhuifei
> 
> You can identify blocks that are aligned to the same region in Amborella. Below is some commands to get started:
> 
> ```
> $ python -m jcvi.compara.catalog ortholog amborella grape
> $ python -m jcvi.compara.synteny mcscan amborella.bed amborella.grape.lifted.anchors --iter=3 -o amborella.grape.i3.blocks
> ```
> 
> The output `amborella.grape.i3.blocks` contains 4 columns: 1st is Amborella genes, columns 2-4 are grape genes aligned.
> 
> See also: https://github.com/tanghaibao/jcvi/wiki/MCscan-(Python-version)#microsynteny-getting-fancy

**Comment by tanghaibao** [comment]
@sunnycqcn 

Grape is a 'hexaploid' compared to Amborella.
https://www.nature.com/articles/nature06148

So there will be up to three genes (columns 2, 3, 4) when compared with a single Amborella gene (column 1) in this case.

**Comment by sunnycqcn** [comment]
> @sunnycqcn
> 
> Grape is a 'hexaploid' compared to Amborella. https://www.nature.com/articles/nature06148
> 
> So there will be up to three genes (columns 2, 3, 4) when compared with a single Amborella gene (column 1) in this case.

Dear Dr. Tang,
My plant genome should have duplication events. I do not know the number of ploidy in this plant. So column 2,3,4 present the different duplicated times. 
Thanks,
Fuyou
