### ISSUE TITLE
Set text.usetex=False. Font styles may be inconsistent.

### ISSUE THREAD

**Issue by LcW-ai** [tanghaibao/jcvi#278]
Dear Tang,
i am trying to use python -m jcvi.compara.catalog ortholog grape peach --no_strip_names
but result this erro:
01:59:36 [base] Set text.usetex=False. Font styles may be inconsistent.

so i try to find matplotibrc ,but i find:
#text.usetex : False  ## use latex for all text handling. The following fonts
                      ## are supported through the usual rc parameter settings:
                      ## new century schoolbook, bookman, times, palatino,
                      ## zapf chancery, charter, serif, sans-serif, helvetica,
                      ## avant garde, courier, monospace, computer modern roman,
                      ## computer modern sans serif, computer modern typewriter
                      ## If another font is desired which can loaded using the
                      ## LaTeX \usepackage command, please inquire at the
                      ## matplotlib mailing list
can anyone help me.

**Comment by Wangqq0515** [comment]
Hello, I have the same situation, have you solved it?

**Comment by kedduck** [comment]
Hello, I meet the same problem, can you give me the solution? thanks.
