### ISSUE TITLE
How to remove the separate line of contigs?

### ISSUE THREAD

**Issue by nzx9581** [tanghaibao/jcvi#281]
Dear Tang, 

Thanks for your excellent Python version MCscan sofware. I have two questions about pairwise synteny dot plot, 1) how can I remove the "green" separate line of contigs, 2) how to change the color of the synteny region, eg. the color of positive slope is blue ortherwise is red. Thank you for your kind help!
![wpic wstri](https://user-images.githubusercontent.com/51120830/88017616-a0968100-cb58-11ea-9463-06806721d513.jpg)

**Comment by tanghaibao** [comment]
@nzx9581 

There are two options that could help:

```console
$ python -m jcvi.graphics.dotplot

  --nosep               Do not add contig lines [default: False]
  --colormap=COLORMAP   Two column file, block id to color mapping [default:
                        none]
```

- `--nosep` could remove the contig separator lines
- `--colormap map.txt` allows you to show blocks in any given color. The first column is the id (sequential id in the `.anchors` file). The second column is the color name (e.g. 'g', 'r', 'lightgreen', '#101010').

I have not implemented the automatic coloring for forward/reverse blocks. I might get it implemented when I get the time.

Haibao

**Comment by tanghaibao** [comment]
@nzx9581 

I have implemented the coloring based on block orientation. So back to your original request, we can do:

```console
python -m jcvi.graphics.dotplot grape.peach.anchors --nosep --colororientation
```

![image](https://user-images.githubusercontent.com/106987/88458722-dd0df980-ce44-11ea-86de-ef766dac3912.png)

**Comment by nzx9581** [comment]
Thank you very much for your kind help!
