### ISSUE TITLE
Hi, Haibao,

### ISSUE THREAD

**Issue by ITEliteCCY** [tanghaibao/jcvi#287]
Hi, Haibao,
I have the latex errors when I running the test analysis
`RuntimeError: Failed to process string with tex because latex could not be found`
I installed latex by `pip install latex` but not working.
I have no sudo authority, and using python3.7, what can I do to fix this bug?
Thanks!

_Originally posted by @DieTANG in https://github.com/tanghaibao/jcvi/issues/160#issuecomment-575528670_

**Comment by tanghaibao** [comment]
@ITEliteCCY 

Unfortunately, with the current version, we will need LATEX installed. If this can't be installed.
I will look into ways to still generate results without LATEX however it may take a while.

Haibao
