### ISSUE TITLE
install problem about pandas and lzma

### ISSUE THREAD

**Issue by shiyi-pan** [tanghaibao/jcvi#289]
hi, when I installed the pandas and jcvi . there were nothing wrong . but when I run the jcvi, it told me that :
/pandas/compat/__init__.py:117: UserWarning: Could not import the lzma module. Your installed Python is incomplete. Attempting to use lzma compression will result in a RuntimeError.
I checked in the web and  I need to install xz-devel and python-backports-lzma and backports.lzma before I install the pandas and jcvi.but I don't know where to download the python-backports-lzma,could you give me a link or some advise to fix this problem? thank you.

**Comment by tanghaibao** [comment]
@shiyi-pan 

This seems to be an issue with `pandas` and not `jcvi`. I have not encountered this problem before.
Also, if this is a `UserWarning` sometimes you may be able to ignore this error and still get things to run.

Haibao

**Comment by shiyi-pan** [comment]
thank you for your reply.but I got a error after the warning when i run it. I am not sure whether the warning cause the error.could you give me some advise?

 here is the error it is:

22:34:57 [chain] File written to `/ds3512/home/panyp/denovo/allmaps/ALLMAPS-testdata/JM-2.chain`.
22:34:57 [base] liftOver -minMatch=1 /ds3512/home/panyp/denovo/allmaps/ALLMAPS-testdata/JM-2.bed /ds3512/home/panyp/denovo/allmaps/ALLMAPS-testdata/JM-2.chain /ds3512/home/panyp/deno
vo/allmaps/ALLMAPS-testdata/JM-2.lifted.bed unmapped
/bin/bash: liftOver: command not found
Traceback (most recent call last):
  File "/ds3512/home/panyp/ruanjian/python/lib/python3.6/runpy.py", line 193, in _run_module_as_main

before that error ,here are the warnings:

/ds3512/home/panyp/ruanjian/python/lib/python3.6/site-packages/pandas/compat/__init__.py:117: UserWarning: Could not import the lzma module. Your installed Python is incomplete. Attempting to use l
zma compression will result in a RuntimeError.
  warnings.warn(msg)

/ds3512/home/panyp/ruanjian/python/lib/python3.6/site-packages/deap/creator.py:141: RuntimeWarning: A class named 'FitnessMax' has already been created and it will be overwritten. Consider deleting
 previous creation of that class or rename it.
  RuntimeWarning)
/ds3512/home/panyp/ruanjian/python/lib/python3.6/site-packages/deap/creator.py:141: RuntimeWarning: A class named 'Individual' has already been created and it will be overwritten. Consider deleting
 previous creation of that class or rename it.

**Comment by tanghaibao** [comment]
@shiyi-pan 

See manual and download `liftOver` and place it on your `PATH`
https://github.com/tanghaibao/jcvi/wiki/ALLMAPS#external-dependencies

**Comment by shiyi-pan** [comment]
thank you for your reply,dear haibao, I'm sorry I didn't notice it. I will read it carefully this time.
