### ISSUE TITLE
Output from python -m jcvi.compara.reconstruct fuse *bed *anchors 

### ISSUE THREAD

**Issue by scotty323** [tanghaibao/jcvi#291]
Dear Professor Haibao Tang,

I tried to fuse several anchor files by using "python -m jcvi.compara.reconstruct fuse *bed *anchors ".

I am not quite sure about the meaning of these signs in the output file, including "=" , "<--<",  ">-->",  "<-->",  ">--<"

Could you provide any clue for these signs?

AL1G10010=Bo8g118320.1=Bra032670.1=AT1G02205.2<--<AT1G02190.1=AL1G10020
AT1G02190.1=AL1G10020<-->AL1G10040=Bo5g001370.1=Bra033213.1
AL1G10040=Bo5g001370.1=Bra033213.1>--<AT1G02170.1=AL1G10050
AT1G02170.1=AL1G10050<--<AL1G10060=Bo5g001360.1=Bra033214.1=AT1G02160.1
AL1G10060=Bo5g001360.1=Bra033214.1=AT1G02160.1<--<AL1G10070=Bo5g001350.1=Bra033215.1=AT1G02150.1
AL1G10070=Bo5g001350.1=Bra033215.1=AT1G02150.1<--<AL1G10080=Bo5g001340.1=Bo8g118300.1=Bra032669.1=AT1G02145.1
AL1G10080=Bo5g001340.1=Bo8g118300.1=Bra032669.1=AT1G02145.1<-->AL1G10090=Bo5g001330.1=Bo8g118290.1=Bra032668.1=Bra033217.1=AT1G02140.1
AL1G10090=Bo5g001330.1=Bo8g118290.1=Bra032668.1=Bra033217.1=AT1G02140.1>-->AL1G10104=Bo8g118280.1
AL1G10104=Bo8g118280.1>--<AL1G10110=Bo5g001320.1=Bra033218.1=AT1G02120.1
AL1G10110=Bo5g001320.1=Bra033218.1=AT1G02120.1<--<AL4G43920=Bo3g037440.1=Bo8g095070.1=AL5G42540=Bo4g105080.1=Bra000365.1=Bra007523.1=Bra014497.1=AT3G60320.1=AT1G02110.1=AL1G10120
AL4G43920=Bo3g037440.1=Bo8g095070.1=AL5G42540=Bo4g105080.1=Bra000365.1=Bra007523.1=Bra014497.1=AT3G60320.1=AT1G02110.1=AL1G10120<--<AL1G10130=Bo8g118270.1=Bra032667.1=AT1G02100.1

Tao

**Comment by tanghaibao** [comment]
@scotty323 

Sorry for the slow response. These are the edge annotation in a bidirected graph. However, due to the exploratory nature of this particular tool, we do not currently support the use of the `fuse` script directly.

Haibao
