### ISSUE TITLE
Segmentation fault  error

### ISSUE THREAD

**Issue by shiyi-pan** [tanghaibao/jcvi#292]
Hi,when I run the allmap , I met an error :

/opt/gridengine/default/spool/compute-0-1/job_scripts/25767: line 27: 16395 Segmentation fault      $PYTHON -m jcvi.assembly.allmaps path $DIR/JM-2.bed $DIR/scaffolds.fasta -w $DIR/weights.txt

here is my script:

PYTHON=/ds3512/home/panyp/biosoft/python/bin/python3
DIR=/ds3512/home/panyp/denovo/allmaps/ALLMAPS-testdata

$PYTHON -m jcvi.assembly.allmaps merge $DIR/JMMale.csv $DIR/JMFemale.csv -o $DIR/JM-2.bed -w $DIR/weights.txt
$PYTHON -m jcvi.assembly.allmaps path $DIR/JM-2.bed $DIR/scaffolds.fasta -w $DIR/weights.txt

could you give me some advise to fix this error ? thank you very much.

**Comment by tanghaibao** [comment]
@shiyi-pan 

Often "segmentation fault" is due to bad installation of Python, or one of the installed modules. If there was a bug within the Python code, usually you'll be able to see the Python traceback.
