### ISSUE TITLE
Unable to generate file

### ISSUE THREAD

**Issue by yueyuanshuai** [tanghaibao/jcvi#293]
Dear Mr. Tang Haibao, first of all, I would like to thank you for providing such excellent software. However, I found some problems in the process of using it, and I suspect that there may be some mistakes in the configuration file. The command line and errors are as follows.

# python3 -m jcvi.graphics.synteny all.block all.bed all.layout
/usr/local/lib/python3.6/dist-packages/jcvi/graphics/base.py:229: MatplotlibDeprecationWarning: You are modifying the state of a globally registered colormap. In future versions, you will not be able to modify a registered colormap in-place. To remove this warning, you can make a copy of the colormap first. cmap = copy.copy(mpl.cm.get_cmap("Reds"))
  reds.set_bad("white")
/usr/local/lib/python3.6/dist-packages/jcvi/graphics/base.py:230: MatplotlibDeprecationWarning: You are modifying the state of a globally registered colormap. In future versions, you will not be able to modify a registered colormap in-place. To remove this warning, you can make a copy of the colormap first. cmap = copy.copy(mpl.cm.get_cmap("Reds"))
  reds.set_under("white")
/usr/local/lib/python3.6/dist-packages/jcvi/graphics/base.py:233: MatplotlibDeprecationWarning: You are modifying the state of a globally registered colormap. In future versions, you will not be able to modify a registered colormap in-place. To remove this warning, you can make a copy of the colormap first. cmap = copy.copy(mpl.cm.get_cmap("Blues_r"))
  blues_r.set_bad("white")
/usr/local/lib/python3.6/dist-packages/jcvi/graphics/base.py:234: MatplotlibDeprecationWarning: You are modifying the state of a globally registered colormap. In future versions, you will not be able to modify a registered colormap in-place. To remove this warning, you can make a copy of the colormap first. cmap = copy.copy(mpl.cm.get_cmap("Blues_r"))
  blues_r.set_under("white")
22:15:29 [base] Load file `all.bed`
22:15:31 [base] Load file `all.block`
22:15:31 [base] Load file `all.layout`
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.6/dist-packages/jcvi/graphics/synteny.py", line 592, in <module>
    main()
  File "/usr/local/lib/python3.6/dist-packages/jcvi/graphics/synteny.py", line 580, in main
    glyphstyle=opts.glyphstyle,
  File "/usr/local/lib/python3.6/dist-packages/jcvi/graphics/synteny.py", line 370, in __init__
    ext = bf.get_extent(i, order)
  File "/usr/local/lib/python3.6/dist-packages/jcvi/compara/synteny.py", line 179, in get_extent
    si, start = min(ocol)
ValueError: min() arg is an empty sequence

**Comment by haiyun-fan** [comment]
Have you solved it? I have the same problem.
File "/home/user/miniconda3/envs/jcvi/lib/python3.6/site-packages/jcvi/compara/synteny.py", line 184, in get_extent
si, start = min(ocol)
ValueError: min() arg is an empty sequence
