### ISSUE TITLE
Microsynteny with multiple species

### ISSUE THREAD

**Issue by siva5** [tanghaibao/jcvi#299]
Hi Haibao,

I am trying to look at microsynteny (at the gene level) between ~20 different species at a specific locus. I have the corresponding .bed and .cds files for all the species for the particular locus. However, I would like know if there is any way to compare all the species at the same time using `jcvi.compara.catalog ortholog` to get all the pairwise comparisons between the species?

**Comment by tanghaibao** [comment]
@siva5 

This is not currently supported. Think about how your final figure should look like, and then try a series of pairwise comparisons, most often between neighboring tracks in your final figure.
