### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by wsweishang** [tanghaibao/jcvi#300]
Hi there,
I'm trying to install the jcvi package. So I did this: 'pip install jcvi'.
And the computer returned this message: 

DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. pip 21.0 will drop support for Python 2.7 in January 2021. More details about Python 2 support in pip can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support pip 21.0 will remove support for this functionality.
Processing /home/hanshuang/.cache/pip/wheels/b8/c3/7b/2069ff98e2818736f5e80088fc8998a796c472dc8d22d0d2d7/jcvi-1.0.9-cp27-cp27mu-linux_x86_64.whl
Requirement already satisfied: graphviz in /home/hanshuang/.local/lib/python2.7/site-packages (from jcvi) (0.14.1)
Requirement already satisfied: deap in /home/hanshuang/.local/lib/python2.7/site-packages (from jcvi) (1.3.1)
Requirement already satisfied: scipy in /home/hanshuang/.local/lib/python2.7/site-packages (from jcvi) (1.2.3)
Requirement already satisfied: seaborn in /home/hanshuang/.local/lib/python2.7/site-packages (from jcvi) (0.9.1)
Requirement already satisfied: networkx in /home/hanshuang/.local/lib/python2.7/site-packages (from jcvi) (2.2)
Requirement already satisfied: cython in /home/hanshuang/.local/lib/python2.7/site-packages (from jcvi) (0.29.21)
Requirement already satisfied: gffutils in /home/hanshuang/.local/lib/python2.7/site-packages (from jcvi) (0.10.1)
Requirement already satisfied: PyPDF2 in /home/hanshuang/.local/lib/python2.7/site-packages (from jcvi) (1.26.0)
Requirement already satisfied: goatools in /home/hanshuang/.local/lib/python2.7/site-packages (from jcvi) (1.0.6)
Requirement already satisfied: pytest-benchmark in /home/hanshuang/.local/lib/python2.7/site-packages (from jcvi) (3.2.3)
Requirement already satisfied: biopython in /home/hanshuang/.local/lib/python2.7/site-packages (from jcvi) (1.70)
Requirement already satisfied: numpy in /home/hanshuang/miniconda3/lib/python2.7/site-packages (from jcvi) (1.16.5)
Requirement already satisfied: jinja2 in /home/hanshuang/.local/lib/python2.7/site-packages (from jcvi) (2.11.2)
Requirement already satisfied: ete3 in /home/hanshuang/.local/lib/python2.7/site-packages (from jcvi) (3.1.2)
Requirement already satisfied: coveralls in /home/hanshuang/.local/lib/python2.7/site-packages (from jcvi) (1.11.1)
Requirement already satisfied: PyYAML in /home/hanshuang/.local/lib/python2.7/site-packages (from jcvi) (5.3.1)
Requirement already satisfied: boto3 in /home/hanshuang/.local/lib/python2.7/site-packages (from jcvi) (1.15.3)
Requirement already satisfied: pytest in /home/hanshuang/.local/lib/python2.7/site-packages (from jcvi) (4.6.11)
Requirement already satisfied: matplotlib in /home/hanshuang/.local/lib/python2.7/site-packages (from jcvi) (2.2.5)
Requirement already satisfied: pytest-cov in /home/hanshuang/.local/lib/python2.7/site-packages (from jcvi) (2.10.1)
Requirement already satisfied: pandas>=0.17.1 in /home/hanshuang/.local/lib/python2.7/site-packages (from seaborn->jcvi) (0.24.2)
Requirement already satisfied: decorator>=4.3.0 in /home/hanshuang/.local/lib/python2.7/site-packages (from networkx->jcvi) (4.4.2)
Requirement already satisfied: simplejson in /home/hanshuang/.local/lib/python2.7/site-packages (from gffutils->jcvi) (3.17.2)
Requirement already satisfied: pyfaidx>=0.5.5.2 in /home/hanshuang/.local/lib/python2.7/site-packages (from gffutils->jcvi) (0.5.9.1)
Requirement already satisfied: six>=1.12.0 in /home/hanshuang/miniconda3/lib/python2.7/site-packages (from gffutils->jcvi) (1.12.0)
Requirement already satisfied: argcomplete>=1.9.4 in /home/hanshuang/.local/lib/python2.7/site-packages (from gffutils->jcvi) (1.12.0)
Requirement already satisfied: argh>=0.26.2 in /home/hanshuang/.local/lib/python2.7/site-packages (from gffutils->jcvi) (0.26.2)
Requirement already satisfied: xlrd in /home/hanshuang/.local/lib/python2.7/site-packages (from goatools->jcvi) (1.2.0)
Requirement already satisfied: nose in /home/hanshuang/.local/lib/python2.7/site-packages (from goatools->jcvi) (1.3.7)
Requirement already satisfied: statsmodels in /home/hanshuang/.local/lib/python2.7/site-packages (from goatools->jcvi) (0.11.0)
Requirement already satisfied: docopt in /home/hanshuang/.local/lib/python2.7/site-packages (from goatools->jcvi) (0.6.2)
Requirement already satisfied: requests in /home/hanshuang/miniconda3/lib/python2.7/site-packages (from goatools->jcvi) (2.22.0)
Requirement already satisfied: xlsxwriter in /home/hanshuang/.local/lib/python2.7/site-packages (from goatools->jcvi) (1.3.5)
Requirement already satisfied: pydot in /home/hanshuang/.local/lib/python2.7/site-packages (from goatools->jcvi) (1.4.1)
Requirement already satisfied: wget in /home/hanshuang/.local/lib/python2.7/site-packages (from goatools->jcvi) (3.2)
Requirement already satisfied: py-cpuinfo in /home/hanshuang/.local/lib/python2.7/site-packages (from pytest-benchmark->jcvi) (7.0.0)
Requirement already satisfied: statistics; python_version < "3.4" in /home/hanshuang/.local/lib/python2.7/site-packages (from pytest-benchmark->jcvi) (1.0.3.5)
Requirement already satisfied: pathlib2; python_version < "3.4" in /home/hanshuang/.local/lib/python2.7/site-packages (from pytest-benchmark->jcvi) (2.3.5)
Requirement already satisfied: MarkupSafe>=0.23 in /home/hanshuang/.local/lib/python2.7/site-packages (from jinja2->jcvi) (1.1.1)
Requirement already satisfied: urllib3[secure]; python_version < "3" in /home/hanshuang/miniconda3/lib/python2.7/site-packages (from coveralls->jcvi) (1.24.2)
Requirement already satisfied: coverage<6.0,>=3.6 in /home/hanshuang/.local/lib/python2.7/site-packages (from coveralls->jcvi) (5.3)
Requirement already satisfied: botocore<1.19.0,>=1.18.3 in /home/hanshuang/.local/lib/python2.7/site-packages (from boto3->jcvi) (1.18.3)
Requirement already satisfied: s3transfer<0.4.0,>=0.3.0 in /home/hanshuang/.local/lib/python2.7/site-packages (from boto3->jcvi) (0.3.3)
Requirement already satisfied: jmespath<1.0.0,>=0.7.1 in /home/hanshuang/.local/lib/python2.7/site-packages (from boto3->jcvi) (0.10.0)
Requirement already satisfied: py>=1.5.0 in /home/hanshuang/.local/lib/python2.7/site-packages (from pytest->jcvi) (1.9.0)
Requirement already satisfied: atomicwrites>=1.0 in /home/hanshuang/.local/lib/python2.7/site-packages (from pytest->jcvi) (1.4.0)
Requirement already satisfied: pluggy<1.0,>=0.12 in /home/hanshuang/.local/lib/python2.7/site-packages (from pytest->jcvi) (0.13.1)
Requirement already satisfied: importlib-metadata>=0.12; python_version < "3.8" in /home/hanshuang/.local/lib/python2.7/site-packages (from pytest->jcvi) (2.0.0)
Requirement already satisfied: attrs>=17.4.0 in /home/hanshuang/.local/lib/python2.7/site-packages (from pytest->jcvi) (20.2.0)
Requirement already satisfied: funcsigs>=1.0; python_version < "3.0" in /home/hanshuang/.local/lib/python2.7/site-packages (from pytest->jcvi) (1.0.2)
Requirement already satisfied: wcwidth in /home/hanshuang/.local/lib/python2.7/site-packages (from pytest->jcvi) (0.2.5)
Requirement already satisfied: packaging in /home/hanshuang/.local/lib/python2.7/site-packages (from pytest->jcvi) (20.4)
Requirement already satisfied: more-itertools<6.0.0,>=4.0.0; python_version <= "2.7" in /home/hanshuang/.local/lib/python2.7/site-packages (from pytest->jcvi) (5.0.0)
Requirement already satisfied: cycler>=0.10 in /home/hanshuang/.local/lib/python2.7/site-packages (from matplotlib->jcvi) (0.10.0)
Requirement already satisfied: kiwisolver>=1.0.1 in /home/hanshuang/.local/lib/python2.7/site-packages (from matplotlib->jcvi) (1.1.0)
Requirement already satisfied: subprocess32 in /home/hanshuang/.local/lib/python2.7/site-packages (from matplotlib->jcvi) (3.5.4)
Requirement already satisfied: backports.functools-lru-cache in /home/hanshuang/.local/lib/python2.7/site-packages (from matplotlib->jcvi) (1.6.1)
Requirement already satisfied: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.1 in /home/hanshuang/.local/lib/python2.7/site-packages (from matplotlib->jcvi) (2.4.7)
Requirement already satisfied: pytz in /home/hanshuang/.local/lib/python2.7/site-packages (from matplotlib->jcvi) (2020.1)
Requirement already satisfied: python-dateutil>=2.1 in /home/hanshuang/.local/lib/python2.7/site-packages (from matplotlib->jcvi) (2.8.1)
Requirement already satisfied: setuptools>=0.7 in /home/hanshuang/miniconda3/lib/python2.7/site-packages (from pyfaidx>=0.5.5.2->gffutils->jcvi) (41.4.0)
Requirement already satisfied: patsy>=0.5 in /home/hanshuang/.local/lib/python2.7/site-packages (from statsmodels->goatools->jcvi) (0.5.1)
Requirement already satisfied: idna<2.9,>=2.5 in /home/hanshuang/miniconda3/lib/python2.7/site-packages (from requests->goatools->jcvi) (2.8)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in /home/hanshuang/miniconda3/lib/python2.7/site-packages (from requests->goatools->jcvi) (3.0.4)
Requirement already satisfied: certifi>=2017.4.17 in /home/hanshuang/miniconda3/lib/python2.7/site-packages (from requests->goatools->jcvi) (2019.9.11)
Requirement already satisfied: docutils>=0.3 in /home/hanshuang/.local/lib/python2.7/site-packages (from statistics; python_version < "3.4"->pytest-benchmark->jcvi) (0.16)
Requirement already satisfied: scandir; python_version < "3.5" in /home/hanshuang/.local/lib/python2.7/site-packages (from pathlib2; python_version < "3.4"->pytest-benchmark->jcvi) (1.10.0)
Requirement already satisfied: pyOpenSSL>=0.14 in /home/hanshuang/miniconda3/lib/python2.7/site-packages (from urllib3[secure]; python_version < "3"->coveralls->jcvi) (19.0.0)
Requirement already satisfied: cryptography>=1.3.4 in /home/hanshuang/miniconda3/lib/python2.7/site-packages (from urllib3[secure]; python_version < "3"->coveralls->jcvi) (2.8)
Requirement already satisfied: ipaddress in /home/hanshuang/miniconda3/lib/python2.7/site-packages (from urllib3[secure]; python_version < "3"->coveralls->jcvi) (1.0.23)
Requirement already satisfied: futures<4.0.0,>=2.2.0; python_version == "2.7" in /home/hanshuang/miniconda3/lib/python2.7/site-packages (from s3transfer<0.4.0,>=0.3.0->boto3->jcvi) (3.3.0)
Requirement already satisfied: contextlib2; python_version < "3" in /home/hanshuang/.local/lib/python2.7/site-packages (from importlib-metadata>=0.12; python_version < "3.8"->pytest->jcvi) (0.6.0.post1)
Requirement already satisfied: zipp>=0.5 in /home/hanshuang/.local/lib/python2.7/site-packages (from importlib-metadata>=0.12; python_version < "3.8"->pytest->jcvi) (1.2.0)
Requirement already satisfied: configparser>=3.5; python_version < "3" in /home/hanshuang/.local/lib/python2.7/site-packages (from importlib-metadata>=0.12; python_version < "3.8"->pytest->jcvi) (4.0.2)
Requirement already satisfied: cffi!=1.11.3,>=1.8 in /home/hanshuang/miniconda3/lib/python2.7/site-packages (from cryptography>=1.3.4->urllib3[secure]; python_version < "3"->coveralls->jcvi) (1.13.0)
Requirement already satisfied: enum34; python_version < "3" in /home/hanshuang/miniconda3/lib/python2.7/site-packages (from cryptography>=1.3.4->urllib3[secure]; python_version < "3"->coveralls->jcvi) (1.1.6)
Requirement already satisfied: pycparser in /home/hanshuang/miniconda3/lib/python2.7/site-packages (from cffi!=1.11.3,>=1.8->cryptography>=1.3.4->urllib3[secure]; python_version < "3"->coveralls->jcvi) (2.19)
Installing collected packages: jcvi
Successfully installed jcvi-1.0.9

Seems like it has already installed jcvi on my computer.
But when I did this: 

python -m jcvi.assembly.allmaps merge Takifugu1.csv Takifugu2.csv -o Takifugu_combined.bed

The computer would return error message like this:

Traceback (most recent call last):
  File "/home/hanshuang/miniconda3/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/home/hanshuang/miniconda3/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/hanshuang/miniconda3/lib/python2.7/site-packages/jcvi/assembly/allmaps.py", line 35, in <module>
    from jcvi.graphics.landscape import draw_gauge
  File "/home/hanshuang/miniconda3/lib/python2.7/site-packages/jcvi/graphics/landscape.py", line 22, in <module>
    from jcvi.graphics.base import (
  File "/home/hanshuang/miniconda3/lib/python2.7/site-packages/jcvi/graphics/base.py", line 394, in <module>
    setup_theme()
  File "/home/hanshuang/miniconda3/lib/python2.7/site-packages/jcvi/graphics/base.py", line 368, in setup_theme
    import seaborn as sns
  File "/home/hanshuang/.local/lib/python2.7/site-packages/seaborn/__init__.py", line 9, in <module>
    from .relational import *
  File "/home/hanshuang/.local/lib/python2.7/site-packages/seaborn/relational.py", line 20, in <module>
    from .axisgrid import FacetGrid, _facet_docs
  File "/home/hanshuang/.local/lib/python2.7/site-packages/seaborn/axisgrid.py", line 16, in <module>
    from .distributions import distplot, kdeplot,  _freedman_diaconis_bins
  File "/home/hanshuang/.local/lib/python2.7/site-packages/seaborn/distributions.py", line 16, in <module>
    import statsmodels.nonparametric.api as smnp
  File "/home/hanshuang/.local/lib/python2.7/site-packages/statsmodels/nonparametric/__init__.py", line 7, in <module>
    from statsmodels.tools._testing import PytestTester
  File "/home/hanshuang/.local/lib/python2.7/site-packages/statsmodels/tools/__init__.py", line 1, in <module>
    from .tools import add_constant, categorical
  File "/home/hanshuang/.local/lib/python2.7/site-packages/statsmodels/tools/tools.py", line 8, in <module>
    from statsmodels.compat.python import lzip, lmap
  File "/home/hanshuang/.local/lib/python2.7/site-packages/statsmodels/compat/__init__.py", line 1, in <module>
    from statsmodels.tools._testing import PytestTester
  File "/home/hanshuang/.local/lib/python2.7/site-packages/statsmodels/tools/_testing.py", line 11, in <module>
    from statsmodels.compat.pandas import assert_equal
  File "/home/hanshuang/.local/lib/python2.7/site-packages/statsmodels/compat/pandas.py", line 4, in <module>
    import numpy as np
  File "/home/hanshuang/.local/lib/python2.7/site-packages/statsmodels/compat/numpy.py", line 46, in <module>
    NP_LT_114 = LooseVersion(np.__version__) < LooseVersion('1.14')
AttributeError: 'module' object has no attribute '__version__'

Could any help to fix it?
Thanks a lot

**Comment by HaoZhour** [comment]
@wsweishang Hi，you can try to change the version of numpy <1.14. (pip install numpy==1.13).

**Comment by tanghaibao** [comment]
@wsweishang 

Also, try installing jcvi with python 3. We are migrating our code to Python 3 and will drop support for Python 2 soon.
