### ISSUE TITLE
dockerfile updates

### ISSUE THREAD

**Issue by goertzenlr** [tanghaibao/jcvi#304]
great utilities, thank you. containers an ideal way to run this package and avoid most errors people are coming up with.

to avoid hang on libxml2 install (wanting tzdata), put   ARG DEBIAN_FRONTEND=noninteractive   after FROM line.

not sure how you want to handle some other py3 issues.  eg. change each pip statement to pip3, also explicitly call python3 vs. "update alternatives" in the image build. 

thanks again

**Comment by tanghaibao** [comment]
@goertzenlr 

Thanks for the update. Would you consider making a PR for this?

Haibao

**Comment by goertzenlr** [comment]
will do
