### ISSUE TITLE
fetch.py fails on initial phytozome api download request (owing to no cookie file?)

### ISSUE THREAD

**Issue by goertzenlr** [tanghaibao/jcvi#307]
From newly built docker container of jcvi suite, fetch.py (called directly) or "jcvi.apps.fetch phytozome" aborts due to 'anonDownload' state -- no cookiefile available and script does not make one, even when correct jgi login credentials supplied.

However, regular api request from same container works fine:

curl 'https://signon.jgi.doe.gov/signon/create' --data-urlencode 'login=goertzxxxxxxx' --data-urlencode 'password=XXXXXXXX' -c cookies > /dev/null

curl 'https://genome.jgi.doe.gov/portal/ext-api/downloads/get-directory?organism=PhytozomeV12' -b cookies > files12.xml

Any jcvi fetch command subsequent to above signon (with cookiefile now in wd), download is successful and new "phytozome.cookies" is created.  

-------------------------------
\# python3 -m jcvi.apps.fetch phytozome
Phytozome Login: goertzxxxx
Phytozome Password: 
Cannot open cookies file '.phytozome_cookies': No such file or directory
--2020-10-22 19:04:16--  http://genome.jgi.doe.gov/ext-api/downloads/get-directory?organism=PhytozomeV12
Resolving genome.jgi.doe.gov (genome.jgi.doe.gov)... 128.55.209.36
Connecting to genome.jgi.doe.gov (genome.jgi.doe.gov)|128.55.209.36|:80... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://genome.jgi.doe.gov/ext-api/downloads/get-directory?organism=PhytozomeV12 [following]
--2020-10-22 19:04:17--  https://genome.jgi.doe.gov/ext-api/downloads/get-directory?organism=PhytozomeV12
Connecting to genome.jgi.doe.gov (genome.jgi.doe.gov)|128.55.209.36|:443... connected.
HTTP request sent, awaiting response... 307 Temporary Redirect
Location: https://genome.jgi.doe.gov/portal/ext-api/downloads/get-directory?organism=PhytozomeV12 [following]
--2020-10-22 19:04:18--  https://genome.jgi.doe.gov/portal/ext-api/downloads/get-directory?organism=PhytozomeV12
Reusing existing connection to genome.jgi.doe.gov:443.
HTTP request sent, awaiting response... 302 Found
Location: https://genome.jgi.doe.gov/portal/pages/accessDenied.jsf?state='anonDownload' [following]
--2020-10-22 19:04:19--  https://genome.jgi.doe.gov/portal/pages/accessDenied.jsf?state='anonDownload'
Reusing existing connection to genome.jgi.doe.gov:443.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [text/html]
Saving to: '.phytozome_directory_V12.xml'

.phytozome_directory_V12.xml             [ <=>                                                                 ]   9.46K  52.7KB/s    in 0.2s    

2020-10-22 19:04:19 (52.7 KB/s) - '.phytozome_directory_V12.xml' saved [9690]

19:04:19 [fetch] Error downloading directory listing ... cleaning up
19:04:19 [base] rm -rf .phytozome_directory_V12.xml

----------------------------------

with cookiefile ("cookie") in dir,  fetch.py works correctly, still makes password request, but then writes its own cookiefile

\# python3 usr/local/lib/python3.8/dist-packages/jcvi/apps/fetch.py phytozome
Phytozome Login: goertzxxx
Phytozome Password: 
URL transformed to HTTPS due to an HSTS policy
--2020-10-22 19:31:23--  https://genome.jgi.doe.gov/ext-api/downloads/get-directory?organism=PhytozomeV12
Resolving genome.jgi.doe.gov (genome.jgi.doe.gov)... 128.55.209.36
Connecting to genome.jgi.doe.gov (genome.jgi.doe.gov)|128.55.209.36|:443... connected.
HTTP request sent, awaiting response... 307 Temporary Redirect
Location: https://genome.jgi.doe.gov/portal/ext-api/downloads/get-directory?organism=PhytozomeV12 [following]
--2020-10-22 19:31:23--  https://genome.jgi.doe.gov/portal/ext-api/downloads/get-directory?organism=PhytozomeV12
Reusing existing connection to genome.jgi.doe.gov:443.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [application/xml]
Saving to: '.phytozome_directory_V12.xml'

.phytozome_directory_V12.xml             [       <=>                                                           ] 620.59K   420KB/s    in 1.5s    

2020-10-22 19:31:27 (420 KB/s) - '.phytozome_directory_V12.xml' saved [635483]

Usage: 
    fetch.py phytozome species

    Retrieve genomes and annotations from phytozome using Globus API. Available
    species listed below. Use comma to give a list of species to download. For
    example:

    $ fetch.py phytozome Athaliana,Vvinifera,Osativa,Sbicolor,Slycopersicum

    The downloader will prompt you to enter Phytozome user name and password
    during downloading. Please register for a login at:
    https://phytozome.jgi.doe.gov/pz/portal.html.
    
                 ZmaysPH207                      Zmays
                    Zmarina                  Vvinifera
                   Vcarteri                  Tpratense
                     Tcacao                   Sviridis 
...

**Comment by tanghaibao** [comment]
@goertzenlr 

Thanks for the detailed report. Does it only fail for you running docker? Did it work for you before? It still works on my macOS here so I'll see if I can reproduce this error somehow.

As you probably have observed, after entering username and password, the script makes a `.phytozome_cookies` file in the current working directory (with a similar curl command that you used), and then uses the cookies in subsequent download session.

https://github.com/tanghaibao/jcvi/blob/3196859cce20be19cafa16e06b51f954a5503027/jcvi/apps/fetch.py#L182-L195

For this step, I saw this failure message in your first command:
```
Cannot open cookies file '.phytozome_cookies': No such file or directory
```
which suggests to me that somehow the script failed to write this file for some reason. Attempting to use this nonexistent cookies file then leads to the "accessDenied" page.

Not sure why having your "cookies" file in the directory worked. I am guessing that this is the default file that `wget` loads?

Haibao

**Comment by goertzenlr** [comment]
@tanghaibao 

good question,

made a new conda env on mac os:

conda create --name jcvi_sandbox2 python=3.7 matplotlib numpy biopython
pip install jcvi
python -m jcvi.apps     [works fine]

from empty dir:

(jcvi_sandbox2) mbp:sandbox goertlr$ python -m jcvi.apps.fetch phytozome
Phytozome Login: goertzxxxx
Phytozome Password: 
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   264  100   264    0     0    610      0 --:--:-- --:--:-- --:--:--   609
10:56:21 [fetch] Error downloading directory listing ... cleaning up
10:56:21 [base] rm -rf .phytozome_directory_V12.xml .phytozome_cookies

[fails with same, but much less verbose error]

Performed curl signon + get-directory request [success]

re-submitted jcvi.fetch command [fails, same error as above]

--- so oddly, in this env, initial request fails, and can't be fixed by curl signon.   I also wondered why the generic
cookiefile "cookies" would do anything.  Tried creating empty "cookies" placeholder, empty ".phytozome_cookies", mv'ed valid cookies file to .phytozome_cookies, no success.   when blank .phytozome_cookies is present, fetch.pl did not prompt for user/password.

--- tried simple pip install of jcvi in plain ubuntu docker container - also got less verbose message on fail as above.  diff in your dev version (current jcvi_dockerfile installs dev I believe). haven't tried curl fix

note: on mac os, python2 conda env without those 3 packages, "pip install jcvi" fails with 20 pages of error output.

**Comment by tanghaibao** [comment]
@goertzenlr 

Interesting and thanks for experimenting with it.

I tried it again on a Linux server that I have access to and it works okay. I noticed that if you entered the password wrong, the cookies won't be valid and then it fails with a very similar debug message as you showed above.

Worth confirming that the login works by going to the Phytozome website to confirm you can do login there. For me, I have to use my full gmail address as the username, otherwise it fails in the same way as above. Not sure if you had checked your login.

Either way, we'll need to show a message like "Authentication failure" when cookies fail to generate instead of these cryptic  %&%*^* failure messages.

Haibao

**Comment by goertzenlr** [comment]
@tanghaibao 

interesting -- you are trying it from a "clean" directory with no trace of your old cookiefiles?  any possibility of py2 vs 3 handling of url string? 

password good, I use phytozome fairly often, and just double checked it.  note also that these curl commands have the pswd in them and they execute perfectly from inside both the container and mac os cli.

will think of another way to test this.

Thanks,

Les

**Comment by goertzenlr** [comment]
could be special characters -- is fetch.py doing url encoding?

**Comment by tanghaibao** [comment]
@goertzenlr 

You are absolutely right about missing `curl` command and it was the issue at least for the docker image. So I added the line to install curl (and a few other changes to use Python 3) and rebuilt the image.

So now you can test it like so:

```
docker run -ti -v `pwd`:`pwd` -w `pwd` tanghaibao/jcvi python -m jcvi.apps.fetch phytozome
```

After pulling the image, this command asks you for the login, which if you enter correctly will get you the resources you want.

Thank you for your investigation here. Please let me know if the problem still exists.

Haibao

**Comment by tanghaibao** [comment]
> @tanghaibao
> 
> could be special characters -- is fetch.py doing url encoding?
> 
> Update: changed password to pure alphanumeric, signon issue persists

The username and password are passed to the `curl` command as is and not escaped (which is probably an issue for those who use special chars). Ideally, we should consider using the python requests API to handle those cases.

**Comment by tanghaibao** [comment]
> @tanghaibao
> 
> good question,
> 
> made a new conda env on mac os:
> 
> conda create --name jcvi_sandbox2 python=3.7 matplotlib numpy biopython
> pip install jcvi
> python -m jcvi.apps [works fine]
> 
> from empty dir:
> 
> (jcvi_sandbox2) mbp:sandbox goertlr$ python -m jcvi.apps.fetch phytozome
> Phytozome Login: goertzxxxx
> Phytozome Password:
> % Total % Received % Xferd Average Speed Time Time Time Current
> Dload Upload Total Spent Left Speed
> 100 264 100 264 0 0 610 0 --:--:-- --:--:-- --:--:-- 609
> 10:56:21 [fetch] Error downloading directory listing ... cleaning up
> 10:56:21 [base] rm -rf .phytozome_directory_V12.xml .phytozome_cookies
> 
> [fails with same, but much less verbose error]
> 
> Performed curl signon + get-directory request [success]
> 
> re-submitted jcvi.fetch command [fails, same error as above]
> 
> --- so oddly, in this env, initial request fails, and can't be fixed by curl signon. I also wondered why the generic cookiefile "cookies" would do anything. Tried creating empty "cookies" placeholder, empty ".phytozome_cookies", mv'ed valid cookies file to .phytozome_cookies, no success. when blank .phytozome_cookies is present, fetch.pl did not prompt for user/password.
> 
> --- tried simple pip install of jcvi in plain ubuntu docker container - also got less verbose message on fail as above. diff in your dev version? (current jcvi_dockerfile installs dev I believe). haven't tried curl fix
> 
> note: on mac os, python2 conda env without those 3 packages, "pip install jcvi" fails with 20 pages of error output.

I have a feeling that there may be other complex issues here. However, try the latest patch and see if it helps, make sure you use:

```
pip install git+git://github.com/tanghaibao/jcvi.git
```

to get the latest version.

**Comment by goertzenlr** [comment]
@tanghaibao 

jcvi.apps.fetch from new jcvi.dockerfile build works perfectly -- thanks for those updates.

will try latest version in mac conda env again.

am still curious to know what produces all the handshake output without curl installed

Les

**Comment by tanghaibao** [comment]
@goertzenlr 

It was trying to retrieve the species list, even when the cookies fetch failed. And of course, you can't get anything without valid cookies so was just a series of download attempts and failures.

Now that you make me think that we need to abort when obviously can't proceed with the rest of the fetch. I'll fix this when I get to it. Also, feel free to add your patches in the future - and thank you for your PR earlier.

Haibao

**Comment by goertzenlr** [comment]
@tanghaibao 

looking further into this issue in a conda env on mac os ... py3.7 and installed via the pip command you provided.

jcvi.apps.fetch phytozome performs curl signon correctly, writes .phytozome_cookies, then fails on download of directory listing.

tracking progress of get_best_downloader [jcvi.utils.ez_setup] -- moves through each option and declares function download_file_curl as "viable" and assigns that to variable "downloader"

note formatting of curl api request string done as a concatenated string for curlcmd/cmd in signon,  but download_file_curl is a concatenated list.  may not be good format for curl. 

back to miniconda container from new dockerfile build ... fetch phytozome command uses curl for signon, but chooses download_file_wget as viable downloader function.  "cmd" variable formatted as concatenated list but no problem for wget.

add wget to mac os conda env it takes same approach (curl, then wget) for signon/directory fetch respectively, works perfectly. 

I hesitate to just add wget to conda env as solution, because there is some underlying issue with either how curl/wget handle concatenated list request string, or perhaps the download_file_curl block has curl syntax problem. I couldn't get that list formatted correctly to add verbose and stndout/err options to see detailed handshake info.

best,

Les

**Comment by tanghaibao** [comment]
@goertzenlr 

Great insight and I think you are right. If you have a patch feel free to send a PR, otherwise I'll find some time to get this bug fixed.

**Comment by goertzenlr** [comment]
@tanghaibao 

will remove the wget in docker container and force it to choose curl for that second step to see if it is really broken or platform specific

**Comment by tanghaibao** [comment]
@goertzenlr 

Thanks again for your help with this. I found that curl failed due to missing a parameter `-L` since Phytozome goes through a few redirects before giving you the listing page.

I also added an option `--downloader` to allow you to switch between downloaders.

For example, if you run it like this it will use curl (but you need to have curl on your system, of course)
```
$ python -m jcvi.apps.fetch phytozome Athaliana --downloader curl
```

If you don't specify the downloader, the script cycles through wget, curl, ... until it finds one to use.

Haibao

**Comment by goertzenlr** [comment]
@tanghaibao 
nice! -- i wondered about that redirect.  thanks for looking at this 

Les

**Comment by tanghaibao** [comment]
The credits is yours @goertzenlr you identified that it was curl downloader that was failing. I wasn't looking in the right places.
