### ISSUE TITLE
1x2.anchors file

### ISSUE THREAD

**Issue by ascendo** [tanghaibao/jcvi#31]
Dear Haibao,

Is there any simple way to generate 1x2.anchors ?

Thank you for your help.

Regards,

Won

**Comment by tanghaibao** [comment]
@ascendo it is the same command, but with ``--quota`` option. For example:

`$ python -m jcvi.compara.catalog ortholog sorghum maize --quota=1x2`

This will generate ``sorghum.maize.1x2.anchors``. As usual, you'll need ``sorghum.cds``, ``sorghum.bed``, ``maize.cds``, ``maize.bed`` before running this command.

You also need a binary file ``scip`` to be on your ``PATH``. Please download it [here](https://github.com/tanghaibao/jcvi-bin/blob/master/bin/scip) or [here](http://scip.zib.de/#download).

**Comment by ascendo** [comment]
Thank you!

**Comment by ascendo** [comment]
Can you specify the version of SCIP? 

scip-3.2.1.darwin.x86_64.gnu.opt.spx this one doesn;t work.

**Comment by tanghaibao** [comment]
SCIP version 3.0.1 [precision: 8 byte] [memory: block] [mode: optimized] [LP solver: SoPlex 1.7.1] [GitHash: 9ee94b7]

**Comment by ascendo** [comment]
It only generated *lifted.1x2 *lifted.1x2.anchors.

Is there any problem in my file or other reason?
I did self comparison and want to find paleo hexaploid event.
python -m jcvi.compara.catalog ortholog mc mc --cscore=0.5 --dist=50 --quota=1:2 

Thank you.

**Comment by tanghaibao** [comment]
@ascendo please use ``--quota=2:2`` (the same as [QUOTA-ALIGN](https://github.com/tanghaibao/quota-alignment)). The easiest way to check if your results are good is to perform a dot plot.

`python -m jcvi.graphics.dotplot mc.mc.lifted.2x2.anchors`
