### ISSUE TITLE
Can different collinear blocks present in different colors in the dotplot?

### ISSUE THREAD

**Issue by xieyichun50** [tanghaibao/jcvi#316]
Hi Haibao,
I would like to visualise the pairwise synteny of two species. The package is overall easy to use!
With the command `python -m jcvi.graphics.dotplot cc130.cc326.anchors.new.test -o test.png --format=png --dpi=300`, I can successfully generate a plot.
I then try to plot those collinear blocks in different color, with `python -m jcvi.graphics.dotplot cc130.cc326.anchors.new.test -o test.png --format=png --dpi=300 --cmap=Spectral --diverge=Spectral --colormap=colormap.txt`. My `colormap.txt` is like this,
1       a
2       b
3       c
4       d
5       e

The output showed those "a b c d e" each with a color block on the bottom-left corner, but dots on the main plot remained in black color. Is there a way to shade the dot of different collinear blocks in different colors?

Thanks in advance!

**Comment by tanghaibao** [comment]
@xieyichun50 

I just confirmed that the colormap works, but sometimes you have to look carefully. Sometimes the blocks are small and cover only a few dots, so they might be difficult to find.

![image](https://user-images.githubusercontent.com/106987/99891636-ece5f080-2c20-11eb-8596-f970bc4fb416.png)

This just uses the `colormap.txt` like yours, basically coloring the first 5 blocks. You can see that the first 5 blocks are located in the top left corner of the dot plots but they are hard to spot. Try plotting more blocks (there are usually hundreds of blocks in a dot plot) and you'll see the coloring much better.

**Comment by xieyichun50** [comment]
> @xieyichun50
> 
> I just confirmed that the colormap works, but sometimes you have to look carefully. Sometimes the blocks are small and cover only a few dots, so they might be difficult to find.
> 
> ![image](https://user-images.githubusercontent.com/106987/99891636-ece5f080-2c20-11eb-8596-f970bc4fb416.png)
> 
> This just uses the `colormap.txt` like yours, basically coloring the first 5 blocks. You can see that the first 5 blocks are located in the top left corner of the dot plots but they are hard to spot. Try plotting more blocks (there are usually hundreds of blocks in a dot plot) and you'll see the coloring much better.

Hi Haibao,
I think I have figured out how it works after adding more blocks. Thank you for your suggestion!

**Comment by septem1412** [comment]
@tanghaibao
Is it possible to use custom hex color codes in the dotplot? Many thanks!

**Comment by erya-song** [comment]
Hi, I would like to visualize 3 or more colors in the Dotplot, but the above second and third colors were too similar.
![image](https://user-images.githubusercontent.com/90766519/229059206-2c04e26c-9b7b-46d5-9de9-c7b685ecb6a8.png)
Whether a higher contrast color scheme is available, and which parameters can be achieved.
Thanks.

**Comment by tanghaibao** [comment]
@erya-song 

The palette is currently fixed in code:
https://github.com/tanghaibao/jcvi/blob/9d8b3d232dd76572b0284f87765d545080a92ed7/jcvi/graphics/dotplot.py#L67

"rbcygmk" means red, blue, cyan, yellow ... and you pointed out blue is similar to cyan.

I could find a different palette or make this customizable, but it may take me some time. If you know how to edit code, you may be able to modify yourself and get results fasta.
