### ISSUE TITLE
error: malformed marker name when running jcvi.assembly.allmaps

### ISSUE THREAD

**Issue by hungweichen0327** [tanghaibao/jcvi#320]
Dear @tanghaibao and community,

I am new using the ALLMAPS. I used the code below to do scaffold ordering:
``python -m jcvi.assembly.allmaps path 07-OUTPUT-Crystal.bed Crystal_flye_10kb_3t_haploid_polished.fasta``

However, I got the error message as attached:
[error_message.txt](https://github.com/tanghaibao/jcvi/files/5594412/error_message.txt)
I think the main error to stop running is this: ``Malformed marker name: lg0:62.084``

The .bed file is generated by python -m jcvi.assembly.geneticmap
[07-OUTPUT-Crystal_bed.txt](https://github.com/tanghaibao/jcvi/files/5594427/07-OUTPUT-Crystal_bed.txt)

Hope someone can help me to find the problem. Thank you very much!

**Comment by tanghaibao** [comment]
@hungweichen0327 

There was [one last step](https://github.com/tanghaibao/jcvi/wiki/ALLMAPS%3A-How-to-use-different-types-of-genomic-maps#combine-everything) that perhaps you missed when following the tutorial.

```console
mv 07-OUTPUT-Crystal.bed Crystal.bed
python -m jcvi.assembly.allmaps mergebed Crystal.bed -o Crystal_merged.bed
```

If you have other maps, you can include and merge them together in this one command. 

What this command does is it will prepend the map name `Crystal` in front of the marker name. So `lg0:62.084` => `Crystal-lg0:62.084` and becomes a valid name. Note that your old file also had '-' in the filename, so I renamed it to a much simple filename in the first command above.

Haibao

**Comment by hungweichen0327** [comment]
Dear @tanghaibao,

Thank you for the clear and quick reply. I followed the script you described and it successfully run. Unfortunately, Some output data can't generate well (e.g. Visualize alignments: chrlg0.pdf). I think it's better to post a new issue. Once again, thank you for the kind response and developing very useful software.
