### ISSUE TITLE
Visualize alignments (lg.pdf) can't generate after run ALLMAPS

### ISSUE THREAD

**Issue by hungweichen0327** [tanghaibao/jcvi#321]
Dear @tanghaibao and community,

First, thanks for the convenient software for scaffolding chromosome-level assembly. After I ran the step 4: ``python -m jcvi.assembly.allmaps`` and I got the result of merged.fasta, .agp, .chain and others. However, I can't get the visualize alignments (lg.pdf) corresponds to reconstructed chromosomes. 
The log file is below:
[job_ALLMAPS_Crystal_log.txt](https://github.com/tanghaibao/jcvi/files/5597690/job_ALLMAPS_Crystal_log.txt)

I quickly went through the log file and I found some errors which would be the main reason:
1. ``! LaTeX Error: File `type1ec.sty' not found.``
2. ``subprocess.CalledProcessError: Command '['latex', '-interaction=nonstopmode', '--halt-on-error', '/home/hpc/crlee/.cache/matplotlib/tex.cache/bcb470c9624113f0f80b208749ee76ab.tex']' returned non-zero exit status 1.``

Besides, I want to compare the new assembled genome to the previous published reference genome. I would like to check whether the orientation of the scaffolds across chromosomes is the same as that in reference genome if those scaffolds existed in both new assembled and reference genome. Do you have any suggestions about dealing with this issue? I am sorry if this question should not be asked here. Thank you.

**Comment by tanghaibao** [comment]
@hungweichen0327 

There is a missing LaTex package. See discussion here:
https://stackoverflow.com/questions/11354149/python-unable-to-render-tex-in-matplotlib

On your second question, you want to do a dot plot comparing your results with the reference genome. There are many tools to do this, this one is quite fast:
http://dgenies.toulouse.inra.fr

**Comment by hungweichen0327** [comment]
Dear @tanghaibao and community,
Thank you for the suggestion and clear reply. Since I install ALLMAPS and dependent packages and run it on the PBS cluster (server). it's difficult for me to install the package or software using script ``sudo apt-get install``. And this package was not in AnacondaCloud. Unfortunately, I am not familiar with other way of installation. But I am still thankful for the LaTex information and user-friendly ALLMAPS conduction.

**Comment by tanghaibao** [comment]
@hungweichen0327 

You can try to use the option `--notex` which may disable running LaTeX altogether:

```console
python -m jcvi.assembly.allmaps path --notex ...
```

**Comment by hungweichen0327** [comment]
Thank you @tanghaibao. But I still can't generate Visualize alignments (lg.pdf) across chromosome. But I probably ignore this problem. The main purpose for me is to get chromosome-level genome assembly with ALLMAPS.

The log file after I run the code: ``python -m jcvi.assembly.allmaps path --notex ...`` is below:
[job_ALLMAPS_Crystal_log_2.txt](https://github.com/tanghaibao/jcvi/files/5658092/job_ALLMAPS_Crystal_log_2.txt)
