### ISSUE TITLE
Question about JMFemale.csv

### ISSUE THREAD

**Issue by X-WJ** [tanghaibao/jcvi#323]
Hi,haibao:
Now ,i have a draft genome assemblied  using ONT data,and I also hava the genetic map of this species.How can i build  the Chr genome using my genetic data.
Especially This file 
head JMFemale.csv  
ScaffoldID,ScaffoldPosition,Linkage,GeneticPosition
scaffold_158,913334,23,1.324
scaffold_382,324260,23,2.013
scaffold_513,59818,23,2.361
scaffold_513,201118,23,3.452
scaffold_331,297877,23,8.264
scaffold_642,120661,23,8.71
scaffold_150,442102,23,9.618
scaffold_150,337745,23,9.874
scaffold_150,840618,23,10.73

but my genetic map file look like this 
head male.bed 
S3_66915283	Chr1	0
S3_66915258	Chr1	0.61
dT6838	Chr1	5.54
dT44555	Chr1	6.46
dT27134	Chr1	6.89
S3_66915278	Chr1	7.47
S1_7068544	Chr1	8.94
dT3437	Chr1	10.18
dT46011	Chr1	10.37
dT38476	Chr1	13.28
 
I want to know how to get the ScaffoldPosition?

Thanks

**Comment by tanghaibao** [comment]
@X-WJ 

You have to identify where your genetic markers are on the genome. It depends on how the original genetic markers were obtained. A popular method is to use flanking sequences of the markers and BLAST them to the genome and take the best hit.

**Comment by X-WJ** [comment]
Does The scaffold position is the location where the markers best hit in  ?

**Comment by X-WJ** [comment]
Thank you very much.
