### ISSUE TITLE
The orientation of scaffold in "?" in chr.fasta and manually adjust

### ISSUE THREAD

**Issue by hungweichen0327** [tanghaibao/jcvi#328]
Dear @tanghaibao and community,

After running the convenient and useful ALLMAPS, I got the ``chr.fasta``, ``Crystal_merged.chr.agp``, and others. I am curious about the orientation of some scaffolds labeled ``?`` in .agp file. I know the orientation of scaffold can't confirm after running ALLMAPS. I check the previous steps generated by MSTmap and I suggest the orientation of one scaffold is ``-``. I want to manually orientated the scaffold to "-" direction, but I don't know the orientation of this scaffold in chr.fasta. Is that "+" in chr.fasta?

**Comment by tanghaibao** [comment]
@hungweichen0327 

By default, "?" = "+" in `chr.fasta`.

**Comment by hungweichen0327** [comment]
Thank you!
