### ISSUE TITLE
landscape heatmap colors

### ISSUE THREAD

**Issue by ascendo** [tanghaibao/jcvi#33]
Dear Haibao,

I tried to draw landscape figure but the components heatmap colors are only generated gray.

Is there any option or do I need to add more options?

Won

python -m jcvi.graphics.landscape heatmap --heatmaps=test,test,Helitron Mcr_Scaffold_003.fas McrScaffold003 --diverge=RdYlBu --stacks=test,test,Helitron,aa

**Comment by tanghaibao** [comment]
@ascendo make this change (https://github.com/tanghaibao/jcvi/commit/68f31679b864f828ae4fd3746245381d3b0c72cd), and then replace ``--diverge=RdYlBu`` to ``--cmap=RdYlBu``

**Comment by ascendo** [comment]
Works fine.

Thank you.
