### ISSUE TITLE
Manually change gap length in agp file and update the .fasta

### ISSUE THREAD

**Issue by hungweichen0327** [tanghaibao/jcvi#332]
Dear @tanghaibao,

Thanks for the useful and convenient tools. Currently, I use ``python -m jcvi.formats.agp build`` to generate scaffolding genome fasta file using modifying the agp file which I manually re-orientate one scaffold. The code is below:
``
python -m jcvi.formats.agp build CQ3649_merged_modified_1_line_contig.fasta.agp CQ3649_merged_modified_1_line_contig.fasta test_n100.fasta
``

Since I want to manually change the gap length in each scaffold (ex: 100Ns to 50Ns), can I use modified agp file to build new scaffold.fasta file?

**Comment by tanghaibao** [comment]
@hungweichen0327 

Yes, that is the right command to do it.

**Comment by hungweichen0327** [comment]
Thank you!
