### ISSUE TITLE
visualization Error in run jcvi.graphics.karyotype 

### ISSUE THREAD

**Issue by chaimol** [tanghaibao/jcvi#335]
i am follow the example run `python -m jcvi.graphics.karyotype seqids layout` also can success output the `karyotype.pdf`.
but the `karyotype.pdf` do not show all the Chromosomes of chr17.
my seqids and layout file like this:
`cat seqids`
```
Chr01,Chr02,Chr03,Chr04,Chr05,Chr06,Chr07,Chr08,Chr09,Chr10,Chr11,Chr12,Chr13,Chr14,Chr15,Chr16,Chr17 #Spo
Chr1,Chr2,Chr3,Chr4,Chr5,Chr6,Chr7,Chr8,Chr9,Chr10,Chr11,Chr12,Chr13,Chr14,Chr15,Chr16,Chr17 #Pco
```
`vim layout`
```
# y, xstart, xend, rotation, color, label, va, bed
 .6,    .1,    .75,    0,    red,    Spo,    top, Spo.bed
 .4,    .1,    .75,    0,    blue,    Pco,    top,    Pco.bed
# edges
e, 0, 1, Spo.Pco.anchors.simple
```
karyotype.pdf
![karyotype](https://user-images.githubusercontent.com/13585735/102858756-c1476780-4465-11eb-90f2-4d4359cd47d6.png)
my simple file Spo.Pco.anchors.simple.txt in server is `Spo.Pco.anchors.simple` .
[Spo.Pco.anchors.simple.txt](https://github.com/tanghaibao/jcvi/files/5728285/Spo.Pco.anchors.simple.txt)

___
Question2: if i have 3 species A，B，C.
Is there a way to show that the lines of genes shared by A/B and B/C are green.
By add `g*` to `.simple` will be useful for `is a synteny blocks`. I mean useful to genes not `synteny blocks`.From `.anchors` file i can extract the share genes of A/B and B/C. So if whether have a function can make it from `JCVI`.

**Comment by tanghaibao** [comment]
@chaimol 

1. Is it possible that `Chr17` is very small. Can you count the number of genes on `Chr17`, and compare to the rest? Perhaps with the command:

```console
cut -f1 Spo.bed | uniq -c
```

2. This isn't directly possible. However, there is a workaround. Create a fake line within `.simple` file with just your gene pair (pretend that this is a block rather than just one gene pair), and color it `g*`.

**Comment by chaimol** [comment]
@tanghaibao  
the Spo.bed chr genes count is this:
```
   2102 Chr1
   2753 Chr2
   2705 Chr3
   2203 Chr4
   3401 Chr5
   2194 Chr6
   2737 Chr7
   2293 Chr8
   2593 Chr9
   3193 Chr10
   2944 Chr11
   2397 Chr12
   2521 Chr13
   2375 Chr14
   3859 Chr15
   2580 Chr16
   2621 Chr17
```
2.I have test the methods.from the `.anchors.new` build a fake `.simple`.it can be work successful.


About Question1:
if i use 3 group spo,pco and mdo , and then run `python -m jcvi.graphics.karyotype seqids layout`,can be run successful. and the `chr17` also complete display.
[Spo_Mdo_Pco.pdf](https://github.com/tanghaibao/jcvi/files/5733052/Spo_Mdo_Pco.pdf)

**Comment by tanghaibao** [comment]
@chaimol 

I think the issue is the trailing comments in seqids file `Chr17 #Spo` and `Chr17 #Pco`. Remove the species name and it should work.

**Comment by chaimol** [comment]
@tanghaibao thank you ! Ifound it that most Error course of do not install `LaTex` or user input file format is not standardized. Python has strict requirements for user input.
