### ISSUE TITLE
How not to show the chromosomes name ?

### ISSUE THREAD

**Issue by fantasticair** [tanghaibao/jcvi#337]
Hello,
    When I run the command `python -m jcvi.graphics.karyotype seqids layout` to draw the synteny picture, but I have some chromosomes, so it's very messy，if I needn't to show the chromosomes labels, what should to change the command or add some parameters?

Best Wishes~

**Comment by tanghaibao** [comment]
@fantasticair 

Trying adding the option `--nocircle` to your command.

**Comment by fantasticair** [comment]
Thanks, it OK.
