### ISSUE TITLE
plot estimate gap size

### ISSUE THREAD

**Issue by Homap** [tanghaibao/jcvi#34]
Dear Haibao,

I was wondering whether it is possible to generate the gap size estimate plot like the one you have shown here [https://github.com/tanghaibao/jcvi/wiki/ALLMAPS:-How-to-estimate-gap-sizes] using ALLMAPS commands? 

Another question is that whether it is possible to change the ylim in the plot option?

Thank you,
Best,
Homa

**Comment by tanghaibao** [comment]
@Homap we don't yet have a generic code to do that yet. The plot you saw was done using code here:
https://github.com/tanghaibao/jcvi/blob/master/projects/allmaps.py#L205

With command like this:
``python -m jcvi.projects.allmaps estimategaps JM-4 chr1 JMMale-1``

Panel C is very specific to the yellow catfish data in the paper. You'll need to modify the code.

Yes it is possible to change the ylim (relevant code [here](https://github.com/tanghaibao/jcvi/blob/master/assembly/allmaps.py#L1674)) - is the default not working for you?

**Comment by Homap** [comment]
@tanghaibao The default is working for me but in the case of sex chromosome, you see a lot of a markers at the same genetic map position in females which is the last in the y axis and because of that, they can not be seen very clearly as they are just at the border with the y axis, it is done correctly just not very clear so I thought to increase the y axis for 10 more units so the last points can be seen more clearly. I  actually tried to change the exact line such as this:
`ax.set_ylim(0, mlgsize+10)`

but after saving the code, it does not apply the change to the graph. Is the change correct in this way?

**Comment by tanghaibao** [comment]
@Homap it should work in theory, can you try:

``ax.set_ylim(0, mlgsize * 1.2)``

To see if it changes at all. Also make sure the python script you changed is the one that's actually run - trust me, I've that problem a lot ;-)

**Comment by Homap** [comment]
@tanghaibao Great, it worked! Your guess was right :) I will be more careful from now on.
