### ISSUE TITLE
Error in gaps

### ISSUE THREAD

**Issue by Homap** [tanghaibao/jcvi#35]
Dear Haibao,

I am trying to use the split option in ALLMAPS but in computing the gaps in the assembly, I encounter the following errors. To make sure the problem is not of my data, I tried it with the test data of ALLMAPS package but I still receive the following errors:

Command: python -m jcvi.formats.fasta gaps scaffolds.fasta 

Errors:
16:13:57 [base] Load file `scaffolds.fasta`
Process Process-5:
Traceback (most recent call last):
  File "/Users/homa/anaconda2/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/Users/homa/anaconda2/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(_self._args, *_self._kwargs)
  File "/Users/homa/anaconda2/lib/python2.7/site-packages/jcvi-0.6.6-py2.7.egg/jcvi/apps/grid.py", line 157, in write
    isize = queue_in.qsize()
  File "/Users/homa/anaconda2/lib/python2.7/multiprocessing/queues.py", line 143, in qsize
    return self._maxsize - self._sem._semlock._get_value()
NotImplementedError
16:14:03 [base] sort -k1,1 -k2,2n -k4,4 scaffolds.gaps.bed -o scaffolds.gaps.bed
16:14:03 [base] Load file `scaffolds.gaps.bed`
16:14:03 [fasta] Write gap (>=100bp) locations to `scaffolds.gaps.bed`.

Thanks for your help,
Best,
Homa

**Comment by tanghaibao** [comment]
@Homap this seems to be due to Mac not supporting ``qsize``: https://sourceforge.net/p/blockit/support-requests/1/

Not sure what the fix would be at this point. I'll have to look into this. Do you happen to have a Linux server that you can play with?

**Comment by Homap** [comment]
@tanghaibao I see, I actually have a Linux server and I am now trying to see how I can solve it there. Thanks!
