### ISSUE TITLE
ALLMAPS errors running test data 

### ISSUE THREAD

**Issue by jguppy** [tanghaibao/jcvi#356]
Hi,
I've recently been trying to install and run ALLMAPs but have been running into a few errors.
I've followed the installation guide on the wiki on both a local linux machine and a uni HPC server and have come across the following syntax error when trying to use the shell script calling allmaps.py.

![image](https://user-images.githubusercontent.com/23031754/107017944-8f0e8100-67eb-11eb-8c11-13048e830825.png)

I've taken a look through the allmaps.py script itself (v1.1.7) and proceeding the code I couldn't see any obvious issues, however when looking back at the earlier version (v1.1.5) i noticed that line 7 "from __future__ import print_function" was removed.
Replacing this line in the allmaps.py script allowed me to pass the syntax error.
Does this make sense for me to do in context with the syntax error?

After this a second error has now come up -> 
Traceback (most recent call last):
  File "allmaps2.py", line 21, in <module>
    from more_itertools import flatten, pairwise
ImportError: No module named more_itertools

Is this a new dependency not covered in the wiki page that I should install?

Thanks for your help here,

Jarrod Guppy

**Comment by tanghaibao** [comment]
@jguppy 

Sorry for the inconvenience. We are dropping Python 2 support.
Please move to Python 3 if possible.

Haibao

**Comment by jguppy** [comment]
Thanks @tanghaibao 
I should have thought to check that myself. Looks to have solved it.
As a FYI for others users I needed to install the following modules with pip3 in addition to those listed the wiki page instructions.
more-itertools
dataclasses
natsort
rich
brewer2mpl

Thanks again for your help

**Comment by tanghaibao** [comment]
@jguppy 

Thanks for the notes. I was hoping when you do:

```console
pip3 install -U jcvi
```

All these dependencies should be installed automatically for you.

Haibao
