### ISSUE TITLE
micro collinearity analysis of more than 4 species

### ISSUE THREAD

**Issue by Zefeng-Wu** [tanghaibao/jcvi#359]
I have got several pairwise blocks  several species, and I have tried to use the command
`python -m jcvi.formats.base join  A_B.block B_C.block C_D.block --noheader --column 1,0,1`
BUT, the merged result is not right. I want to know how to solve the problem like this, or even perform the micro collinearity between more species, please.

**Comment by tanghaibao** [comment]
@Zefeng-Wu 

For this to work you'll need a common species as the pivot column. Let's say that species is A. Then,

```
python -m jcvi.formats.base join A_B.block A_C.block A_D.block --noheader --column 0,1,3,5
```

This command assumes that you used `--iter 1` when generating the blocks file. If more than 1, you'll need to adjust the corresponding indices in `--column`.
