### ISSUE TITLE
I  have only two genome files(fasta) and no annotation files(gff/cds/bed). How can I use jcvi to do synteny analysis?

### ISSUE THREAD

**Issue by pjx1990** [tanghaibao/jcvi#361]
I  have only two genome files(fasta) and no annotation files(gff). How can I use jcvi do synteny analysis? Is there any documents? Thanks very much.

**Comment by tangerzhang** [comment]
Hi @pjx1990 
Can you access the annotation (CDS) file from a close related species? If so, you can use GMAP program to align the CDS against the two target genomes you are interesting in, and then simulate annotation (CDS and bed files) for the two genomes.

**Comment by pjx1990** [comment]
Thanks to your reply and suggestions, but that was not what my want. I just did a new plant  genome denovo (another version had been done before), and I wanted to verify that my genome was assembled corrrectly. Therefore, before annotating the genome, I prepared to compare the synteny of these two genome.  Any suggrestions for me? Looking forward to your reply.

**Comment by tanghaibao** [comment]
@pjx1990 

If you don't have gene models, the best tools are just to use the genome aligners. For example, [dgenies](https://github.com/genotoul-bioinfo/dgenies) or [LAST](http://last.cbrc.jp/doc/last-dotplot.html).

The JCVI synteny pipeline assumes gene models to start with, so you'll have to first annotate the genomes (or use a poor man's annotation strategy as @tangerzhang suggested above).

Haibao
