### ISSUE TITLE
Forcing orientations of scaffold comparisons to the genetic map?

### ISSUE THREAD

**Issue by goeckeritz** [tanghaibao/jcvi#362]
Hi there, 

First off, great tool! It's going to give us nice figures for our upcoming genome paper - thank you!!

I had an issue with visualization of one of my chromosomes though, which is making it hard to think about how the genetic map and chromosomes orientations differ in some places. Based on the output of the pipeline, it looks like my homeologous chromosomes (I am working with a polyploid) are concatenated end to end in the + direction, except for ONE of them:

>chr1 (allmaps_FINAL-1) FINAL
Pcerasus_chr1B+ Pcerasus_chr1A+
>chr2 (allmaps_FINAL-2) FINAL
Pcerasus_chr2A+ Pcerasus_chr2B+
>chr3 (allmaps_FINAL-3) FINAL
Pcerasus_chr3B+ Pcerasus_chr3A+
>chr4 (allmaps_FINAL-4) FINAL
Pcerasus_chr4B+ Pcerasus_chr4A+
>chr5 (allmaps_FINAL-5) FINAL
Pcerasus_chr5B+ Pcerasus_chr5A+
>chr6 (allmaps_FINAL-6) FINAL
Pcerasus_chr6A+ Pcerasus_chr6B+
>chr7 (allmaps_FINAL-7) FINAL
Pcerasus_chr7B+ Pcerasus_chr7A+
>chr8 (allmaps_FINAL-8) FINAL
**Pcerasus_chr8B-** Pcerasus_chr8A+

I see that chr8B has a - after the name... this means that it has been flipped prior to comparison to the genetic map, right? This is problematic because it's hard to compare/visualize the homeologs collinearity together with the genetic map. I've attached the resulting figure. Is there a way I can force all chromosomes to be compared in their + directions? 

Thanks for the help, 
Charity 
[chr8_OG.pdf](https://github.com/tanghaibao/jcvi/files/6206149/chr8_OG.pdf)

**Comment by tanghaibao** [comment]
@goeckeritz 

This can be a bit manual and I don't have a machine to test it. But this might work:

- Identify a file called `prefix.chr.agp`, find the line that says `Pcerasus_chr8B`, instead of the "-", change it to "+"

- Run `build` to generate new AGP, assembly, and CHAIN file for liftover
```
python -m jcvi.assembly.allmaps build prefix.bed scaffolds.fasta
```

- Run plotting again, if you just want chr8, then
```
python -m jcvi.assembly.allmaps plot prefix.bed chr8
```

**Comment by goeckeritz** [comment]
Hi @tanghaibao,

Your instructions worked beautifully! Thanks - I really appreciate it!

Kindly, 
Charity
