### ISSUE TITLE
synteny.py: error: no such option: --genelabelsize

### ISSUE THREAD

**Issue by Journeyant** [tanghaibao/jcvi#366]
Dear Mr. Tang,

Thanks for developing this useful package. When I plot the Microsynteny visualization, occurs an error :
synteny.py: error: no such option: --genelabelsize
![image](https://user-images.githubusercontent.com/79972658/114391683-5bc0e780-9bca-11eb-854a-0f665483f87c.png)
 
Can you tell me how to solve this problem? Thank you!
@tanghaibao 
Sincerely,

Cui

**Comment by tanghaibao** [comment]
@Journeyant 

You may have an old version of `jcvi`. 
Ensure that you upgrade to a recent version of JCVI (`pip -U jcvi`). Also use Python 3 since we have dropped support for Python 2.

**Comment by Journeyant** [comment]
> @Journeyant
> 
> You may have an old version of `jcvi`.
> Ensure that you upgrade to a recent version of JCVI (`pip -U jcvi`). Also use Python 3 since we have dropped support for Python 2.

I got it. Thank you very much!
