### ISSUE TITLE
How to get lifted.anchors by running own blast output

### ISSUE THREAD

**Issue by EvoEcoImm** [tanghaibao/jcvi#367]
Dear Haibao,

I want to use prepared blast output to visualize microsynteny. The `python -m jcvi.compara.synteny scan bm.ms.blast bm.ms.anchors` could return anchors, but no **lifted.anchors**. Could you please advice how to get **lifted.anchors** file for microsynteny plot? Thanks.

Shulin

**Comment by EvoEcoImm** [comment]
Hi Haibao,

I tried to look for a turn around for the lifed.anchors from my own blast output. But I think I cannot find one. Could you please give some advice on this. Thanks.

Shulin

**Comment by tanghaibao** [comment]
@EvoEcoImm 

```console
$ python -m jcvi.compara.synteny liftover

Usage:
    synteny.py liftover blastfile anchorfile [options]

    Typical use for this program is given a list of anchors (syntennic
    genes), choose from the blastfile the pairs that are close to the anchors.

    Anchorfile has the following format, each row defines a pair.

        geneA geneB
        geneC geneD
```

In your case, then just `python -m jcvi.compara.synteny liftover bm.ms.blast bm.ms.anchors`

**Comment by EvoEcoImm** [comment]
Hi Haibao,  thank you very much for the help. It works great.
