### ISSUE TITLE
MatplotlibDeprecationWarning and missing font metrics file:phvr7t

### ISSUE THREAD

**Issue by LHXqwq** [tanghaibao/jcvi#368]
Hello, teacher, sorry to bother you. I encountered a problem when I was running the program. It was able to run successfully before, but I deleted some things without using it for a while. Now the data before the run is found to be unsuccessful. I have checked the bed file and there is no problem. Can you help to see if I deleted something by mistake that caused the program to report an error.
![error1](https://user-images.githubusercontent.com/50397597/114978412-bfddf700-9ebb-11eb-93cf-7310985f77f4.png)
![error2](https://user-images.githubusercontent.com/50397597/114978418-c1a7ba80-9ebb-11eb-9384-faa505f8749f.png)

**Comment by tanghaibao** [comment]
@LHXqwq 

Have you tried upgrading `jcvi` to the latest version `pip install -U jcvi`?

**Comment by LHXqwq** [comment]
Yes，I upgraded JCVI，latex and matplotlib，and run it again. It showed "FileNotFoundError:missing font metrics file: phvr7t"

**Comment by wyim-pgl** [comment]
If you install LaTex or Textlive properly, then please use this
```tlmgr install fontspec```

**Comment by LHXqwq** [comment]
After running “tlmgr install fontspec”, the program still reports an error, but it can be determined that the problem originated from latex. 
Then I run "sudo apt-get install -y texlive texlive-latex-extra texlive-latex-recommended texlive-fonts-recommended". 
So a new problem appeared “! LaTeX Error: File `type1ec.sty’ not found. ”
Then"sudo apt-get install cm-super".
After that, JCVI can run successfully, and I also got the desired result, thank you！

**Comment by wook2014** [comment]
> After running “tlmgr install fontspec”, the program still reports an error, but it can be determined that the problem originated from latex. Then I run "sudo apt-get install -y texlive texlive-latex-extra texlive-latex-recommended texlive-fonts-recommended". So a new problem appeared “! LaTeX Error: File `type1ec.sty’ not found. ” Then"sudo apt-get install cm-super". After that, JCVI can run successfully, and I also got the desired result, thank you！

In conda it can be solved by install package miktex

**Comment by winni-liu** [comment]
> > After running “tlmgr install fontspec”, the program still reports an error, but it can be determined that the problem originated from latex. Then I run "sudo apt-get install -y texlive texlive-latex-extra texlive-latex-recommended texlive-fonts-recommended". So a new problem appeared “! LaTeX Error: File `type1ec.sty’ not found. ” Then"sudo apt-get install cm-super". After that, JCVI can run successfully, and I also got the desired result, thank you！
> 
> In conda it can be solved by install package texlive-core
> 
> ```
> conda install -c conda-forge texlive-core
> ```

i use this conda command to install texlive-core, but get now error message:
RuntimeError: latex was not able to process the following string:
b'chr01'

Here is the full command invocation and its output:

latex -interaction=nonstopmode --halt-on-error --output-directory=tmp2g6ne0uk c86bca16e72db77513e4bcf36d49be7d.tex

This is pdfTeX, Version 3.141592653-2.6-1.40.25 (TeX Live 2023) (preloaded format=latex)
 restricted \write18 enabled.

kpathsea: Running mktexfmt latex.fmt
Can't locate mktexlsr.pl in @INC (@INC contains: /home/../miniconda3/envs/snakemake/share/tlpkg /home/data/../miniconda3/envs/snakemake/share/texmf-dist/scripts/texlive /etc/perl /usr/local/lib/x86_64-linux-gnu/perl/5.30.0 /usr/local/share/perl/5.30.0 /usr/lib/x86_64-linux-gnu/perl5/5.30 /usr/share/perl5 /usr/lib/x86_64-linux-gnu/perl/5.30 /usr/share/perl/5.30 /usr/local/lib/site_perl /usr/lib/x86_64-linux-gnu/perl-base) at /home/data/.../miniconda3/envs/snakemake/bin/mktexfmt line 23.
BEGIN failed--compilation aborted at /home/data/.../miniconda3/envs/snakemake/bin/mktexfmt line 25.
I can't find the format file `latex.fmt'!

**Comment by Adamtaranto** [comment]
I think the texlive-core package is missing a bunch of modules see #489 

Try using the --notex option.
