### ISSUE TITLE
about outparalogs

### ISSUE THREAD

**Issue by mo716** [tanghaibao/jcvi#370]
Hi! I hope you are doing well! I really like the MCScan pipeline made for python (https://github.com/tanghaibao/jcvi/wiki/MCscan-(Python-version)) that you have developed. I would however like to ask:

Are outparalogs automatically excluded from the orthologs identified by MSCan?

My question arises from the fact that some genes could have duplicated before an speciation event. I am working with Brassica napus; hence, my interest on knowing more about how orthologs are defined in the MCScan python pipeline. Thank you very much for any answer in advance :)

**Comment by tanghaibao** [comment]
@mo716 

This is controlled by the magic option `--cscore`. 

The [wiki](https://github.com/tanghaibao/jcvi/wiki/MCscan-(Python-version)) already has an example for grape vs. peach -- when `cscore` is close to 1 (i.e. 0.99), we find pretty much direct orthologs (split at the time of species divergence). As you relax the `cscore`, more outparalogs are allowed. The default value is `0.7` which allowed for some recent outparalogs (with scores at least 70% compared to direct orthologs). Occasionally, I relax to `0.5` to look for really ancient events.

**Comment by mo716** [comment]
HI @tanghaibao! Thank you very much for the reply. As I understand now, one can use the c-score to filter the the likelihood of orthologs being outparalogs or not. Thank you very much! That was quite helpful! :)
