### ISSUE TITLE
Circle plot of collinearity analysis in MCscan

### ISSUE THREAD

**Issue by danilotrabuco** [tanghaibao/jcvi#371]
Hi Dr. Tang,

I'm using your script to identify the synteny blocks and to draw the genome collinearity among 10 bacterial genomes. I would like to know if you have any advice or way to draw a circle plot instead of the linear way that you exemplified in the tutorial.

Thanks in advance

Best wishes

**Comment by tanghaibao** [comment]
@danilotrabuco 

We can't do circle plots yet. There is a well-established software for that - Circos plot (http://circos.ca/).

**Comment by danilotrabuco** [comment]
Thanks, Dr. Tang! I will check it!

Best,
Danilo
