### ISSUE TITLE
Microsynteny plots: rotating labels and displaying full length of contigs?

### ISSUE THREAD

**Issue by mauriciolangleib** [tanghaibao/jcvi#373]
Hi! First of all many thanks for this GREAT tool. Visualizations are just beautiful and informative, and the tool has proven to be easily adaptable to my needs so far.

I have the following question: I am currently trying to display some homology relationships between annotated features in some contigs that I've been working with. 
So far I have been able to create a satisfying microsynteny plot showing this relationships by creating some files indicating the infered homology relationships (which I've previously infered by a pipeline that isn't relevant for my question).
Nevertheless, I have found the following problems:

1. Some of this contigs are "flipped" with respect to the others. I have managed to solve how to create a clearer plot by rotating this contigs 180 degrees, but the displayed labels for this contigs are also rotated (and therefore they appear upside down). I've tried also to indicate a "-1" in the ratio of this contigs, but labels are then plotted over the contig image.
2. I would like to display the whole contigs in my microsynteny plots. So far it seems to be that only ranges with annotated features are shown in the plot (which makes sense to the general use of the tool, of course). Is there a way to plot the full length of my contig sequences? I've thought of creating "dummy" annotated features at their ends (with negligible sizes), but it may be the case that there is an easier and cleaner way to achieve this.

Hope my question is clear (and that I'm not asking a silly question or one that has already been answered). I've looked in past Issues and in the Wiki but haven't found the info.

Thanks in advance and thanks again for this great tool!
Mauricio

**Comment by tanghaibao** [comment]
@mauriciolangleib 

Thanks for using our tool. It may be possible to achieve point 2 that you desire, but is a little hackish. I assume you currently have a `.blocks` file with two columns, something like:

```
GSVIVT01012255001	Prupe.1G290900.1
GSVIVT01012253001	Prupe.1G290800.2
GSVIVT01012252001	Prupe.1G290700.1
GSVIVT01012250001	Prupe.1G290600.1
```

In this example, I have 4 pairs of syntenic genes, and column 1 is always going positive, but the 2nd column can be flipped as you see from the descending gene ids. The plots, as you noted, may not be complete since the span is from the matching genes. The trick is to include the first gene and last gene in that column.

```
first_gene_on_contig1    .
GSVIVT01012255001	Prupe.1G290900.1
GSVIVT01012253001	Prupe.1G290800.2
GSVIVT01012252001	Prupe.1G290700.1
GSVIVT01012250001	Prupe.1G290600.1
last_gene_on_contig1    .
```

If you need the second contig to be the entire extent, similarly:

first_gene_on_contig1    .
.    first_gene_on_contig2
GSVIVT01012255001	Prupe.1G290900.1
GSVIVT01012253001	Prupe.1G290800.2
GSVIVT01012252001	Prupe.1G290700.1
GSVIVT01012250001	Prupe.1G290600.1
last_gene_on_contig1    .
.    last_gene_on_contig2
```

Note that they may not have anything to match on the other contig, thereby a placeholder "." is there.

For your first point, the flipping occurs automatically by calculating the gene rank correlation, so it may be a bit tricky to "un-flip" it.

**Comment by mauriciolangleib** [comment]
@tanghaibao

Many thanks for the quick and clear response! I will try that approach, and regarding labels I think manual edition with a graphic software is OK for my case if a programmatic solution is too complex.

I would like to ask a third question before closing this Issue, if you let me.

Is there a way to plot some selected features with a more transparent colour? Or, as another option, to display some selected features with a specific colour? To be specific, I would like to plot all the annotated features in this contigs, but to distinguish between the ones presenting homology in other contig and those that don't. As there are many annotated features in each cntig the plot becomes a bit crowded, and I thought a workaround would be to relax the visual impact of some features by plotting them with a softer colour.

Many thanks again,
Mauricio

**Comment by tanghaibao** [comment]
@mauriciolangleib 

Can you be specific on what colors that you want to change? Currently, genes are green/blue depending on their orientation.
In the [wiki](https://github.com/tanghaibao/jcvi/wiki/MCscan-(Python-version)#microsynteny-visualization), we also showed an example where you can color the features based on orthogroup (with option `--glyphcolor=orthogroup`). I could add another option for you to customize the genes, but it will help if you can describe (or better to sketch) specifically what's on your mind.

**Comment by mauriciolangleib** [comment]
Dear @tanghaibao, sorry for the delay in the reply.

Actually, after modifying a bit my script, I think that the option --glyphcolor=orthogroup may be actually quite good for what I am seeking. The only detail is the following: as far as I understand, this option sets colors randomly to each orthogroup. Is there a way to specify desired, fixed colors for each orthogroup? If this isn't possible, in which part of the source code is this specified? (May be I can modify it myself to try to accomplish my goal).

Many thanks,
Mauricio

**Comment by tanghaibao** [comment]
@mauriciolangleib 

The relevant code is here:

https://github.com/tanghaibao/jcvi/blob/3afd44255f9e9de99bd6ba2c2fba6cd7a692e431/jcvi/graphics/glyph.py#L217-L245

Just let me know if anything is unclear.

Haibao

**Comment by mauriciolangleib** [comment]
Many thanks @tanghaibao for all your replies!
Unfortunately I think the task is a bit off my current coding skills, so an image post-processing seems more reasonable to me in this moment. Hope to be able to contribute to this in the future, as I think it would be a nice feature for the library

Again, many thanks for all and for creating this great tool, the images are amazing!
Going to close the issue.

Best regards,
Mauricio
