### ISSUE TITLE
How to combine Hi-C and genetic map data to scaffolding?

### ISSUE THREAD

**Issue by hungweichen0327** [tanghaibao/jcvi#374]
Dear community and Dr. @tanghaibao,

Thank you for the convenient and useful software. 
Recently I used ALLMAPS with two genetic map data to construct pseudo-chromosome level genome. There 14 scaffolds with 1Mb total length anchored but not oriented. I am curious how can I used both Hi-C map and genetic map data together to assemble the genome. I saw the issue #276 and I think it's possible to combine Hi-C and genetic map data. But I don't know how to do. Can you briefly tell me the process or the related information of which I can follow the pipeline. Thank you!

In addition, If I add the Hi-C map to scaffolding with ALLMAPS. Is there any criteria for the Hi-C map? For example, only Hi-C map data generated by ALLHiC software or some kind of format is available with ALLMAPS.

**Comment by tanghaibao** [comment]
@hungweichen0327 

so that was a comment a while ago. now there have been quite a few software to leverage HiC in genome scaffolding nowadays - ALLHiC, 3D-DNA ... to name a few. I'd suggest scaffolding based on Hi-C data alone by other Hi-C specific scaffolders and then cross-checked with the results from the genetic map only separately by ALLMAPs.

**Comment by hungweichen0327** [comment]
Dear Dr. @tanghaibao,

Thank you for the kind response and suggestions. 
I had Hi-C data to scaffold the draft genome assembly. Unfortunately, I can't obtain good assembly with ALLHiC, 3D-DNA, or SALSA. So, I think whether I can used Hi-C data to further confirm the orientation of small contigs which labeled "?" in the agp file after run ALLmaps with 2 genetic data and draft genome assembly. 
The attachment is the agp file.
[Crystal_merged.chr_agp.txt](https://github.com/tanghaibao/jcvi/files/6506138/Crystal_merged.chr_agp.txt)

These files are the 11 alignments between genetic map and physical map.
[chrlg0.pdf](https://github.com/tanghaibao/jcvi/files/6506140/chrlg0.pdf)
[chrlg1.pdf](https://github.com/tanghaibao/jcvi/files/6506141/chrlg1.pdf)
[chrlg2.pdf](https://github.com/tanghaibao/jcvi/files/6506142/chrlg2.pdf)
[chrlg3.pdf](https://github.com/tanghaibao/jcvi/files/6506143/chrlg3.pdf)
[chrlg4.pdf](https://github.com/tanghaibao/jcvi/files/6506144/chrlg4.pdf)
[chrlg5.pdf](https://github.com/tanghaibao/jcvi/files/6506145/chrlg5.pdf)
[chrlg6.pdf](https://github.com/tanghaibao/jcvi/files/6506146/chrlg6.pdf)
[chrlg7.pdf](https://github.com/tanghaibao/jcvi/files/6506148/chrlg7.pdf)
[chrlg8.pdf](https://github.com/tanghaibao/jcvi/files/6506149/chrlg8.pdf)
[chrlg9.pdf](https://github.com/tanghaibao/jcvi/files/6506150/chrlg9.pdf)
[chrlg10.pdf](https://github.com/tanghaibao/jcvi/files/6506151/chrlg10.pdf)

Do you think the result after running ALLMAPS is good enough as pseudo-chromosome level assembly? Or did I use Hi-C data to further improve the scaffolding? Currently, two possible way I think:

1. As the suggestion you mentioned, I can use the scaffold assembly after run software with Hi-C data (ex: ALLHiC, 3D-DNA). Then I use ALLMAPS to cross-checked with the scaffold assembly from the genetic map. But this way I need to spend some time to map the raw RIL data to the scaffold assembly and generate the genetic map.

2. I don't know whether a software can help me to use both Hi-C map and genetic map data to assemble the genome. Or help me to know the orientation of contigs labeled "?" in the agp file.

Since it's my first time to denovo assemble the genome, I may ask some basic or unrealistic questions. Thank you for your patience.

**Comment by tanghaibao** [comment]
@hungweichen0327 

Actually your results from genetic maps look very good -- your contigs are already big and require not a lot of scaffolding (few scaffolds each linkage group). I wouldn't worry too much about using both datasets, since there are not a whole lot of controversy to your current results (and is expected to agree well with HiC results anyways).

**Comment by hungweichen0327** [comment]
Dear Dr. @tanghaibao,

Thank you for spending time to examine these results. I would like to ask additional questions about the results:

1. According the alignment between genetic map and physical map, the middle region is relative messy than the side region the pseudo-chromosome. Is that because the middle region is maybe the centromere or repeated region?

2. Can I say aquamarine genetic map data is better than the orange genetic map data? Because the dotplot of  aquamarine genetic map looks more diagonal than orange genetic map. But maybe we can said the reason is partially due to more markers in orange genetic map? Thus, it's reliable to get relative messy result in orange genetic data. 
![chrlg7](https://user-images.githubusercontent.com/54091758/119296471-9159f580-bc8b-11eb-9ed5-454e2956a128.png)
![chrlg8](https://user-images.githubusercontent.com/54091758/119296479-9454e600-bc8b-11eb-9224-7a0d7de1dc5c.png)

3. In your opinion, you think two genetic map data can be used for ALLAMPS since there are not a whole lot of controversy to my current result. Is that right?

4. Since there are 14 scaffolds/contigs, total length about 1.1Mb, are anchored but not oriented (meaning "?" in agp file) in current result. If I eventually can't know the orientation of these scaffolds/contigs (Even though I use Hi-C data or homology-based assembly for correction). I should remove those scaffolds/contigs in the merged.chr.fasta as final genome at pseudo-chromosome level. Is that right?

**Comment by hungweichen0327** [comment]
Sorry, if the questions above are too complicate or not precise, I can modify the questions. Thank you.

**Comment by tanghaibao** [comment]
Unfortunately, this requires a little more investigation than a regular question so I'll try my best - 

> Dear Dr. @tanghaibao,
> 
> Thank you for spending time to examine these results. I would like to ask additional questions about the results:
> 
> 1. According the alignment between genetic map and physical map, the middle region is relative messy than the side region the pseudo-chromosome. Is that because the middle region is maybe the centromere or repeated region?

Yes, the messy region is usually centromeric or pericentromeric.

> 2. Can I say aquamarine genetic map data is better than the orange genetic map data? Because the dotplot of  aquamarine genetic map looks more diagonal than orange genetic map. But maybe we can said the reason is partially due to more markers in orange genetic map? Thus, it's reliable to get relative messy result in orange genetic data.

One can infer with high confidence that one genetic map is better than another, since now your sequence assembly agrees with (i.e. more collinear) one but not others. 

>    ![chrlg7](https://user-images.githubusercontent.com/54091758/119296471-9159f580-bc8b-11eb-9ed5-454e2956a128.png)
>    ![chrlg8](https://user-images.githubusercontent.com/54091758/119296479-9454e600-bc8b-11eb-9224-7a0d7de1dc5c.png)
> 3. In your opinion, you think two genetic map data can be used for ALLAMPS since there are not a whole lot of controversy to my current result. Is that right?

You are ultimately the judge for your own study but if you don't have other data to utilize at this point, I would say the current results look reasonably good except for a few chromosomes.

> 4. Since there are 14 scaffolds/contigs, total length about 1.1Mb, are anchored but not oriented (meaning "?" in agp file) in current result. If I eventually can't know the orientation of these scaffolds/contigs (Even though I use Hi-C data or homology-based assembly for correction). I should remove those scaffolds/contigs in the merged.chr.fasta as final genome at pseudo-chromosome level. Is that right?

Again, it is up to you. Some studies chose not to reject those contigs since there are not many that oriented and their placement (order) is still good, just not sure about the orientation. Feel free to remove those if this level of uncertainty bothers you.

**Comment by hungweichen0327** [comment]
Dear @tanghaibao ,

Thank you for the kind reply and patience!
