### ISSUE TITLE
Gene colour based on function

### ISSUE THREAD

**Issue by sandipmkale** [tanghaibao/jcvi#377]
Hello,
Please see attached figure, How do you colour genes based on function/domain?
Also, Is it necessary to use same reference for "Microsynteny getting fancy" ? 
<img width="1440" alt="Screenshot 2021-06-03 at 06 12 48" src="https://user-images.githubusercontent.com/28163992/120586070-25b61c00-c433-11eb-97fc-0529615079b1.png">

**Comment by tanghaibao** [comment]
@sandipmkale 

Currently, we color the genes either by orientation (+/-) or by ortho-group. However, there may be alternative ways to color these. I have to think about how to generically assign the color classes for the genes.

**Comment by sandipmkale** [comment]
Thanks Alot for reply. The above image is also generated using MCScan. Maybe, we can change the gene orientation as per the function. I will try and let you know.

with best regards

Sandip
