### ISSUE TITLE
ValueError: Invalid RGBA argument: ''

### ISSUE THREAD

**Issue by sandipmkale** [tanghaibao/jcvi#378]
Hello,

I am trying to generate microsynteny plot for 10 samples. 
$python -m jcvi.graphics.synteny block_ordered_loc All_samples.bed test_block4 --notex --shadestyle=line --glyphstyle=arrow

However, I am getting above error. The log file is attached.

Can you please help

Thanks and regards

Sandip

[log.txt](https://github.com/tanghaibao/jcvi/files/6589806/log.txt)

**Comment by tanghaibao** [comment]
@sandipmkale 

I have not seen this error before. Could you share what's in `test_block4`?

**Comment by sandipmkale** [comment]
Thanks Alot for reply. 
Test block is just layout file. 
I observed that, I get the error whenever I have more than 8 samples including reference. is there sample limit?

Thanks and regards

Sandip

**Comment by tanghaibao** [comment]
@sandipmkale 

Looking at the current code, there seems to be a limitation of 8. You are right.

https://github.com/tanghaibao/jcvi/blob/09994dd266b42105ab35f1836379f1d44c347d22/jcvi/graphics/synteny.py#L93

All this does is assign a color to the sample (name) in the figure.

You can try to remove this condition and it should still work. The catch is that with samples > 8 it is possible that some colors in different tracks may share the same color.

**Comment by yangqihang1230** [comment]
> @sandipmkale
> 
> 查看当前代码，似乎有 8 个限制。您是对的。
> 
> https://github.com/tanghaibao/jcvi/blob/09994dd266b42105ab35f1836379f1d44c347d22/jcvi/graphics/synteny.py#L93
> 
> 所有这些都是为图中的样本（名称）分配一种颜色。
> 
> 您可以尝试消除这种情况，它应该仍然有效。问题在于，样本数 > 8 时，不同轨道中的某些颜色可能共享相同的颜色。

Hello, how can I get rid of this restriction
Can you help? Thank you

**Comment by tanghaibao** [comment]
@sandipmkale @yangqihang1230 

I just removed the limitation when assigning colors to more than 8 tracks. 

Please update `jcvi` (`pip install -U jcvi`) and the issue should be fixed now. Let me know if the error still exists.

Haibao

**Comment by yangqihang1230** [comment]
Thank you for your reply.
 The updated JCVI is no longer limited and works perfectly. 
Thanks again for your help
qihang
