### ISSUE TITLE
Why those scaffolds which can not be Oriented are random anchored everywhere?

### ISSUE THREAD

**Issue by xiekunwhy** [tanghaibao/jcvi#38]
Hi,
In allmaps lifted files, many scaffolds which can not be Oriented are random anchored everywhere. I would like to known why allmaps do in this way?
Thank you.
![anchored_chr8](https://cloud.githubusercontent.com/assets/17738229/21629321/2faa2e4e-d262-11e6-9fc1-8433b4b95ef4.png)
![anchored_chr7](https://cloud.githubusercontent.com/assets/17738229/21629318/2ef895f8-d262-11e6-972c-9cd02d893f57.png)

**Comment by tanghaibao** [comment]
@xiekunwhy which version did you use? This was a bug which was an issue in an earlier version of ALLMAPS but should have been fixed since then.

**Comment by xiekunwhy** [comment]
@tanghaibao I don't known how to see which version I am using, but all things were ok when updated to the latest version. Thank you.
Kun Xie
