### ISSUE TITLE
Microsynteny isualization name of the species changes position

### ISSUE THREAD

**Issue by yangqihang1230** [tanghaibao/jcvi#385]
Hello Professor Tang, I use the microsynty isualization, the result is as follows, the name of the gene segment because of the length of the sequence will not show up neatly, I want to make these names aligned on the left, but after trying, but failed, how do I modify the parameters？
![1626091367(1)](https://user-images.githubusercontent.com/77334699/125284931-a2022000-e34c-11eb-99d5-a4ed2d5451c1.png)

**Comment by tanghaibao** [comment]
@yangqihang1230 

I just added support for labels aligned on the left (and right). Please update `jcvi` (`pip install -U jcvi`).

In the `ha` column of the layout file, use `leftalign` instead of `left`. For example:

```
# x,   y, rotation,   ha,     va,   color, ratio,            label
0.5, 0.6,        0, leftalign, center,       m,     1,       grape Chr1
0.5, 0.4,        0, leftalign, center, #fc8d62,     1, peach scaffold_1
```

**Comment by yangqihang1230** [comment]
Dear Professor Tang, thank you very much. After I updated the JCVI, the genetic names were aligned to the left.
