### ISSUE TITLE
Why I can't change the genes' color when I specify "--glyphcolor=orientation"?

### ISSUE THREAD

**Issue by xdli009** [tanghaibao/jcvi#387]
Hello,
Thanks a lot for the wonderful tools!
Why I can't change the genes' color when I specify "--glyphcolor=orientation"? When I change the values ​​of the --cmap or --diverge parameter, the color of gene is always green and gray. How do I change the color?
Thanks

**Comment by tanghaibao** [comment]
@xdli009 

When `--glyphcolor=orientation` is on, the colors are fixed at green and blue, depending on the orientation.
Unfortunately they do not respond to the changes in `--cmap` or `--diverge` (which are used to configure color maps).

What colors do you want to see them in? I can point you to where the code is.

**Comment by xdli009** [comment]
@tanghaibao 
I want to change the colors to "#0077c8" and "#a51890". Where I change the code?
Thanks
