### ISSUE TITLE
Can ALLMAPS be used to lift Scaffold annotations back down to Contigs?

### ISSUE THREAD

**Issue by aaronphillips7493** [tanghaibao/jcvi#391]
Hey,

I have done a de novo assembly to produce contigs. I then used RagTag to scaffold the contigs into Scaffolds using a reference genome as a guide. I then annotated the scaffolded assembly. My supervisor wants me to now go back to my original contigs and use these, not the scaffolds. I am wondering: can I take the annotation file for the scaffolds (a GFF3 file) and the AGP file explaining how the contigs were scaffolded to convert the Scaffolded annotation into an annotation for the contigs? Annotation took me ages to figure out, and I don't want to repeat, so if I can find a way to convert scaffold annotation to contain annotation I will be very happy!

Thanks,
Aaron :)

**Comment by tanghaibao** [comment]
@aaronphillips7493 

Normally folks would like to lift over from contigs to scaffolds/chromosomes.
https://github.com/tanghaibao/jcvi/wiki/ALLMAPS%3A-How-to-lift-over-gene-annotations

But, you want the reverse mapping here so we'd need to swap the AGP file.

```
python -m jcvi.formats.agp swap assembly.agp
```

This generates a new AGP `assembly.swap.agp`. You'll see that it basically swaps the components/objects from the original AGP file. We would then need to generate a `.chain` file for liftOver.

```
python -m jcvi.formats.chain fromagp JM-2.swapped.agp assembly.fasta contigs.fasta
```

The `assembly.fasta` and `contigs.fasta` are two FASTA files from scaffolded assembly, and contigs, respectively. This generates `assembly.swapped.chain` file which you could then use in `liftOver`, as mentioned at the beginning.

```
liftOver -gff as.gff3 assembly.swapped.chain assembly.gff3 unmapped
```

This should generate a GFF on the contig coordinates.
