### ISSUE TITLE
Use exist .maf file contain the synteny information to draw synteny graphs

### ISSUE THREAD

**Issue by rillaxy** [tanghaibao/jcvi#392]
Dear Professor Tang,
    I have used the last to align the genome and graped the synteny region by USUC，and the synteny file style is .maf. How can I omit the  comparison by the soft LAST  ,and use the exist .maf file to draw the nice synteny graphs by jcvi ?
 
Thanks for your listening, I'm looking forward to your reply!
Rilla

**Comment by tanghaibao** [comment]
@rillaxy 

The synteny graph in `jcvi` assumes alignment based on genes. If you have genomic alignments (such as `.maf` file), then the pipeline won't quite work.

**Comment by rillaxy** [comment]
Thanks for your help, I get it!
