### ISSUE TITLE
Could i ues lastz to alignment and run jcvi.graphics.synteny ?

### ISSUE THREAD

**Issue by Jwindler** [tanghaibao/jcvi#394]
Dear Haibao,
I know Pairwise synteny search is used by ‘last’ , but I want to use ‘lastz’ to alignment and generate the Macrosynteny graph, but I don't know how to configure the lastz result(axt/maf) to .anchors.
Can you tell me the general method or idea ? Thank you very much!
Zijie

**Comment by tanghaibao** [comment]
@Jwindler 

Unfortunately as `jcvi` package is focusing on using markers (genes) rather than whole genome alignments, we do not currently support `.axt` or `.maf` input at this point. But thanks for your interest.

Haibao

**Comment by Jwindler** [comment]
@tanghaibao 
Tanks for your reply. I don't know  `###` in the file `.lifted.anchors` means. The corresponding site between '###', how to determine the `anchors ` between double  `###`.
If have a method that when i havn't GFF file and only use genomic sequence to genertate  the Macrosynteny graph which is in the specific area.
Thanks again!
Zijie

**Comment by tanghaibao** [comment]
@Jwindler 

The anchors in between the `###` are gene pairs. So columns 1 and 2 are gene names in two genomes, respectively.

Again, if you really want to use `jcvi`, you'd need to get some gene models (even preliminary models). In my workflow, when I just have a draft genome assembly, I often use the gene CDS sequences from a related species, and use `gmap` to map it onto the assembly. `gmap` generates a GFF file which you could use. This is poo rman's approach to gene annotation. 

To get the CDS sequences for the preliminary annotations, use `python -m jcvi.formats.gff load` with your draft genome to get the gene sequences.

This may not be what you wanted after all, but `jcvi` really need to start with some sort of named features like genes.

Haibao
