### ISSUE TITLE
How to use different color to highlight specific blocks?

### ISSUE THREAD

**Issue by Bioinformatics-rookie** [tanghaibao/jcvi#395]
I know how to highlight a specific block, but I dot know how many letters before the '*' can be used to indicate different colors

**Comment by tanghaibao** [comment]
@Bioinformatics-rookie 

It follows the color convention used by matplotlib. So it can be either named (like `r`, `g`, `tomato`, `lightgray` etc), or even hex code (`#3a3a3a`). See details in:

https://matplotlib.org/stable/gallery/color/named_colors.html
https://matplotlib.org/stable/tutorials/colors/colors.html

**Comment by Bioinformatics-rookie** [comment]
thanks , I will close the comment
