### ISSUE TITLE
bar_plotter

### ISSUE THREAD

**Issue by fengyuanli304** [tanghaibao/jcvi#398]
Hi Dr. Tang,

I'm using Bar_plotter of MCScanX to generate a bar plot (PNG file) displaying chromosome rearrangement between reference and target chromosome sets. I would like to know if you have any advice or way to draw this file (SVG format) using JCVI.

Thank you.

**Comment by tanghaibao** [comment]
@fengyuanli304 

You may be able to do a similar plot by following:

https://github.com/tanghaibao/jcvi/wiki/Miscellaneous-plotting
