### ISSUE TITLE
concorde no more in jksrc

### ISSUE THREAD

**Issue by smoretti** [tanghaibao/jcvi#40]
Hi

the tool **concorde** does not look to be available any more in the Jim Kent UCSC source (last version 343).

So recompile it - as mention in https://github.com/tanghaibao/jcvi/wiki/ALLMAPS%3A-How-to-install - could be problematic.

**Comment by tangerzhang** [comment]
Hi,
One copy of concorde could be found here:
https://github.com/tanghaibao/jcvi-bin/tree/master/bin
