### ISSUE TITLE
MCscan (Python version) with few genes

### ISSUE THREAD

**Issue by Jacky749** [tanghaibao/jcvi#401]
Hi Dr. Tang,
I would like to do pairwise synteny visualization, but there was something wrong. The log of the command `python -m jcvi.compara.synteny screen --minspan=30 --simple *.anchors *.anchors.new` said "No blocks found in *.anchors.new". 
I guess it may because of the small number of genes in my bed files. There are only 8 genes in my both two bed files . And these genes are with one-to-one correspondence.
One of the output of `python -m jcvi.compara.catalog ortholog $1 $2 --no_strip_names` is pdf. In this pdf, there is only five dispersed dots.
Could I obtain synteny plot with few genes?

**Comment by tanghaibao** [comment]
@Jacky749 

Since you only have 8 genes, the `--minspan=30` will remove all blocks that span less than 30 genes - basically removing everything you have. You need to remove that option, or skip the `screen` step altogether.
