### ISSUE TITLE
How to displays a specific gene label

### ISSUE THREAD

**Issue by Bioinformatics-rookie** [tanghaibao/jcvi#404]
in Microsynteny visualization part ,I know how to display gene label 
`python -m jcvi.graphics.synteny blocks grape_peach.bed blocks.layout --genelabelsize 6`
but I want to know how to displays a specific gene label instead of all gene label at a local synteny

**Comment by tanghaibao** [comment]
@Bioinformatics-rookie 

Perhaps we should add an option `--genelabels=GENE1,GENE2` to show the given gene labels.

This is not difficult but would require some time to implement it so you'd have to wait a bit ... alternatively, feel free to code this up yourself and open a pull request here.

**Comment by tanghaibao** [comment]
@Bioinformatics-rookie 

I just implemented this option.

To show just a few gene labels, use `--genelabels`.

    $ python -m jcvi.graphics.synteny blocks grape_peach.bed blocks.layout --genelabelsize=10 --genelabels=GSVIVT01012244001,Prupe.1G289800.1,GSVIVT01012225001,Prupe.1G288000.1

![Grape-peach-blocks-genelabel-selected](https://www.dropbox.com/s/u72nwwnxxrp0ryd/Grape-peach-blocks-genelabel-selected.png?raw=1)
