### ISSUE TITLE
Can I just use one map?

### ISSUE THREAD

**Issue by Yutang-ETH** [tanghaibao/jcvi#409]
Hi Haibao,

I followed the instruction on wiki and I made two csv maps including one female and one male map. Then I merged these two maps to get the bed file and finally anchored my assembly using the bed file. I am just wondering is it possible that I can only use one map for anchoring? What command should I use? 

I don't know why for my case, the consensus map anchors less than each individual map according to the summary file so I am wondering if it is possible to just use one map. 

Thank you very much.
Yutang

**Comment by tanghaibao** [comment]
@Yutang-ETH 

It is the same process - when you are at the step to merge 2 maps, just feed it with a single map. For example, with the sample data:

```console
python -m jcvi.assembly.allmaps merge JMMale.csv -o JM-2-Single.bed -w Single_weights.txt
python -m jcvi.assembly.allmaps path JM-2-Single.bed scaffolds.fasta -w Single_weights.txt
```

Note only one CSV file after the `merge` command.

**Comment by Yutang-ETH** [comment]
Hi haibao,

Thank you very much for your reply. I just tried it and it turned out two maps gave better results than one map.

Best wishes,
Yutang

**Comment by Yutang-ETH** [comment]
Hi Haibao,

Thank you very much for your explanation. Got it.

Best wishes,
Yutang
