### ISSUE TITLE
Provide command/action `version`

### ISSUE THREAD

**Issue by paulmenzel** [tanghaibao/jcvi#41]
It’d be great if you could implement the action/command `version`, so that `python -m jcvi.formats.fasta version` prints the version of the module.

**Comment by tanghaibao** [comment]
@paulmenzel Thanks for the suggestion. This is good idea however I don't currently have module-specific version. The version is package-wide and is in `__init__.__version__`. Perhaps have the version always there in the help string?

**Comment by tanghaibao** [comment]
@paulmenzel I now added version string and also allowing --version option to print the version of the module. For example the help of the command below contains version:

```bash
$ python -m jcvi.apps
Usage:
    python -m jcvi.apps.SCRIPT


Available SCRIPTs:
          align | Perform DNA-DNA alignment using BLAST, NUCMER and BLAT. Keep the interface the
           base | Basic support for running library as script
...
        uniprot | Programatically accessing UniprotKB to get data from a list of queries
      vecscreen | Run through NCBI vecscreen on a local machine

JCVI utility libraries v0.7.3 [Copyright (c) 2010-2017, Haibao Tang]
```

or another example
```bash
$ python -m jcvi.apps.bwa align
Usage:
    bwa.py align database.fasta read1.fq [read2.fq]

    Wrapper for three modes of BWA - mem (default), aln, bwasw (long reads).


Options:
  --version            Show program's version number and exit
  -h, --help           show this help message and exit
...
  --cpus=CPUS          Number of CPUs to use, 0=unlimited [default: 64]
  --params=EXTRA       Extra parameters to pass  (these WILL NOT be validated)
                       [default: ]

JCVI utility libraries v0.7.3 [Copyright (c) 2010-2017, Haibao Tang]
```

Please notice the version string at the end of each usage text printed.

Thanks for the nice idea.

Haibao
