### ISSUE TITLE
jcvi.formats.chain fromagp

### ISSUE THREAD

**Issue by johnburley3000** [tanghaibao/jcvi#411]
Hi, 

I'm having trouble running jcvi.formats.chain fromagp. I would appreciate any advice about what the issue might be. 

I have two genome assemblies of the same species. The first assembly is much more fragmented, but I have done a lot of analysis based on VCF files (for example) based on this assembly. The second assembly is very contiguous, so I'd like to transpose the variants obtained in a VCF from the first assembly to correct positions in the second assembly. 

I see picardtools has a program for this, but it requires a USCS-like .chain file, which is what I would like to create using your program. 

I generated an .agp file using RagTag, here is the head:

```
## agp-version 2.1
# AGP created by RagTag v2.0.1
contig_14_segment0_RagTag	1	109240	1	W	scaffold_498	1	109240	-
contig_14_segment0_RagTag	109241	109340	2	U	100	scaffold	yes	align_genus
contig_14_segment0_RagTag	109341	1678530	3	W	scaffold_180	1	1569190	+
contig_14_segment0_RagTag	1678531	1680530	4	N	2000	scaffold	yes	align_genus
contig_14_segment0_RagTag	1680531	1719265	5	W	scaffold_647	1	38735	-
contig_14_segment0_RagTag	1719266	1720113	6	N	848	scaffold	yes	align_genus
contig_14_segment0_RagTag	1720114	1722040	7	W	scaffold_2063	1	1927	+
contig_14_segment0_RagTag	1722041	1722140	8	U	100	scaffold	yes	align_genus

```

When I run
`python -m jcvi.formats.chain fromagp ragtag-made.agp Assembly2.fasta Assembly1.fasta`

I get a keyword error related to the name of the first scaffold in the Assembly1.fasta.  Nothing is generated in the ragtag-made.chain file. I noticed a similar issue [here](https://github.com/tanghaibao/jcvi/issues/14), but in my case no output is generated. 

Here is my output

```
(ragtag) [jtb@holylogin04 Genome_Alignments]$ python -m jcvi.formats.chain fromagp ragtag-made.agp Z_ONT.fasta Allpaths.fasta
[19:45:58] DEBUG    Load file `ragtag-made.agp`                                                                     base.py:34
           DEBUG    Load file `Z_ONT.fasta.sizes`                                                                   base.py:34
[19:45:59] DEBUG    Load file `Allpaths.fasta.sizes`                                                                base.py:34
Traceback (most recent call last):
  File "/n/sw/eb/apps/centos7/Anaconda3/2020.11/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/n/sw/eb/apps/centos7/Anaconda3/2020.11/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/n/home01/jtb/.local/lib/python3.8/site-packages/jcvi/formats/chain.py", line 313, in <module>
    main()
  File "/n/home01/jtb/.local/lib/python3.8/site-packages/jcvi/formats/chain.py", line 84, in main
    p.dispatch(globals())
  File "/n/home01/jtb/.local/lib/python3.8/site-packages/jcvi/apps/base.py", line 110, in dispatch
    globals[action](sys.argv[2:])
  File "/n/home01/jtb/.local/lib/python3.8/site-packages/jcvi/formats/chain.py", line 162, in fromagp
    tSize = componentsizes[tName]
KeyError: 'scaffold_498'
```

**Comment by tanghaibao** [comment]
@johnburley3000 

Try flipping the order of `Assembly2.fasta` and `Assembly1`.fasta in your command. Notice the AGP essentially saying how to construct the assembly (the one that contains `contig_14_segment0_RagTag`) from another assembly (the one that contains `scaffold_498`). So if you get the order wrong, it gives you a `KeyError` since it's in the other file.
