### ISSUE TITLE
Hi ! 我用了JCVI鉴定共线性,是该引用MCscan(2008.Science)还是JCVI(2015.Zenodo)呀~

### ISSUE THREAD

**Issue by kuangzhuoran** [tanghaibao/jcvi#422]
![image](https://user-images.githubusercontent.com/76553133/143241543-7bfaaf52-2c81-4215-becb-eb6589922f52.png)
最后用的就是这么一张图

**Comment by tanghaibao** [comment]
谢谢。可以引用Science那篇。README里有写。
