### ISSUE TITLE
Hi！我需要画十多个物种的Macrosynteny，请问如何调节circles的大小

### ISSUE THREAD

**Issue by ChenXi1201** [tanghaibao/jcvi#427]
我通过--figsize调节了图的大小，但最后circles太大了遮住了大部分的track，我看karyotype.py中可以通过textcircle设置circles中字体的大小，但没找到更改circles大小的地方

**Comment by tanghaibao** [comment]
@ChenXi1201 

可以发个部分截图么？我看下

**Comment by ChenXi1201** [comment]
> @ChenXi1201
> 
> 可以发个部分截图么？我看下

python -m jcvi.graphics.karyotype seqids.sort layout --figsize=30x100
就像这样，这个circles圈很大
![image](https://user-images.githubusercontent.com/74816124/144788911-55d7ee97-f012-4177-8407-1c3a47077509.png)

**Comment by tanghaibao** [comment]
@ChenXi1201 

同样的地方，需要添加参数`radius`：

https://github.com/tanghaibao/jcvi/blob/4930fafd949afe054f55bc7ecac0ea5d582f9443/jcvi/graphics/karyotype.py#L228-L237

默认这个圈圈的半径是图长的2%(0.02)，指定更小的半径，比如`radius=0.005`可以把圆画的更小些。目前我暂时没时间研究出一个通用的半径配置。

**Comment by ChenXi1201** [comment]
您的来信已收到，我会尽快查看，谢谢陈曦

**Comment by ChenXi1201** [comment]
你好！我发现两个问题不知如何解决，
1.当染色体数目大于31条时，有些染色体的名字就不会显示
2.左边的物种名会和染色体画在一块，不知如何调整物种名的位置
![image](https://user-images.githubusercontent.com/74816124/145666864-0931b9d3-66b4-4cbe-9153-2f9d7d38cf26.png)

**Comment by tanghaibao** [comment]
@ChenXi1201 

默认参数都是按照正常大小来优化的，所以如果图太大，布局就会产生bug。

1. 如果染色体数>=32，会自动稀疏化，你只要删除这两行即可

https://github.com/tanghaibao/jcvi/blob/4930fafd949afe054f55bc7ecac0ea5d582f9443/jcvi/graphics/karyotype.py#L221-L222

2. 画物种名标签是这一行，你看情况调整`x`和`y`

https://github.com/tanghaibao/jcvi/blob/4930fafd949afe054f55bc7ecac0ea5d582f9443/jcvi/graphics/karyotype.py#L248

**Comment by ChenXi1201** [comment]
请问染色体大小是否能调节，我这个染色体序号是按染色体大小排序的，但2号画出来却很短，我想可能和它缺乏共线性有关？
![image](https://user-images.githubusercontent.com/74816124/147207143-71d513a1-5f8d-4e11-9acd-bbe60c3c6838.png)

**Comment by tanghaibao** [comment]
@ChenXi1201 

染色体长度取决于上面的基因数目（相应 `.bed` 文件中属于该染色体的基因数）。可能2号基因密度比较低，但是最好检查下是否所有基因都从 `.gff` 成功导入 `.bed` 文件。

**Comment by ChenXi1201** [comment]
您的来信已收到，我会尽快查看，谢谢陈曦
