### ISSUE TITLE
Primary transcript selected by `--primary_only`

### ISSUE THREAD

**Issue by obenno** [tanghaibao/jcvi#429]
Hi,

I would like to ask which isoform will be selected as priamry transcript when using `python -m jcvi.formats.gff bed` with `--primary_only` option? Is the one appearing the first in the `gff` file? Thank you in advance.

Best regards,
obenno

**Comment by tanghaibao** [comment]
@obenno 

The first transcript that appears in the GFF file is considered primary in this case.

**Comment by obenno** [comment]
@tanghaibao

Thank you very much for your prompt reply, it's quite helpful.

Bests,
obenno
