### ISSUE TITLE
Grabseed with test data

### ISSUE THREAD

**Issue by ascendo** [tanghaibao/jcvi#43]
Dear Haibao,

"grabseeds" simply wouldn't work on test image. 

Will you please check this?

 python -m jcvi.graphics.grabseeds seeds test.JPG
17:25:35 [Image] Error closing: 'NoneType' object has no attribute 'close'
17:25:35 [grabseeds] Image `./test.resize.jpg` loaded (376px x 250px).
17:25:35 [Image] Error closing: 'NoneType' object has no attribute 'close'
17:25:35 [grabseeds] Image `./test.resize.jpg` loaded (376px x 250px).
17:25:35 [grabseeds] Running canny edge detection ...
/usr/local/lib/python2.7/dist-packages/skimage/filters/__init__.py:28: skimage_deprecation: Call to deprecated function ``canny``. Use ``skimage.feature.canny`` instead.
  def canny(*args, **kwargs):
17:25:35 [grabseeds] Find objects with pixels between 47 (0.05%) and 47000 (50%)
17:25:35 [grabseeds] A total of 52 objects identified.
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/wyim/.local/lib/python2.7/site-packages/jcvi/graphics/grabseeds.py", line 591, in <module>
    main()
  File "/home/wyim/.local/lib/python2.7/site-packages/jcvi/graphics/grabseeds.py", line 114, in main
    p.dispatch(globals())
  File "/home/wyim/.local/lib/python2.7/site-packages/jcvi/apps/base.py", line 84, in dispatch
    globals[action](sys.argv[2:])
  File "/home/wyim/.local/lib/python2.7/site-packages/jcvi/graphics/grabseeds.py", line 533, in seeds
    square = img[(y0 - d):(y0 + d), (x0 - d):(x0 + d)]
TypeError: slice indices must be integers or None or have an __index__ method

Thank you .

Won

**Comment by tanghaibao** [comment]
@ascendo This is a problem due to the use of non-integer indices in numpy array. Newer version of numpy no longer allows non-integers. Please update the code accordingly to incorporate this fix.

PS: it was nice chatting with you this past Friday night.

Haibao

**Comment by ascendo** [comment]
Oh thank you.

 I was very nice to meet you there. :)

I need stay one more days due to snow.

**Comment by ascendo** [comment]
which color is the best for background?

**Comment by tanghaibao** [comment]
anything other than red would work. I usually go with white or black, less texture is better (so for example paper is better than cloth).
