### ISSUE TITLE
How to handle new added APG evidence"proximity_ligation"

### ISSUE THREAD

**Issue by dongzhang0725** [tanghaibao/jcvi#434]
Dear developers,

I used `jcvi.formats.chain` function to convert apg file (generated by `juicebox_assembly_converter`) to chain file, however I encounterred the following error:
```ERROR    linkage_evidence must be one of |na|paired-ends|align_genus|align_xgenus|align_trnscpt|within_clone|clone_contig|map|strobe|unspecified, you have ['proximity_ligation'] ```.

I searched that "proximity_ligation" is a new added APG evidence in version 2.1, see https://www.ncbi.nlm.nih.gov/assembly/agp/AGP_Specification/.

Do you have any idea for fixing this bug?

Sincerely,
Dong

**Comment by tanghaibao** [comment]
@dongzhang0725 

Thanks for the issue! 
I have added support for AGP version 2.1. Please update to the latest version (`pip install -U jcvi`).

**Comment by dongzhang0725** [comment]
Thank you very much, the bug disappeared after I updated jcvi.

However, it seems the command in #391 did not work in my case, when I use the following command:

```python -m jcvi.formats.chain fromagp JM-2.swapped.agp assembly.fasta contigs.fasta```

I get this error:

```
Traceback (most recent call last):
  File "/apps/zhangdong/Anaconda/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/apps/zhangdong/Anaconda/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/apps/zhangdong/Anaconda/lib/python3.7/site-packages/jcvi/formats/chain.py", line 314, in <module>
    main()
  File "/apps/zhangdong/Anaconda/lib/python3.7/site-packages/jcvi/formats/chain.py", line 84, in main
    p.dispatch(globals())
  File "/apps/zhangdong/Anaconda/lib/python3.7/site-packages/jcvi/apps/base.py", line 110, in dispatch
    globals[action](sys.argv[2:])
  File "/apps/zhangdong/Anaconda/lib/python3.7/site-packages/jcvi/formats/chain.py", line 163, in fromagp
    tSize = componentsizes[tName]
KeyError: 'ctg001160_np121212121212'
```

I checked the source code, and found that `componentsizes` is a dict for `assembly.fasta`, whereas `tName` is the sequence name in `contigs.fasta`, so I changed the command to:

```python -m jcvi.formats.chain fromagp JM-2.swapped.agp contigs.fasta assembly.fasta```

Finally, this command worked and I got the chain file.

Am I correct?

Sincerely,
Dong

**Comment by tanghaibao** [comment]
@dongzhang0725 

Depending on which direction you want to map the gene features (contigs → assembly, or assembly → FASTA), the AGP (and the resulting chain file) are different and swap contig names or assembly names. We provide the `jcvi.formats.agp swap` command for this purpose.

Therefore, the reason for the inverted order of FASTA in #391 was that the AGP was swapped. If you use the same command to swap the AGP first, then you get the chain file in the other direction as well.

**Comment by dongzhang0725** [comment]
I get it, thank you for your detailed reply @tanghaibao
