### ISSUE TITLE
AttributeError: module 'string' has no attribute 'letters'

### ISSUE THREAD

**Issue by inspirewind** [tanghaibao/jcvi#437]
hello developers,

I installed jcvi via conda and ran the
`python -m jcvi.formats.fasta clean chr21.fna`

then,

> Traceback (most recent call last):
>   File "/home/inspirewind/miniconda3/envs/jcvi/lib/python3.9/runpy.py", line 197, in _run_module_as_main
>     return _run_code(code, main_globals, None,
>   File "/home/inspirewind/miniconda3/envs/jcvi/lib/python3.9/runpy.py", line 87, in _run_code
>     exec(code, run_globals)
>   File "/home/inspirewind/miniconda3/envs/jcvi/lib/python3.9/site-packages/jcvi/formats/fasta.py", line 2642, in <module>
>     main()
>   File "/home/inspirewind/miniconda3/envs/jcvi/lib/python3.9/site-packages/jcvi/formats/fasta.py", line 405, in main
>     p.dispatch(globals())
>   File "/home/inspirewind/miniconda3/envs/jcvi/lib/python3.9/site-packages/jcvi/apps/base.py", line 110, in dispatch
>     globals[action](sys.argv[2:])
>   File "/home/inspirewind/miniconda3/envs/jcvi/lib/python3.9/site-packages/jcvi/formats/fasta.py", line 813, in clean
>     for header, seq in iterator(fastafile):
>   File "/home/inspirewind/miniconda3/envs/jcvi/lib/python3.9/site-packages/jcvi/formats/fasta.py", line 752, in iter_clean_fasta
>     seq = "".join(x for x in seq if x in string.letters or x == "*")
>   File "/home/inspirewind/miniconda3/envs/jcvi/lib/python3.9/site-packages/jcvi/formats/fasta.py", line 752, in <genexpr>
>     seq = "".join(x for x in seq if x in string.letters or x == "*")
> AttributeError: module 'string' has no attribute 'letters'

Maybe the `letters` is abolished in python3 and replaced with `ascii_letters`, so what version python should I use?

**Comment by tanghaibao** [comment]
@inspirewind 

Thank you. This was an error not caught when we migrated from py2 to py3 earlier. I took the py3 version in your PR (thanks) and made the suggested changes and a small test.
