### ISSUE TITLE
Force ALLmaps to use the user defined orientation to build pseudo chrmosomes

### ISSUE THREAD

**Issue by yilongyang** [tanghaibao/jcvi#44]
For my assembly, I have the orientation of scaffolds determined by HiC data and genetic map. I can use genetic map only to orient scaffold using ALLmaps. But how could I add the orientation provided by HiC data? I want ALLmaps to use the genetic map and also the specified orientation of scaffolds (from HiC data) to build the final pseudo chromosomes. Thank you!

**Comment by tanghaibao** [comment]
@yilongyang 'orientation' or 'order'? You can use ALLMAPS to run on genetic map and then write a script to change the 'orientation' of scaffolds based on Hi-C in the AGP file. Then convert from AGP to CHAIN file using ``python -m jcvi.formats.chain fromagp``.

**Comment by yilongyang** [comment]
Thanks. That is exactly what I want. For this chain command, do I need to
give it the assembly  fasta input file? Or only the modified agp file is
needed?

Thank you!
Haibao Tang <notifications@github.com>于2017年3月4日 周六下午3:58写道：

**Comment by tanghaibao** [comment]
Say if you have `contigs.fasta` and `modified.agp`. Use two commands below:

```bash
$ python -m jcvi.formats.agp build modified.agp contigs.fasta chr.fasta
$ python -m jcvi.formats.chain fromagp modified.agp contigs.fasta chr.fasta
```
These commands will generate:
- `chr.fasta`, final assembly
- `modified.chain`, which you can use to re-build gene model coordinates (see https://github.com/tanghaibao/jcvi/wiki/ALLMAPS%3A-How-to-lift-over-gene-annotations).

**Comment by yilongyang** [comment]
Thank you! That's very helpful!
Haibao Tang <notifications@github.com>于2017年3月4日 周六下午4:20写道：

**Comment by tanghaibao** [comment]
Closing issue. Please feel free to open another ticket if you have more questions.
