### ISSUE TITLE
python -m jcvi.formats.gff fixpartials cost huge memory.

### ISSUE THREAD

**Issue by xiekunwhy** [tanghaibao/jcvi#452]
Hi,

Why python -m jcvi.formats.gff fixpartials cost huge memory?
Gene number in gff file ~30000(~60000 mRNA, ~19000 are partial). And genome fasta 1.3G

![memory](https://user-images.githubusercontent.com/17738229/157595556-7a77e876-4d0d-4196-8a4a-1d6714f158de.png)

Best,
Kun

**Comment by tanghaibao** [comment]
@xiekunwhy 

this is an uncommon utility in the library and hasn't been worked on for a while.
I'd be happy to take a look - would you happen to have a sample gff for me to test? this would help a lot for me to debug this.
