### ISSUE TITLE
microsynteny plot: using the front bed file and back bed file lead different results

### ISSUE THREAD

**Issue by Li-Tianran** [tanghaibao/jcvi#454]
唐老师您好！
我在分析物种1和物种2之间区段共线性的时候，发现分别使用物种1和物种2的bed文件时会导致小部分基因不同的区段共线性，代码如下：

`python -m jcvi.compara.catalog ortholog D5new G1new --dbtype prot --cscore=.99 --no_strip_names`
`python -m jcvi.compara.synteny mcscan D5new.bed D5new.G1new.lifted.anchors --iter=1 -o D5new.G1new.i1.blocks`
`python -m jcvi.compara.synteny mcscan G1new.bed D5new.G1new.lifted.anchors --iter=1 -o D5new.G1new.i1.change.blocks`

使用不同bed文件关系不同的基因例子：

`grep GrD5_02G14890 D5new.G1new.i1.change.blocks`
`GbiG1_02G19510  GrD5_02G14890`
`grep GrD5_02G14890 D5new.G1new.i1.blocks`
`GrD5_02G14890   .`
`grep GbiG1_02G19510 D5new.G1new.i1.blocks #不存在`

请问我该如何处理这些不一致的部分呢？以哪个结果为准还是需要过滤掉它们？

祝软件越来越好，也祝您工作顺利！

**Comment by tanghaibao** [comment]
@Li-Tianran 

共线性比对和BLAST类似，有时候存在不对称性，特别是如果有类似分值的片段，A对B的最优匹配可能不是B对A的最优匹配。

这个很正常。如果比较在意的话，可以过滤到互为最优，类似于BLAST里面的reciprocal best match (RBH)。

海宝

**Comment by Li-Tianran** [comment]
好的明白了，谢谢唐老师！
