### ISSUE TITLE
ALLMAPS movie AGP bug?

### ISSUE THREAD

**Issue by jguppy** [tanghaibao/jcvi#456]
Hi,

I've run ALLMAPS (V1.1.7) using the '_path_' flag successfully with my own data and the pdfs and AGP files have generating as expected.

Next I've looked to run instead with the '_movie_' flag to provide visualisations of each step. The first round of pdfs (_INIT_) are generate normally for the single Pseudomolecule requested. However, it throws a Assertion Error (Line 1845) before generating the second set of pdfs. Also the AGP file written out midway through has reverted to using the scaffold IDs rather than the pseudomolecule ID provided.

From scanning through the allmaps.py code, I think when running the '_movie_' flag the AGP files are updated after each step (_INIT_, _FLIP_, _TSP_, _FINAL_) based on the 'need_update()' check (Line 1753), this is then replacing the combined_AGP with the chr_agp, and reverting to the scaffold ID's rather than pseudomolecule ID.

I've also run this through using the test data set provided in the instructions (https://www.dropbox.com/s/b497bi2b594m6fp/ALLMAPS-testdata.zip), and the same issue occurs.

`python3 -m jcvi.assembly.allmaps merge JMFemale.csv JMMale.csv`
`python3 -m jcvi.assembly.allmaps path JM-2.bed scaffolds.fasta`
`python3 -m jcvi.assembly.allmaps movie JM-2.bed scaffolds.fasta chr23`

Here is the output using the test data.
[error.log.txt](https://github.com/tanghaibao/jcvi/files/8304177/error.log.txt)

Is this a bug?

Thanks for your help here,

**Comment by tanghaibao** [comment]
@jguppy 

Thank you much for reporting this. This particular code path (`movie`) isn't executed often - so the potential for bugs is large.

I'll take a look at this when I get a chance.

**Comment by tanghaibao** [comment]
@jguppy 

Turns out this was a bug when we migrated from py2 to py3. Should be fixed now and I was able to generate the animation for the testdata. Once again, thank you for your insight.

https://user-images.githubusercontent.com/106987/159040286-70ffb438-5fb8-48ee-a4c9-584ca377a8fe.mp4

**Comment by jguppy** [comment]
Thank you for looking into this so quickly, I do really appreciate it.

I updated my local copy of the jcvi git repo, and checked  the changes from #457 are present in the allmaps.py script.

Unfortunately, I seem to be coming up against the same Assertion error when using the code:
`python3 -m jcvi.assembly.allmaps movie JM-2.bed scaffolds.fasta chr23`

Error:
>   File "/home/aqlinux/code/jcvi/jcvi/assembly/allmaps.py", line 1848, in plot
    assert seqid in allseqids, "{0} not in {1}".format(seqid, allseqids)
AssertionError: chr23 not in ['scaffold_1006', 'scaffold_1189', 'scaffold_129', 'scaffold_148', 'scaffold_150', 'scaffold_158', 'scaffold_164', 'scaffold_225', 'scaffold_310', 'scaffold_331', 'scaffold_375', 'scaffold_382', 'scaffold_43', 'scaffold_513', 'scaffold_642', 'scaffold_648', 'scaffold_792', 'scaffold_80', 'scaffold_821', 'scaffold_829', 'scaffold_866', 'scaffold_95']

Based on the help text chr23 would be the correct notation, but am I doing something wrong here? Should I be calling a single scaffold only within the pseudomolecule?
> ... The third argument limits the plotting to a specific pseudomolecule, for example `chr1`.

My overall aim here isn't so much to create the movie, but get both a initial and final pdf for each pseudomolecule.

Thanks again for your help here,

**Comment by tanghaibao** [comment]
@jguppy 

Try running the previous `path` command again to re-generate a new set of output files, in particular, the `.tour` file needs to be updated since the fix.

**Comment by jguppy** [comment]
Sorry I should have mentioned that, I removed all but the 4 starting test files (2x maps, scaffolds and weights) and I ran all three steps from the start, and then hit the error

`python3 -m jcvi.assembly.allmaps merge JMFemale.csv JMMale.csv -o JM-2.bed`
`python3 -m jcvi.assembly.allmaps path JM-2.bed scaffolds.fasta`
`python3 -m jcvi.assembly.allmaps movie JM-2.bed scaffolds.fasta chr23`

The tour file ([JM-2.tour.txt](https://github.com/tanghaibao/jcvi/files/8313005/JM-2.tour.txt)) the scaffold names from the for the FLIP step though

**Comment by tanghaibao** [comment]
@jguppy 

My bad. There was an unintended secondary change in my bug fix that reverted my fix.
Can you try again with the latest commit/version?

**Comment by jguppy** [comment]
Thanks! That works perfectly now.

I also had to change the policy.xml file for `convert` as per [https://askubuntu.com/questions/1081895/trouble-with-batch-conversion-of-png-to-pdf-using-convert](https://askubuntu.com/questions/1081895/trouble-with-batch-conversion-of-png-to-pdf-using-convert). This is just an individual user issue but thought I'd add it here in case others run into it.

Thanks again for looking into all this so quickly
