### ISSUE TITLE
jcvi.formats.gff bed --primary_only couldn't select primary transcript

### ISSUE THREAD

**Issue by yanyew** [tanghaibao/jcvi#458]
Hi, Thank you so much for your excellent tool!
When I try to select primary transcript with `jcvi.formats.gff bed --type=mRNA --key=ID --primary_only`, I found that all the non-primary transcripts were kept. I check the `.gff3` and I think there is no problem about the naming format of the isoforms. Here is the `.gff3` I used. 
[A.zip](https://github.com/tanghaibao/jcvi/files/8308440/A.zip)
Can you tell the reason? Thank you very much!
In addition, is it more reasonable to choose the longest transcript as primary transcript rather than 'The first transcript that appears in the GFF file'?

**Comment by tanghaibao** [comment]
@yanyew 

Multiple transcripts grouped with under the same gene via `Parent=ABC`, so try something similar to below:

```console
$ perl -pi -e "s/geneID=/Parent=/g" A.gff3
$ python -m jcvi.formats.gff bed --type=mRNA --key=ID --primary_only A.gff3
...
[20:08:56] DEBUG    Extracted 32798 features (type=mRNA id=ID) 
           DEBUG    Skipped non-primary: 27734
```

Longest transcript may be more reasonable, but a little more work to implement. For synteny analysis, this may not have a big impact and often the first isoform has the most expression support by convention.

Haibao

**Comment by yanyew** [comment]
Thanks for your quick reply and it works.
I wonder is it possible to add an option to choose the transcripts group name? It may reduce some invisible error.

**Comment by tanghaibao** [comment]
@yanyew 

Good idea.

I added an option `--parent_key` based on your suggestion.

```console
$ python -m jcvi.formats.gff bed --type=mRNA --key=ID --primary_only A.gff3 --parent_key=geneID
[21:58:19] DEBUG    Extracted 32798 features (type=mRNA id=ID parent=geneID)
           DEBUG    Skipped non-primary: 27734
```

**Comment by yanyew** [comment]
Thanks!

**Comment by yanyew** [comment]
Thanks! And hope someday JCVI can provide the function to get longest transcript too~
