### ISSUE TITLE
Concatenating scaffolds

### ISSUE THREAD

**Issue by Homap** [tanghaibao/jcvi#46]
Hi,

I was wondering when concatenating scaffolds reported in the file (file.lifted.bed), what is the gap
length inserted between the two scaffolds?

In some cases in other genomes, for example they use a value of 5000 bp or 100 bp between scaffolds when they concatenate them to one, however, I couldn't figure out how Allmaps does this.

Thank you,
Homa

**Comment by tanghaibao** [comment]
@Homap By default ALLMAPS adds 100bp per gap. This can be modified with the option ``--gapsize``. See below:

```
$ python -m jcvi.assembly.allmaps path
Usage:
    allmaps.py path input.bed scaffolds.fasta

    Construct golden path given a set of genetic maps. The respective weight for
    each map is given in file `weights.txt`. The map with the highest weight is
    considered the pivot map. The final output is an AGP file that contains
    ordered scaffolds.

    Please note that BED file and FASTA file cannot share the same prefix.


Options:
  --version             Show program's version number and exit
  -h, --help            show this help message and exit
...
  --gapsize=GAPSIZE     Insert gaps of size between scaffolds [default: 100]
...
```

**Comment by Homap** [comment]
Great, thank you very much!

Another question I was wondering about is if you could direct me to the script in allmaps where it translates the scaffold positions to the constructed genome position?

Thank you in advance!

**Comment by tanghaibao** [comment]
Closing issue.
