### ISSUE TITLE
ModuleNotFoundError: No module named 'jcvi.para'

### ISSUE THREAD

**Issue by C2051** [tanghaibao/jcvi#464]
I installed jcvi on Ubuntu 20.04 using 'pip install jcvi'.
When I use jcvi to present the results of MCScans，I got this error while running jcvi.para.synteny module.
(jcvi) wang@ubuntu:~/Collinearity/jcvi$ python3 -m jcvi.para.synteny fromaligns Cang_Egra.collinearity > Cang_Egra.anchors1
/usr/bin/python3: Error while finding module specification for 'jcvi.para.synteny' (ModuleNotFoundError: No module named 'jcvi.para')

And I tried to run synteny.py. Here's what I got.
(jcvi) wang@ubuntu:/opt/biosoft/jcvi/jcvi/compara$ python3 synteny.py
Traceback (most recent call last):
  File "synteny.py", line 2018, in <module>
    main()
  File "synteny.py", line 571, in main
    p.dispatch(globals())
  File "/opt/biosoft/jcvi/jcvi/apps/base.py", line 97, in dispatch
    self.print_help()
  File "/opt/biosoft/jcvi/jcvi/apps/base.py", line 70, in print_help
    meta, args = self.get_meta()
  File "/opt/biosoft/jcvi/jcvi/apps/base.py", line 61, in get_meta
    if args[-2] == "jcvi":
IndexError: list index out of range

I will very thank you if you can help me. Look forward to your reply.

**Comment by SoledadPianist** [comment]
Error while finding module specification for 'jcvi.compara.synteny.scan' (ModuleNotFoundError: __path__ attribute not found on 'jcvi.compara.synteny' while trying to find 'jcvi.compara.synteny.scan')

I have the same problem too
