### ISSUE TITLE
Example of chromosome.py bedfile id_mappings

### ISSUE THREAD

**Issue by chriswyatt1** [tanghaibao/jcvi#468]
Hi, thanks for the great code, have been enjoying using it alot.

I was trying to work out how to run some of the additional scripts such as the chromosome painting one:
`python -m jcvi.graphics.chromosome`

Is there a way to create the input bedfile and id_mappings? Or example input.

**Comment by tanghaibao** [comment]
@chriswyatt1 

Have you checked out this page?
https://github.com/tanghaibao/jcvi/wiki/Miscellaneous-plotting

Let me know if there are additional clarifications needed

**Comment by chriswyatt1** [comment]
Great, thanks. Sorry I don't know how I missed that. Very clear
