### ISSUE TITLE
The problem with drawing with the old MCscanX

### ISSUE THREAD

**Issue by Wenwen012345** [tanghaibao/jcvi#469]
Hello @tanghaibao @vivekkrish @orionzhou 
Recently I have read the literature (https://onlinelibrary.wiley.com/doi/10.1111/jse.12850) and conducted research on LTR- retrotransposon.
In this article, the author made the following image using MCscanX. The image seems to be drawn by the Python version of MCscanX, but the method seems to be the old MCscanX method.

![图片3453](https://user-images.githubusercontent.com/63379795/167611414-2d9fc323-05d3-4b8d-93e0-668885c3fc42.png)

Method:
"2.6 Syntenic LTR retrotransposons analysis
We firstly extracted the coding sequences of all LTR retrotransposons from three 
chromosome-level genomes, PN40024, V. ripara and V. amurensis genomes. Then 
the coding sequences were translated into amino acid sequences by using TBtools
v1.098 (Chen et al., 2020). Next, multiple sequence alignment inter- and intra-species was performed using blastp of BLAST+ v2.10.1 with ‘-evalue 1e-5,-outfmt 6’ (Camacho et al., 2009), and finally the alignment results were entered 
into MCScanX (Wang et al., 2012) with default parameters for syntenic analysis. 
The downstream script ‘duplicate_gene_classifier’ was used to classify origins 
duplicate LTR retrotransposons into tandem, proximal, dispersed, segmental or 
singleton. The number of intra-species syntenic LTR retrotransposons and the 
number of inter-species syntenic LTR retrotransposons was dissected by the script 
‘dissect_multiple_alignment’. We clustered the LTR retrotransposons shared 
among these three genomes according to their syntenic LTR retrotransposons 
within each genome (results from MCScanX) using Yifan Hu multilevel layout 
algorithm of Gephi v0.9.2 (https://gephi.org/)."

I used the method used by the authors of this article and got something like this:

![dual_synteny](https://user-images.githubusercontent.com/63379795/167611069-1b3aae74-1913-4383-92b1-f7f2d5766da2.PNG)

What's the matter, please? How can I make figures of MCscanX in Python while using MCscanX in Java?

**Comment by wyim-pgl** [comment]
https://github.com/tanghaibao/jcvi/wiki/MCscan-%28Python-version%29
