### ISSUE TITLE
How to control the direction of the gene block in Microsynteny visualization part

### ISSUE THREAD

**Issue by Bioinformatics-rookie** [tanghaibao/jcvi#475]
In Microsynteny visualization plot,  sometimes the direction of the gene block is positive, sometimes it is negative, how can I control the direction of the gene block in the picture

**Comment by tanghaibao** [comment]
@Bioinformatics-rookie 

These are determined in the BED file, column 6.

**Comment by Bioinformatics-rookie** [comment]
I mean this，in this plot, I want the Ath gene block to display in reverse.
![微信截图_20220607110518](https://user-images.githubusercontent.com/67935442/172287277-2711ba01-62c6-4889-bfd4-ccdab851d480.png)
n

**Comment by tanghaibao** [comment]
@Bioinformatics-rookie 

Are you plotting from a `.blocks` file? The direction should be flipped automagically -  the script computes a correlation, and if it is less than zero, we flip. Somehow the flipping fails here.

For other tracks on the figure, is Ath Chr1 the only track that needs flipping?

**Comment by Bioinformatics-rookie** [comment]
It was drawn from the block file, and there were other gene blocks above the Pco, but when I scaled down the number of genes, the picture went back to norma
![微信截图_20220607143107](https://user-images.githubusercontent.com/67935442/172311449-01a26fe0-592a-4a94-8d45-65592f0178c4.png)
l

**Comment by sjfleck** [comment]
@tanghaibao I'm having this issue too. Is there a way to manually flip a segment in the microsynteny view? My plot looks like the first image Bioinformatics-rookie shared. Thank you for any help you're able to provide

**Comment by Adamtaranto** [comment]
@tanghaibao where is the code that computes the correlation and flips the annotations that you mentioned above? 

I've implemented a manual flip feature in my dev fork that would handle this. In the `Region` class I flip the chromosome region being plotted [here](https://github.com/Adamtaranto/jcvi/blob/dev/jcvi/graphics/ribbon.py#L274) and the annotations [here](https://github.com/Adamtaranto/jcvi/blob/dev/jcvi/graphics/ribbon.py#L313).

Users pass a comma delim string of fwd/rev flipping options for each region in the layout file (same order as layout file) with the [option](https://github.com/Adamtaranto/jcvi/blob/dev/jcvi/graphics/ribbon.py#L757) `--reorient` i.e for the original image above you would set `--reorient F,R,F,F` to flip the Ath chromosome and all of its annotations.

Currently this module is designed to work with arbitrary whole genome alignment blocks and uses a slightly customised layout file. I'd have to check if it is backwards compatible with CDS blocks that are used in the regular microsynteny plots.

Alternatively, we could migrate the flipping code back over to `jcvi.graphics.synteny`

It would be nice to keep the `--reorient` flag behaviour for consistency with `jcvi.graphics.ribbon` when I get around to doing a PR.

**Comment by tanghaibao** [comment]
@Adamtaranto 

The code for automatic flip is this line:

https://github.com/tanghaibao/jcvi/blob/b5bb9322f15c19f2849979fedc5c14eed932cae9/jcvi/compara/synteny.py#L1236

This basically look at the two array of gene ranks, and then regress a line between them, the orientation is just the sign of the slope of this line. Apparently this may produce a wrong orientation esp. when there are outliers to to the primary synteny pattern.

**Comment by Adamtaranto** [comment]
Ok cool, so `get_orientation()` decides if one of the sets of genes needs to be flipped. Where do you calculate the new flipped coords for genes on a flipped chrm before plotting?

**Comment by tanghaibao** [comment]
@Adamtaranto 

The coordinates are converted from the genomic coordinates `.start`, `.end`, note the start and end are simply swapped in the case of a `-` orientation. 

https://github.com/tanghaibao/jcvi/blob/b5bb9322f15c19f2849979fedc5c14eed932cae9/jcvi/graphics/synteny.py#L242-L250
