### ISSUE TITLE
How to relay chromosome sizes to MCscan (python version), 

### ISSUE THREAD

**Issue by ohdongha** [tanghaibao/jcvi#476]
Hi, 
To my understanding, MCscan accepts only the .bed for coordinates of features (e.g. CDS), plus the sequences of the said features.  

Then, I wonder for example for the karyotype (i.e. macro-synteny) view, how does the program know the actual chromosome sizes, especially when features are sparsely distributed and far from the ends of chromosomes?   

Will it be helpful if I add a 1-nt mock feature just to mark the end of each chromosome (inferred from e.g. [chrom.sizes](https://software.broadinstitute.org/software/igv/chromSizes))?  Or if we convert .gff to .bed as instructed by the wiki, will the .bed file somehow contains the information where chromosomes end?    

Thanks!
Dong-Ha  

P.S. I saw in [a previous issues]((https://github.com/tanghaibao/jcvi/issues/170) the option of "--basepair" was added.  But I still wonder whether the chromosomes will be drawn to the end (in macro-synteny views) if there is no features (e.g. CDS) near the chromosome end.

**Comment by tanghaibao** [comment]
@ohdongha 

The default chromosome sizes are based on number of genes, which we can get from the BED files. For plotting with basepairs, the script uses the maximum coordinate it is seen. This won't be very accurate, like you said, if the chromosome has no genes, or regions with no genes.

Feel free to open a PR adding the parameters that you suggested.

**Comment by ohdongha** [comment]
@tanghaibao 

I think more formally an optional argument, for example, `--chrom_sizes <file>` could be added to `jcvi.formats.gff bed`, but this workaround could work, too. 

Here, I'm following the graph-peach example in the wiki [Macrosynteny visualization](https://github.com/tanghaibao/jcvi/wiki/MCscan-(Python-version)#macrosynteny-visualization) section, with human-chimpanzee.   

The result without chromosome sizes looks like this (`jcvi.graphics.karyotype` with `--notex --basepair` showing only main chromosomes `NC_*`):
![cut_human chimpanzee karyotype basepair](https://user-images.githubusercontent.com/748486/174456119-adcb6a46-8a55-470c-b4e7-6ce6753729d9.png)

Suppose you have a `human.chrom.sizes`, a tab-delimited text with chromosome id and chromosome size, one per line  (as in [igvtools](https://software.broadinstitute.org/software/igv/chromSizes). This could be obtained by `samtools faidx` or similar)

Then you can add the end position of all chromosomes as a 1-nt mock feature to the `human.bed` file: 
```
cat human.bed <(awk -v FS="\t" '{print $1"\t"($2-1)"\t"$2"\t"$1".chromEnd\t0\t."}' human.chrom.sizes) | sort -k1,1 -k2,2n > human_chromEndMarked.bed
```
Do this for `chimpanzee.bed` as well, and modify the `.layout` file to accept the `*_chromEndMarked.bed` files.

The difference is noticeable in the chromosome "24" (=NC_000024.10 or the GRCh38 Y chromosome) where the synteny is found only in the first half of the human chromosome (the part sequenced in GRCh38):  
![cut_human chimpanzee karyotype basepair chromEndMarked](https://user-images.githubusercontent.com/748486/174456136-0b255adc-09c7-4b5a-82ba-99b071ce18eb.png)

Hope this could be helpful to others trying something similar.  
Thanks!

**Comment by mrmrwinter** [comment]
Hi @ohdongha,

Im trying to recreate what you have done here with the lengths but I'm getting the following error from the one-liner:
```
bash: syntax error near unexpected token `('
```
Could you send an example of the final bed file you produce if that is ok?

**Comment by ohdongha** [comment]
,@mrmrwinter  Sure, I can upload them later today when I have my computer.  

Before that, could you try again making sure not to have a space between `<` and `(awk ...`?  It should be `cat human.bed <(awk ...)` and not `cat human.bed < (awk ...)`.  Having a space there caused the same syntax error you had.

**Comment by mrmrwinter** [comment]
@ohdongha, thankyou. I checked for this but it was not the problem, but it got me thinking that maybe the notebook i was running the command into bash from changed the formatting, and it does! Your one liner works fine straight into the terminal. 

It would be great to see your .layout file as an example still though if possible.

**Comment by ohdongha** [comment]
@mrmrwinter Glad that you figured it out!

Please download all files related to these views, including `.bed` and `.layout` files before and after adding the chromosome ends and command lines used: 
https://www.dropbox.com/s/nowxavh0velepf4/220608_MCscan_chromEnds.zip?dl=0

Let me know if there is anything else.  Thanks!

**Comment by ohdongha** [comment]
@mrmrwinter 
In your case, both scaffolds have features (transcript models?) that are quite close to the end of the scaffolds.  So even if MCscan tries to draw chromosome size differently, it will be unrecognizable if the difference is less than a pixel.   

In my case, the difference was only visible for the human Y chromosome (GRCh38), which had gene models called only the first half of the chromosome: 
```
$ tail -n5 human_chromEndMarked.bed
NC_000024.10    24833918        24907040        NM_001388484.1  0       +       NP_001375413.1  57135   MANE Select     723
NC_000024.10    25030900        25052104        NM_001002761.1  0       -       NP_001002761.1  442868  MANE Select     106
NC_000024.10    25622116        25624902        NM_004680.3     0       +       NP_004671.1     9085    MANE Select     554
NC_000024.10    57227414        57227415        NC_000024.10.chromEnd   0       .
NC_012920.1     16568   16569   NC_012920.1.chromEnd    0  
```

If you want to see a visible difference, you could try (artificially) modifying the chromosome end to a larger number, e.g. twice larger than the end of the last feature coordinate, just to see whether it works?

**Comment by mrmrwinter** [comment]
Yeah, i think i sent examples where therea re transcripts nearly to the end of the scaffold. Some others do end much earlier, but still plot the rest of the space.

I tried artificially extending it as you suggested and saw something interesting.

Here is the first, with the genuine length:
![image](https://user-images.githubusercontent.com/52489932/175044468-a531703a-1857-46e3-82c5-e97f7068f01f.png)

And here is the second with the length of Scaffold 10 artificially extended by 1 Gbp:
![image](https://user-images.githubusercontent.com/52489932/175044629-dae54b2d-b2a4-4bc2-8ca3-c5e37288a336.png)

As you can see, the artificially extended plot has indeed extended the range of Scaffold 10, but this has only affected the region covered by links, and Scaffold 7 has been plotted just as long as before. This leads me to believe that there is a setting for overall haplotype length in the plotting code, and that it is this setting automatically stretching my scaffolds to full length, regardless of their actual size in the length file or the bed file.

@tanghaibao, is there a way to prevent the module plotting both chromosomes/scaffolds at artificially the same length? And instead plot them relative to each others lengths?

I am hoping to produce something like this:
![image](https://user-images.githubusercontent.com/52489932/175045869-29eac1e9-f2e8-40a1-b00b-782ac3fe03b5.png)

**Comment by mrmrwinter** [comment]
@tanghaibao, @ohdongha,

i have managed to do this programmatically with python.

```
df_lengths = "a tsv of scaffold names and their length"
top_pairings = "a dataframe of homeologous scaffolds, organised longest first"

for index, row in top_pairings.iterrows():                                                        # loop through top_pairings
    layout = row[0] + "." + row[1] + ".layout"                                                     # title of layout file
    a = int(df_length.loc[row[0],1])                                                                    # get length of longest scaffold
    b = int(df_length.loc[row[1],1])                                                                    # get length of shortest scaffold
    r = a/b                                                                                                         # determine ratio of the two lengths
    rell = str(0.8/r)                                                                                             # get length of shorter scaffold relative to the longer one
    with open (layout, "w+") as f:                                                                       # open new layout file
        f.write("# y, xstart, xend, rotation, color, label, va,  bed\n")                     # write the layout file
        f.write(".6, .1, " + rell + ", 0, , " + row[1] + ", top, " + row[1] + ".bed \n")  # shortest scaffold on top, with the calculated new length, rell
        f.write(".4, .1, .8, 0, , " + row[0] + ", bottom, " + row[0] + ".bed \n")         # longest scaffold below, at default length .8
        f.write("# edges\n")  
        f.write("e, 0, 1, " + row[0] + "." + row[1] + ".anchors.simple")
    f.close                                                                                                         # close the file
```

This is now creating plots that look like this, programmatically.

![image](https://user-images.githubusercontent.com/52489932/175295842-89cd5065-0709-4f19-92ce-1b0c3a306828.png)

Thank you both for all of your help!
