### ISSUE TITLE
microsynteny-multispecies microsynyeny

### ISSUE THREAD

**Issue by xhlin321** [tanghaibao/jcvi#477]
Hi,haibao!
   Thank you for the jcvi !   When I plot collinearity for multiple species,but the results seem to be the same .  And I added the gene ID, it  showed up in the multiple species. here is my file and the result! 
[3blocks.txt](https://github.com/tanghaibao/jcvi/files/8842887/3blocks.txt)
[allbed.txt](https://github.com/tanghaibao/jcvi/files/8842891/allbed.txt)
[blockslayout.txt](https://github.com/tanghaibao/jcvi/files/8842895/blockslayout.txt)
![@@92D@A3X2XE %0N(I9V5Y5](https://user-images.githubusercontent.com/101160438/172123227-6caefa43-057e-40a6-bbbf-d3cc6eeeb3d2.png)

**Comment by tanghaibao** [comment]
also note that you have multiple species sharing the same chromosome name like "Chr1", you may need to disambiguate in your `allbed.txt`. Otherwise, the genes from different tracks with the same chromosome name would be plotted over each other, like shown above..

**Comment by xhlin321** [comment]
thank you haibao !!! I changed the chromosome names like you said, it worked!
