### ISSUE TITLE
how to plot duplication result from iter=2?

### ISSUE THREAD

**Issue by zhidaobuzhidao** [tanghaibao/jcvi#479]
Hi, when I set "iter=2",the third column may be "."  When I run this command "python -m jcvi.graphics.synteny pic.block all.bed blocks.layout ". We cannot get the picture.

the block files：
Ag1A03G0004000.1.CS.mrna1_Species1      Ag1A03G0004000.1.CS.mrna1_Species2      .
evm.model.ctg1.17.mrna1_Species1    evm.model.ctg1.38.mrna1_Species2        evm.model.ctg120.537.mrna1_Species2
Ag1A03G0004200.3.CS.mrna1_Species1      Ag1A03G0004200.3.CS.mrna1_Species2      .
Ag1A03G0004400.1.CS.mrna1_Species1      Ag1A03G0004400.1.CS.mrna1_Species2      Ag1B03G0002200.1.CS.mrna1_Species2
Ag1A03G0004500.1.CS.mrna1_Species1      evm.model.ctg1.51.mrna1_Species2        Ag1D03G0000800.2.CS.mrna2_Species2

layout：：
# x,   y, rotation,   ha,     va,   color, ratio,               label
0.5, .90,        0, left, center,       m,     1,               Spe1
0.5, .80,        0, left, center,       m,     1,               Spe2
#edges
e,0,1

how to resolve this problem?

**Comment by tanghaibao** [comment]
@zhidaobuzhidao 

It doesn't matter if the column has "." - but all the genes in each column must be on the same contig/chromosome.
What was the error message?

**Comment by zhidaobuzhidao** [comment]
Thanks for reply!
the error message  is as follows:

[13:57:31] DEBUG    Load file `all.bed`                                                                                                            base.py:37
[13:57:34] DEBUG    Load file `1.block`                                                                                                            base.py:37
           DEBUG    Load file `test1.layout`                                                                                                       base.py:37
Column 0: Ag1A03G0004000.1.CS.mrna1Species1 - Ag1A03G0004500.1.CS.mrna1Species1 (Chr1ASpecies1:1198637-1235274)
  Chr1A_Species1 .. 5 (5) features .. +
Column 1: Ag1A03G0004000.1.CS.mrna1_Species2 - evm.model.ctg1.51.mrna1_Species2 (Chr1A_Species2:699361-744444)
  Chr1A_Species2 .. 7 (5) features .. +
Column 2: Ag1D03G0000800.2.CS.mrna2_Species2 - evm.model.ctg120.537.mrna1_Species2 (Chr1B_Species2:27941881-28037213)
  Chr1B_Species2 .. 4 (3) features .. -
Traceback (most recent call last):
  File "/conda/miniconda3/envs/jcvi/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/conda/miniconda3/envs/jcvi/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/conda/miniconda3/envs/jcvi/lib/python3.9/site-packages/jcvi/graphics/synteny.py", line 620, in <module>
    main()
  File "/conda/miniconda3/envs/jcvi/lib/python3.9/site-packages/jcvi/graphics/synteny.py", line 595, in main
    Synteny(
  File "/conda/miniconda3/envs/jcvi/lib/python3.9/site-packages/jcvi/graphics/synteny.py", line 412, in __init__
    lo[i],
IndexError: list index out of range

**Comment by tanghaibao** [comment]
@zhidaobuzhidao 

The issue is in the layout file (`blocks.layout`). There are only two lines (Spe1 and Spe2) before `#edges`, you need 3 to match the 3 columns in the blocks file (`pic.block`).

**Comment by zhidaobuzhidao** [comment]
I just found out that the genes in the third column aren't on the same chromosome.
If I want  to draw inter=2 for multiple species, the block file's 4,5 columns would be one species, the 6,7 columns would be anther species. Do I understand this correctly?
Thanks!

**Comment by zhidaobuzhidao** [comment]
Understand!!
I will try this join later.
You are right ! there is something wrong with the layout file.
block file :
Ag7B03G0358300.1.CS.mrna1_Species1      evm.model.ctg1261.110.mrna1_Species2    .
g*Ag7B03G0358400.1.CS.mrna1_Species1    Ag7B03G0358400.1.CS.mrna2_Species2      Ag7B03G0358400.1.CS.mrna1_Species2
Ag7B03G0358500.1.CS.mrna1_Species1      Ag7B03G0358500.1.CS.mrna2_Species2 
Ag7B03G0358600.1.CS.mrna1_Species1      Ag7B03G0358600.1.CS.mrna1_Species2      .

I want to emphasize the duplicated gene in second line.

The layout should be written like this:
# x,   y, rotation,   ha,     va,   color, ratio,               label
0.5, .90,        0, left, center,       m,     1,               Species1
0.5, .80,        0, left, center,       m,     1,               Species2
0.5, .80,        0, left, center,       m,     1,               Species2
#edges
e,0,1
e,0,2

Thank you very much for your reply!!!

**Comment by zhidaobuzhidao** [comment]
Is there any format explanation about layout file?

**Comment by zhidaobuzhidao** [comment]
There still some problems.
Is there any format explanation about layout file?
the picture ilooks like this:
![image](https://user-images.githubusercontent.com/35095417/172786615-1ce71922-9998-4d31-bfa3-a564f7e6452d.png)

**Comment by tanghaibao** [comment]
@zhidaobuzhidao 

You may want to tweak x, y to better position the `Species2` tracks in the layout file (see top row in the layout file for field names).
