### ISSUE TITLE
translating scaffold position to genomic position

### ISSUE THREAD

**Issue by Homap** [tanghaibao/jcvi#48]
Hi,

Would it be possible to direct me to the part of the script where the scaffold positions are translated to the genomic positions?

I have a set of genic coordinates of the scaffolds and I would like to translate them to the genomic position but as I have used allmaps for generating the final assembly, it is important that I use the same criteria as allmaps for translating new positions.

Thanks in advance!

**Comment by tanghaibao** [comment]
@Homap ALLMAPS translates coordinates through ``.chain`` file. Please see documentation on this [here](https://github.com/tanghaibao/jcvi/wiki/ALLMAPS%3A-How-to-lift-over-gene-annotations).

**Comment by Homap** [comment]
@tanghaibao Thanks, it worked very well!
