### ISSUE TITLE
Questions about macrosynteny visualization

### ISSUE THREAD

**Issue by Youpu-Chen** [tanghaibao/jcvi#481]
Hi, there.
I am using JCVI to conduct some synteny analysis and visualization based on one species/genome.

But I have some problems as described below.
The original, but painted/colored pdf was like:
![](https://user-images.githubusercontent.com/88021864/173737225-73aa4c79-7dcc-4013-afde-0288b87e82ee.png)

But when I changed the seqids file (removed some sequence and change the order), it missed some synteny relation, which is:
![](https://user-images.githubusercontent.com/88021864/173737513-a409f851-7f87-470a-b475-c52699130a5b.png)

I'll really appreciate it if you could give me a hint about how to solve the problem.

**Comment by Youpu-Chen** [comment]
Oh, I just found that I forgot to set the track1 in the layout.
Thanks for developing such a great tools.

**Comment by mrmrwinter** [comment]
Hi @Youpu-Chen,

Did you develop a programmatic way to colour anchors by associated chromosome? I'm hoping to do this myself but it is seeming more complicated than i previously thought, as the .simple file has no chromosome information.

Thanks
