### ISSUE TITLE
[Grabseed] Background color

### ISSUE THREAD

**Issue by wyim-pgl** [tanghaibao/jcvi#49]
Hello Haibao,

I have a suggestion regarding Grabseed background.

Grabseed shows color of seed and sometimes it grab the background as a seed.

 If user can define the background color as an input option, Grabseed can exclude the similar color based on their color name.

For example backgroud is blue (from user option) then Grabseed can exclude the similar color such as blue, royalblue, darkblue, lightblue and etcs from results.
https://en.wikipedia.org/wiki/Web_colors

I should move to Bay area to drink with you for weekend :)

Cheers,

**Comment by tanghaibao** [comment]
@ascendo good idea. I'll see what I can do on this. I'll keep this issue open for now.

**Comment by ascendo** [comment]
Alright!
