### ISSUE TITLE
Allmaps chromosome patch colours bug

### ISSUE THREAD

**Issue by jguppy** [tanghaibao/jcvi#490]
Hi,

When generating the plots from ALLMAPS I've notice that for chromosomes with a odd number of scaffolds (when n >1), that the last scaffold patch is always white, rather than grey as should be expected.

For example a chromosome with 3 scaffolds, is assigned patch colours in order of 'grey, white, white' currently.

For chromosomes with even number the colours are instead 'grey, white, ....' in a repeating pattern.

Having a quick look at the related code ALLMAPs code, this traces back to defining patch colour in [jcvi/graphics/chromosome.py](url) at Line 57 for vertical chromosomes and Line 132 for horizontal chromosomes.

For each patch (p1) the colour is defined as patch, while p2 is fill is left as false (the inherited default). To resolve this I think the colour of a p2 patch should instead be defined, avoiding adjacent white scaffolds. 

I have update the chromosome.py [chromosome.txt](https://github.com/tanghaibao/jcvi/files/9060947/chromosome.txt) (uploaded here as  [chromosome.txt](https://github.com/tanghaibao/jcvi/files/9060947/chromosome.txt)) script to do this when the number of scaffolds is odd. It seems to run ok now with my data.

**Comment by tanghaibao** [comment]
@jguppy 

thanks for the PR - there are some formatting issue that fails the tests.

Based on your changes, I had a slightly different fix but hopefully has the same effect. Let me know if it works for you.
