### ISSUE TITLE
Unable to install 

### ISSUE THREAD

**Issue by TommySalvetti01** [tanghaibao/jcvi#493]
I've currently tried to install jcvi but something has been alluding me. I have attempted to install using PyPi and conda and nothing has worked. When I tried with PyPi I get a "metadata-generation-failed" error. Any help would be appreciated! Thanks!

**Comment by tanghaibao** [comment]
@TommySalvetti01 

Would you please paste in the error logs when you run `pip install jcvi`? Thanks.

**Comment by TommySalvetti01** [comment]
Hi Prof. Tang. I managed to get JCVI installed, but thank you! I uninstalled and reinstalled conda, then I added the bioconda channel and it worked!
