### ISSUE TITLE
Report a problem about pad.py

### ISSUE THREAD

**Issue by LQHHHHH** [tanghaibao/jcvi#494]
Hi Haibao,

Thanks for providing JCVI. Recently I am trying to use ```python -m jcvi.compara.pad ``` to identify putative ancestral regions. However, an error ```TypeError: '>' not supported between instances of 'int' and 'str'``` occurred during running ```python -m jcvi.compara.pad cluster```. It may because in [jcvi/compara/pad.py](https://github.com/tanghaibao/jcvi/blob/main/jcvi/compara/pad.py) line 208 gives strings in b and i is an int. So I traced your old code (v1.1.11) and inserted ```a,b=pads[j]``` after lines 213 and 215 respectively. And it works. 

Then running ```python -m jcvi.compara.pad pad``` error ```TypeError: 'zip' object is not subscriptable ```  occurred in [jcvi/formats/cdt.py](https://github.com/tanghaibao/jcvi/blob/main/jcvi/formats/cdt.py) and can be solved by revising line 47 from ```self.anames =zip(aid, gid)[4:]``` to ```self.anames = list(zip(aid, gid))[4:]```.

After doing all above, the pipeline can be run from head to toe. But I don't know if the results are correct by adding the code by myself. By the way, I would be appreciate if you can explain the meaning of the results. I paste part of my results below:

```
Han_rev:04148-04543|Han_rev:09667-09864 Rag_rev:06429-06586|Rag_rev:15017-15061 170.21570267228037
Han_rev:03218-03473|Han_rev:18266-18341 Rag_rev:03027-03160 136.79261644081382
Han_rev:14806-15172 Rag_rev:01715-01862 129.3725354931103
Han_rev:20791-21179 Rag_rev:05759-05876|Rag_rev:06244-06428 287.5941667160763
Han_rev:39809-39946 Rag_rev:00757-00852 82.58212423492218
Han_rev:08858-08936 Rag_rev:06025-06082 81.73455257653757
Han_rev:37699-37918|Han_rev:38418-38465 Rag_rev:19471-19552 120.59692529844499
Han_rev:07541-07636|Han_rev:08586-08857|Han_rev:07637-07690|Han_rev:13476-13743 Rag_rev:14182-14288|Rag_rev:14289-14341 118.45426159129497
Han_rev:13149-13280|Han_rev:13281-13475|Han_rev:41992-42535 Rag_rev:13574-13822|Rag_rev:18730-18921 405.31433726808496
Han_rev:05783-05998|Han_rev:30366-30509 Rag_rev:11976-12043|Rag_rev:17861-17937 189.91526771827986
Han_rev:25265-25562|Han_rev:38267-38372 Rag_rev:17190-17321|Rag_rev:19199-19298 182.92099444686005
Han_rev:25702-25908 Rag_rev:17322-17411 124.52004423807162

```

**Comment by tanghaibao** [comment]
@LQHHHHH 

Thanks for the bug report. I think your fix looks good (and this is mostly due to the code written originally for Python 2).

However, the PAD method was originally written for constructing the pan-cereal WGD and there is no documentation. I'd suggest that you find an alternative tool for this task.

Haibao

**Comment by LQHHHHH** [comment]
Thanks for your suggestion.

Best
