### ISSUE TITLE
Citation?

### ISSUE THREAD

**Issue by erikvdbergh** [tanghaibao/jcvi#5]
Hello all,

This is not a real issue, but I have used the JCVI library for several analyses in my study and I was wondering what way you would prefer to be cited?

Thanks,
Erik

**Comment by tanghaibao** [comment]
Hi Erik,

Thanks for using the library. We've now added a DOI to the repo. You can click on the DOI badge [![DOI](https://zenodo.org/badge/doi/10.5281/zenodo.31631.svg)](http://dx.doi.org/10.5281/zenodo.31631) in the README.

Many thanks to @vivekkrish for the excellent idea of using Zenodo to generate DOI.

Thanks,
Haibao
