### ISSUE TITLE
MCScan microsynteny comparisons between multiple species

### ISSUE THREAD

**Issue by sjfleck** [tanghaibao/jcvi#506]
Thank you for such a useful tool. I'm trying to accomplish a microsynteny view similar to this:
![MCScan_TDC_Vitis_Camptotheca_Ophiorrhiza_Gardenia](https://user-images.githubusercontent.com/53409202/195744453-023bd9fa-b248-4ec6-b01e-6d912bcb76ea.png)

It differs from other issues, because this example is 3 separate pairwise syntenic comparisons combined. I want: A-B, B-C, C-D, D-E, and so on. In other examples, this is achieved by doing: A-B, A-C, A-D, A-E, and so on. It can be done by comparing everything to species A, but it's harder to get strong synteny between the comparisons that don't include A:
![example](https://user-images.githubusercontent.com/53409202/195744205-b00af6e8-06ae-4da2-ae3e-b060c80db69a.png)

The way I'm currently doing it is pretty time consuming and unfortunately results in some flipped sequences. It also makes it difficult to match font sizes, etc. Any help on this would be appreciated. Thanks!

EDIT: I realize I could leave off the labels and label the genes and species names separately in an editor after the fact for uniformity. If that's what I need to do, I'll do it that way

**Comment by yushengak47** [comment]
Yeah, I'm facing the same problem. I tried to do a series joining, i.e., first join A-B and B-C, got ABC, and then join ABC and C-D, got ABCD. Unfortunately, I found that, in this way, once a gene got no pairing gene in another species, seems it won't get pairing gene in all downstream-joined species. This is not the true case.

Is there special considerations that graphics.synteny requires a joined and 'pivot-wider' blocks file? Sometimes we don't want the joined result. How about accepting an input block table of four columns, the first two columns give pairing geneIds, the last two columns give species labels corresponding to the label strings used in the layout file? Any follow up would be appreciated. Thanks!

**Comment by tanghaibao** [comment]
@sjfleck @yushengak47 

Yes, I understand this problem. There is an undocumented script that helps assemble a set of regions into a `.blocks` file that can be plotted.

```console
python -m jcvi.compara.synteny assemble
Usage:
    synteny.py assemble regionsfile all.bed all.cds

    Assemble blocks file based on regions file. Regions file may look like:

    amborella evm_27.model.AmTr_v1.0_scaffold00004.87 evm_27.model.AmTr_v1.0_scaffold00004.204
    apostasia Ash010455 Ash010479 (fragScaff_scaffold_5)
    apostasia Ash018328 Ash018367 (original_scaffold_2912)
    apostasia Ash007533 Ash007562 (fragScaff_scaffold_132)
    apostasia Ash002281 Ash002299 (fragScaff_scaffold_86)

    Where each line lists a region, starting with the species name (species.bed
    must be present in the current directory). Followed by start and end gene.
    Contents after the 3rd field (end gene) are ignored. Using the example
    above, the final .blocks file will contain 5 columns, one column for each line.
```

Basically the input is a regions file with each row containing start and end gene, a concatenated `all.bed` and `all.cds` for all species involved. This command will run `LAST` on the fly and generate a `.blocks` file with your regions of interest.

I have used this command in the past in a few pubs yet have not extensively tested this. 

Haibao

**Comment by yushengak47** [comment]
I tried this script these days, it did a great job! Thank for your reply and providing this amazing tool, Haibao, really appreciated! You should have documented this script earlier, ^_^


YU Sheng

**Comment by jonnyPizza** [comment]
@yushengak47 @tanghaibao Have you been able to use this method on different regions of the same species? 

DEBUG    Load file `Digitalis_lanata.bed`                                                base.py:34
           DEBUG    Gene ids written to `/tmp/tmpehmxs89y/tmp8z6f7620`                          synteny.py:716
           DEBUG    A total of 404 records written to `/tmp/tmpehmxs89y/tmptcehsiym`             fasta.py:1859
           DEBUG    lastdb /tmp/tmpehmxs89y/tmptcehsiym /tmp/tmpehmxs89y/tmptcehsiym              base.py:1181
           DEBUG    lastal -u 0 -P 32 -i3G -f BlastTab /tmp/tmpehmxs89y/tmptcehsiym               base.py:1181
                    /tmp/tmpehmxs89y/tmptcehsiym >/tmp/tmpehmxs89y/tmptcehsiym.tmptcehsiym.last               
           DEBUG    Load file `/tmp/tmpehmxs89y/tmptcehsiym.tmptcehsiym.last`                       base.py:34
           DEBUG    Extracted 0 gene pairs from `/tmp/tmpehmxs89y/tmptcehsiym.tmptcehsiym.last` synteny.py:734
           DEBUG    Before compression: 0, After compression: 0  

I know these regions are syntenic but am not getting any gene pairs for outputs.

Jonathan

**Comment by Chenglin20170390** [comment]
> @yushengak47 @tanghaibao Have you been able to use this method on different regions of the same species?
> 
> DEBUG Load file `Digitalis_lanata.bed` base.py:34 DEBUG Gene ids written to `/tmp/tmpehmxs89y/tmp8z6f7620` synteny.py:716 DEBUG A total of 404 records written to `/tmp/tmpehmxs89y/tmptcehsiym` fasta.py:1859 DEBUG lastdb /tmp/tmpehmxs89y/tmptcehsiym /tmp/tmpehmxs89y/tmptcehsiym base.py:1181 DEBUG lastal -u 0 -P 32 -i3G -f BlastTab /tmp/tmpehmxs89y/tmptcehsiym base.py:1181 /tmp/tmpehmxs89y/tmptcehsiym >/tmp/tmpehmxs89y/tmptcehsiym.tmptcehsiym.last DEBUG Load file `/tmp/tmpehmxs89y/tmptcehsiym.tmptcehsiym.last` base.py:34 DEBUG Extracted 0 gene pairs from `/tmp/tmpehmxs89y/tmptcehsiym.tmptcehsiym.last` synteny.py:734 DEBUG Before compression: 0, After compression: 0
> 
> I know these regions are syntenic but am not getting any gene pairs for outputs.
> 
> Jonathan

Hi, Jonathan

   I have the same question.  It's may raise by non-synteny gene in your input regions. I solved this by change regions.
