### ISSUE TITLE
MCScan dotplot grid

### ISSUE THREAD

**Issue by kfuku52** [tanghaibao/jcvi#507]
Thanks to the helpful tutorial of MCScan, I was able to create a dot plot (below). However, the grid looks somewhat strange. Narrow grids are incorrectly inserted on the right-hand side of C3, C7, C10... and that of C18 even has a small duplicated label "C18". Looking back at the [tutorial](https://github.com/tanghaibao/jcvi/wiki/MCscan-(Python-version)), there seems to be a similar trend in the vertical grid lines (see the small C13 and C18 labels there). I might have missed something here, but is it intended behavior?

<img width="548" alt="image" src="https://user-images.githubusercontent.com/19270515/198066351-ef49a1c9-f4fc-4786-97ae-b0c2cd5983bb.png">

**Comment by tanghaibao** [comment]
@kfuku52 

These are quite common. Often this is due to "unplaced" scaffolds that are known to belong to a chromosome (e.g. C18) but do not know their precise locations.

Please print out a list of the sequence names from your FASTA file and you'll understand where these come from.

**Comment by kfuku52** [comment]
Thank a lot! I was not aware of this scaffold notation, but the narrow grids indeed come from unplaced sequences named `*_random`.
```
cut -f 1 Vitis_vinifera_Vvinifera-457-v2.1.gene-exons.gff3 | sort -u
##annot-version v2.1
##gff-version 3
##species Vitis vinifera
chr1
chr10
chr10_random
chr11
chr11_random
chr12
chr12_random
chr13
chr13_random
chr14
chr15
chr16
chr16_random
chr17
chr17_random
chr18
chr18_random
chr19
chr1_random
chr2
chr3
chr3_random
chr4
chr4_random
chr5
chr5_random
chr6
chr7
chr7_random
chr8
chr9
chr9_random
chrUn
```
