### ISSUE TITLE
Plot TEs in MCScan microsynteny ? 

### ISSUE THREAD

**Issue by amvarani** [tanghaibao/jcvi#508]
Hi there!
Simple question:
Is there any way to plot the TEs in the MCScan microsynteny ? 

Best

**Comment by wyim-pgl** [comment]
You could add bed file and it will show up as orange color.
Figure 3. in below paper.
https://www.nature.com/articles/nature15714

**Comment by amvarani** [comment]
Do you mean the flag:

  --extra=EXTRA         Extra features in BED format [default: none]

?

**Comment by wyim-pgl** [comment]
@amvarani Yes
