### ISSUE TITLE
docker build error, "Connection timed out"

### ISSUE THREAD

**Issue by scottcain** [tanghaibao/jcvi#509]
Hi,

Thanks so much for providing this excellent tool and a docker file to go along with it. I wanted to build the docker file for myself so that I could add a `/data` mount point, but when I build, I get this message:
```
Step 22/24 : RUN pip install git+git://github.com/tanghaibao/jcvi.git
 ---> Running in ece1cb04e6f4
Collecting git+git://github.com/tanghaibao/jcvi.git
  Cloning git://github.com/tanghaibao/jcvi.git to /tmp/pip-req-build-hf51vcd2
  Running command git clone -q git://github.com/tanghaibao/jcvi.git /tmp/pip-req-build-hf51vcd2
  fatal: unable to connect to github.com:
  github.com[0: 140.82.113.3]: errno=Connection timed out

WARNING: Discarding git+git://github.com/tanghaibao/jcvi.git. Command errored out with exit status 128: git clone -q git://github.com/tanghaibao/jcvi.git /tmp/pip-req-build-hf51vcd2 Check the logs for full command output.
ERROR: Command errored out with exit status 128: git clone -q git://github.com/tanghaibao/jcvi.git /tmp/pip-req-build-hf51vcd2 Check the logs for full command output.
The command '/bin/sh -c pip install git+git://github.com/tanghaibao/jcvi.git' returned a non-zero code: 1
```
Do you have any insights as to why this is happening?

Thanks,
Scott

**Comment by scottcain** [comment]
I should have added: I can certainly connect to github.com, so I don't think that is really the issue.

**Comment by scottcain** [comment]
I replaced the git-based pip install with a straight pip install:

RUN pip install jcvi

which will likely be good enough for me for the moment. I'll leave this open in case you'd like to comment, but feel free to quietly close it.

**Comment by tanghaibao** [comment]
@scottcain 

Thank you for suggesting a fix - I don't use docker often on jcvi, but have just now modified it accordingly
