### ISSUE TITLE
CSV input file

### ISSUE THREAD

**Issue by babbanicchio** [tanghaibao/jcvi#51]
Hi Haibao,
I'm using three linkage maps to improve a draft genome assembly. It's not clear for me if I can  use the CSV files containing all the linkage groups (one file for each map with all the 24 LGs)  or whether I have to split  LGs (producing a csv file for each LG)  and analyze them separately. 
I have also noticed that sometimes ALLMAPS clear all the temporary files in the working folder at the end of the analysis and sometimes not. Do you know why? 
Thanks a lot
Max

**Comment by tanghaibao** [comment]
@babbanicchio you can place all LGs in the same csv file. With regards to the temporary files, it depends whether certain step (like the TSP step) fails or not. If you save the run log, you should be able to tell. If you are able to see all the output (``lifted.bed``, ``agp``) then you are fine.

Haibao
