### ISSUE TITLE
ValueError: A total of 0 anchor was found——compare human with Distant species

### ISSUE THREAD

**Issue by MR-D-CJ** [tanghaibao/jcvi#511]
hi profesor:
thanks for u！
when i do synteny with human and Saccharomyces.cerevisiae,it return an error,like is
![image](https://user-images.githubusercontent.com/52587925/202831271-ab4566b9-ee95-44b3-8a2e-4616e207658c.png)
![image](https://user-images.githubusercontent.com/52587925/202831016-759d0f6d-25a9-4ea8-b3d1-7c5d7a95033b.png)
when i use the same code with other species,it work.I see it also generate `.last.filtered` and `.last`.
the `.last.filtered` document is as follow:
![image](https://user-images.githubusercontent.com/52587925/202831207-d8b7f274-0294-4ae0-a0f6-81ce6a95f0f0.png)
I also check the gene_ID in `.bed` and `.cds` is same.I guess it may the two species are distantly related, and i need to adjust some parameter?
Thanks!

**Comment by tanghaibao** [comment]
@MR-D-CJ 

The lack of synteny between human and yeast genomes is expected due to the evolutionary distance (~ 1 billion years).
Something closer like human-mouse, or human-chicken, the signal would be more abundant. 
Usually, genomic synteny is much weaker beyond ~100 million years divergence due to the chance of shuffling events.

**Comment by MR-D-CJ** [comment]
Thanks for your answer!
Dose the jcvi judges have a synteny block between two species base on certain number of homologous genes contained in this block?What's the minimum number of gene in a synteny block.
**Because i have some gene and want to see the location of homologous genes in yeast**

**Comment by tanghaibao** [comment]
Default is 4 genes in a block.

```console
  -n N, --min_size=N    Minimum number of anchors in a cluster [default: 4]
```

**Comment by MR-D-CJ** [comment]
ok, thank you, i'll try it
