### ISSUE TITLE
Downloaded all previous version when install with pip

### ISSUE THREAD

**Issue by xunsheng** [tanghaibao/jcvi#517]
Dear JCVI Developer,

Nice tool for comparative genomics!

I have tried pip install, and noticed that it tried to download older versions before installation (log below). Just want to let you know if that's really needed. 

Thanks!
Best,
Lijing

  Downloading jcvi-1.1.21.tar.gz (796 kB)
     ���������������������������������������� 796.3/796.3 kB 40.9 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
  Downloading jcvi-1.1.20.tar.gz (795 kB)
     ���������������������������������������� 795.3/795.3 kB 38.1 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
  Downloading jcvi-1.1.19.tar.gz (795 kB)
     ���������������������������������������� 795.3/795.3 kB 36.1 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
  Downloading jcvi-1.1.18.tar.gz (795 kB)
     ���������������������������������������� 795.3/795.3 kB 36.3 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
  Downloading jcvi-1.1.17.tar.gz (795 kB)
     ���������������������������������������� 795.9/795.9 kB 36.3 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
  Downloading jcvi-1.1.16.tar.gz (795 kB)
     ���������������������������������������� 795.8/795.8 kB 39.9 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
  Downloading jcvi-1.1.15.tar.gz (794 kB)
     ���������������������������������������� 794.8/794.8 kB 18.1 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
  Downloading jcvi-1.1.14.tar.gz (794 kB)
     ���������������������������������������� 794.8/794.8 kB 42.6 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
  Downloading jcvi-1.1.13.tar.gz (799 kB)
     ���������������������������������������� 799.2/799.2 kB 43.3 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
  Downloading jcvi-1.1.12.tar.gz (820 kB)
     ���������������������������������������� 820.6/820.6 kB 46.9 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
  Downloading jcvi-1.1.11.tar.gz (820 kB)
     ���������������������������������������� 820.5/820.5 kB 42.3 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
  Downloading jcvi-1.1.10.tar.gz (819 kB)
     ���������������������������������������� 819.6/819.6 kB 42.6 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
  Downloading jcvi-1.1.9.tar.gz (819 kB)
     ���������������������������������������� 819.6/819.6 kB 37.6 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
  Downloading jcvi-1.1.8.tar.gz (819 kB)
     ���������������������������������������� 819.3/819.3 kB 41.9 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
  Downloading jcvi-1.1.7.tar.gz (819 kB)
     ���������������������������������������� 819.3/819.3 kB 35.5 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
  Downloading jcvi-1.1.6.tar.gz (818 kB)
     ���������������������������������������� 818.4/818.4 kB 35.7 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
  Downloading jcvi-1.1.5.tar.gz (821 kB)
     ���������������������������������������� 821.8/821.8 kB 15.2 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
  Downloading jcvi-1.1.4.tar.gz (820 kB)
     ���������������������������������������� 820.9/820.9 kB 41.7 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Collecting rich
  Downloading rich-12.6.0-py3-none-any.whl (237 kB)
     ���������������������������������������� 237.5/237.5 kB 17.8 MB/s eta 0:00:00

**Comment by tanghaibao** [comment]
@xunsheng 

This is weird. I can't seem to reproduce it on my mac or Linux box.

What happens if you try `pip install -U jcvi` (U for upgrade)?
