### ISSUE TITLE
Interpretation of Tandem files

### ISSUE THREAD

**Issue by fafuyyk** [tanghaibao/jcvi#518]
Hello Haibao,
I have two questions. One is that I got a tandem file with MCScanX, but I don't know how to interpret it. I have not received a reply to the email I sent to the author. I found that you are also one of the authors, so I ask for advice here.
The second is that I have used jcvi many times in my work, but I found that it seems to have not been published, so should I use MCScan or MCScanX when citing?

**Comment by fafuyyk** [comment]
This is result!
![WNYMZ)~S}BB$3$25SJ35_)O](https://user-images.githubusercontent.com/55135744/203972782-9614dc91-7b02-4fba-9480-de7c379fd067.png)

**Comment by tanghaibao** [comment]
@fafuyyk 

The tandem files are lists of tandemly duplicated genes, one group per line.

For example, the first line says the genes `...1650` and `...1660` are duplicate genes - you can also see that they are next to each other.

Regarding whether you cite MCScan/MCScanX, it depends on which program you actually used to produce results in your paper.

For MCscan, please cite:
Tang et al. (2008) Synteny and Collinearity in Plant Genomes. [Science](https://science.sciencemag.org/content/320/5875/486)
