### ISSUE TITLE
graphics.synteny 如何更改染色体之间线的粗细和颜色

### ISSUE THREAD

**Issue by shuazhenyang** [tanghaibao/jcvi#530]
您好，我想请问是否有办法更改graphics.synteny 绘制的结果图里的连接线的粗细和颜色
![image](https://user-images.githubusercontent.com/120489302/207377302-3b192ea3-2aab-4680-9b1f-5db74f564168.png)

**Comment by shuazhenyang** [comment]
即这个绿线的颜色和粗细

**Comment by shuazhenyang** [comment]
![image](https://user-images.githubusercontent.com/120489302/207537310-655fa61d-a6c7-4d53-a78c-dfcb7ac17e40.png)
我已经找到如何更改颜色，那么如何更改线的粗细呢

**Comment by tanghaibao** [comment]
粗细是基因大小决定的（即上图中绿盒子的宽度）。连接两个基因的不是一根“线”，而是一个平滑边的“梯形”。
有一个参数可以试试，这个控制“梯形”边缘的宽度，默认是1，可以试下0。

https://github.com/tanghaibao/jcvi/blob/0726c3941cf3266d2a6cf582058546629a7205f3/jcvi/graphics/synteny.py#L127

**Comment by shuazhenyang** [comment]
非常感谢您的帮助，这个问题被解决了，感谢您百忙之中回复我

**Comment by wrmlight** [comment]
老师您好，关于“graphics.synteny 如何更改染色体之间线的粗细和颜色”这个问题，您说的是使用相应颜色的缩写，是不是只有一些简单的颜色能用，比如红橙黄绿蓝这种，如果要使用亮蓝色(light blue),输入lb是不是不能识别？
