### ISSUE TITLE
question in jcvi.assembly.kmer

### ISSUE THREAD

**Issue by xingjianfeng100** [tanghaibao/jcvi#531]
Hi @tanghaibao ,
I have got the strange Kmer graph, does this account for the complexity of this plant genome or contaminate of the illumina data? And the vertical dashed line marked with CN*, the dashed curve and green strip, what do they mean, respectively? Thank you!
![kmer_stats](https://user-images.githubusercontent.com/34566522/208011281-962810c2-1901-4ba2-9a7d-c3c553ae6e32.jpg)

**Comment by tanghaibao** [comment]
The K-mer graph has inferred that this genome is a tetraploid, since there is not just a single peak, but multiple peaks.
CN1 - 4 are copy numbers. For example 10.9% of the genome is single copy, ... 7.3 % of genome is 4 copies, the rest are >= 4 copies (repeats).
