### ISSUE TITLE
Parsing error for *cds_from_genomic.fna.gz from NCBI's Genome database 

### ISSUE THREAD

**Issue by gunjanpandey** [tanghaibao/jcvi#533]
I downloaded the following cognate gff and cds files from GenBank's refseq ftp site.  

`https://ftp.ncbi.nlm.nih.gov/genomes/refseq/invertebrate/Bactrocera_tryoni/representative/GCF_016617805.1_CSIRO_BtryS06_freeze2/GCF_016617805.1_CSIRO_BtryS06_freeze2_genomic.gff.gz

https://ftp.ncbi.nlm.nih.gov/genomes/refseq/invertebrate/Bactrocera_tryoni/representative/GCF_016617805.1_CSIRO_BtryS06_freeze2/GCF_016617805.1_CSIRO_BtryS06_freeze2_cds_from_genomic.fna.gz`

these files have the following structure which is default for NCBI's RefSeq Genome database.

`NC_065919.1     Gnomon  gene    7       819     .       -       .       ID=gene-LOC126767602;Dbxref=GeneID:126767602;Name=LOC126767602;description=uncharacterized LOC126767602;gbkey=Gene;gene=LOC126767602;gene_biotype=lncRNA`

`>lcl|NC_062139.1_cds_YP_010328127.1_25553 [gene=ND4] [locus_tag=MUR92_mgp05] [db_xref=GeneID:71473019] [protein=NADH dehydrogenase subunit 4] [protein_id=YP_010328127.1] [location=complement(8264..9604)] [gbkey=CDS]`

I tried to reformat the *.fna and generate *.bed file but it is not working

Command used was `python -m jcvi.formats.fasta format *cds_from_genomic.fna.gz out.cds ` But the output names are not matching the extracted bed file that came out of the command `python -m jcvi.formats.gff bed --type=mRNA --key=Name *.gff -o out.bed`

The out.cds fasta header looks like 
`>lcl|NC_065919.1_cds_XP_050340999.1_1 [gene=LOC126767570] [db_xref=GeneID:126767570] [protein=glycogen [starch] synthase] [protein_id=XP_050340999.1] [location=join(7698..8124,8200..8273,8538..9010,9073..9475,9545..10009,10073..10208,10265..10356)] [gbkey=CDS]` 

while the out.bed looks like this 
`NC_062139.1     272     1295    mrna_416380     0       +`

It looks the cds fasta is not getting formatted correctly. Could you please tell how to fix it?
or a better way for generating these files from the NCBI RefSeq Genome's ftp site as above?

**Comment by tanghaibao** [comment]
@gunjanpandey 

It is sometimes easier to use GFF and the genome sequence and extract the mRNA sequence so the names might match.

```console
python -m jcvi.formats.gff load genome.gff genome.fa -o genome.cds --id_attribute=Name
```

Note that the `--key` from GFF formatting and `--id_attribute` here should match, in this case, both uses the `Name` field.

**Comment by gunjanpandey** [comment]
@tanghaibao Thank you very much. It works now. 
Could you please help me understand how can I draw:
> 1. different chromosomes with different colors 
> 2. different links with different colors
> 3. show invested links with a different color

**Comment by tanghaibao** [comment]
@gunjanpandey 

1. Not supported.
2. Not supported.
3/4. Details [here](https://github.com/tanghaibao/jcvi/wiki/MCscan-(Python-version)#macrosynteny-visualization). You need to enter add the colors in front of the block in the `.simple` file.
5. Not supported to hide just the middle row. You can turn all labels off by `--nocircles`.

Haibao
