### ISSUE TITLE
compara catalog.py error

### ISSUE THREAD

**Issue by ABDULLAHGUJJAR** [tanghaibao/jcvi#539]
Hi Tanghaibao
i am using last version 
lastal 874
I installed through conda

But still showing error with 0 Anchor out put. 
can you guide me about this?

[10:37:33] DEBUG    File `peach.prj` found. Computation skipped.                                                    base.py:1353
           DEBUG    lastal -u 0 -P 8 -i3G -f BlastTab peach grape.cds >./grape.peach.last                           base.py:1181
lasta     DEBUG    Assuming --qbed=grape.bed --sbed=peach.bed                                                    synteny.py:496
           DEBUG    Load file `grape.bed`                                                                             base.py:34
           DEBUG    Load file `peach.bed`                                                                             base.py:34
[10:37:34] DEBUG    Load BLAST file `grape.peach.last` (total 0 lines)                                         blastfilter.py:46
           DEBUG    Load file `grape.peach.last`                                                                      base.py:34
           DEBUG    running the cscore filter (cscore>=0.70) ..                                               blastfilter.py:108
           DEBUG    after filter (0->0) ..                                                                    blastfilter.py:110
           DEBUG    running the local dups filter (tandem_Nmax=10) ..                                         blastfilter.py:115
           DEBUG    after filter (0->0) ..                                                                    blastfilter.py:155
           DEBUG    Assuming --qbed=grape.bed --sbed=peach.bed                                                    synteny.py:496
           DEBUG    Load file `grape.bed`                                                                             base.py:34
           DEBUG    Load file `peach.bed`                                                                             base.py:34
           DEBUG    Load file `grape.peach.last.filtered`                                                             base.py:34
           DEBUG    A total of 0 BLAST imported from `grape.peach.last.filtered`.                                 synteny.py:383
           DEBUG    Chaining distance = 20                                                                       synteny.py:1928
           DEBUG    Load file `grape.peach.anchors`                                                                   base.py:34
           DEBUG    A total of 0 anchor was found. Aborted.l: I was installed here with multi-threading disabled
      
please give me suggestion to solve this problem

**Comment by SAMANDOLL** [comment]
Hi 
I am also facing the same problem.
I have tried reinstalling jcvi and conda but the error is the same.

**Comment by jacquelinemattos** [comment]
Hi,
I am also facing the same problem.
Anyone knows how to solve it? 
Thanks!

**Comment by ABDULLAHGUJJAR** [comment]
I have solved this error by uninstall lastal and again install lastal. After that its working now. Thanks
________________________________
