### ISSUE TITLE
Whether each square represents a gene？

### ISSUE THREAD

**Issue by xiaoguizz** [tanghaibao/jcvi#540]
when I running microsynteny，I have 20 genes for one of my species, but 30 squares in the results.

**Comment by tanghaibao** [comment]
@xiaoguizz 

Sounds like a bug. Can you print out the gene labels for your 30 genes and see what names they have?
Instructions in [wiki](https://github.com/tanghaibao/jcvi/wiki)

<img width="937" alt="image" src="https://user-images.githubusercontent.com/106987/218219338-ed60f0b7-2a79-4ff5-8645-82e049bab97e.png">
