### ISSUE TITLE
problem with synteny analysis 

### ISSUE THREAD

**Issue by olisubo** [tanghaibao/jcvi#55]
Hi 

I'm trying to do a synteny comparison between physcomitrella and selaginella. I download the data and convert it as in the tutorial. When running python -m jcvi.compara.catalog ortholog i get the following error.

$ python -m jcvi.compara.catalog ortholog patens selaginella
11:47:18 [driver] Generating grammar tables from /usr/lib/python2.7/lib2to3/Grammar.txt
11:47:18 [driver] Generating grammar tables from /usr/lib/python2.7/lib2to3/PatternGrammar.txt
11:47:18 [base] lastdb selaginella selaginella.cds
11:47:30 [base] lastal -u 0 -P 1 -i3G -f BlastTab selaginella patens.cds >patens.selaginella.last
11:54:04 [synteny] Assuming --qbed=patens.bed --sbed=selaginella.bed
11:54:04 [base] Load file `patens.bed`
11:54:05 [base] Load file `selaginella.bed`
11:54:05 [blastfilter] Load BLAST file `patens.selaginella.last` (total 423596 lines)
11:54:05 [base] Load file `patens.selaginella.last`
11:54:08 [blastfilter] Pp3c8_25090V3 not in patens.bed
11:54:08 [blastfilter] Pp3c8_25090V3 not in patens.bed
11:54:08 [blastfilter] Pp3c24_20910V3 not in patens.bed
11:54:08 [blastfilter] Pp3c24_20910V3 not in patens.bed
...
11:54:08 [blastfilter] too many warnings.. suppressed
11:54:08 [blastfilter] running the cscore filter (cscore>=0.70) ..
11:54:08 [blastfilter] after filter (0->0) ..
11:54:08 [blastfilter] running the local dups filter (tandem_Nmax=10) ..
11:54:08 [blastfilter] after filter (0->0) ..
11:54:09 [synteny] Assuming --qbed=patens.bed --sbed=selaginella.bed
11:54:09 [base] Load file `patens.bed`
11:54:10 [base] Load file `selaginella.bed`
11:54:10 [base] Load file `patens.selaginella.last.filtered`
11:54:10 [synteny] A total of 0 BLAST imported from `patens.selaginella.last.filtered`.
11:54:10 [synteny] Chaining distance = 20
11:54:10 [base] Load file `patens.selaginella.anchors`
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/local/lib/python2.7/dist-packages/jcvi/compara/catalog.py", line 811, in <module>
    main()
  File "/usr/local/lib/python2.7/dist-packages/jcvi/compara/catalog.py", line 73, in main
    p.dispatch(globals())
  File "/usr/local/lib/python2.7/dist-packages/jcvi/apps/base.py", line 87, in dispatch
    globals[action](sys.argv[2:])
  File "/usr/local/lib/python2.7/dist-packages/jcvi/compara/catalog.py", line 646, in ortholog
    "--liftover={0}".format(last)])
  File "/usr/local/lib/python2.7/dist-packages/jcvi/compara/synteny.py", line 1464, in scan
    summary([anchor_file])
  File "/usr/local/lib/python2.7/dist-packages/jcvi/compara/synteny.py", line 1042, in summary
    nranchors = [_score(c) for c in clusters]  # non-redundant anchors
  File "/usr/local/lib/python2.7/dist-packages/jcvi/compara/synteny.py", line 260, in _score
    x, y = zip(*cluster)[:2]
ValueError: need more than 0 values to unpack

I suspect it's a mistake with naming. it reads the ID's as for example Pp3c8_25090V3 whereas in the bed file it looks like this

$ head patens.bed
Chr01	8930	13135	Pp3c1_20V**3.1**	0	+
Chr01	8934	13028	Pp3c1_20V**3.2**	0	+
Chr01	16795	21548	Pp3c1_40V**3.2**	0	+
Chr01	18887	19968	Pp3c1_40V3.1	0	+
Chr01	20197	21468	Pp3c1_50V3.1	0	+

Any ideas?

**Comment by tanghaibao** [comment]
@olisubo the BLAST parser automatically strips names after the "." - One solution is to create a new bed file with gene names without the .1 or .2 - you can perhaps just extract the .1 lines and then remove the .1 part. Are .1 and .2 represent isoforms?

Haibao

**Comment by ascendo** [comment]
For me the easist way is at vim, try this %s/\.\d*//gc

**Comment by olisubo** [comment]
Yes, that helped

Thanks!
