### ISSUE TITLE
bug for jcvi.graphics.synteny model

### ISSUE THREAD

**Issue by DengHAU** [tanghaibao/jcvi#554]
Hi,

This is my bed file:
chr10	1713499	1725421	Zm00039ab413550	0	+  ##Oh43 6 gene features
chr10	1845553	1846949	Zm00039ab413650	0	-
chr10	1909509	1914900	Zm00039ab413670	0	-
chr10	2694642	2697486	Zm00039ab414010	0	+
chr10	2702354	2703624	Zm00039ab414020	0	+
chr10	2781682	2785271	Zm00039ab414050	0	+

chr10	1698884	1705910	Zm00098aa038316_T001	0	+   ## OH43 3 features
chr10	2721880	2728625	Zm00098aa038349_T001	0	+
chr10	2809070	2816971	Zm00098aa038351_T001	0	+

This is my blocks:
Zm00039ab413550	Zm00098aa038316_T001
Zm00039ab413650	Zm00098aa038316_T001
Zm00039ab413670	Zm00098aa038316_T001
Zm00039ab414010	Zm00098aa038349_T001
Zm00039ab414020	Zm00098aa038349_T001
Zm00039ab414050	Zm00098aa038351_T001

layout:
#x,     y,      rotation,       ha,     va,     color,  ratio,  label
0.5,    0.9,    0,      right,  center, ,       1,      Oh43
0.5,    0.7,    0,      left,   center, ,       1,      OH43
#edges
e,      0,      1

The generated PDF is wired. Only 3 OH43 gene features in bed file, but the plotting in OH43 genome has 9 gene feature. It seems that all gene features in bed file was  treated as OH43 genes.
![20230325183700](https://user-images.githubusercontent.com/29788898/227712120-8cd8391a-dcfe-4709-8404-3fbea2a4a3a3.png)

I have re-run this model with different bed files and blocks files, this problems is always there.

Any suggestion?

**Comment by tanghaibao** [comment]
@DengHAU 

Would you please add `--genelabelsize=10` to the command and see what the gene names are?
I suspect that since both tracks are `chr10`, for some reason the script gets confused about where to plot the genes.

**Comment by DengHAU** [comment]
Yes, this issue was caused by the use of the same tracks.
![20230327092036](https://user-images.githubusercontent.com/29788898/227819384-487b43ca-c0d2-4022-96a9-3f3067961677.png)

**Comment by tanghaibao** [comment]
@DengHAU 

Thank you! very helpful.
Would you forwarding me your input (or a portion of it)? I'll get this fixed asap.

Haibao

**Comment by DengHAU** [comment]
Yes, I am glad to share my input file.
I was unable to successfully upload the file via GitHub, so I sent it to you via your Gmail. Hope it can help.
