### ISSUE TITLE
LayoutLine' object has no attribute 'color'

### ISSUE THREAD

**Issue by Zefeng-Wu** [tanghaibao/jcvi#56]
#y,xstart,xend,rotation,color,label,va,bed
.6,.1,.8,0,m,Grape,top,rice.bed
.4,.1,.8,0,k,Peach,top,ara.bed
#edges
e,0,1,rice.ara.anchors.simple

**Comment by ascendo** [comment]
Check the rice.ara.anchors.simple file

**Comment by Zefeng-Wu** [comment]
Thanks,but this file seems right.
###
OS01G0901000	OS01G0908700	AT1G67530	AT1G67800	38	+
OS01G0847600	OS01G0856500	AT2G37790	AT2G38120	44	+
OS01G0844200	OS01G0854000	AT2G39705	AT2G39980	49	+
OS01G0836600	OS01G0842200	AT2G37360	AT2G37650	38	+
OS01G0818100	OS01G0832900	AT2G40120	AT2G40815	88	-
OS01G0846800	OS01G0851400	AT3G53830	AT3G54130	33	+

**Comment by ascendo** [comment]
seqids and  head of rice.bed ?

**Comment by Zefeng-Wu** [comment]
seqids:
1,2,3,4,5,6,7,8,9,10,11,12
1,2,3,4,5

rice.bed:
1	2983	10815	OS01G0100100	0	+
1	11218	12435	OS01G0100200	0	+
1	11372	12284	OS01G0100300	0	-
1	12721	15685	OS01G0100400	0	+
1	12808	13978	OS01G0100466	0	-
1	16399	20144	OS01G0100500	0	+
1	22841	26892	OS01G0100600	0	+

**Comment by ascendo** [comment]
Ref [#20](https://github.com/tanghaibao/jcvi/issues/20)

Please remove the bottom blank line in "layout" file.

**Comment by Zefeng-Wu** [comment]
I have tried, but it gave these error
File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/local/lib/python2.7/dist-packages/jcvi-0.7.3-py2.7.egg/jcvi/graphics/karyotype.py", line 320, in <module>
    main()
  File "/usr/local/lib/python2.7/dist-packages/jcvi-0.7.3-py2.7.egg/jcvi/graphics/karyotype.py", line 308, in main
    Karyotype(fig, root, seqidsfile, layoutfile)
  File "/usr/local/lib/python2.7/dist-packages/jcvi-0.7.3-py2.7.egg/jcvi/graphics/karyotype.py", line 265, in __init__
    t = layout[i]
IndexError: list index out of range

**Comment by Zefeng-Wu** [comment]
Thank you very much , i have success

**Comment by ascendo** [comment]
IndexError: list index out of range

= Bottom blank line in "Seqids" file

**Comment by Zefeng-Wu** [comment]
Yeah, i have noticed it, tks
