### ISSUE TITLE
Self comparison bug

### ISSUE THREAD

**Issue by AzumaSerenThePatriot** [tanghaibao/jcvi#567]
I'm using the jcvi.compara.catalog module to generate synteny comparison. It works well with comparison between species, but when I do self-comparison within one genome like this, it comes out with error:

python3 -m jcvi.compara.catalog ortholog  --no_strip_names R22 R22
[03:42:03] DEBUG    File `R22.R22.last` found. Computation skipped.                                                       base.py:1367
[03:42:04] DEBUG    Assuming --qbed=R22.bed --sbed=R22.bed                                                              synteny.py:390
           DEBUG    Looks like self-self comparison.                                                                    synteny.py:403
           DEBUG    Load file `R22.bed`                                                                                     base.py:34
           DEBUG    Load file `R22.bed`                                                                                     base.py:34
Traceback (most recent call last):
  File "/my/software/Python-3.9.6/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/my/software/Python-3.9.6/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/my/software/Python-3.9.6/lib/python3.9/site-packages/jcvi/compara/catalog.py", line 965, in <module>
    main()
  File "/my/software/Python-3.9.6/lib/python3.9/site-packages/jcvi/compara/catalog.py", line 79, in main
    p.dispatch(globals())
  File "/my/software/Python-3.9.6/lib/python3.9/site-packages/jcvi/apps/base.py", line 110, in dispatch
    globals[action](sys.argv[2:])
  File "/my/software/Python-3.9.6/lib/python3.9/site-packages/jcvi/compara/catalog.py", line 713, in ortholog
    blastfilter_main(dargs)
  File "/my/software/Python-3.9.6/lib/python3.9/site-packages/jcvi/compara/blastfilter.py", line 322, in main
    blastfilter_main(blastfile, p, opts)
  File "/my/software/Python-3.9.6/lib/python3.9/site-packages/jcvi/compara/blastfilter.py", line 44, in blastfilter_main
    fp = open(blast_file)
**FileNotFoundError: [Errno 2] No such file or directory: 'R22.R22.last.P98L0.inverse'**

Interestingly, there's a file named 'R22.R22.last.P98.0L0.inverse' generated, and as I renamed it with 'R22.R22.last.P98L0.inverse' and run comparison again, it worked. So it should be a bug?

**Comment by dwpeng** [comment]
It looks like an f-string formatting error. `self_remove` is a float type value and it's default value is 98, but while doing formatting, it will be `98.0`.

```py
# https://github1s.com/tanghaibao/jcvi/blob/main/jcvi/compara/catalog.py#L645-L650
p.add_option(
    "--self_remove",
    default=98,
    type="float",
    help="Remove self hits that are above this percent identity",
)

# https://github1s.com/tanghaibao/jcvi/blob/main/jcvi/compara/catalog.py#L696-L703
self_remove = opts.self_remove
if a == b:
    lastself = last + f".P{self_remove}L0.inverse"
    if need_update(last, lastself, warn=True):
        filter(
            [last, "--hitlen=0", f"--pctid={self_remove}", "--inverse", "--noself"]
        )
    last = lastself
```

**Comment by dwpeng** [comment]
```py
import optparse
parser = optparse.OptionParser()

parser.add_option(
    '-f',
    '--float',
    default=98,
    type='float'
)

if __name__ == '__main__':
    options, args = parser.parse_args([
        '-f', '98'
    ])
    f = options.float
    print(f'float is : {f}')
    # float is : 98.0

    options, args = parser.parse_args()
    f = options.float
    print(f'float is : {f}')
    # float is : 98

    print(f'float is : {float(options.float)}')
    # float is : 98.0
```
While using default value, optparse would not convert value type, only convert value type when pass args. So I think just ensure float type value always float type by float functoin can fix the bug.

```diff
# https://github1s.com/tanghaibao/jcvi/blob/main/jcvi/compara/catalog.py#L696-L703
self_remove = opts.self_remove
if a == b:
-   lastself = last + f".P{self_remove}L0.inverse"
+   lastself = last + f".P{float(self_remove)}L0.inverse"
    if need_update(last, lastself, warn=True):
        filter(
            [last, "--hitlen=0", f"--pctid={self_remove}", "--inverse", "--noself"]
        )
    last = lastself
```

**Comment by tanghaibao** [comment]
@dwpeng 

This is a recent regression and a bug - thanks for reporting. I'll pull your change and fix accordingly.
