### ISSUE TITLE
agp swap fails

### ISSUE THREAD

**Issue by splaisan** [tanghaibao/jcvi#57]
Hi,
It seems I cannot swap a AGP files which works fine for chain fromagp.
Could you please help me find out what is wrong here.
I paste below the top of my AGP for the first two records.

`python -m jcvi.formats.agp swap test.agp` (JCVI utility libraries v0.7.3)

```
##agp-version   2.0
# Organism:  
# Platform:     
# Model:        
# Enzyme(s):    
# BioSample:    
# BioProject:   
# Obj_Name      Obj_Start       Obj_End PartNum Compnt_Type     CompntId_GapLength      CompntStart_GapType     CompntEnd_Linkage       Orientation_LinkageEvidence
Super-Scaffold_2        1       634629  1       W       000000F_018_pilon       1       634629  +
Super-Scaffold_4        1       1183857 1       W       000060F_pilon   1       1183857 +
Super-Scaffold_4        1183858 1184356 2       N       499     scaffold        yes     map
Super-Scaffold_4        1184357 1526320 3       W       000238F_pilon   301099  643062  +
Super-Scaffold_4        1526321 1526819 4       N       499     scaffold        yes     map
Super-Scaffold_4        1526820 2029751 5       W       000133F_001_pilon       1       502932  -
Super-Scaffold_4        2029752 2035765 6       N       6014    scaffold        yes     map
Super-Scaffold_4        2035766 2207240 7       W       001674F_pilon   1       171475  +
Super-Scaffold_4        2207241 2207739 8       N       499     scaffold        yes     map
Super-Scaffold_4        2207740 2779450 9       W       000000F_pilon   242991  814701  -
Super-Scaffold_4        2779451 2779949 10      N       499     scaffold        yes     map
Super-Scaffold_4        2779950 4500618 11      W       000000F_050_pilon       1       1720669 -
Super-Scaffold_4        4500619 4507675 12      N       7057    scaffold        yes     map
Super-Scaffold_4        4507676 4667134 13      W       001817F_pilon   1       159459  +
Super-Scaffold_4        4667135 4667633 14      N       499     scaffold        yes     map
Super-Scaffold_4        4667634 5570684 15      W       000000F_039_pilon       1       903051  -
```

returns:

```
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/local/lib/python2.7/dist-packages/jcvi/formats/agp.py", line 1824, in <module>
    main()
  File "/usr/local/lib/python2.7/dist-packages/jcvi/formats/agp.py", line 741, in main
    p.dispatch(globals())
  File "/usr/local/lib/python2.7/dist-packages/jcvi/apps/base.py", line 87, in dispatch
    globals[action](sys.argv[2:])
  File "/usr/local/lib/python2.7/dist-packages/jcvi/formats/agp.py", line 978, in swap
    agp = AGP(agpfile)
  File "/usr/local/lib/python2.7/dist-packages/jcvi/formats/agp.py", line 219, in __init__
    self.append(AGPLine(row, validate=validate))
  File "/usr/local/lib/python2.7/dist-packages/jcvi/formats/agp.py", line 65, in __init__
    self.object_beg = int(atoms[1])
IndexError: list index out of range
```

A different but not more clear error occurs when I run on the full data

```
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/local/lib/python2.7/dist-packages/jcvi/formats/agp.py", line 1824, in <module>
    main()
  File "/usr/local/lib/python2.7/dist-packages/jcvi/formats/agp.py", line 741, in main
    p.dispatch(globals())
  File "/usr/local/lib/python2.7/dist-packages/jcvi/apps/base.py", line 87, in dispatch
    globals[action](sys.argv[2:])
  File "/usr/local/lib/python2.7/dist-packages/jcvi/formats/agp.py", line 979, in swap
    agp.sort(key=lambda x: (x.component_id, x.component_beg))
  File "/usr/local/lib/python2.7/dist-packages/jcvi/formats/agp.py", line 979, in <lambda>
    agp.sort(key=lambda x: (x.component_id, x.component_beg))
AttributeError: 'AGPLine' object has no attribute 'component_beg'
```
**I get the same error with AGP sample 'Scaffold from component (WGS)' from https://www.ncbi.nlm.nih.gov/assembly/agp/AGP_Specification/scaffold_from_contig_WGS.agp.v2.0/**

**Comment by tanghaibao** [comment]
There are two separate issues going on here.

In the first file, the script was not able to split the line in the AGP file, so perhaps you did not use tab separator (`\t`)? Per AGP specification, you must have `\t` in each AGP line except for the comment lines starting with `#`.

Second, the `swap` command did not work when there are gap lines since I did not encounter the usage of using `swap` with a scaffolded genome (usually the opposite). This bug has now been fixed in commit https://github.com/tanghaibao/jcvi/commit/84fc7a240c175b7e3388e04427304141ab566eac. Please let me know if it works now.

**Comment by splaisan** [comment]
Dear Haibao,

Thanks a lot for fixing this so fast.
The tab issue was likely due to my copy-paste, the gap issue was the more concerning one and I am very happy it now swaps.

==> test.agp <==
##agp-version	2.0
# Organism:  
# Platform:     
# Model:        
# Enzyme(s):    
# BioSample:    
# BioProject:   
# Obj_Name	Obj_Start	Obj_End	PartNum	Compnt_Type	CompntId_GapLength	CompntStart_GapType	CompntEnd_Linkage	Orientation_LinkageEvidence
Super-Scaffold_2	1	634629	1	W	000000F_018_pilon	1	634629	+
Super-Scaffold_4	1	1183857	1	W	000060F_pilon	1	1183857	+

==> test.swapped.agp <==
000000F_013_pilon	1	31911	1	W	000000F_013_pilon_obj	1	31911	+
000000F_018_pilon	1	634629	1	W	Super-Scaffold_2	1	634629	+
000000F_036_pilon	1	39792	1	W	000000F_036_pilon_obj	1	39792	+
000000F_039_pilon	1	903051	1	W	Super-Scaffold_4	4667634	5570684	-
000000F_044_pilon	1	24278	1	W	000000F_044_pilon_obj	1	24278	+
000000F_050_pilon	1	1720669	1	W	Super-Scaffold_4	2779950	4500618	-
000000F_072_pilon	1	2226523	1	W	Super-Scaffold_7	1	2226523	+
000000F_077_pilon	1	29510	1	W	000000F_077_pilon_obj	1	29510	+
000000F_pilon	1	188249	1	W	Super-Scaffold_9	1	188249	+
000000F_pilon	188250	209441	2	W	000000F_pilon_subseq_188250:209441_obj	1	21192	+

May I suggest copying over the header to the new AGP (and maybe adding a line to inform about the swapping!!, this would be handy to keep traceability, mine being a naked header as for testing purpose).

Thanks for the great tool of which I still have a LOT to discover.

BTW, is there a way to use my optical mapping AGP input for ALLMAPS instead of a BED or XML format in https://github.com/tanghaibao/jcvi/wiki/ALLMAPS:-How-to-use-different-types-of-genomic-maps ? I believe that AGP contains more info than the BED will but did not find info about this option.

Thanks & Best Regards,

**Comment by tanghaibao** [comment]
Great idea. I've created a new commit to transfer the existing header in commit https://github.com/tanghaibao/jcvi/commit/85849bcb0c0bb5108a1b1585c0d34a926dcc4936.

For using AGP input as ALLMAPS, I've never seen optical mapping data in that format. Would you like to show an example?

Haibao

**Comment by splaisan** [comment]
Sure,
Bionano delivers AGP but with a formatting error in the right part (NGS contigs), I corrected this and attach the head of one corrected file

##agp-version	2.0
# Organism:  
# Platform:     
# Model:        
# Enzyme(s):    
# BioSample:    
# BioProject:   
# Obj_Name	Obj_Start	Obj_End	PartNum	Compnt_Type	CompntId_GapLength	CompntStart_GapType	CompntEnd_Linkage	Orientation_LinkageEvidence
Super-Scaffold_2	1	634629	1	W	000000F_018_pilon	1	634629	+
Super-Scaffold_4	1	1183857	1	W	000060F_pilon	1	1183857	+
Super-Scaffold_4	1183858	1184356	2	N	499	scaffold	yes	map
Super-Scaffold_4	1184357	1526320	3	W	000238F_pilon	301099	643062	+
Super-Scaffold_4	1526321	1526819	4	N	499	scaffold	yes	map
Super-Scaffold_4	1526820	2029751	5	W	000133F_001_pilon	1	502932	-
Super-Scaffold_4	2029752	2035765	6	N	6014	scaffold	yes	map
Super-Scaffold_4	2035766	2207240	7	W	001674F_pilon	1	171475	+
Super-Scaffold_4	2207241	2207739	8	N	499	scaffold	yes	map
Super-Scaffold_4	2207740	2779450	9	W	000000F_pilon	242991	814701	-
Super-Scaffold_4	2779451	2779949	10	N	499	scaffold	yes	map
Super-Scaffold_4	2779950	4500618	11	W	000000F_050_pilon	1	1720669	-
Super-Scaffold_4	4500619	4507675	12	N	7057	scaffold	yes	map
Super-Scaffold_4	4507676	4667134	13	W	001817F_pilon	1	159459	+
Super-Scaffold_4	4667135	4667633	14	N	499	scaffold	yes	map
Super-Scaffold_4	4667634	5570684	15	W	000000F_039_pilon	1	903051	-
Super-Scaffold_7	1	2226523	1	W	000000F_072_pilon	1	2226523	+
Super-Scaffold_7	2226524	2635853	2	N	409330	scaffold	yes	map
Super-Scaffold_7	2635854	2999448	3	W	000630F_pilon	1	363595	+
Super-Scaffold_9	1	188249	1	W	000000F_pilon	1	188249	+
Super-Scaffold_9	188250	469926	2	N	281677	scaffold	yes	map
Super-Scaffold_9	469927	799598	3	W	000735F_pilon	1	329672	-
Super-Scaffold_9	799599	800097	4	N	499	scaffold	yes	map
Super-Scaffold_9	800098	1167777	5	W	000616F_pilon	1	367680	-
Super-Scaffold_9	1167778	1530826	6	N	363049	scaffold	yes	map
Super-Scaffold_9	1530827	1699763	7	W	001676F_pilon	1	168937	+
Super-Scaffold_9	1699764	1809117	8	N	109354	scaffold	yes	map
Super-Scaffold_9	1809118	1938750	9	W	002076F_pilon	1	129633	+
Super-Scaffold_9	1938751	2053393	10	N	114643	scaffold	yes	map
Super-Scaffold_9	2053394	2266064	11	W	001256F_pilon	1	212671	+

it follows the AGP guidelines and looks pretty standard to me.
the gaps are real optical gaps and the contigs are the original NGS contigs used for scaffolding or pieces thereof.

Thanks for looking into this

Best
Stephane

PS: I will be in holiday from tomorrow until 22nd.



Stéphane Plaisance – Staff Scientist | Bioinformatician 
VIB Nucleomics Core  
Campus Gasthuisberg
Herestraat 49 – Post Box 816 – 3000 Leuven – Belgium 
O&N4 Building – 8th Floor – Room 08.440 
Tel. +32 16 37 31 26  
Lync. +32 16 32 00 60  
www.nucleomics.be  <http://www.nucleomics.be/> <http://www.nucleomics.be/> <http://www.nucleomics.be/> <http://www.nucleomics.be/> <http://www.vib.be/>
