### ISSUE TITLE
老师您好！请帮我解答一下的问题：

### ISSUE THREAD

**Issue by Daishoulu** [tanghaibao/jcvi#571]
1，目前我有gff文件和基因组fasta文件,没有cds序列文件，请问如何提取类似的.cds文件？
2，在最后的共线性图中我需要用chr01 chr02...来代替基因组文件中的染色体号，请问在您的经验中我应该在哪一步就对染色体号进行替换。
3，python -m jcvi.formats.gff bed --type=mRNA --key=ID 该命令中的--type为何用mRNA,可否用--type=CDS等，区别是什么？
期待老师您的解答！祝愿老师工作顺利！

**Comment by Threeman8** [comment]
1.用软件gffread
2.seqids要与bed文件的命名一致，导出图后用ai调吧

**Comment by flyingicedragon** [comment]
> 用软件gffread

补充一下，用`jcvi.formats.gff load`应该也可以。
