### ISSUE TITLE
Doubt about the jcvi.formats.gff bed

### ISSUE THREAD

**Issue by z626093820** [tanghaibao/jcvi#572]
When I use the  command ：
python -m jcvi.formats.gff bed --type=gene --key=Accession I_aquatica.gff3 -o I_aquatica.bed

The fourth column name of the output bed file is not the name corresponding to the accession of the original gff3 file。

for example： 
the accession of the original gff3 file is

GWHABKX00000001	.	gene	28934982	28940366	.	-	.	ID=iaq.scaf_1036.5.p;Accession=GWHGABKX002090
GWHABKX00000001	EVM	gene	28969689	28970288	.	+	.	ID=iaq.scaf_1036.6.p;Accession=GWHGABKX002091
GWHABKX00000001	EVM	gene	28970575	28971141	.	+	.	ID=iaq.scaf_1036.7.p;Accession=GWHGABKX002092

but the bed out is：
GWHABKX00000001	28934981	28940366	gene_1	0	-
GWHABKX00000001	28969688	28970288	gene_11	0	+
GWHABKX00000001	28970574	28971141	gene_17	0	+

Thank you in advance

**Comment by z626093820** [comment]
> Hi!I think we might fall in the same hole, I also met this problem but for me the case is I can't get the correct gene name (in my code I used CDS rather then gene because my format looks a bit different from yours, but the principle is the same), did you finally figure what happened to your script?

如果ID和Accession或者Parent为分号分割，则不会识别Accession或者Parent，好像是这个原因，我不太记得了，这个问题好久了

**Comment by yyyuechen** [comment]
> 如果ID和Accession或者Parent为分号分割，则不会识别Accession或者Parent，好像是这个原因，我不太记得了，这个问题好久了

感谢解答！！如果您有空的话 能麻烦您看一下我的这个问题吗？ https://github.com/tanghaibao/jcvi/issues/634#issue-2167830223
在这里面我不太清楚是我的cds文件有问题（我直接从fasta文件跑这个代码提取的： python -m jcvi.formats.fasta format --sep="|" myfile.fasta  my.cds）还是我的bed文件有问题 再次感谢您的回复！！
