### ISSUE TITLE
Draw dotplot for a certain chromosomes order

### ISSUE THREAD

**Issue by Wanliwill** [tanghaibao/jcvi#573]
Hi,

I have a dotplot for a comparison of two plant species, including all chromosomes. I wonder is there a way to dotplot following a certain order of the chromosomes.

Thanks in advance

**Comment by tanghaibao** [comment]
@Wanliwill 

I think you can run with `--nosort` option so the script will not try to re-order the chromosome and just follow the order they appear in the BED files.

```console
python -m jcvi.graphics.dotplot --nosort
```

Then you can use `--qbed` or `--sbed` (depending on x-axis or y-axis) to specify the BED file with different order.

This is also a technique if you want to plot only a subset of chromosomes, just keep those chromosomes you want in the BED files. Note you can keep your original `.anchors` file untouched.

As an example if we just want to plot peach chr01

```console
grep Pp01 peach.bed > peach_chr01.bed
python -m jcvi.graphics.dotplot grape.peach.anchors --qbed grape.bed --sbed peach_chr01.bed
```

<img width="735" alt="image" src="https://github.com/tanghaibao/jcvi/assets/106987/0ab6a2fd-d71b-4e37-94ce-22d54a0dce93">

Haibao

**Comment by Wanliwill** [comment]
I got it. 
Thank you so much.
