### ISSUE TITLE
Private reporting of a vulnerability request

### ISSUE THREAD

**Issue by Sim4n6** [tanghaibao/jcvi#576]
I may have identified a potential vulnerability in the latest codebase of jcvi could you please consider enabling GitHub private reporting [feature](https://docs.github.com/en/code-security/security-advisories/repository-security-advisories/configuring-private-vulnerability-reporting-for-a-repository).

**Comment by tanghaibao** [comment]
done. please report the vulnerability. thanks in advance!

**Comment by Sim4n6** [comment]
I'm working on that ... today.
