### ISSUE TITLE
Pairwise syntensy search process aborted

### ISSUE THREAD

**Issue by UpalabdhaD** [tanghaibao/jcvi#578]
Hi, 
I am running the pipeline for synteny detection. I am using anaconda distribution of jcvi.  Command issued inside a shell script 'python -m jcvi.compara.catalog ortholog species1 species2 --no_strip_names'. Run the shell script with nohup. Raw file has been generated named "species1.species2.last". However, later on the process was killed autaomatically. I have attached the nohup.out output below. 

PS. the .last file size is 53GB, and the pipeline was run on a 128 GB memory machine with 24 physical cores : multithreading on (48 verual cores).

As. the raw file is generated, what would be the next steps ? I would sincirely appreciate any help.

tail -f nohup.out 

"""
[18:27:34] DEBUG    lastal -u 0 -i3G -f BlastTab -P 48 species2      base.py:1182
                    species1.cds >./species1.species2.last                   
[19:20:36] DEBUG    Assuming --qbed=species1.bed                synteny.py:390
                    --sbed=species2.bed                                          
           DEBUG    Load file `species1.bed`                        base.py:34
           DEBUG    Load file `species2.bed`                           base.py:34
[19:22:02] DEBUG    Load BLAST file `species1.species2.last`  blastfilter.py:46
                    (total 630635423 lines)                                     
           DEBUG    Load file `species1.species2.last`               base.py:34
pairwise_synteny_search.sh: line 13: 45794 Killed                  python -m jcvi.compara.catalog ortholog species1 species2 --no_strip_names

"""

**Comment by tanghaibao** [comment]
@UpalabdhaD 

Are you comparing gene models? It is super rare that the last file size is this big. 
It probably is too big to load (Python data structure would use more memory than 53Gb).

**Comment by UpalabdhaD** [comment]
@tanghaibao 

Thanks for the reply. I am fairly new to the MCScan. As suggested in the wiki page of the repo, I have used CDS nucleoitde and the bed files. However, both of the genomes are not chromosome scale assembly, there are many unplaced scaffolds. Do you think that might be the reason for such a big .last file ?  The CDS inputs are ~ 2GB files.  Should i use the translated cds ?  

PS. As you mentioned, I checked the dmesg log and found oom issues and kernel has killed the job after 115 GB of memory usage.

Kinldy, suggest.

**Comment by tanghaibao** [comment]
@UpalabdhaD 

CDS are usually quite small in size, and ~2GB is definitely on the high end (human genome is ~3GB). CDS should be the sequences that directly translates to a protein, e.g. starts with `ATG` and ends with `TAA/TGA/TAG`.

Do you happen to have a big genome?

If you have lots of unplaced scaffold, my recommendation is to remove the smaller scaffolds that contain very few genes on them, they will not contribute to synteny blocks.

**Comment by UpalabdhaD** [comment]
Genome size for both of the species are ~2Gb. I have downloaded the cds file from ncbi ftp: https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/000/325/575/GCF_000325575.1_ASM32557v1/GCF_000325575.1_ASM32557v1_cds_from_genomic.fna.gz

Filneame: GCF_000325575.1_ASM32557v1_cds_from_genomic.fna.gz

Kindly check once whether this file would be suitable for analysis. I will consider to remove small unplaced scaffolds.

**Comment by tanghaibao** [comment]
The file that this link is pointing to should be fine to use directly, that's CDS (just ~75MB, ~40k sequences).

I don't think that's the file you used to produce the LAST though.
Did you happen to use the genome FASTA (which would explain 53GB LAST file) instead of the CDS (that should generate a much smaller LAST file) when you ran MCScan?

**Comment by UpalabdhaD** [comment]
@tanghaibao 
Thanks for your suggestions. Finally I figured out I was using genome FASTA for one of the species. Now the progrmmee run without killing th process and the .last file is ~229M. however, the programme produces the following errors:

`python -m jcvi.compara.catalog ortholog Pgiganteus Palecto --no_strip_names
[16:02:28] DEBUG    lastdb Palecto Palecto.cds                                        base.py:1182
[16:03:44] DEBUG    lastal -u 0 -i3G -f BlastTab -P 24 Palecto Pgiganteus.cds         base.py:1182
                    >./Pgiganteus.Palecto.last                                                    
[16:04:07] DEBUG    Assuming --qbed=Pgiganteus.bed --sbed=Palecto.bed               synteny.py:390
           DEBUG    Load file `Pgiganteus.bed`                                          base.py:34
           DEBUG    Load file `Palecto.bed`                                             base.py:34
           DEBUG    Load BLAST file `Pgiganteus.Palecto.last` (total 1806574     blastfilter.py:46
                    lines)                                                                        
           DEBUG    Load file `Pgiganteus.Palecto.last`                                 base.py:34
[16:04:10] WARNING  lcl|NW_024354875.1_cds_XP_039711289.1_47610 not in           blastfilter.py:65
                    Pgiganteus.bed                                                                
           WARNING  lcl|NW_024354875.1_cds_XP_039711289.1_47610 not in           blastfilter.py:65
                    Pgiganteus.bed                                                                
           WARNING  lcl|NW_024350399.1_cds_XP_039695865.1_32970 not in           blastfilter.py:65
                    Pgiganteus.bed                                                                
           WARNING  lcl|NW_024340695.1_cds_XP_039720519.1_664 not in             blastfilter.py:65
                    Pgiganteus.bed                                                                
           WARNING  lcl|NW_024340695.1_cds_XP_039720523.1_665 not in             blastfilter.py:65
                    Pgiganteus.bed                                                                
           WARNING  lcl|NW_024340695.1_cds_XP_039720527.1_666 not in             blastfilter.py:65
                    Pgiganteus.bed                                                                
           WARNING  lcl|NW_024340695.1_cds_XP_039720538.1_667 not in             blastfilter.py:65
                    Pgiganteus.bed                                                                
           WARNING  lcl|NW_024349225.1_cds_XP_039737169.1_22218 not in           blastfilter.py:65
                    Pgiganteus.bed                                                                
           WARNING  lcl|NW_024354500.1_cds_XP_039709002.1_44908 not in           blastfilter.py:65
                    Pgiganteus.bed                                                                
           WARNING  lcl|NW_024354500.1_cds_XP_039709002.1_44908 not in           blastfilter.py:65
                    Pgiganteus.bed                                                                
           WARNING  lcl|NW_024349225.1_cds_XP_039737170.1_22217 not in           blastfilter.py:65
                    Pgiganteus.bed                                                                
           WARNING  lcl|NW_024349225.1_cds_XP_039737171.1_22219 not in           blastfilter.py:65
                    Pgiganteus.bed                                                                
           WARNING  lcl|NW_024354500.1_cds_XP_039709002.1_44908 not in           blastfilter.py:65
                    Pgiganteus.bed                                                                
           WARNING  lcl|NW_024349225.1_cds_XP_039737170.1_22217 not in           blastfilter.py:65
                    Pgiganteus.bed                                                                
           WARNING  lcl|NW_024349225.1_cds_XP_039737169.1_22218 not in           blastfilter.py:65
                    Pgiganteus.bed                                                                
           WARNING  lcl|NW_024350927.1_cds_XP_039697983.1_34801 not in           blastfilter.py:65
                    Pgiganteus.bed                                                                
           WARNING  lcl|NW_024350927.1_cds_XP_039697985.1_34808 not in           blastfilter.py:65
                    Pgiganteus.bed                                                                
           WARNING  lcl|NW_024350927.1_cds_XP_039697984.1_34809 not in           blastfilter.py:65
                    Pgiganteus.bed                                                                
           WARNING  lcl|NW_024350927.1_cds_XP_039697983.1_34801 not in           blastfilter.py:65
                    Pgiganteus.bed                                                                
           WARNING  lcl|NW_024350927.1_cds_XP_039697983.1_34801 not in           blastfilter.py:65
                    Pgiganteus.bed                                                                
           WARNING  lcl|NW_024350927.1_cds_XP_039697983.1_34801 not in           blastfilter.py:65
                    Pgiganteus.bed                                                                
           WARNING  lcl|NW_024350927.1_cds_XP_039697983.1_34801 not in           blastfilter.py:65
                    Pgiganteus.bed                                                                
           WARNING  lcl|NW_024350927.1_cds_XP_039697989.1_34802 not in           blastfilter.py:65
                    Pgiganteus.bed                                                                
           WARNING  lcl|NW_024350927.1_cds_XP_039697986.1_34803 not in           blastfilter.py:65
                    Pgiganteus.bed                                                                
           WARNING  lcl|NW_024350927.1_cds_XP_039697986.1_34803 not in           blastfilter.py:65
                    Pgiganteus.bed                                                                
           WARNING  lcl|NW_024350927.1_cds_XP_039697986.1_34803 not in           blastfilter.py:65
                    Pgiganteus.bed                                                                
           WARNING  lcl|NW_024350927.1_cds_XP_039697986.1_34803 not in           blastfilter.py:65
                    Pgiganteus.bed                                                                
           WARNING  lcl|NW_024350927.1_cds_XP_039697986.1_34803 not in           blastfilter.py:65
                    Pgiganteus.bed                                                                
           WARNING  lcl|NW_024350927.1_cds_XP_039697987.1_34804 not in           blastfilter.py:65
                    Pgiganteus.bed                                                                
           WARNING  lcl|NW_024350927.1_cds_XP_039697987.1_34804 not in           blastfilter.py:65
                    Pgiganteus.bed                                                                
           WARNING  lcl|NW_024350927.1_cds_XP_039697987.1_34804 not in           blastfilter.py:65
                    Pgiganteus.bed                                                                
           WARNING  lcl|NW_024350927.1_cds_XP_039697987.1_34804 not in           blastfilter.py:65
                    Pgiganteus.bed                                                                
           WARNING  lcl|NW_024350927.1_cds_XP_039697987.1_34804 not in           blastfilter.py:65
                    Pgiganteus.bed                                                                
           WARNING  lcl|NW_024350927.1_cds_XP_039697987.1_34804 not in           blastfilter.py:65
                    Pgiganteus.bed                                                                
           WARNING  lcl|NW_024350927.1_cds_XP_039697988.1_34806 not in           blastfilter.py:65
                    Pgiganteus.bed                                                                
           WARNING  lcl|NW_024350927.1_cds_XP_039697988.1_34806 not in           blastfilter.py:65
                    Pgiganteus.bed                                                                
           WARNING  lcl|NW_024350927.1_cds_XP_039697985.1_34808 not in           blastfilter.py:65
                    Pgiganteus.bed                                                                
           WARNING  lcl|NW_024350927.1_cds_XP_039697985.1_34808 not in           blastfilter.py:65
                    Pgiganteus.bed                                                                
           WARNING  lcl|NW_024350927.1_cds_XP_039697985.1_34808 not in           blastfilter.py:65
                    Pgiganteus.bed                                                                
           WARNING  lcl|NW_024350927.1_cds_XP_039697985.1_34808 not in           blastfilter.py:65
                    Pgiganteus.bed                                                                
           WARNING  lcl|NW_024350927.1_cds_XP_039697984.1_34809 not in           blastfilter.py:65
                    Pgiganteus.bed                                                                
           WARNING  lcl|NW_024350927.1_cds_XP_039697984.1_34809 not in           blastfilter.py:65
                    Pgiganteus.bed                                                                
           WARNING  lcl|NW_024350927.1_cds_XP_039697984.1_34809 not in           blastfilter.py:65
                    Pgiganteus.bed                                                                
           WARNING  lcl|NW_024350927.1_cds_XP_039697984.1_34809 not in           blastfilter.py:65
                    Pgiganteus.bed                                                                
           WARNING  lcl|NW_024350927.1_cds_XP_039697990.1_34805 not in           blastfilter.py:65
                    Pgiganteus.bed                                                                
           WARNING  lcl|NW_024350927.1_cds_XP_039697993.1_34807 not in           blastfilter.py:65
                    Pgiganteus.bed                                                                
           WARNING  lcl|NW_024350927.1_cds_XP_039697991.1_34810 not in           blastfilter.py:65
                    Pgiganteus.bed                                                                
           WARNING  lcl|NW_024350927.1_cds_XP_039697991.1_34810 not in           blastfilter.py:65
                    Pgiganteus.bed                                                                
           WARNING  lcl|NW_024350927.1_cds_XP_039697994.1_34811 not in           blastfilter.py:65
                    Pgiganteus.bed                                                                
           WARNING  lcl|NW_024350927.1_cds_XP_039697992.1_34812 not in           blastfilter.py:65
                    Pgiganteus.bed                                                                
           WARNING  lcl|NW_024350927.1_cds_XP_039697992.1_34812 not in           blastfilter.py:65
                    Pgiganteus.bed                                                                
           WARNING  lcl|NW_024349225.1_cds_XP_039737171.1_22219 not in           blastfilter.py:65
                    Pgiganteus.bed                                                                
           WARNING  lcl|NW_024353909.1_cds_XP_039707960.1_44068 not in           blastfilter.py:65
                    Pgiganteus.bed                                                                
           WARNING  lcl|NW_024353909.1_cds_XP_039707960.1_44068 not in           blastfilter.py:65
                    Pgiganteus.bed                                                                
           WARNING  lcl|NW_024353909.1_cds_XP_039707960.1_44068 not in           blastfilter.py:65
                    Pgiganteus.bed                                                                
           WARNING  lcl|NW_024353909.1_cds_XP_039707960.1_44068 not in           blastfilter.py:65
                    Pgiganteus.bed                                                                
           WARNING  lcl|NW_024353909.1_cds_XP_039707961.1_44069 not in           blastfilter.py:65
                    Pgiganteus.bed                                                                
           WARNING  lcl|NW_024353909.1_cds_XP_039707961.1_44069 not in           blastfilter.py:65
                    Pgiganteus.bed                                                                
           WARNING  lcl|NW_024353909.1_cds_XP_039707961.1_44069 not in           blastfilter.py:65
                    Pgiganteus.bed                                                                
           WARNING  lcl|NW_024353909.1_cds_XP_039707961.1_44069 not in           blastfilter.py:65
                    Pgiganteus.bed                                                                
           WARNING  lcl|NW_024353909.1_cds_XP_039707962.1_44070 not in           blastfilter.py:65
                    Pgiganteus.bed                                                                
           WARNING  lcl|NW_024353909.1_cds_XP_039707962.1_44070 not in           blastfilter.py:65
                    Pgiganteus.bed                                                                
           WARNING  lcl|NW_024353909.1_cds_XP_039707962.1_44070 not in           blastfilter.py:65
                    Pgiganteus.bed                                                                
           WARNING  lcl|NW_024353909.1_cds_XP_039707962.1_44070 not in           blastfilter.py:65
                    Pgiganteus.bed                                                                
           WARNING  lcl|NW_024353909.1_cds_XP_039707963.1_44071 not in           blastfilter.py:65
                    Pgiganteus.bed                                                                
           WARNING  lcl|NW_024353909.1_cds_XP_039707963.1_44071 not in           blastfilter.py:65
                    Pgiganteus.bed                                                                
           WARNING  lcl|NW_024353909.1_cds_XP_039707963.1_44071 not in           blastfilter.py:65
                    Pgiganteus.bed                                                                
           WARNING  lcl|NW_024353909.1_cds_XP_039707963.1_44071 not in           blastfilter.py:65
                    Pgiganteus.bed                                                                
           WARNING  lcl|NW_024348304.1_cds_XP_039735484.1_20664 not in           blastfilter.py:65
                    Pgiganteus.bed                                                                
           WARNING  lcl|NW_024348304.1_cds_XP_039735484.1_20664 not in           blastfilter.py:65
                    Pgiganteus.bed                                                                
           WARNING  lcl|NW_024348304.1_cds_XP_039735484.1_20664 not in           blastfilter.py:65
                    Pgiganteus.bed                                                                
           WARNING  lcl|NW_024348304.1_cds_XP_039735484.1_20664 not in           blastfilter.py:65
                    Pgiganteus.bed                                                                
           WARNING  lcl|NW_024348304.1_cds_XP_039735484.1_20664 not in           blastfilter.py:65
                    Pgiganteus.bed                                                                
           WARNING  lcl|NW_024350927.1_cds_XP_039697996.1_34813 not in           blastfilter.py:65
                    Pgiganteus.bed                                                                
           WARNING  lcl|NW_024350927.1_cds_XP_039697996.1_34813 not in           blastfilter.py:65
                    Pgiganteus.bed                                                                
           WARNING  lcl|NW_024350927.1_cds_XP_039697996.1_34813 not in           blastfilter.py:65
                    Pgiganteus.bed                                                                
           WARNING  lcl|NW_024350927.1_cds_XP_039697996.1_34813 not in           blastfilter.py:65
                    Pgiganteus.bed                                                                
           WARNING  lcl|NW_024350927.1_cds_XP_039697996.1_34813 not in           blastfilter.py:65
                    Pgiganteus.bed                                                                
           WARNING  lcl|NW_024348304.1_cds_XP_039735484.1_20664 not in           blastfilter.py:65
                    Pgiganteus.bed                                                                
           WARNING  lcl|NW_024350927.1_cds_XP_039697983.1_34801 not in           blastfilter.py:65
                    Pgiganteus.bed                                                                
           WARNING  lcl|NW_024350927.1_cds_XP_039697986.1_34803 not in           blastfilter.py:65
                    Pgiganteus.bed                                                                
           WARNING  lcl|NW_024350927.1_cds_XP_039697985.1_34808 not in           blastfilter.py:65
                    Pgiganteus.bed                                                                
           WARNING  lcl|NW_024350927.1_cds_XP_039697984.1_34809 not in           blastfilter.py:65
                    Pgiganteus.bed                                                                
           WARNING  lcl|NW_024353909.1_cds_XP_039707965.1_44075 not in           blastfilter.py:65
                    Pgiganteus.bed                                                                
           WARNING  lcl|NW_024350927.1_cds_XP_039697987.1_34804 not in           blastfilter.py:65
                    Pgiganteus.bed                                                                
           WARNING  lcl|NW_024353909.1_cds_XP_039707966.1_44072 not in           blastfilter.py:65
                    Pgiganteus.bed                                                                
           WARNING  lcl|NW_024353909.1_cds_XP_039707967.1_44084 not in           blastfilter.py:65
                    Pgiganteus.bed                                                                
           WARNING  lcl|NW_024353909.1_cds_XP_039707967.1_44084 not in           blastfilter.py:65
                    Pgiganteus.bed                                                                
           WARNING  lcl|NW_024353909.1_cds_XP_039707967.1_44084 not in           blastfilter.py:65
                    Pgiganteus.bed                                                                
           WARNING  lcl|NW_024353909.1_cds_XP_039707967.1_44084 not in           blastfilter.py:65
                    Pgiganteus.bed                                                                
           WARNING  lcl|NW_024350927.1_cds_XP_039697983.1_34801 not in           blastfilter.py:65
                    Pgiganteus.bed                                                                
           WARNING  lcl|NW_024350927.1_cds_XP_039697989.1_34802 not in           blastfilter.py:65
                    Pgiganteus.bed                                                                
           WARNING  lcl|NW_024350927.1_cds_XP_039697989.1_34802 not in           blastfilter.py:65
                    Pgiganteus.bed                                                                
           WARNING  lcl|NW_024353909.1_cds_XP_039707968.1_44073 not in           blastfilter.py:65
                    Pgiganteus.bed                                                                
           WARNING  lcl|NW_024342473.1_cds_XP_039721280.1_7834 not in            blastfilter.py:65
                    Pgiganteus.bed                                                                
           WARNING  lcl|NW_024342473.1_cds_XP_039721280.1_7834 not in            blastfilter.py:65
                    Pgiganteus.bed                                                                
           WARNING  lcl|NW_024342473.1_cds_XP_039721280.1_7834 not in            blastfilter.py:65
                    Pgiganteus.bed                                                                
           WARNING  lcl|NW_024342473.1_cds_XP_039721280.1_7834 not in            blastfilter.py:65
                    Pgiganteus.bed                                                                
           WARNING  lcl|NW_024342473.1_cds_XP_039721280.1_7834 not in            blastfilter.py:65
                    Pgiganteus.bed                                                                
           WARNING  lcl|NW_024342473.1_cds_XP_039721280.1_7834 not in            blastfilter.py:65
                    Pgiganteus.bed                                                                
           WARNING  too many warnings.. suppressed                               blastfilter.py:67
           DEBUG    running the cscore filter (cscore>=0.70) ..                 blastfilter.py:108
           DEBUG    after filter (0->0) ..                                      blastfilter.py:110
           DEBUG    running the local dups filter (tandem_Nmax=10) ..           blastfilter.py:115
           DEBUG    after filter (0->0) ..                                      blastfilter.py:155
           DEBUG    Assuming --qbed=Pgiganteus.bed --sbed=Palecto.bed               synteny.py:390
           DEBUG    Load file `Pgiganteus.bed`                                          base.py:34
           DEBUG    Load file `Palecto.bed`                                             base.py:34
           DEBUG    Load file `Pgiganteus.Palecto.last.filtered`                        base.py:34
           DEBUG    A total of 0 BLAST imported from                                synteny.py:277
                    `Pgiganteus.Palecto.last.filtered`.                                           
           DEBUG    Chaining distance = 20                                         synteny.py:1794
           DEBUG    Load file `Pgiganteus.Palecto.anchors`                              base.py:34
           DEBUG    A total of 0 anchor was found. Aborted.                        synteny.py:1371
Traceback (most recent call last):
  File "/home/upalabdha/mambaforge/envs/jcvi_env/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/upalabdha/mambaforge/envs/jcvi_env/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/upalabdha/mambaforge/envs/jcvi_env/lib/python3.10/site-packages/jcvi/compara/catalog.py", line 963, in <module>
    main()
  File "/home/upalabdha/mambaforge/envs/jcvi_env/lib/python3.10/site-packages/jcvi/compara/catalog.py", line 78, in main
    p.dispatch(globals())
  File "/home/upalabdha/mambaforge/envs/jcvi_env/lib/python3.10/site-packages/jcvi/apps/base.py", line 110, in dispatch
    globals[action](sys.argv[2:])
  File "/home/upalabdha/mambaforge/envs/jcvi_env/lib/python3.10/site-packages/jcvi/compara/catalog.py", line 730, in ortholog
    scan(dargs)
  File "/home/upalabdha/mambaforge/envs/jcvi_env/lib/python3.10/site-packages/jcvi/compara/synteny.py", line 1811, in scan
    summary([anchor_file])
  File "/home/upalabdha/mambaforge/envs/jcvi_env/lib/python3.10/site-packages/jcvi/compara/synteny.py", line 1372, in summary
    raise ValueError("A total of 0 anchor was found. Aborted.")
ValueError: A total of 0 anchor was found. Aborted.
`
PS: I have checked for the last installation. Since I was using throug anaconda distribution its on proper place.

which lastdb
/home/upalabdha/mambaforge/envs/jcvi_env/bin/lastdb

which lastal
/home/upalabdha/mambaforge/envs/jcvi_env/bin/lastal

Kindly suggest me. Thanks in advance.

**Comment by tanghaibao** [comment]
@UpalabdhaD 

The critical issue is to make sure the gene name used in the CDS matches the 4th column in the BED file. All the warnings:

```
WARNING lcl|NW_024350927.1_cds_XP_039697989.1_34802 not in Pgiganteus.bed
```

This suggests that they don't match. Would you please take a look if the names match? Sometimes it is just removing stupid things like the additional "lcl|" in front of the names in the CDS.
