### ISSUE TITLE
--iter=2 flag in jcvi.compara.synteny mcscan doesnot provide any additional regions !

### ISSUE THREAD

**Issue by UpalabdhaD** [tanghaibao/jcvi#584]
Dear @tanghaibao,
I have used the following command as suggested in the wiki, and my primary objective was to identify and visualize any duplication events in the two genome. And I assumed there will be additional column when one use `iter=2`, I have also used the command without --iter flag assuming the default value 100 will be used in such case. however, in all the cases I didnot get any output of additional coloumn or any additional region. Am I missing something?

Kindly note, I used this tool to identify the regions resulted from genome duplication events. In such case what would be your suggestions? 

> if you take a look at the resulting grape.peach.i1.blocks file, it contains grape as the first column and peach as the second column. If the option --iter is set to 2, there will be 2 peach regions, and so on. Specifically, this will be useful to plot regions resulted from genome duplications.

`python -m jcvi.compara.synteny mcscan Species1.bed Species1.Species2.anchors --iter=2 -o Species1.Species.i2.blocks`

`--iter=1 `results:
```
Pteropus_000001-RA      Ma_sr-lr_union100_HiC.fasta002294-RA
Pteropus_000002-RA      Ma_sr-lr_union100_HiC.fasta002293-RA
Pteropus_000003-RA      Ma_sr-lr_union100_HiC.fasta002292-RA
Pteropus_000004-RA      Ma_sr-lr_union100_HiC.fasta002291-RA
Pteropus_000005-RA      Ma_sr-lr_union100_HiC.fasta002290-RA
Pteropus_000006-RA      Ma_sr-lr_union100_HiC.fasta002289-RA
Pteropus_000007-RA      Ma_sr-lr_union100_HiC.fasta002288-RA
Pteropus_000008-RA      Ma_sr-lr_union100_HiC.fasta002287-RA
Pteropus_000009-RA      Ma_sr-lr_union100_HiC.fasta002286-RA
Pteropus_000010-RA      Ma_sr-lr_union100_HiC.fasta002285-RA
Pteropus_000011-RA      Ma_sr-lr_union100_HiC.fasta002284-RA
```

`--iter=2 `results:
```
Pteropus_000001-RA      Ma_sr-lr_union100_HiC.fasta002294-RA
Pteropus_000002-RA      Ma_sr-lr_union100_HiC.fasta002293-RA
Pteropus_000003-RA      Ma_sr-lr_union100_HiC.fasta002292-RA
Pteropus_000004-RA      Ma_sr-lr_union100_HiC.fasta002291-RA
Pteropus_000005-RA      Ma_sr-lr_union100_HiC.fasta002290-RA
Pteropus_000006-RA      Ma_sr-lr_union100_HiC.fasta002289-RA
Pteropus_000007-RA      Ma_sr-lr_union100_HiC.fasta002288-RA
Pteropus_000008-RA      Ma_sr-lr_union100_HiC.fasta002287-RA
Pteropus_000009-RA      Ma_sr-lr_union100_HiC.fasta002286-RA
Pteropus_000010-RA      Ma_sr-lr_union100_HiC.fasta002285-RA
Pteropus_000011-RA      Ma_sr-lr_union100_HiC.fasta002284-RA
Pteropus_000012-RA      Ma_sr-lr_union100_HiC.fasta002283-RA
Pteropus_000013-RA      Ma_sr-lr_union100_HiC.fasta002282-RA
Pteropus_000014-RA      Ma_sr-lr_union100_HiC.fasta002281-RA
Pteropus_000015-RA      Ma_sr-lr_union100_HiC.fasta002280-RA
Pteropus_000016-RA      Ma_sr-lr_union100_HiC.fasta002278-RA
Pteropus_000017-RA      Ma_sr-lr_union100_HiC.fasta002277-RA
Pteropus_000018-RA      .
Pteropus_000019-RA      Ma_sr-lr_union100_HiC.fasta002276-RA

```

Thanks in advamce!

**Comment by tanghaibao** [comment]
@UpalabdhaD 

I have not seen this before. Can you share the dot plot on the anchors file?
Perhaps the parameters were chosen so that there were not any secondary blocks remained after the first iteration?

Haibao
