### ISSUE TITLE
Miscellaneous chromosome sorting

### ISSUE THREAD

**Issue by cutykaka** [tanghaibao/jcvi#588]
Hello.
I've been finding the jcvi program extremely useful. Currently, I am using python -m jcvi.graphics.chromosome for Miscellaneous plotting.
However, if there are more than 10 chromosomes, they don't get arranged in the order 1, 2, 3,..., 11, 12 but rather 1, 11, 12, 2, 3, 4, 5,... It seems like this issue occurs due to Python's sorting behavior.

Do I need to modify the jcvi/graphics/chromosome.py code to address this, or is there an existing setting option for this?

Thank you.

**Comment by tanghaibao** [comment]
@cutykaka 

I think this is a good idea and modified the `sorted` function to use `natsorted` instead, in https://github.com/tanghaibao/jcvi/commit/a60413503059a16f92697a81b6967fe5ee29f414.

Let me know if this helps.

**Comment by cutykaka** [comment]
I've confirmed that it's working well. However, the problem is that while karyotype sorting is done by chromosome, when reading the information from the BED file, it aligns according to the chromosome array before applying the natsorted function. This creates an issue.

**Comment by cutykaka** [comment]
cool! It's solved. Thank you :)
