### ISSUE TITLE
How to draw lines to the inside

### ISSUE THREAD

**Issue by hushaoqiang** [tanghaibao/jcvi#599]
Hello teacher. I now hope to draw the linear relationship between C and D on the inner side instead of parallel. May I know how to do it。Thansk!

![K}K8A4L@V`QAHE))0LIJH6P](https://github.com/tanghaibao/jcvi/assets/68465643/3e8dbea5-ee73-466a-806a-ea0f9c6d0aa2)

**Comment by tanghaibao** [comment]
@hushaoqiang 

Can you quickly show me what you want to C-D lines instead? (just draw a few lines on top of this picture)
Thanks.

**Comment by hushaoqiang** [comment]
Hello teacher. I hope the connection between CDs is similar to AB

**Comment by hushaoqiang** [comment]
老师，你好，请问我可以把C和D之间的连线变成像A和B一样吗

**Comment by tanghaibao** [comment]
@hushaoqiang 

In the layout file, and the `e` lines, add a 5th column like this:

```
# edges
e, 0, 1, grape.peach.anchors.simple, above
```

This way, the connecting lines will be thrown `above` (you can also choose among `above2`, `below`, `below2`). Also, you need to use a relatively new version of `jcvi`. This change is in early this year.

**Comment by hushaoqiang** [comment]
谢谢老师的解答，我会安装新版本的jcvi尝试绘图。
