### ISSUE TITLE
lastal: I was installed here with multi-threading disabled

### ISSUE THREAD

**Issue by MR-D-CJ** [tanghaibao/jcvi#603]
hello professor,
when i run `python -m jcvi.compara.catalog ortholog --no_strip_names --cscore=.99 Homo_sapiens Pan_troglodytes` , it noted that 'lastal: I was installed here with multi-threading disabled', but i have installed last by conda, `conda install -c bioconda last`
what is the cause of this, is there any way to solve it?
the information of the system:
<img width="1380" alt="image" src="https://github.com/tanghaibao/jcvi/assets/52587925/4a721129-4f47-4894-84d5-d2e0920d79f2">

**Comment by tanghaibao** [comment]
@MR-D-CJ 

This just means that the version installed by conda does not support multiple threads. Doe it crash for you? I can't remember but maybe this will just run more slowly on a single thread.

You can also compile/install a version yourself with multiple threading though: https://gitlab.com/mcfrith/last
