### ISSUE TITLE
How genes in blocks files are connected with layout file in microsynteny plot?

### ISSUE THREAD

**Issue by Tong-Chen** [tanghaibao/jcvi#606]
As illustrated in [microsynteny-visualization](https://github.com/tanghaibao/jcvi/wiki/MCscan-%28Python-version%29#microsynteny-visualization), there is a demo block file like the below:

```
GSVIVT01012261001	.	.
GSVIVT01012259001	.	.
GSVIVT01012258001	.	.
GSVIVT01012257001	.	.
GSVIVT01012255001	Prupe.1G290900.1	Thecc1EG011472t1
GSVIVT01012253001	Prupe.1G290800.2	Thecc1EG011473t1
GSVIVT01012252001	Prupe.1G290700.1	Thecc1EG011474t1
GSVIVT01012250001	Prupe.1G290600.1	Thecc1EG011475t1
GSVIVT01012249001	Prupe.1G290500.1	Thecc1EG011478t1
GSVIVT01012248001	Prupe.1G290400.1	Thecc1EG011482t1
```

A demo `layout` file like the below:

```
# x,   y, rotation,     ha,     va, color, ratio,            label
0.5, 0.6,        0, center,    top,      ,     1,       grape Chr1
0.3, 0.4,        0, center, bottom,      ,    .5, peach scaffold_1
0.7, 0.4,        0, center, bottom,      ,    .5, cacao scaffold_2
# edges
e, 0, 1
e, 0, 2
```

Could I explain their relationship as below:

1. There are **3** columns in the `block` file, so there must be **3** lines in the `layout` file (between `# xy` and `#edges`), representing genes in each column located at the scaffolds in each row. Would these numbers must be equal?
2. Genes in the first column of the `block` file located at the first scaffold, known as `grape Chr1` in this demo data. What if genes in the first column of the `block` file originate from several scaffolds, like `Chr2`, `Chr3`, `Chr1`? Would the layout be written as below:

```
0.2, 0.6,        0, center,    top,      ,     0.3,       grape Chr1
0.5, 0.6,        0, center,    top,      ,     0.3,       grape Chr2
0.7, 0.6,        0, center,    top,      ,     0.3,       grape Chr3
``` 

3. Genes in the second column of the `block` file located at the second scaffold. If there is a condition that gene `GSVIVT01012255001` matches two genes in the genome of `Prupe` and these two genes are located at `chr20` and `chr21` respectively. Would the `block` file be like which format:

```
# first format
GSVIVT01012255001     Prupe_chr20_gene
GSVIVT01012255001     Prupe_chr21_gene
```

or 

```
# second format
GSVIVT01012255001     Prupe_chr20_gene   Prupe_chr21_gene
```

Thanks!

Chen Tong

**Comment by tanghaibao** [comment]
@Tong-Chen 

Yes the column represents a continuous region. If you have 3 regions from grape, then you have to separate them into 3 columns like the following (note the use of '.' as placeholder for a non-match).

```diff
-grape1.1    peach1.1
-grape1.2    peach1.2
-grape2.1    peach1.3
-grape2.2    peach1.4
-grape3.1    peach1.5
-grape3.2    peach1.6
+grape1.1    .    .    peach1.1
+grape1.1    .    .    peach1.2
+.    grape2.1    .    peach1.3
+.    grape2.2    .    peach1.4
+.    .    grape3.1    peach1.5
+.    .    grape3.2    peach1.6
```

Remember in this case, configure your layout file to 4 tracks instead of 2.

**Comment by Tong-Chen** [comment]
Thanks! I would try this.

**Comment by wu116** [comment]
Sorry for reopening this issue, but I still confuse with the format of `block` file.

**How can we show the '1 to many' relationship on a single gene with microsynteny plot?** For example, if there was a gene `grape1.1` which was duplicated in peach as `peach1.1` and `peach1.2`, and I generated the `block` file like this:
```
grape1.1    peach1.1
grape1.1    peach1.2
```
The microsynteny plot seemed to ignore the first row and **ONLY** show the connection bewteen `grape1.1 `and `peach1.2`.

If I separated them into 3 columns:
```
grape1.1    .    peach1.1
.    grape1.1    peach1.2
```
and modified the `layout` to:
```
# x,   y, rotation,     ha,     va, color, ratio,            label
0.5, 0.6,        0, center,    top,      ,     1,       grape Chr1
0.5, 0.6,        0, center,    top,      ,     1,       grape Chr1
0.7, 0.4,        0, center, bottom,      ,    .5, peach scaffold_1
# edges
e, 0, 2
e, 1, 2
```
then a error would be threw out:
```
Traceback (most recent call last):
  File "/home/shu/miniconda3/envs/jcvi/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/shu/miniconda3/envs/jcvi/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/shu/miniconda3/envs/jcvi/lib/python3.10/site-packages/jcvi/graphics/synteny.py", line 666, in <module>
    main()
  File "/home/shu/miniconda3/envs/jcvi/lib/python3.10/site-packages/jcvi/graphics/synteny.py", line 639, in main
    Synteny(
  File "/home/shu/miniconda3/envs/jcvi/lib/python3.10/site-packages/jcvi/graphics/synteny.py", line 425, in __init__
    ext = bf.get_extent(i, order)
  File "/home/shu/miniconda3/envs/jcvi/lib/python3.10/site-packages/jcvi/compara/synteny.py", line 75, in get_extent
    si, start = min(ocol)
ValueError: min() arg is an empty sequence
```

Thanks!!
W

**Comment by tanghaibao** [comment]
@wu116 

If peach are duplicated as `peach1.1` and `peach1.2` (in two separate genomic regions), then the blocks file should look like:

```
grape1.1    peach1.1   peach1.2
```

Note each column in the `blocks` files represents a separate genomic region.

**Comment by wu116** [comment]
Thanks for replying!

_I still have one more question:_

_What should the `blocks` file be if the `peach1.1` and `peach1.2` act as tandem duplicated genes that cannot be separated into two genomic regions?_

But I suddenly thought of the solution when I was writing this comment!!!

I tried to swap the order of the first and second column and it plotted the relationship I needed successfully:
```
peach1.1    grape1.1
peach1.2    grape1.1
```
If there are more than 2 species, just make the species with the most abundant duplicated genes to be the first column:
```
cacao1.1    peach1.1    grape1.1
cacao1.2    peach1.2    grape1.1
cacao1.3    peach1.1    grape1.1
cacao1.4    peach1.2    grape1.1
```
It seems that the first column of the `blocks` file has to be non-redundant?

Thanks for such a perfect tool again!!!

p.s.: This is what I wanted:
![360截图20240202110750002](https://github.com/tanghaibao/jcvi/assets/32994564/43fa2fb2-68d2-451a-8d4a-81a502c995ab)
