### ISSUE TITLE
What is the meaning of x-axis and y-axis? Does it represent the number of genes?

### ISSUE THREAD

**Issue by wang7760** [tanghaibao/jcvi#614]
/
![1701769978287](https://github.com/tanghaibao/jcvi/assets/152969255/7ae9d682-93e3-4db4-84bb-685e0541b31f)

**Comment by tanghaibao** [comment]
@wang7760 

Correct. Number of genes.
Genes are listed in the order along each chromosome.

**Comment by wang7760** [comment]
Thanks for your answer。
