### ISSUE TITLE
ImportError: No module named scipy.spatial

### ISSUE THREAD

**Issue by 494118250** [tanghaibao/jcvi#64]
Hi Haibao,
When I repeat the example of MCScanX(Python version), there was a ImportError and did not know how to deal with it.The details are described below:

~$ python -m jcvi.compara.catalog ortholog grape peach
13:28:42 [driver] Generating grammar tables from /usr/lib/python2.7/lib2to3/Grammar.txt
13:28:42 [driver] Generating grammar tables from /usr/lib/python2.7/lib2to3/PatternGrammar.txt
13:28:42 [synteny] Assuming --qbed=grape.bed --sbed=peach.bed
13:28:42 [base] Load file `grape.bed`
13:28:43 [base] Load file `peach.bed`
13:28:43 [base] Load file `grape.peach.last.filtered`
13:28:44 [synteny] A total of 21089 BLAST imported from `grape.peach.last.filtered`.
13:28:44 [synteny] Chaining distance = 20
13:28:44 [base] Load file `grape.peach.anchors`
A total of 14695 (NR:14578) anchors found in 678 clusters.
Stats: Min=4 Max=385 N=678 Mean=21.6740412979 SD=39.560620805 Median=7.0 Sum=14695
NR stats: Min=4 Max=383 N=678 Mean=21.5014749263 SD=39.355416627 Median=7.0 Sum=14578
13:28:44 [base] Load file `grape.bed`
13:28:45 [base] Load file `peach.bed`
13:28:45 [base] Load file `grape.peach.last`
13:28:52 [synteny] A total of 294217 BLAST imported from `grape.peach.last`.
13:28:53 [base] Load file `grape.peach.anchors`
13:28:53 [synteny] A total of 14695 anchors imported.
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/lxg/jcvi/compara/catalog.py", line 811, in <module>
    main()
  File "/home/lxg/jcvi/compara/catalog.py", line 73, in main
    p.dispatch(globals())
  File "jcvi/apps/base.py", line 82, in dispatch
    globals[action](sys.argv[2:])
  File "/home/lxg/jcvi/compara/catalog.py", line 646, in ortholog
    "--liftover={0}".format(last)])
  File "jcvi/compara/synteny.py", line 1416, in scan
    newanchorfile = liftover([lo, anchor_file] + bedopts + ostrip)
  File "jcvi/compara/synteny.py", line 1457, in liftover
    for point, nearest in synteny_liftover(hits, anchors, dist):
  File "jcvi/compara/synteny.py", line 392, in synteny_liftover
    from scipy.spatial import cKDTree
ImportError: No module named scipy.spatial

Hope to get your help
Thanks a lot!
Lixiaoguang

**Comment by tanghaibao** [comment]
@494118250 Try to install the latest version of ``scipy``. I've always found the [miniconda](https://conda.io/miniconda.html) distribution to be easier.

**Comment by 494118250** [comment]
@tanghaibao thanks, the problem has been solved.
