### ISSUE TITLE
Microsynteny getting fancy

### ISSUE THREAD

**Issue by ABDULLAHGUJJAR** [tanghaibao/jcvi#65]
Hi vivekkrish,
i want microsynteny of strawberry with grape.i am following  "blocks2.layout",i a trying adding more chromosomes grapes/strawberry.but i find only three results one is top and 2 is bottom.i want add 7 chromosomes in bottom like article "http://www.nature.com/nature/journal/v492/n7429/full/nature11798.html?foxtrotcallback=true#ref7".
can you tell me, how i can add 7 chromosomes in bottom in  "Microsynteny getting fancy".
Thanks

**Comment by tanghaibao** [comment]
@ABDULLAHGUJJAR 
Can you send the layout file that you used for this?

**Comment by ABDULLAHGUJJAR** [comment]
i am using this layout file.thanks for your reply.

# x,   y, rotation,     ha,     va, color, ratio,            label
0.5, 0.6,        0, center,    top,      ,     1,       grape Chr1
0.3, 0.4,        0, center, bottom,      ,    .5, peach scaffold_1
0.7, 0.4,        0, center, bottom,      ,    .5, cacao scaffold_2
# edges
e, 0, 1
e, 0, 2




________________________________

**Comment by ABDULLAHGUJJAR** [comment]
i am using this layout file.thanks for your reply.

# x,   y, rotation,     ha,     va, color, ratio,            label
0.5, 0.6,        0, center,    top,      ,     1,       grape Chr1
0.3, 0.4,        0, center, bottom,      ,    .5, peach scaffold_1
0.7, 0.4,        0, center, bottom,      ,    .5, cacao scaffold_2
0.5, 0.4,        0, center, bottom,      ,    .5, cacao scaffold_3
# edges
e, 0, 1
e, 0, 2

**Comment by ABDULLAHGUJJAR** [comment]
sorry I am in hurry send you wrong.i am sending you now.i am using this block2.layout file.
# x,   y, rotation,     ha,     va, color, ratio,            label
0.5, 0.6,        0, center,    top,      ,     1,       grape Chr1
0.3, 0.4,        0, center, bottom,      ,    .5, peach scaffold_1
0.7, 0.4,        0, center, bottom,      ,    .5, cacao scaffold_2
0.5, 0.4,        0, center, bottom,      ,    .5, cacao scaffold_3
# edges
e, 0, 1
e, 0, 2
