### ISSUE TITLE
TypeError: expected a sequence of integers or a single integer, got '69.222553'

### ISSUE THREAD

**Issue by karthickbrlab** [tanghaibao/jcvi#667]
python -m jcvi.graphics.landscape stack ~/chr1.fasta --stacks=gene,mrna --window=1000000 --shift=1000000
[05/13/24 16:51:07] INFO     `latex` not found. latex use is disabled.                                                                                                        base.py:620
/home/ubuntu/anaconda3/lib/python3.11/site-packages/pandas/core/arrays/masked.py:60: UserWarning: Pandas requires version '1.3.6' or newer of 'bottleneck' (version '1.3.5' currently installed).
  from pandas.core import (
[05/13/24 16:51:09] INFO     Set text.usetex=False. Font styles may be inconsistent.                                                                                          base.py:435
[16:51:09] DEBUG    Line/stack-plot options: window=1000000 shift=1000000 subtract=None                                                                                  landscape.py:517
                    DEBUG    Load file `/home/ubuntu/deru/Deru_data/lastz/chr1.fasta.sizes`                                                                                    base.py:33
                    DEBUG    sort -k1,1 -k2,2n -k3,3n -k4,4 gene.bed -o gene.bed                                                                                             base.py:1219
[05/13/24 16:51:10] DEBUG    mergeBed -i gene.bed -c 4 -o collapse -delim ";" >gene.merge.bed                                                                                base.py:1219
                    DEBUG    sort -k1,1 -k2,2n -k3,3n -k4,4 gene.merge.bed -o gene.merge.bed                                                                                 base.py:1219
                    DEBUG    Load file `gene.merge.bed`                                                                                                                        base.py:33
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/home/ubuntu/jcvi/jcvi/graphics/landscape.py", line 1088, in <module>
    main()
  File "/home/ubuntu/jcvi/jcvi/graphics/landscape.py", line 136, in main
    p.dispatch(globals())
  File "/home/ubuntu/jcvi/jcvi/apps/base.py", line 141, in dispatch
    globals[action](sys.argv[2:])
  File "/home/ubuntu/jcvi/jcvi/graphics/landscape.py", line 1021, in stack
    binfiles = get_binfiles(bedfiles, fastafile, shift, subtract=subtract, merge=merge)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/jcvi/jcvi/graphics/landscape.py", line 954, in get_binfiles
    binfiles = [bins([x, fastafile] + binopts) for x in inputfiles if op.exists(x)]
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/jcvi/jcvi/graphics/landscape.py", line 954, in <listcomp>
    binfiles = [bins([x, fastafile] + binopts) for x in inputfiles if op.exists(x)]
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/jcvi/jcvi/formats/bed.py", line 1565, in bins
    a = np.zeros(nbins)  # values
        ^^^^^^^^^^^^^^^
TypeError: expected a sequence of integers or a single integer, got '69.222553'

**Comment by tanghaibao** [comment]
@karthickbrlab 

Would you please try to upgrade JCVI to latest version `pip install -U jcvi`?
There is a recent change that should have (at least in theory) fixed this issue.

**Comment by tanghaibao** [comment]
@karthickbrlab 

This is weird. Did the tutorial example (Arabidopsis) work for you?
https://github.com/tanghaibao/jcvi/wiki/Miscellaneous-plotting

Alternatively, please share the mrna.bed (or part of it) so I can reproduce the error. Thanks!

**Comment by karthickbrlab** [comment]
Hi 
Im uploading it as .txt file as bed file is not supported in github


[mrna.txt](https://github.com/tanghaibao/jcvi/files/15315960/mrna.txt)

**Comment by tanghaibao** [comment]
@karthickbrlab 

I'm not exactly sure why this didn't work.
The mRNAs are collectively 500kb in length and may not be obvious on the stack plot.

Make sure it's not the software issue - try it on Arabidopsis data that I mentioned above in the tutorial.

**Comment by karthickbrlab** [comment]
hi

it works on example data.

so what could go wrong with my file?

any suggestions

**Comment by karthickbrlab** [comment]
hi

i tried giving colour codes to chromosomes and features by including .idmap
file, but colour assignment is random..is there any thing to make to assign
them more specific.

Ba1 #BEBADA
Ba2 #FFFFB3
Ba3 #FDB462
Ba4 #8DD3C7
Ba5 #B3DE69
Ba6 #FCCDE5
Ba7 #FB8072
Ba8 #D9D9D9
Ba9 #80B1D3

 --notex=True. latex use is disabled.    base.py:610
[05/23/24 12:43:06] INFO     Set text.usetex=False. Font styles may
 base.py:453
                             be inconsistent.

                    DEBUG    Load file `features.bed`
base.py:36
                    DEBUG    Load file `ba.idmap`
base.py:36
                    DEBUG    Imported 9 records from `ba.idmap`
 base.py:101
                    DEBUG    A total of 9 classes found:
chromosome.py:542
                             #80B1D3,#8DD3C7,#B3DE69,#BEBADA,#

                             D9D9D9,#FB8072,#FCCDE5,#FDB462,#F

                             FFFB3

                    DEBUG    Assigned colors: {'#80B1D3':
 chromosome.py:551
                             '#FFFFB3', '#8DD3C7': '#FB8072',

                             '#B3DE69': '#BEBADA', '#BEBADA':

                             '#8DD3C7', '#D9D9D9': '#FCCDE5',

                             '#FB8072': '#B3DE69', '#FCCDE5':

                             '#FDB462', '#FDB462': '#D9D9D9',

                             '#FFFFB3': '#80B1D3'}

                    DEBUG    Load file `blk.sizes`
 base.py:36



thanks

**Comment by tanghaibao** [comment]
@karthickbrlab 

Please note that the color assignment file is 3 columns, and tab-separated.
Feature name, display name, color code

The second column is there so that people may want to show extra description on the figure.

```
Ba1    B1    #BEBADA
Ba2    B2    #FFFFB3
```

**Comment by karthickbrlab** [comment]
Got it, thanks!
