### ISSUE TITLE
what tools do I need to compare a denovo to a public reference

### ISSUE THREAD

**Issue by splaisan** [tanghaibao/jcvi#67]
I have for the public reference fasta, gff and gbk files
For the denovo obviously contigs in fasta format.
I used nucmer and mummer-plot already but the biplot is not so nice for publication
I also used mauve to order the contigs but the results are not very useful and lack AGP export

Which jcvi commands do I need to compare the two assemblies, reorder+reorientate the denovo contigs to best match the public chromosomes, then plot pairwise, and finally create a AGP formatted comparison file. A full tutorial for these classical steps eluded me so far :-).

Thanks for you help

**Comment by tanghaibao** [comment]
@splaisan 
The closest thing to what you described is in module ``jcvi.assembly.allmaps``, [see also here](https://github.com/tanghaibao/jcvi/wiki/ALLMAPS%3A-How-to-use-different-types-of-genomic-maps). However there are a number of pre-processing steps that use commands in module ``jcvi.compara.synteny``. 

In summary, not yet streamlined.
