### ISSUE TITLE
install error of jcvi

### ISSUE THREAD

**Issue by ma2o-3** [tanghaibao/jcvi#673]
Hi,
I had an error to install the jcvi.
>  pip install -U jcvi
---
Collecting norns>=0.1.6 (from genomepy->jcvi)
  Using cached norns-0.1.6.tar.gz (3.6 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [7 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/private/var/folders/gw/kty3kfl903g8cnyzrj_k50hw0000gn/T/pip-install-8gypfgsf/norns_b4197d869aac486581dacba5ae716ccf/setup.py", line 19, in <module>
          long_description = pypandoc.convert('README.md', 'rst')
                             ^^^^^^^^^^^^^^^^
      AttributeError: module 'pypandoc' has no attribute 'convert'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
---

how can i solve this error?
i am very happy if you give me the suggestion.

best
Hiroki

**Comment by tanghaibao** [comment]
This is a problem with dependency `genomepy` => `norns`, and a known issue.
https://stackoverflow.com/questions/74745548/attributeerror-module-pypandoc-has-no-attribute-convert

The link given requires downgrading `pypandoc`. I'm not sure of other alternative.

A clean install of `jcvi` with no existing `pypandoc` also works. Bottom line, existing version of `pypandoc` on your computer and `norns` don't like each other.

```
python -m venv .venv
.venv/bin/pip install jcvi
```

**Comment by ma2o-3** [comment]
thank you!
its getting running!
