### ISSUE TITLE
It reported "ERROR    Size of `scaffold_19` is empty. Please check"

### ISSUE THREAD

**Issue by YanCheer** [tanghaibao/jcvi#676]
When I tried to plot **Macrosynteny visualization** with the command `python -m jcvi.graphics.karyotype seqids layout`，it reported that to me "ERROR    Size of `scaffold_*` is empty. Please check" with the times equal to the number of scaffolds in both genomes. 
Before this, I have successfully generated the synteny search outputs and the plot with the code like this `python -m jcvi.compara.catalog ortholog XXX ZebraFinch_bTaeGut1_4 --no_strip_names`. So I think the output files of `*.anchors` and input files of `*.bed` should not have any errors. 
I have provided the needed files for karyotype plot, seqids and layout as instrauctions. 
However, it finally reported errors for my size of scaffold/chr, just like this: 
![微信图片_20240609113619](https://github.com/tanghaibao/jcvi/assets/7344943/71cc65f7-baef-4241-a9bb-534ec7a890d2)

Here is an example of my **seqids** file,
> NC_044211.2,NC_044212.2,NC_044213.2
> scaffold_1,scaffold_2,scaffold_3,scaffold_4

this is an example of my **layout** file, 
![微信图片_20240609114146](https://github.com/tanghaibao/jcvi/assets/7344943/3bf99d93-1fa3-4a1b-9a56-36aed62e9b92)

and this is an example of my `*anchors.simple` file, and I generated it with the command as `python -m jcvi.compara.synteny screen --simple XXX_v1.ZebraFinch_bTaeGut1_4.anchors XXX_v1.ZebraFinch_bTaeGut1_4.anchors.bew`
![微信图片_20240609114417](https://github.com/tanghaibao/jcvi/assets/7344943/3d770179-723e-42d5-873c-bde6ea880ad9)

Could anyone help me with this issues? Thank you very much!

**Comment by tanghaibao** [comment]
@YanCheer 

This error means that the script cannot find any genes under  `NC_044211.2` ... in `XXX.bed`, also no genes under `scaffold_*` ... in `ZebraFinch_bTaeGut1_4.bed`.

The order in the `seqids` file has to match the order in the `layout` file. Can you confirm if they are the same? (or try swap the lines in `seqids`)

**Comment by Pedicularis1kib** [comment]
I also have the same problem and have not found an efficient way to resolve it.
this is my command：

**Comment by Pedicularis1kib** [comment]
I also have the same problem and have not found an efficient way to resolve it.
this is my command：
`python -m jcvi.graphics.karyotype seqids.txt layout.txt`
and get the error:
![image](https://github.com/tanghaibao/jcvi/assets/156170003/f6d0f5b4-f369-4783-8a5a-139326347f7d)

this is my .bed file:
![image](https://github.com/tanghaibao/jcvi/assets/156170003/f9d68e19-3231-4cb2-8ef0-85e8b68e4b93)
this is the corresponding .cds file:
![image](https://github.com/tanghaibao/jcvi/assets/156170003/984921dc-5f23-481b-9a33-1f968671e78e)
this is the seqids.txt:
![image](https://github.com/tanghaibao/jcvi/assets/156170003/e9b2e9ec-c282-41a3-bbc0-9ba64e883f3b)
this is the layout.txt:
![image](https://github.com/tanghaibao/jcvi/assets/156170003/755c1e9e-8b27-464c-9932-4ae3fb1f3802)
I appreciate any useful suggestions!

**Comment by tanghaibao** [comment]
@Pedicularis1kib 

The problem is the comment line in the `seqids.txt` that says `#seqids3` (first row)
Basically the row number in the `seqids.txt` file should match the order in the `.bed` file.

I'll change to comments in the `seqids.txt` later, but for now please remove the comments.

Haibao

**Comment by Pedicularis1kib** [comment]
> @Pedicularis1kib
> 
> The problem is the comment line in the `seqids.txt` that says `#seqids3` (first row) Basically the row number in the `seqids.txt` file should match the order in the `.bed` file.
> 
> I'll change to allow comments in the `seqids.txt` later, but for now please remove the comments.
> 
> Haibao

it works! Thank you so much.
