### ISSUE TITLE
converting  mummer result coords file to blast file

### ISSUE THREAD

**Issue by xiaoguizz** [tanghaibao/jcvi#689]
Hello, Mr. Tang
I want to perform collinearity analysis based on the mummer result coords file, in my opinion, this requires converting the coords file to a blast file, but I didn't convert it successfully when I used python -m jcvi.formats.coords blast, and I didn't find the relevant guidance in your wiki, I don't know how to implement the collinearity analysis based on mummer now.
Thank you very much for your reply!

**Comment by tanghaibao** [comment]
@xiaoguizz 

Can you show what the error message was when converting from coords to blast file? thanks.

**Comment by xiaoguizz** [comment]
Hello,
Mr. Tang,
Thank you very much for your timely reply, the mummer transformation problem has been solved, but I don't know how to perform JCVI collinearity analysis based on coords results, do you have any good solutions here?

**Comment by Adamtaranto** [comment]
@xiaoguizz Can you please post your solution here, it may help future users.

Are you trying to do the analysis using whole genome alignments?

**Comment by xiaoguizz** [comment]
Yes, I have now generated the coords file and I want to use JCVI to de-collinearity plots.

**Comment by wangchengww** [comment]
I have the same question as well. I want to conduct a genome synteny analysis using NUCmer. Could you advise on how to plot the multi-genome macrosynteny relationships?

**Comment by tanghaibao** [comment]
Most of the synteny generation and filtering within JCVI is centered around using 'markers' (or genes). While it is possible to carry out this analysis with NUCmer, it is currently unsupported and likely not going to work particularly well for large genomes without tuning the parameters against NUCmer.
