### ISSUE TITLE
findfont: Generic family 'sans-serif' not found because none of the following families were found: Helvetica

### ISSUE THREAD

**Issue by jjjjccccc** [tanghaibao/jcvi#695]
![屏幕截图 2024-07-25 121224](https://github.com/user-attachments/assets/dd64c1cb-fea0-44a3-8b36-9814df0787b0)
文件如上图所示，运行python -m jcvi.compara.catalog ortholog grape peach --no_strip_names后出现许多findfont: Generic family 'sans-serif' not found because none of the following families were found: Helvetica
![屏幕截图 2024-07-25 122559](https://github.com/user-attachments/assets/3a443c85-2caf-46fb-a246-1997d8e38461)
![屏幕截图 2024-07-25 122609](https://github.com/user-attachments/assets/05fa79f4-ec14-4ca3-9552-7bc172e45711)

**Comment by faustovrz** [comment]
install latex in the same environment

**Comment by Rhylan2333** [comment]
如果你没有安装latex的话，添加`--notex`、`--font=Arial`两个参数可能会有帮助。

**Comment by jjjjccccc** [comment]
thanks for helping

**Comment by Rhylan2333** [comment]
Received!
