### ISSUE TITLE
extra command to get all available modules

### ISSUE THREAD

**Issue by splaisan** [tanghaibao/jcvi#70]
@tanghaibao, could you please add a 'list' item so that people not knowing about which modules exist and get their full list with module items like on your front wiki page
like: python -m jcvi.list or python -m jcvi.modules or python -m jcvi.help
I often need to come to your wiki to find back the module/ families names to avoid typos
Thanks
Stephane

**Comment by vivekkrish** [comment]
@splaisan, that is a great suggestion! Quite often, I have found myself coming to github or listing my local git clone directory to list out the module names.

@tanghaibao, along these lines, I have been able to make some minor changes to ActionDispatcher to produce a neat listing of all modules with a brief description (pulled from docstring). I will make a PR, which you can review and accept into the master branch.

Thank you!

**Comment by tanghaibao** [comment]
@splaisan @vivekkrish 

Thanks. There is already a mechanism for listing modules for separate subfolders. For example:
```bash
$ python -m jcvi.assembly
```
will list all modules in the ``assembly`` directory. And for example:
```bash
$ python -m jcvi.compara
```
will list all modules in the ``compara`` directory.

Perhaps one could somehow list all modules for all directories, but the above mechanism should be quite useful already.

**Comment by vivekkrish** [comment]
Hey @tanghaibao,

I believe Stephane was asking for something like this:
```
$ python -m jcvi
Usage:
    python -m jcvi.MODULE


Available MODULEs:
    annotation | Collection of scripts to run annotation tools, perform QC checks and generate summary statistics
          apps | Collection of wrapper scripts for command-line bioinformatics tools, public data downloaders and other generic routines
:
:
:
```

Is that correct, @splaisan?

**Comment by splaisan** [comment]
Exactly @vivekkrish 
You guys know all module family names by heart but when I discovered  the tool I had no clue which modules weree present. Now it is more clear thanks to the wiki but when you have it installed locally, you do not have the wiki with you.
A listing command would be great even if very basic to suggest the possible 'module' names

**Comment by vivekkrish** [comment]
@splaisan please see #72. The code changes have been merged into the master branch. Please pull down the change to your clone as well.

Hope this is useful! Please close the issue if you think your requirements have been addressed.

Thank you.

**Comment by splaisan** [comment]
This is exactly what I was looking for, thanks a lot @vivekkrish and @tanghaibao
:-)
