### ISSUE TITLE
画图时报错ValueError: not enough values to unpack (expected 6, got 3)

### ISSUE THREAD

**Issue by changchuanjun** [tanghaibao/jcvi#701]
使用python -m jcvi.graphics.karyotype --format=pdf --figsize=20x20 seqids_FJ layout_FJ （画20个species）
![image](https://github.com/user-attachments/assets/90f94b50-97a5-4f6f-853b-837bef2e3ae8)
能画出来图，seqid_FJ内容如下：
![image](https://github.com/user-attachments/assets/57b2e29f-b13e-467a-942a-6076aac54c0d)
layout_FJ文件内容如下：
![image](https://github.com/user-attachments/assets/953531e6-4c2b-49f5-96e1-34d4a45a879b)
以上是画20个species的共线性图可以画出来，
![image](https://github.com/user-attachments/assets/387d8668-6345-4011-9af2-03cb1db3cd76)

##################################################################################
但是我现在要画一个26个species的共线性图，于是在上述基础上又添加了6个物种的信息，结果运行时报错
![image](https://github.com/user-attachments/assets/58feec14-6c3c-4f28-9885-3bc7d328f6a0)
想请问一下可能是什么原因呢？

**Comment by tanghaibao** [comment]
@changchuanjun 

26个物种？！真厉害。

这个报错是某个`.simple`文件列数不对，应该是6列。
看下新添加的这几个种间相应的`.simple`文件是否都是正常的列数。

```
head *.simple
```

**Comment by changchuanjun** [comment]
@tanghaibao ，是的，非常感谢👍，按照您的提示，检查了一下新增的这几个simple文件，确实是有一个simple文件格式有问题，现在问题解决了，已经成功画出来26species的共线性图了。
![image](https://github.com/user-attachments/assets/8d32c0d2-ef1a-4cea-aa0c-86e0dfb12e8e)
但是现在又有一个问题，染色体名字太大了，遮挡了很大的区域了，十分不美观，我已经按照统一的染色体名称及顺序把他们都排序好了，所以只用显示最上面或者最下面一个物种所有的染色体名称作为代表就好了，如何更改画布格式文件使其隐藏染色体名称呢？还是说源代码当时没有考虑到我这种情况呀，如果不行的话我再用AI处理一下😀

**Comment by tanghaibao** [comment]
@changchuanjun 

的确太大了。可以看看这两个选项（至少可以关掉圆圈或者染色体字体）：

```
$ python -m jcvi.graphics.karyotype
...
  --keep-chrlabels      Keep chromosome labels [default: False]
  --nocircles           Do not plot chromosome circles [default: False]
...
```

实在不行只有用AI硬调了。

**Comment by tanghaibao** [comment]
染色体圈圈的相关代码在这里，如果会改Python，可以尝试customize一下：

https://github.com/tanghaibao/jcvi/blob/9b9dd69b4b5248129ed91244d46013296203e45c/jcvi/graphics/karyotype.py#L244-L254

**Comment by changchuanjun** [comment]
感谢感谢，加上--keep-chrlabels --nocircles这两个参数，使用python -m jcvi.graphics.karyotype --keep-chrlabels --nocircles --format=pdf --figsize=20x20 seqids layout -o test.pdf命令解决了。
![image](https://github.com/user-attachments/assets/64573a38-1875-427a-937b-b3a2c715fa20)
现在还有一个问题，就是有没有可以用哪一个参数可以控制各个物种之间syntenic flanking genes 之间的高亮连线的线条宽度呀？

**Comment by tanghaibao** [comment]
@changchuanjun 

这个没有option，需要改`lw`

https://github.com/tanghaibao/jcvi/blob/9b9dd69b4b5248129ed91244d46013296203e45c/jcvi/graphics/karyotype.py#L322

**Comment by changchuanjun** [comment]
@tanghaibao  好嘞，感谢感谢👍  我尝试一下改写一下原脚本，添加一个linewidth的paramater，方便不断变化参数选出一个最佳效果😀
