### ISSUE TITLE
画图时出现警告信息：WARNING  Shade: None found in coordinates, skipping

### ISSUE THREAD

**Issue by changchuanjun** [tanghaibao/jcvi#710]
作者您好，感谢你开发的一个实用工具！
我现在遇到一个问题，想请您帮忙指点以下，万分感谢。
我画图时能成功运行，但是中间会出现好多行的相同的警告信息：
WARNING  Shade: None found in coordinates, skipping                                                 synteny.py:175，
![image](https://github.com/user-attachments/assets/6264aa2e-17ae-4011-85fb-d5773a324863)
请问出现这个警告信息的原因是什么呢？影响最终的结果吗？

最终的结果图是可以成功画出来的
![image](https://github.com/user-attachments/assets/56a4cc8c-447e-4993-8679-b2562407da7a)

**Comment by tanghaibao** [comment]
@changchuanjun 

不影响结果。这些是因为有些共线性区块所在染色体不在seqids之列（通常是因为`chr_Un`或者其他未锚定contigs上）。
我后面会移除这些（无用的）警告信息。

**Comment by changchuanjun** [comment]
@tanghaibao 好的，感谢感谢👍

**Comment by changchuanjun** [comment]
@tanghaibao 好的，感谢感谢👍
