### ISSUE TITLE
Change color of inversions

### ISSUE THREAD

**Issue by alexzaccaron** [tanghaibao/jcvi#714]
Hello,

I am generating a synteny plot using
```
python -m jcvi.graphics.karyotype --figsize=10x13 --chrstyle=rect seqids layout
```

It works really well. The chromosomes I am plotting have many inversions, which I would like to highlight somehow. Is there a way to change the color of the syntenic wedges that are inversions? Also, just a small detail, but is there a way to ommit the chomosome labels?

Thank you for this nice tool

<img width="749" alt="jcvi_inversions" src="https://github.com/user-attachments/assets/3021ae1d-ebab-4545-97fd-ae620ea14c97">

**Comment by tanghaibao** [comment]
@alexzaccaron 

The blocks can be generally colored following the tutorial ("What if we want to highlight a specific block?"):
https://github.com/tanghaibao/jcvi/wiki/MCscan-(Python-version)

However, there is no support to automatically color inversions at this point. It's not hard, but it needs some coding.

The chromosome labels can be removed with this option:

```console
  --nocircles           Do not plot chromosome circles [default: False]
```

Haibao

**Comment by alexzaccaron** [comment]
Hi Haibao,

Thank you for your reply.
Instead of trying to change the code, I changed the anchor files to add color to the inversions, based on the tutorial you mentioned.
```
for SIMPLE in *anchors.simple; do 
   sed -i '/-$/ s/^/g*/g' $SIMPLE; 
done
```

My apologies, I missed the `--nocircles` option in the help page to hide the chr labels.

The resulting plot is what I wanted.
Thank you

<img width="830" alt="jcvi_inversions_color" src="https://github.com/user-attachments/assets/97509ef4-dceb-424a-ac8f-4b0cf6681536">
