### ISSUE TITLE
Error: some genes in blocks can't be found, please rerun after making sure that bed file agree with simple file

### ISSUE THREAD

**Issue by oddguyeee** [tanghaibao/jcvi#727]
I used this cmd to visualize synteny:
```sh
python3 -m jcvi.graphics.karyotype all.seqids all.layout --format=pdf  --figsize=15x10  --shadestyle=curve --chrstyle=roundrect -o Primula_4sp_raw.pdf
```
But encountered a error like this:
```sh
pveT_jg18160 pveT_jg18218 evm.model.Pflo_scaf9.2073 evm.model.Pflo_scaf9.2123 can not found in bed files.
pveT_jg18245 pveT_jg18418 evm.model.Pflo_scaf9.1233 evm.model.Pflo_scaf9.1631 can not found in bed files.
pveT_jg18441 pveT_jg18611 evm.model.Pflo_scaf9.616 evm.model.Pflo_scaf9.1068 can not found in bed files.
.........................
pveT_jg18623 pveT_jg18687 evm.model.Pflo_scaf9.408 evm.model.Pflo_scaf9.539 can not found in bed files.
pveT_jg18708 pveT_jg18920 evm.model.Pflo_scaf9.5 evm.model.Pflo_scaf9.319 can not found in bed files.
pveT_jg18975 pveT_jg19011 evm.model.Pflo_scaf10.5407 evm.model.Pflo_scaf10.5464 can not found in bed files.
Error: some genes in blocks can't be found, please rerun after making sure that bed file agree with simple file.
```
I've checked some item in the error information. However, all of them were indeed in `bed` and `simple` files. Furthermore, I also try to run jcvi.graphics.karyotype with `Primula_edelbergii.Primula_alpicola.anchors.simple` ,`Primula_florindae.Primula_alpicola.anchors.simple`  `Primula_veris.Primula_edelbergii.anchors.simple`,`Primula_edelbergii.Primula_florindae.anchors.simple` ,`Primula_veris.Primula_alpicola.anchors.simple` ,`Primula_veris.Primula_florindae.anchors.simple`, respectively. Errors only occur in species pairs which emcompressed Primula_veris. However, I as say above, all of gene items were indeed in `bed` corresponding those in `simple` files.

How can I deal with this problem? Any suggestion must be be deeply grateful, whether in English or `Chinese`. Thank you!!

In addition, all of dotplots, including pairs with Primula veris, were succssfully produced by `jcvi.compara.catalog ortholog`. And both `bed` and `simple` files in this analysis were processed by `jcvi`.

If you need any data I used, just please let me konw. Thank you !!!!!

`all.seqids`
```
Palp_scaf1,Palp_scaf2,Palp_scaf3,Palp_scaf4,Palp_scaf5,Palp_scaf6,Palp_scaf7,Palp_scaf8,Palp_scaf9,Palp_scaf10,Palp_scaf11
Pflo_scaf1,Pflo_scaf2,Pflo_scaf3,Pflo_scaf4,Pflo_scaf5,Pflo_scaf6,Pflo_scaf7,Pflo_scaf8,Pflo_scaf9,Pflo_scaf10,Pflo_scaf11
pve_haplotypeT_001,pve_haplotypeT_002,pve_haplotypeT_003,pve_haplotypeT_004,pve_haplotypeT_005,pve_haplotypeT_006,pve_haplotypeT_007,pve_haplotypeT_008,pve_haplotypeT_009,pve_haplotypeT_010,pve_haplotypeT_011
ped_chr001,ped_chr002,ped_chr003,ped_chr004,ped_chr005,ped_chr006,ped_chr007,ped_chr008,ped_chr009
```
`all.layout`
```
# y, xstart, xend, rotation, color, label, va,  bed
 .7,     .05,    .48,      20,      pink, Palp, top, Primula_alpicola.bed
 .7,     .52,    .95,       20,      orange, Pflo, top, Primula_florindae.bed
 .5,     .35,    .65,      0,      yellow, Pver, top, Primula_veris.bed
 .2,     .30,    .70,       0,      blue, Pede, top, Primula_edelbergii.bed
# edges
e, 0, 2, Primula_veris.Primula_florindae.anchors.simple
e, 1, 2, Primula_veris.Primula_alpicola.anchors.simple
e, 2, 3, Primula_veris.Primula_edelbergii.anchors.simple
```

**Comment by oddguyeee** [comment]
I have already solved the problem, just a little mistake regard to indices of edges. `Jcvi` must be a great program!!!!!!!!

**Comment by tanghaibao** [comment]
Thanks @oddguyeee. Closing issue but feel free to reopen if the problem persists.
