### ISSUE TITLE
Error:Pairwise synteny search

### ISSUE THREAD

**Issue by ABDULLAHGUJJAR** [tanghaibao/jcvi#75]
00:04:49 [synteny] A total of 0 BLAST imported from `hirsutum.raimondi.last.filtered`.
00:04:49 [synteny] Chaining distance = 20
00:04:49 [base] Load file `hirsutum.raimondi.anchors`
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/Users/Abdullah/Library/Python/2.7/lib/python/site-packages/jcvi/compara/catalog.py", line 811, in <module>
    main()
  File "/Users/Abdullah/Library/Python/2.7/lib/python/site-packages/jcvi/compara/catalog.py", line 73, in main
    p.dispatch(globals())
  File "/Users/Abdullah/Library/Python/2.7/lib/python/site-packages/jcvi/apps/base.py", line 87, in dispatch
    globals[action](sys.argv[2:])
  File "/Users/Abdullah/Library/Python/2.7/lib/python/site-packages/jcvi/compara/catalog.py", line 646, in ortholog
    "--liftover={0}".format(last)])
  File "/Users/Abdullah/Library/Python/2.7/lib/python/site-packages/jcvi/compara/synteny.py", line 1464, in scan
    summary([anchor_file])
  File "/Users/Abdullah/Library/Python/2.7/lib/python/site-packages/jcvi/compara/synteny.py", line 1042, in summary
    nranchors = [_score(c) for c in clusters]  # non-redundant anchors
  File "/Users/Abdullah/Library/Python/2.7/lib/python/site-packages/jcvi/compara/synteny.py", line 260, in _score
    x, y = zip(*cluster)[:2]
ValueError: need more than 0 values to unpack

**Comment by tanghaibao** [comment]
@ABDULLAHGUJJAR 
It seems that the BLAST file is likely empty or names are not maching up between the BLAST output and the BED files. Would you please send first few lines of file `hirsutum.raimondi.last.filtered`, `hirsutum.bed` and `raimondi.bed`?

**Comment by ABDULLAHGUJJAR** [comment]
yes,hirsutum.raimondi.last.filtered is empty.
hirsutum.bed
A01	15704	19194	m%2Cr%2Cn%2Ca%2C_%2C4%2C9%2C5%2C3	0	+
A01	22807	24529	m%2Cr%2Cn%2Ca%2C_%2C4%2C9%2C7%2C0	0	+
A01	36427	36860	m%2Cr%2Cn%2Ca%2C_%2C4%2C9%2C7%2C9	0	-
raimondi.bed
Chr01	6157	6456	Gorai.001G000100.1	0	-
Chr01	6986	7491	Gorai.001G000200.1	0	-
Chr01	7491	12104	Gorai.001G000300.1	0	-
Chr01	7491	9809	Gorai.001G000300.2	0	-

**Comment by ABDULLAHGUJJAR** [comment]
**# I try by using different crops but i am finding same problem except crop (grape, peach).**
appledeMacBook-Pro-3:Downloads Abdullah$ python -m jcvi.formats.gff bed --type=mRNA --key=Name Osativa_204_v7.0.gene.gff3.gz -o osativa.bed
10:57:03 [base] Load file `Osativa_204_v7.0.gene.gff3.gz`
10:57:27 [gff] Extracted 49061 features (type=mRNA id=Name)
appledeMacBook-Pro-3:Downloads Abdullah$ python -m jcvi.formats.fasta format --sep="|" Osativa_204_v7.0.cds.fa.gz osativa.cds
appledeMacBook-Pro-3:Downloads Abdullah$ python -m jcvi.compara.catalog ortholog grape osativa
10:59:08 [base] lastdb osativa osativa.cds
10:59:43 [base] lastal -u 0 -P 4 -i3G -f BlastTab osativa grape.cds >grape.osativa.last
11:00:42 [synteny] Assuming --qbed=grape.bed --sbed=osativa.bed
11:00:42 [base] Load file `grape.bed`
11:00:42 [base] Load file `osativa.bed`
11:00:43 [blastfilter] Load BLAST file `grape.osativa.last` (total 357447 lines)
11:00:43 [base] Load file `grape.osativa.last`
11:00:46 [blastfilter] LOC_Os05g07050 not in osativa.bed
11:00:46 [blastfilter] LOC_Os11g01380 not in osativa.bed
11:00:46 [blastfilter] LOC_Os12g01390 not in osativa.bed
11:00:46 [blastfilter] LOC_Os11g01380 not in osativa.bed
11:00:46 [blastfilter] LOC_Os12g01390 not in osativa.bed
11:00:46 [blastfilter] LOC_Os02g47970 not in osativa.bed

**Comment by tanghaibao** [comment]
@ABDULLAHGUJJAR 
Make sure the identifiers in the BED file and the LAST file match. What are the contents in `hirsutum.raimondi.last`?

**Comment by ABDULLAHGUJJAR** [comment]
@tanghaibao @Jingping @vivekkrish ,hi,i am using different genome cds and gff3 files,but i found same error.i try by changing computer but same error.i think my "hirsutum.raimondi.last have no problem.i use strawberry genome with grape but same error.kindly you check this error and guide me.if you want i can send you genome cds and gff3 files.please help me on this error.i will be very thankful.i am attaching here picture of hirsutum.bed and hirsutum.raimondi.last files.kindly help me,i am waiting for your reply.

**Comment by tanghaibao** [comment]
@ABDULLAHGUJJAR 
Looking at the gene names in `hirsutum.bed`, all gene names seem mangled. It is likely that you were converting from a gzipped gff file and we were not able to identify the specific gff format. Before you converted the gff to the bed, could you try unzipping the file?

**Comment by ABDULLAHGUJJAR** [comment]
@tanghaibao i use with first unzip gff3 file, after that again same hirsutum.bed.i have tried with unzipping and zipping but error is same. even for strawberry "bed file" name looking no problem but for this is also same error.

**Comment by tanghaibao** [comment]
@ABDULLAHGUJJAR 
Then there is something wrong with the gff file, or the conversion is faulty. The names are all wrong in the `hirsutum.bed` (names are in the 4th column, currently they look like "m%2Cr%2Cn%2Ca%2C_%2C4%2C9%2C5%2C3" which is gibberish). 

Would you mind sending the gff file?

**Comment by ABDULLAHGUJJAR** [comment]
muhammad abdullah has shared a OneDrive file with you. To view it, click the link below.


<https://1drv.ms/u/s!AhQGATZXTCspkTZTYKUUniB0Cu-g>
[https://r1.res.office365.com/owa/prem/images/dc-generic_20.png]<https://1drv.ms/u/s!AhQGATZXTCspkTZTYKUUniB0Cu-g>

gene.hirsutum.NAU.gff3.gz<https://1drv.ms/u/s!AhQGATZXTCspkTZTYKUUniB0Cu-g>





i am sending you gff3 file.thanks for your cooperation.

________________________________

**Comment by vivekkrish** [comment]
@ABDULLAHGUJJAR @tanghaibao, it seems that in your GFF3 file, the `mRNA` features do not have a `Name` attribute
```
A01	EVM	mRNA	15705	19194	.	+	.	ID=Gh_A01G0001.1;Parent=Gh_A01G0001
```

As such, by executing the command `python -m jcvi.formats.gff bed --type=mRNA --key=Name` on the GFF3 file, the script is inventing a new `Name` for each **mRNA** (using the template `ftype_linenumber`), and in that process, also mangling the name.

For e.g. the first **mRNA** feature appears on the line 4953. So, the invented `Name` is **mrna_4953**, which when mangled with the `%2C` (which is the comma symbol), corresponds to `m%2Cr%2Cn%2Ca%2C_%2C4%2C9%2C5%2C3`.

The issue is in this section of the code: https://github.com/tanghaibao/jcvi/blob/master/formats/gff.py#L179-L188

I have gone ahead and issued a fix which should correct the issue.

However, you should reformat your command to extract the `ID` attribute instead of `Name`.

**Comment by ABDULLAHGUJJAR** [comment]
muhammad abdullah has shared a OneDrive file with you. To view it, click the link below.


<https://1drv.ms/u/s!AhQGATZXTCspkTe5S35EbsrCCtvu>
[https://r1.res.office365.com/owa/prem/images/dc-generic_20.png]<https://1drv.ms/u/s!AhQGATZXTCspkTe5S35EbsrCCtvu>

CDS.seq.hirsutum.NAU.fa.gz<https://1drv.ms/u/s!AhQGATZXTCspkTe5S35EbsrCCtvu>




I am sending you cds file,you can check it same error.now bed file name is correct .i check with you instruction.i am facing with other crop that bed file name is correct like strawberry.error that i mention in first.


________________________________

**Comment by vivekkrish** [comment]
OK, next, the issue seems to be that your CDS FASTA file does not originate from Phytozome, as such, the FASTA header does not follow the form (which is using "|" pipe separator):
```
>GSVIVT01000001001|PACid:17816625
>GSVIVT01000002001|PACid:17816626
```

Your FASTA file has the following header style:
```
>Gh_D12G2826.1 NAME:LIMYB; DESC:L10-interacting MYB domain-containing protein ; LOC:scaffold4651_D12|12888..14029|-;
>Gh_D12G2827.1 NAME:At5g06290; DESC:2-Cys peroxiredoxin BAS1-like, chloroplastic ; LOC:scaffold4651_D12|15048..17035|+;
```

So, you should alter the FASTA formatting command like so:
```
python -m jcvi.formats.fasta --nodesc CDS.seq.hirsutum.NAU.fa.gz hirsutum.cds
```

This will remove the verbose information in the header line and leave you with:
```
>Gh_D12G2826.1
>Gh_D12G2827.1
```

**Comment by ABDULLAHGUJJAR** [comment]
appledeMacBook-Pro-3:Downloads Abdullah$ python -m jcvi.formats.fasta --nodesc CDS.seq.hirsutum.NAU.fa.gz hirsutum.cds
[error] --nodesc not a valid ACTION

Did you mean one of these?
	

Usage:
    python -m jcvi.formats.fasta ACTION


Available ACTIONs:
          clean | Remove irregular chars in FASTA seqs
           diff | Check if two fasta records contain same information
        extract | Given fasta file and seq id, retrieve the sequence in fasta format
          fastq | Combine fasta and qual to create fastq file
         filter | Filter the records by size
         format | Trim accession id to the first space or switch id based on 2-column mapping file
        fromtab | Convert 2-column sequence file to FASTA format
           gaps | Print out a list of gap sizes within sequences
      identical | Given 2 fasta files, find all exactly identical records
            ids | Generate a list of headers
           info | Run `sequence_info` on fasta files
          ispcr | Reformat paired primers into isPcr query format
           join | Concatenate a list of seqs and add gaps in between
     longestorf | Find longest orf for CDS fasta
           pair | Sort paired reads to .pairs, rest to .fragments
    pairinplace | Starting from fragment.fasta, find if adjacent records can form pairs
           pool | Pool a bunch of fastafiles together and add prefix
           qual | Generate dummy .qual file based on FASTA file
         random | Randomly take some records
         sequin | Generate a gapped fasta file for sequin submission
           some | Include or exclude a list of records (also performs on .qual file if available)
           sort | Sort the records by IDs, sizes, etc.
        summary | Report the real no of bases and N's in fasta files
           tidy | Normalize gap sizes and remove small components in fasta
      translate | Translate CDS to proteins
           trim | Given a cross_match screened fasta, trim the sequence
      trimsplit | Split sequences at lower-cased letters
           uniq | Remove records that are the same

JCVI utility libraries v0.7.3 [Copyright (c) 2010-2017, Haibao Tang]
appledeMacBook-Pro-3:Downloads Abdullah$

**Comment by vivekkrish** [comment]
Sorry, I mistyped the command. It should be:
```
python -m jcvi.formats.fasta  format --nodesc CDS.seq.hirsutum.NAU.fa.gz hirsutum.cds
```

**Comment by ABDULLAHGUJJAR** [comment]
@vivekkrish thank you sooooooo much.i am working on it. just need to check.after that i will inform you.thankyou

**Comment by ABDULLAHGUJJAR** [comment]
@vivekkrish still error as your instruction i use for both hirsutum and raimondi and now both bed and cds file correct for hirsutum and raimondi but still error???
appledeMacBook-Pro-3:Downloads Abdullah$ python -m jcvi.compara.catalog ortholog hirsutum raimondi
03:35:39 [base] lastdb raimondi raimondi.cds
03:35:58 [base] lastal -u 0 -P 4 -i3G -f BlastTab raimondi hirsutum.cds >hirsutum.raimondi.last
03:39:11 [synteny] Assuming --qbed=hirsutum.bed --sbed=raimondi.bed
03:39:11 [base] Load file `hirsutum.bed`
03:39:12 [base] Load file `raimondi.bed`
03:39:14 [blastfilter] Load BLAST file `hirsutum.raimondi.last` (total 1336417 lines)
03:39:14 [base] Load file `hirsutum.raimondi.last`
03:39:26 [blastfilter] Gh_D07G1808 not in hirsutum.bed
03:39:26 [blastfilter] Gh_A07G1608 not in hirsutum.bed
03:39:26 [blastfilter] Gh_D12G1346 not in hirsutum.bed
03:39:26 [blastfilter] Gh_A12G1222 not in hirsutum.bed
03:39:26 [blastfilter] Gh_D08G1755 not in hirsutum.bed
03:39:26 [blastfilter] Gh_A10G1566 not in hirsutum.bed
03:39:26 [blastfilter] Gh_A03G0037 not in hirsutum.bed
03:39:26 [blastfilter] Gh_D03G1614 not in hirsutum.bed
03:39:26 [blastfilter] Gh_D10G1822 not in hirsutum.bed
03:39:26 [blastfilter] Gh_D11G1778 not in hirsutum.bed
03:39:26 [blastfilter] Gh_A11G1618 not in hirsutum.bed
03:39:26 [blastfilter] Gh_D01G0740 not in hirsutum.bed
03:39:26 [blastfilter] Gh_D05G2525 not in hirsutum.bed
03:39:26 [blastfilter] Gh_D06G0250 not in hirsutum.bed
03:39:26 [blastfilter] Gh_D05G2097 not in hirsutum.bed
03:39:26 [blastfilter] Gh_A05G2265 not in hirsutum.bed
03:39:26 [blastfilter] Gh_D11G1305 not in hirsutum.bed
03:39:26 [blastfilter] Gh_D03G0089 not in hirsutum.bed
03:39:26 [blastfilter] Gh_A06G0248 not in hirsutum.bed
03:39:26 [blastfilter] Gh_D08G0502 not in hirsutum.bed
03:39:26 [blastfilter] Gh_A02G1633 not in hirsutum.bed
03:39:26 [blastfilter] Gh_D02G0861 not in hirsutum.bed
03:39:26 [blastfilter] Gh_A10G2284 not in hirsutum.bed
03:39:26 [blastfilter] Gh_D08G1755 not in hirsutum.bed
03:39:26 [blastfilter] Gh_A01G0721 not in hirsutum.bed
03:39:26 [blastfilter] Gh_A08G0411 not in hirsutum.bed
03:39:26 [blastfilter] Gh_A02G0812 not in hirsutum.bed
03:39:26 [blastfilter] Gh_D01G1779 not in hirsutum.bed
03:39:26 [blastfilter] Gh_D11G1901 not in hirsutum.bed
03:39:26 [blastfilter] Gh_A03G0037 not in hirsutum.bed
03:39:26 [blastfilter] Gh_D04G0176 not in hirsutum.bed
03:39:26 [blastfilter] Gh_A11G1742 not in hirsutum.bed
03:39:26 [blastfilter] Gh_A01G1530 not in hirsutum.bed
03:39:26 [blastfilter] Gh_D02G2103 not in hirsutum.bed
03:39:26 [blastfilter] Gh_D03G1614 not in hirsutum.bed
03:39:26 [blastfilter] Gh_A08G1459 not in hirsutum.bed
03:39:26 [blastfilter] Gh_D08G0368 not in hirsutum.bed
03:39:26 [blastfilter] Gh_A11G0753 not in hirsutum.bed
03:39:26 [blastfilter] Gh_A10G2249 not in hirsutum.bed
03:39:26 [blastfilter] Gh_A05G2265 not in hirsutum.bed
03:39:26 [blastfilter] Gh_D05G2525 not in hirsutum.bed
03:39:26 [blastfilter] Gh_D06G0250 not in hirsutum.bed
03:39:26 [blastfilter] Gh_A06G0248 not in hirsutum.bed
03:39:26 [blastfilter] Gh_D08G1428 not in hirsutum.bed
03:39:26 [blastfilter] Gh_D05G0647 not in hirsutum.bed
03:39:26 [blastfilter] Gh_D07G0024 not in hirsutum.bed
03:39:26 [blastfilter] Gh_D12G0337 not in hirsutum.bed
03:39:26 [blastfilter] Gh_D02G1138 not in hirsutum.bed
03:39:26 [blastfilter] Gh_D05G0990 not in hirsutum.bed
03:39:26 [blastfilter] Gh_A12G0328 not in hirsutum.bed
03:39:26 [blastfilter] Gh_A07G0018 not in hirsutum.bed
03:39:26 [blastfilter] Gh_A03G0827 not in hirsutum.bed
03:39:26 [blastfilter] Gh_D05G2101 not in hirsutum.bed
03:39:26 [blastfilter] Gh_D05G2526 not in hirsutum.bed
03:39:26 [blastfilter] Gh_A05G0907 not in hirsutum.bed
03:39:26 [blastfilter] Gh_D11G2503 not in hirsutum.bed
03:39:26 [blastfilter] Gh_A05G2266 not in hirsutum.bed
03:39:26 [blastfilter] Gh_D05G3178 not in hirsutum.bed
03:39:26 [blastfilter] Gh_D11G1037 not in hirsutum.bed
03:39:26 [blastfilter] Gh_A11G2208 not in hirsutum.bed
03:39:26 [blastfilter] Gh_A05G2869 not in hirsutum.bed
03:39:26 [blastfilter] Gh_D07G2262 not in hirsutum.bed
03:39:26 [blastfilter] Gh_A06G0515 not in hirsutum.bed
03:39:26 [blastfilter] Gh_A05G0143 not in hirsutum.bed
03:39:26 [blastfilter] Gh_D10G0536 not in hirsutum.bed
03:39:26 [blastfilter] Gh_D02G1894 not in hirsutum.bed
03:39:26 [blastfilter] Gh_A11G0890 not in hirsutum.bed
03:39:26 [blastfilter] Gh_D11G1247 not in hirsutum.bed
03:39:26 [blastfilter] Gh_D08G1989 not in hirsutum.bed
03:39:26 [blastfilter] Gh_D01G0092 not in hirsutum.bed
03:39:26 [blastfilter] Gh_D12G2836 not in hirsutum.bed
03:39:26 [blastfilter] Gh_D13G1119 not in hirsutum.bed
03:39:26 [blastfilter] Gh_A05G0397 not in hirsutum.bed
03:39:26 [blastfilter] Gh_A06G1045 not in hirsutum.bed
03:39:26 [blastfilter] Gh_A05G0553 not in hirsutum.bed
03:39:26 [blastfilter] Gh_D05G2554 not in hirsutum.bed
03:39:26 [blastfilter] Gh_D06G0572 not in hirsutum.bed
03:39:26 [blastfilter] Gh_D11G0949 not in hirsutum.bed
03:39:26 [blastfilter] Gh_D01G1885 not in hirsutum.bed
03:39:26 [blastfilter] Gh_D12G1091 not in hirsutum.bed
03:39:26 [blastfilter] Gh_A08G1459 not in hirsutum.bed
03:39:26 [blastfilter] Gh_D11G0352 not in hirsutum.bed
03:39:26 [blastfilter] Gh_D10G0536 not in hirsutum.bed
03:39:26 [blastfilter] too many warnings.. suppressed
03:39:29 [blastfilter] running the cscore filter (cscore>=0.70) ..
03:39:29 [blastfilter] after filter (0->0) ..
03:39:29 [blastfilter] running the local dups filter (tandem_Nmax=10) ..
03:39:29 [blastfilter] after filter (0->0) ..
03:39:30 [synteny] Assuming --qbed=hirsutum.bed --sbed=raimondi.bed
03:39:30 [base] Load file `hirsutum.bed`
03:39:31 [base] Load file `raimondi.bed`
03:39:32 [base] Load file `hirsutum.raimondi.last.filtered`
03:39:32 [synteny] A total of 0 BLAST imported from `hirsutum.raimondi.last.filtered`.
03:39:32 [synteny] Chaining distance = 20
03:39:32 [base] Load file `hirsutum.raimondi.anchors`
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/Users/Abdullah/Library/Python/2.7/lib/python/site-packages/jcvi/compara/catalog.py", line 811, in <module>
    main()
  File "/Users/Abdullah/Library/Python/2.7/lib/python/site-packages/jcvi/compara/catalog.py", line 73, in main
    p.dispatch(globals())
  File "/Users/Abdullah/Library/Python/2.7/lib/python/site-packages/jcvi/apps/base.py", line 87, in dispatch
    globals[action](sys.argv[2:])
  File "/Users/Abdullah/Library/Python/2.7/lib/python/site-packages/jcvi/compara/catalog.py", line 646, in ortholog
    "--liftover={0}".format(last)])
  File "/Users/Abdullah/Library/Python/2.7/lib/python/site-packages/jcvi/compara/synteny.py", line 1464, in scan
    summary([anchor_file])
  File "/Users/Abdullah/Library/Python/2.7/lib/python/site-packages/jcvi/compara/synteny.py", line 1042, in summary
    nranchors = [_score(c) for c in clusters]  # non-redundant anchors
  File "/Users/Abdullah/Library/Python/2.7/lib/python/site-packages/jcvi/compara/synteny.py", line 260, in _score
    x, y = zip(*cluster)[:2]
ValueError: need more than 0 values to unpack

**Comment by wzhjlau2009** [comment]
@ABDULLAHGUJJAR，@tanghaibao
Hi,  I have met the same error , can you help me to solve the problem, kindly help me,i am waiting for your reply,thanks.
