### ISSUE TITLE
bed file error

### ISSUE THREAD

**Issue by SAMANDOLL** [tanghaibao/jcvi#78]
@tanghaibao @vivekkrish kindly please guide me.i have same error.i am working for one month,i can't solve this.please help me.i am using even cds and gff3 file from phytozome 10 for strawberry and rice but same error after blast error apear not found in bed file.
appledeMacBook-Pro-3:Downloads Abdullah$ python -m jcvi.compara.catalog ortholog grape strawberry1
01:59:50 [base] lastdb strawberry1 strawberry1.cds
02:00:07 [base] lastal -u 0 -P 4 -i3G -f BlastTab strawberry1 grape.cds >grape.strawberry1.last
02:01:08 [synteny] Assuming --qbed=grape.bed --sbed=strawberry1.bed
02:01:08 [base] Load file `grape.bed`
02:01:09 [base] Load file `strawberry1.bed`
02:01:09 [blastfilter] Load BLAST file `grape.strawberry1.last` (total 361041 lines)
02:01:09 [base] Load file `grape.strawberry1.last`
02:01:13 [blastfilter] mrna15731.1-v1 not in strawberry1.bed
02:01:13 [blastfilter] mrna01602.1-v1 not in strawberry1.bed
02:01:13 [blastfilter] mrna24411.1-v1 not in strawberry1.bed
02:01:13 [blastfilter] mrna15440.1-v1 not in strawberry1.bed
02:01:13 [blastfilter] mrna07940.1-v1 not in strawberry1.bed
02:01:13 [blastfilter] mrna20994.1-v1 not in strawberry1.bed
02:01:13 [blastfilter] mrna16707.1-v1 not in strawberry1.bed
02:01:13 [blastfilter] mrna20994.1-v1 not in strawberry1.bed
02:01:13 [blastfilter] mrna07940.1-v1 not in strawberry1.bed
02:01:13 [blastfilter] mrna20366.1-v1 not in strawberry1.bed
02:01:13 [blastfilter] mrna30932.1-v1 not in strawberry1.bed
02:01:13 [blastfilter] mrna24411.1-v1 not in strawberry1.bed
02:01:13 [blastfilter] mrna12856.1-v1 not in strawberry1.bed
02:01:13 [blastfilter] mrna12700.1-v1 not in strawberry1.bed
02:01:13 [blastfilter] mrna11610.1-v1 not in strawberry1.bed
02:01:13 [blastfilter] mrna12700.1-v1 not in strawberry1.bed
02:01:13 [blastfilter] mrna08375.1-v1 not in strawberry1.bed
02:01:13 [blastfilter] mrna19353.1-v1 not in strawberry1.bed
02:01:13 [blastfilter] mrna11225.1-v1 not in strawberry1.bed
02:01:13 [blastfilter] mrna01020.1-v1 not in strawberry1.bed
02:01:13 [blastfilter] mrna31723.1-v1 not in strawberry1.bed
02:01:13 [blastfilter] mrna18626.1-v1 not in strawberry1.bed
02:01:13 [blastfilter] mrna21129.1-v1 not in strawberry1.bed
02:01:13 [blastfilter] mrna10631.1-v1 not in strawberry1.bed
02:01:13 [blastfilter] mrna18596.1-v1 not in strawberry1.bed
please fix it for me.i will be thankful.

**Comment by ABDULLAHGUJJAR** [comment]
@SAMANDOLL @tanghaibao @vivekkrish i am facing same error,but no solution.i think MCscan is a very good, if its working for other crop.its really amazing but unfortunately not working for other crop only working for few crops.
