### ISSUE TITLE
BioNano data

### ISSUE THREAD

**Issue by ascendo** [tanghaibao/jcvi#8]
Dear Haibao,

Is there anyway to use Bionano data?

The tutorial shows only opgen data and I think it's a little bit difficult to use.

But I just want to check it.

Won

**Comment by tanghaibao** [comment]
@ascendo I have not tested ALLMAPS on BioNano data. In theory, if you can format the BED file properly (see examples in tutorial) you may be able to get it to run. But it is currently unsupported.

**Comment by ascendo** [comment]
Thank you for your answer.
