### ISSUE TITLE
No PDF figure if a chromosome is composed by one single contig?

### ISSUE THREAD

**Issue by StefanoLonardi** [tanghaibao/jcvi#83]
Hello,
I have been using ALLMAPS several times, and it is a wonderful tool. Today we received an dovetail assembly which I ran through ALLMAPS. Surprisingly, I did not get the PDF for the all the chromosomes (chr2 is missing). I took a look at the .agp file, and it turns out that chromosome two is composed by one single dovetail contig (see below). Would that be a reason to skip the plot? Maybe a little bug? :)

I tried again now using `python -m jcvi.assembly.allmaps plotall map.bed --figsize=12x36 --dpi=600 --format=eps` and ALLMAPS skips chr2.

> 15:16:19 [base] Load file `map.agp`
> 15:16:19 [base] Load file `map.lifted.bed`
> 15:16:22 [allmaps] Map contains 146675 markers in 110 linkage groups.
> 15:16:24 [base] Load file `weights.txt`
> 15:16:24 [base] Imported 10 records from `weights.txt`.
> 15:16:24 [allmaps] Map weights: [('27B', 1), ('WC', 1), ('27I', 1), ('SV', 1), ('NF', 1), ('46I', 1), ('27U', 1), ('ZZ', 1), ('TI', 1), ('5I', 1)]
> 15:16:35 [base] Load file `map.agp`
> 15:16:57 [base] Figure saved to `chr1.eps` (7200px x 21600px)
> 15:16:58 [base] Load file `map.lifted.bed`
> 15:17:00 [allmaps] Map contains 146675 markers in 110 linkage groups.
> 15:17:02 [base] Load file `weights.txt`
> 15:17:02 [base] Imported 10 records from `weights.txt`.
> 15:17:02 [allmaps] Map weights: [('27B', 1), ('WC', 1), ('27I', 1), ('SV', 1), ('NF', 1), ('46I', 1), ('27U', 1), ('ZZ', 1), ('TI', 1), ('5I', 1)]
> 15:17:28 [base] Load file `map.agp`
> 15:18:16 [base] Figure saved to `chr3.eps` (7200px x 21600px)
> 15:18:19 [base] Load file `map.lifted.bed`
> 15:18:21 [allmaps] Map contains 146675 markers in 110 linkage groups.
> 15:18:23 [base] Load file `weights.txt`
> ...

> COMMENT: Generated by ALLMAPS v0.7.3 (2017-12-20)
> COMMAND: python -m jcvi.assembly.allmaps path map.bed input.fasta -w weights.txt
> FIELDS: object, object_beg, object_end, part_number, component_type, component_id/gap_length, component_beg/gap_type, component_end/linkage, orientation/linkage_evidence
> chr1	1	14214582	1	W	ScsGwly_6539;HRSCAF=6694	1	14214582	-
> chr1	14214583	14214682	2	U	100	map	yes
> chr1	14214683	14224623	3	W	ScsGwly_4458;HRSCAF=4554	1	9941	?
> chr1	14224624	14224723	4	U	100	map	yes
> chr1	14224724	38197998	5	W	ScsGwly_6546;HRSCAF=6715	1	23973275	-
> chr1	38197999	38198098	6	U	100	map	yes
> chr1	38198099	38201502	7	W	ScsGwly_1821;HRSCAF=1873	1	3404	?
> chr2	1	30697058	1	W	ScsGwly_6550;HRSCAF=6729	1	30697058	+
> chr3	1	28359662	1	W	ScsGwly_6554;HRSCAF=6747	1	28359662	+
> chr3	28359663	28359762	2	U	100	map	yes

**Comment by tanghaibao** [comment]
@StefanoLonardi 
Sounds like a bug to me. I'll take a look when I get a chance to after the holidays.
Merry Christmas!

Haibao
