### ISSUE TITLE
How scaffolds were ordered with the same genetic positions

### ISSUE THREAD

**Issue by yilongyang** [tanghaibao/jcvi#84]
Hi Author:

If multiple scaffolds with their markers mapped to the same genetic position, how the linear order of these scaffolds on the pseudochromosome was established? Is it arbitrary within this region? If not arbitrary, on what basis was the order determined?

Thank you!

**Comment by tanghaibao** [comment]
@yilongyang 
When there is no additional information to orient, they usually have an inferred orientation of '?' (as opposed to either '+' or '-'). From a computation standpoint, if the score is the whether the contig is using '+' or '-', then the software will put '?' as the orientation.

Haibao

**Comment by yilongyang** [comment]
Thank you. I mean if two scaffolds only have markers at the same genetic position, how the software decides which scaffold is on the left side of the chromosome? I mean their order not the orientation.

**Comment by tanghaibao** [comment]
@yilongyang 
In that case, it is a random order - when they occupy the same genetic position, then either order has the same score, so the program may report either one.

Haibao

**Comment by yilongyang** [comment]
Thank you so much. This is what I guessed.
