### ISSUE TITLE
Unplaced scaffolds with markers

### ISSUE THREAD

**Issue by yilongyang** [tanghaibao/jcvi#85]
Hi Haibao,

I have another question. From the summary of the pseudochromosome construction, there are the number of unplaced scaffolds and  scaffolds with 1 or 2 or 3 or >= markers. Could you explain why there are scaffolds with one or more markers, but they were still unplaced? What factors could cause this?

Thank you!

**Comment by tanghaibao** [comment]
@yilongyang 
Some scaffolds do not contribute to the collinearity score - for example, consider a small scaffold in the middle of a larger one. The large scaffold A has markers on [1,2,3,7,8,9] centiMorgans, where the small scaffold B has markers on [5,6] centiMorgans. Then no matter how you place the relative order of A or B, the collinearity score (LMS) is the same as only A. Therefore, B was removed to unplaced.

Haibao
