### ISSUE TITLE
Testdata cannot be downloaded

### ISSUE THREAD

**Issue by thkitapci** [tanghaibao/jcvi#91]
Hi,
I am trying to download the testdata and this error occurs

-bash-4.2$ wget https://dl.dropboxusercontent.com/u/15937715/Data/ALLMAPS/ALLMAPS-testdata.zip
--2018-03-01 10:14:51--  https://dl.dropboxusercontent.com/u/15937715/Data/ALLMAPS/ALLMAPS-testdata.zip
Resolving dl.dropboxusercontent.com (dl.dropboxusercontent.com)... 162.125.2.6
Connecting to dl.dropboxusercontent.com (dl.dropboxusercontent.com)|162.125.2.6|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2018-03-01 10:14:51 ERROR 404: Not Found.

Can you please fix this ?

Thanks
Best Regards

**Comment by thkitapci** [comment]
Actually I found another link to the test data in the wiki page

https://www.dropbox.com/s/b497bi2b594m6fp/ALLMAPS-testdata.zip

this one works I think the link to testdata in the how to install page https://github.com/tanghaibao/jcvi/wiki/ALLMAPS:-How-to-install needs to be updated

Best Regards
Hamdi

**Comment by vivekkrish** [comment]
Thank you for letting us know. We have fixed the download link on the "How-To Install" page.
