### ISSUE TITLE
Anchored vs Oriented

### ISSUE THREAD

**Issue by thkitapci** [tanghaibao/jcvi#92]
Hi,
In the resulting .summary.txt for the test data there is a percentage for anchored and for oriented. I don't understand what does it mean for a sequence to be "anchored" but "not oriented" In the test data 100% of the output is anchored but 80% if oriented. What is the interpretation for the 20% which is not oriented but anchored ? Does that mean they are places in the "chromosomes" but their 5' to 3' orientation is not known ? If that is the case are they places in the *.chr.fasta file in a random order ? 

Thanks
Best Regards

**Comment by tanghaibao** [comment]
@thkitapci 
That's right, this means there is not enough information within the contig to determine 5`-3` orientation. For example, there is just a single genetic marker within the contig. In that case, they just inherit the same orientation as the input contig (i.e. no reverse complement) in the final `.chr.fasta`.

**Comment by thkitapci** [comment]
Thanks for the clarification
