### ISSUE TITLE
Question about split chimeric contigs

### ISSUE THREAD

**Issue by thkitapci** [tanghaibao/jcvi#93]
Hi,
I run the split chimeric contigs procedure (https://github.com/tanghaibao/jcvi/wiki/ALLMAPS:-How-to-split-chimeric-contigs). Does AllMaps provides any script to convert the initial map.bed file into the coordinates in the new genome.SPLIT.fasta using the genome.fasta.masked.agp ? 

Thanks
Best Regards
Hamdi

**Comment by tanghaibao** [comment]
@thkitapci 
Unfortunately no. The idea is to re-run ALLMAPS on the `genome.SPLIT.fasta` and generate the agp file.
